/** Actual normal CLI bounded admission, owned loopback fixture only. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import type {ChildProcess} from 'node:child_process';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';
import {hash,workInputHash} from '../src/domain.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
const entrypoint=fileURLToPath(new URL('../src/server.ts',import.meta.url));
async function until<T>(read:()=>Promise<T>|T,ready:(value:T)=>boolean){const end=Date.now()+10000;while(true){const value=await read();if(ready(value))return value;assert.ok(Date.now()<end,'CLI drain fixture deadline');await new Promise(r=>setTimeout(r,10));}}
async function freePort(){const server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');await new Promise<void>(r=>server.close(()=>r()));return address.port;}
const skip=process.platform!=='linux'?'Linux owned process proof required':!process.env.SURREAL_TEST_RUNTIME?'Owned disposable actual SurrealDB required':false;
test('normal CLI explicit causal sequence completes and interrupted remainder never resumes or replays',{skip,timeout:45000},async t=>{
 const f=await fixture(t,true,{cli:true,hold:'executor',runTimeoutMs:1500});assert.ok(f.transport);const database=(await f.transport.query('RETURN $session.db;',{}))[0] as string;await f.product.admit('mission',{commandId:'old-unknown-admit',expectedRevision:(await f.current()).revision,workId:'old-unknown',title:'Original unrelated unknown run',budget:8});await f.runtime.run('mission','old-unknown','original-other-host',(await f.current()).revision);await f.product.appendWorkMessage('mission',{commandId:'original-discussion',expectedRevision:(await f.current()).revision,workId:'work',messageId:'original-discussion',replyTo:null,text:'Original owner conversation <img src=x>'});await f.product.admit('mission',{commandId:'second-admit',expectedRevision:(await f.current()).revision,workId:'second',title:'Later explicit Work',budget:8});const original=structuredClone((await f.current()).value);let heldWorkId='third';let release!:()=>void;const held=new Promise<void>(r=>release=r),sends:string[]=[],provider=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw),prompt=JSON.parse(body.messages[0].content);sends.push(body.model);if(prompt.binding.workId===heldWorkId)await held;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:body.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Original bounded',reason:'Independent owned fixture review'}]}):'Original bounded lifetime fixture'}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}));});provider.listen(0,'127.0.0.1');await once(provider,'listening');const address=provider.address();assert.ok(address&&typeof address==='object');const file=join(f.root,'host.json');await writeFile(file,JSON.stringify({version:1,revision:'owned-drain-v1',mode:'local-http-mock',connections:[{id:'fixture',label:'Owned shutdown fixture',providerType:'compatible',baseUrl:`http://127.0.0.1:${address.port}/v1/`,models:['executor','verifier']}]}));const argv=[process.execPath,entrypoint,'--host-config',file];let child:ChildProcess|undefined,base='',logs='';
 async function start(){const port=await freePort();logs='';const owned=spawn(process.execPath,argv.slice(1),{cwd:f.root,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child=owned;owned.stdout!.on('data',d=>logs+=String(d));owned.stderr!.on('data',d=>logs+=String(d));await until(()=>{assert.equal(owned.exitCode,null,'CLI exited: '+logs);return logs.includes('Massion development workbench:');},Boolean);base=`http://127.0.0.1:${port}`;return owned;}
 async function call(path:string,body?:unknown){const r=await fetch(base+path,{...(body===undefined?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),signal:AbortSignal.timeout(12000)});return {status:r.status,body:await r.json()};}

 try{
  const host=await start(),connections=(await call('/connections')).body;assert.equal(connections.liveExecutionEnabled,false);const executor=connections.runtime.connections.find((p:any)=>p.model==='executor'),verifier=connections.runtime.connections.find((p:any)=>p.model==='verifier');assert.equal((await call('/connection-authorizations',{id:'owned-fixture-grant',scope:'local',executorProfileId:executor.id,verifierProfileId:verifier.id,maxOutputTokensPerCall:4,expectedConfigHash:connections.configHash})).status,200);const selection={executorProfileId:executor.id,verifierProfileId:verifier.id,authorizationId:'owned-fixture-grant',outputTokenCap:4};let current=await f.current();const first=current.value.works.find(w=>w.id==='fresh')!;assert.equal((await call('/missions/mission/work-prerequisite',{commandId:'causal-owner-pin',expectedRevision:current.revision,workId:'second',prerequisiteId:'fresh',criteriaHash:hash(first.criteria),inputHash:workInputHash(first),reason:'Original ordered dependent Work'})).status,200);
  async function sequence(commandId:string,ids:string[]){const s=await f.current();return {commandId,expectedRevision:s.revision,selection,works:ids.map(workId=>{const w=s.value.works.find(w=>w.id===workId)!;return {workId,inputHash:workInputHash(w),criteriaHash:hash(w.criteria)};})};}
  const initialInput=await sequence('normal-completed-sequence',['fresh','second']),accepted=await call('/missions/mission/run-sequence',initialInput);assert.equal(accepted.status,200);assert.equal(accepted.body.status,'completed');assert.deepEqual(accepted.body.completedWorkIds,['fresh','second']);assert.equal(sends.length,4);const initialAccepted=structuredClone((await f.current()).value);assert.equal(initialAccepted.works.find(w=>w.id==='second')!.prerequisiteRecords![0]!.checksum,initialAccepted.works.find(w=>w.id==='fresh')!.record!.checksum);
  for(const workId of ['third','fourth'])assert.equal((await call('/missions/mission/work',{commandId:'admit-'+workId,expectedRevision:(await f.current()).revision,workId,title:'Later '+workId,budget:8})).status,201);
  const interruptedInput=await sequence('normal-interrupted-sequence',['third','fourth']),running=call('/missions/mission/run-sequence',interruptedInput);await until(()=>sends.length,n=>n===5);const active=await f.current(),third=active.value.works.find(w=>w.id==='third')!;assert.ok(third.effects[0]!.providerDispatch);const beforeBusy=await f.journal(),busy=await call('/missions/mission/run-sequence',await sequence('busy-new-sequence',['fourth']));assert.equal(busy.body.status,'stopped');assert.match(busy.body.reason,/local host/);assert.deepEqual(await f.journal(),beforeBusy);assert.equal(sends.length,5);t.diagnostic(JSON.stringify({...await verifyOwnedChild(host,{cwd:f.root,argv}),entry:'normal src/server.ts --host-config',boundary:'third sequence Work fixture invocation held',liveCalls:0}));const exited=once(host,'exit');assert.equal(host.kill('SIGTERM'),true);const stopped=await running;assert.equal(stopped.status,200);assert.equal(stopped.body.status,'stopped');assert.deepEqual(stopped.body.completedWorkIds,[]);assert.deepEqual(await exited,[0,null]);const after=await f.current(),originalThird=structuredClone(after.value.works.find(w=>w.id==='third')!);assert.equal(originalThird.runtimeInterruption?.reason,'host-shutdown');assert.deepEqual(originalThird.runtimeRun,third.runtimeRun);assert.deepEqual(originalThird.effects[0]!.providerDispatch,third.effects[0]!.providerDispatch);assert.equal(originalThird.effects[0]!.status,'unknown');assert.equal(originalThird.budget.reserved,4);assert.equal(after.value.works.find(w=>w.id==='fourth')!.runtimeRun,undefined);assert.deepEqual(after.value.works.filter(w=>!['third','fourth'].includes(w.id)),initialAccepted.works);assert.deepEqual(after.value.conversations,initialAccepted.conversations);const journal=await f.journal();release();f.release();await new Promise(r=>setTimeout(r,30));assert.deepEqual(await f.journal(),journal);
  await start();const restarted=(await call('/connections')).body;assert.equal(restarted.runtime.authorizations.length,0);assert.equal((await call('/missions/mission/run-ownership?work=third')).body.replayPermitted,false);const repeated=await call('/missions/mission/run-sequence',{...interruptedInput,expectedRevision:after.revision});assert.equal(repeated.body.status,'stopped');assert.equal(repeated.body.results[0].status,'already-started');assert.deepEqual(await f.journal(),journal);assert.equal(sends.length,5);assert.equal((await f.current()).value.works.find(w=>w.id==='fourth')!.runtimeRun,undefined);
  const newExecutor=restarted.runtime.connections.find((p:any)=>p.model==='executor'),newVerifier=restarted.runtime.connections.find((p:any)=>p.model==='verifier');assert.equal((await call('/connection-authorizations',{id:'new-fixture-grant',scope:'local',executorProfileId:newExecutor.id,verifierProfileId:newVerifier.id,maxOutputTokensPerCall:4,expectedConfigHash:restarted.configHash})).status,200);const newSelection={executorProfileId:newExecutor.id,verifierProfileId:newVerifier.id,authorizationId:'new-fixture-grant',outputTokenCap:4};const reordered=await call('/missions/mission/run-sequence',{...await sequence(interruptedInput.commandId,['fourth']),selection:newSelection});assert.equal(reordered.status,409);assert.equal(reordered.body.status,'stopped');assert.equal(reordered.body.results[0].status,'conflict');assert.deepEqual(await f.journal(),journal);assert.equal(sends.length,5);const deliberate=await call('/missions/mission/run-sequence',{...await sequence('new-reviewed-fourth-only',['fourth']),selection:newSelection});assert.equal(deliberate.body.status,'completed');assert.equal(sends.length,7);assert.deepEqual((await f.current()).value.works.find(w=>w.id==='third'),originalThird);assert.deepEqual((await f.current()).value.works.filter(w=>!['third','fourth'].includes(w.id)),initialAccepted.works);assert.deepEqual((await f.current()).value.conversations,original.conversations);validateMissionJournalLineage(await f.journal());t.diagnostic(JSON.stringify({normalCLI:true,sequenceCompleted:['fresh','second'],signal:'SIGTERM',interruptedRemainderAutoStarts:0,restartedGrants:0,replayedProviderCalls:0,explicitNewRequestForFourth:true,fixtureNetworkCalls:sends.length,controlledOlderSeedCalls:f.calls.length,liveCalls:0,originalClaimsReservationsRecordsConversationExact:true}));
 }finally{if(child)await stopOwnedChild(child,{cwd:f.root,argv});release();provider.closeAllConnections();await new Promise<void>(r=>provider.close(()=>r()));}
});
