/** One held-call SIGKILL through the actual CLI entrypoint, without store hooks. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import type {ChildProcess} from 'node:child_process';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInContext} from 'node:vm';
import {createHttpRpcTransport,SurrealStore} from '../src/storage.ts';
import type {Mission} from '../src/domain.ts';
import {harness,reply,selectionField} from './support/workbench-client.ts';
import {verifyDisposableDatabase,verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';
const entrypoint=fileURLToPath(new URL('../src/server.ts',import.meta.url));
async function until<T>(read:()=>Promise<T>|T,ready:(value:T)=>boolean){const end=Date.now()+10000;while(true){const value=await read();if(ready(value))return value;assert.ok(Date.now()<end,'CLI state deadline');await new Promise(r=>setTimeout(r,10));}}
async function freePort(){const socket=createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const address=socket.address();assert.ok(address&&typeof address==='object');const port=address.port;await new Promise<void>(r=>socket.close(()=>r()));return port;}
const skip=process.platform!=='linux'?'Linux /proc ownership verification required':!process.env.SURREAL_TEST_RUNTIME?'scripts/with-surreal.py disposable ownership proof required':false;
test('normal CLI SIGKILL during fixture invocation retains drafts and unknown quarantine without replay',{skip,timeout:45000},async t=>{
 await verifyDisposableDatabase();
 const root=await mkdtemp(join(tmpdir(),'massion-owned-cli-kill-'));
 const db='cli_kill_'+crypto.randomUUID().replaceAll('-',''),rpc=process.env.MASSION_TEST_SURREAL_RPC!,namespace=process.env.MASSION_TEST_SURREAL_NAMESPACE!;
 const transport=createHttpRpcTransport({endpoint:rpc,namespace,database:db});await transport.query('DEFINE DATABASE '+db+';',{});const store=new SurrealStore<Mission>(transport);
 const sends:string[]=[];let release!:()=>void;const held=new Promise<void>(r=>{release=r;});
 const provider=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);sends.push(body.model);await held;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:body.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:'CLI kill fixture output'}}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}}));});
 provider.listen(0,'127.0.0.1');await once(provider,'listening');const address=provider.address();assert.ok(address&&typeof address==='object');
 const file=join(root,'host.json');await writeFile(file,JSON.stringify({version:1,revision:'cli-kill-fixture-v1',mode:'local-http-mock',connections:[{id:'fixture',label:'Owned CLI fixture',providerType:'compatible',baseUrl:`http://127.0.0.1:${address.port}/v1/`,models:['executor','verifier']}]}));
 const argv=[process.execPath,entrypoint,'--host-config',file];let child:ChildProcess|undefined,base='';
 async function start(){const port=await freePort();const spawned=spawn(process.execPath,argv.slice(1),{cwd:root,env:{MASSION_SURREAL_RPC:rpc,MASSION_SURREAL_NAMESPACE:namespace,MASSION_SURREAL_DATABASE:db,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child=spawned;let logs='';spawned.stdout!.on('data',c=>{logs+=c;});spawned.stderr!.on('data',c=>{logs+=c;});await until(()=>{assert.equal(spawned.exitCode,null,'CLI exited before readiness: '+logs);return logs.includes('Massion development workbench:');},Boolean);base='http://127.0.0.1:'+port;return spawned;}
 async function call(path:string,body?:unknown){const response=await fetch(base+path,{...(body===undefined?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),signal:AbortSignal.timeout(10000)});return {status:response.status,value:await response.json()};}
 try{
  const host=await start();const initial=(await call('/connections')).value;assert.equal(initial.liveExecutionEnabled,false);assert.equal(initial.runtime.authorizations.length,0);assert.deepEqual(sends,[]);
  const executor=initial.runtime.connections.find((p:any)=>p.model==='executor'),verifier=initial.runtime.connections.find((p:any)=>p.model==='verifier');assert.ok(executor&&verifier);
  assert.equal((await call('/connection-authorizations',{id:'fixture-grant',scope:'cli-kill',executorProfileId:executor.id,verifierProfileId:verifier.id,maxOutputTokensPerCall:8,expectedConfigHash:initial.configHash})).status,200);
  const id='mission:cli-kill',workId='work:cli-kill';assert.equal((await call('/missions',{id,commandId:'create',purpose:'Normal CLI kill fixture',scope:'cli-kill',constraints:['Fixture only'],criteria:{version:1,description:'CLI kill fixture output',oracle:'bounded-text-review/v1'}})).status,201);assert.equal((await call('/missions/'+id+'/work',{commandId:'admit',expectedRevision:1,workId,title:'Interrupted CLI Work',budget:16})).status,201);
  const selection={executorProfileId:executor.id,verifierProfileId:verifier.id,authorizationId:'fixture-grant',outputTokenCap:8};const check=await call('/missions/'+id+'/preflight',{commandId:'check',expectedRevision:2,workId,selection});assert.equal(check.value.ready,true);assert.deepEqual(sends,[]);
  const app=harness(async(path,init)=>{const response=await fetch(base+path,init);return reply(await response.json(),response.status);},{},undefined,{network:true,fragment:'#mission='+encodeURIComponent(id),identity:crypto.randomUUID()});await until(()=>app.node('sync-notice').hidden&&app.node('snapshot-json').textContent.includes(workId),Boolean);
  app.node('purpose').value='Private CLI creation draft';const direction=selectionField(app,'steer-'+workId);direction.value='Private CLI direction';await direction.fire('input');
  const runBody={commandId:'cli-run',expectedRevision:2,workId,selection};const running=runInContext(`write('/missions/${id}/run',${JSON.stringify(runBody)},'${id}','Fixture run')`,app.context) as Promise<unknown>;void running.catch(()=>{});
  await until(()=>sends.length,n=>n===1);assert.deepEqual(sends,['executor']);const before=(await store.load(id))!,journalBefore=await store.exportJournal();const original=before.value.works[0]!;assert.equal(original.runtimeRun?.id,'cli-run');assert.equal(original.effects.length,1);assert.equal(original.effects[0]!.status,'pending');assert.equal(original.effects[0]!.receipt,undefined);assert.equal(original.record,undefined);
  const proof=await verifyOwnedChild(host,{cwd:root,argv});t.diagnostic(JSON.stringify({...proof,entry:'src/server.ts --host-config',databaseOwnership:'verified disposable launcher',boundary:'fixture HTTP call observed; response held'}));const exited=once(host,'exit');assert.equal(host.kill('SIGKILL'),true);const [code,signal]=await exited;assert.equal(code,null);assert.equal(signal,'SIGKILL');release();await running;await app.tick();assert.equal(app.node('sync-notice').hidden,false);assert.equal(app.node('work-fields').disabled,true);assert.ok(app.storage.get('massion.workbench.pending'));assert.equal(app.calls.filter(c=>c.options.method==='POST').length,1);assert.deepEqual(await store.load(id),before);assert.deepEqual(await store.exportJournal(),journalBefore);
  await start();const restarted=(await call('/connections')).value;assert.equal(restarted.runtime.authorizations.length,0);assert.equal(restarted.liveExecutionEnabled,false);assert.deepEqual(sends,['executor']);await app.windowEvent('online');await until(()=>app.node('sync-notice').hidden,Boolean);assert.equal(app.node('purpose').value,'Private CLI creation draft');assert.equal(selectionField(app,'steer-'+workId).value,'Private CLI direction');assert.equal(app.storage.get('massion.workbench.pending'),undefined,'Exact activation receipt settles admission only');assert.equal(app.calls.filter(c=>c.options.method==='POST').length,1);assert.deepEqual(await store.load(id),before);assert.deepEqual(await store.exportJournal(),journalBefore);
  const fresh=harness(async(path,init)=>{const response=await fetch(base+path,init);return reply(await response.json(),response.status);},{},undefined,{network:true,fragment:'#mission='+encodeURIComponent(id),identity:crypto.randomUUID()});await until(()=>fresh.node('sync-notice').hidden,Boolean);assert.equal(fresh.calls.filter(c=>c.options.method==='POST').length,0);
  for(const commandId of ['cli-run','explicit-retry-probe']){const retry=await call('/missions/'+id+'/run',{commandId,expectedRevision:before.revision,workId,selection});assert.equal(retry.value.status,'already-started');assert.deepEqual(await store.exportJournal(),journalBefore);assert.deepEqual(sends,['executor']);}
  const recovery={commandId:'owner-quarantine',expectedRevision:before.revision,command:{type:'quarantine-runtime',workId,runId:'cli-run',reason:'Owner fixture inspected killed CLI; external outcome remains unresolved.',acknowledgeUncertainOutcome:true}};assert.equal((await call('/missions/'+id+'/commands',recovery)).status,200);const quarantined=(await store.load(id))!,work=quarantined.value.works[0]!;assert.equal(work.execution,'cancelled');assert.equal(work.effects[0]!.status,'unknown');assert.equal(work.effects[0]!.receipt,undefined);assert.equal(work.budget.measured,null);assert.equal(work.budget.reserved,original.budget.reserved);assert.equal(work.record,undefined);assert.ok(work.runtimeRecovery);assert.equal((await call('/missions/'+id+'/commands',recovery)).value.status,'replayed');assert.equal((await call('/missions/'+id+'/run',{commandId:'after-quarantine',expectedRevision:quarantined.revision,workId,selection})).value.status,'already-started');assert.deepEqual(await store.load(id),quarantined);const journal=await store.exportJournal();assert.equal(journal.operations.length,journalBefore.operations.length+1);assert.deepEqual(journal.operations.at(-1)!.outbox,[]);assert.deepEqual(sends,['executor']);await app.tick();assert.equal(app.calls.filter(c=>c.options.method==='POST').length,1);
  const events=await store.readEvents(0,1000);assert.equal(events.events.filter(e=>e.commandId==='cli-run').length,1);for(let i=1;i<events.events.length;i++)assert.equal(events.events[i]!.cursor,events.events[i-1]!.cursor+1);
  t.diagnostic(JSON.stringify({normalCLI:true,providerCallsBeforeKill:1,providerCallsAfterRecovery:1,automaticProviderReplay:0,automaticClientPosts:0,freshClientPosts:0,privateDraftsPreserved:true,restoredGrants:0,permanentQuarantine:'receipt-free unknown; no reopening'}));
 }finally{
  if(child)await stopOwnedChild(child,{cwd:root,argv});
  release();provider.closeAllConnections();await new Promise<void>(r=>provider.close(()=>r()));await rm(root,{recursive:true,force:true});
 }
});
