import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import type {Mission} from '../src/domain.ts';
import {harness,reply,settle,selectionField} from './support/workbench-client.ts';
import type {Handler} from './support/workbench-client.ts';

async function eventually(check:()=>boolean) {const until=Date.now()+5000;while(!check()){if(Date.now()>until)assert.fail('Timed out waiting for client state');await new Promise(resolve=>setTimeout(resolve,5));}}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory'} client-to-HTTP selection flow checks, runs, reloads and never replays`,{skip:durable&&!process.env.MASSION_TEST_SURREAL_RPC},async t=>{
 const {createServer}=await import('node:http');const {mkdtemp,rm}=await import('node:fs/promises');const {join}=await import('node:path');const {tmpdir}=await import('node:os');
 const {InMemoryStore,SurrealStore,createHttpRpcTransport,initializeSurrealSchema}=await import('../src/storage.ts');const {createWorkbench}=await import('../src/server.ts');const {ConnectionCatalog}=await import('../src/provider-profiles.ts');const {chatProfileFactory}=await import('../src/chat-profile-factory.ts');const {SelectableTextRuntime}=await import('../src/selectable-runtime.ts');const {TextArtifactStore}=await import('../src/text-artifacts.ts');
 const root=await mkdtemp(join(tmpdir(),'massion-workbench-flow-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const calls:string[]=[];const provider=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const request=JSON.parse(body);calls.push(request.model);const prompt=JSON.parse(request.messages[0].content);const content=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Flow fixture result',reason:'Controlled exact-text fixture'}]}):'Flow fixture result';res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:request.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content}}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}}));});
 provider.listen(0,'127.0.0.1');await once(provider,'listening');t.after(async()=>{provider.closeAllConnections();await new Promise<void>(resolve=>provider.close(()=>resolve()));});const providerAddress=provider.address();assert.ok(providerAddress&&typeof providerAddress==='object');
 const profiles=['executor','reviewer'].map(id=>({id,label:'Fixture '+id,backend:'model-provider' as const,providerKind:'fixture',protocol:'openai-chat-completions/v1',model:'fixture-'+id,endpoint:`http://127.0.0.1:${providerAddress.port}/v1/chat/completions`,revision:'1',enabled:true,auth:{method:'none'},capabilities:['text-output'],usage:{inputTokens:'reported' as const,outputTokens:'reported' as const,cost:'unknown' as const},limits:{maxInputBytes:32768,maxOutputTokens:8,maxResponseBytes:32768,timeoutMs:2000}}));
 const catalog=new ConnectionCatalog(profiles,[chatProfileFactory({mode:'local-http-mock',transport:fetch})]);const permissions=catalog.list().map(p=>({profileId:p.id,configHash:p.configHash}));const grants=[{id:'fixture-grant',scope:'fixture-only',mode:'mock-http' as const,executor:permissions,verifier:permissions,maxOutputTokensPerCall:8}];
 const transport=durable?createHttpRpcTransport({endpoint:process.env.MASSION_TEST_SURREAL_RPC!,namespace:'massion_storage_tests',database:'massion_storage_tests'}):undefined;if(transport)await initializeSurrealSchema(transport);
 const freshStore=()=>transport?new SurrealStore<Mission>(transport):new InMemoryStore<Mission>();let store=freshStore();
 const host=()=>createWorkbench(store,root,{runtime:new SelectableTextRuntime(store,catalog,grants,new TextArtifactStore(join(root,'artifacts')))});let server=host();let base='';
 const listen=async()=>{server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');base=`http://127.0.0.1:${address.port}`;};await listen();t.after(async()=>{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));});
 const handler:Handler=async(path,options)=>{const response=await fetch(base+path,options);return reply(await response.json(),response.status);};
 const app=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID()});await eventually(()=>app.node('provider-notice').textContent.includes('Choose configured'));
 assert.match(app.node('work-budget-label').textContent,/output tokens/);assert.match(app.node('work-budget-hint').textContent,/at least twice/);
 app.node('purpose').value='Exercise a bounded fixture flow';app.node('scope').value='fixture-only';app.node('criteria').value='Return controlled fixture text';app.node('criteria-oracle').value='bounded-text-review/v1';await app.submit('mission-form');
 app.node('work-title').value='Review a fixture';app.node('work-budget').value='12';await app.submit('work-form');const snapshot=JSON.parse(app.node('snapshot-json').textContent);const missionId=snapshot.value.id;const workId=snapshot.value.works[0].id;assert.equal(snapshot.revision,2);assert.equal(calls.length,0);
 for(const [id,value] of [['executor-profile-','executor'],['verifier-profile-','reviewer'],['authorization-','fixture-grant'],['output-cap-','4']]){const field=selectionField(app,id+workId);field.value=value!;await field.fire('change');}
 await app.all().find(n=>n.textContent==='Check selection')!.fire('click');assert.match(selectionField(app,'selection-check-'+workId).textContent,/Checked at revision 2/);assert.equal(calls.length,0);assert.equal((await store.load(missionId))!.revision,2);
 const form=app.all().find(n=>n.className==='execution-form')!;await form.fire('submit');await settle();assert.deepEqual(calls,['fixture-executor','fixture-reviewer']);assert.match(app.node('work-list').textContent,/Acceptance: accepted/);assert.match(app.node('work-list').textContent,/fixture evidence/);
 const accepted=(await store.load(missionId))!;const completed=accepted.value.works[0]!;assert.equal(completed.record!.evidenceClass,'fixture');assert.equal(completed.runtimeRun!.connectionBindings!.executor.profileId,'executor');assert.equal(completed.runtimeRun!.connectionBindings!.verifier.profileId,'reviewer');
 const journalBefore=await store.readEvents(0,1000);server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));if(durable)store=freshStore();server=host();await listen();
 const reloaded=harness(handler,Object.fromEntries(app.storage),undefined,{network:true});await eventually(()=>reloaded.node('work-list').textContent.includes('Acceptance: accepted'));
 assert.deepEqual(await store.load(missionId),accepted);assert.deepEqual(await store.readEvents(0,1000),journalBefore);assert.deepEqual(calls,['fixture-executor','fixture-reviewer']);assert.equal(reloaded.calls.filter(c=>c.options.method==='POST').length,0);assert.equal(reloaded.all().some(n=>n.className==='execution-form'),false);
});
