import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import type {Mission} from '../src/domain.ts';
import {harness,reply,settle,selectionField} from './support/workbench-client.ts';
import type {Handler} from './support/workbench-client.ts';

async function eventually(check:()=>boolean) {const until=Date.now()+5000;while(!check()){if(Date.now()>until)assert.fail('Timed out waiting for client state');await new Promise(resolve=>setTimeout(resolve,5));}}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory'} client-to-HTTP selection flow checks, runs, reloads and never replays`,{skip:durable&&!process.env.MASSION_TEST_SURREAL_RPC},async t=>{
 const {createServer}=await import('node:http');const {mkdtemp,rm}=await import('node:fs/promises');const {join}=await import('node:path');const {tmpdir}=await import('node:os');
 const {InMemoryStore,SurrealStore,createHttpRpcTransport,initializeSurrealSchema}=await import('../src/storage.ts');const {createWorkbench}=await import('../src/server.ts');const {ConnectionCatalog}=await import('../src/provider-profiles.ts');const {chatProfileFactory}=await import('../src/chat-profile-factory.ts');const {SelectableTextRuntime}=await import('../src/selectable-runtime.ts');const {TextArtifactStore}=await import('../src/text-artifacts.ts');
 const root=await mkdtemp(join(tmpdir(),'massion-workbench-flow-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const calls:string[]=[];const provider=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const request=JSON.parse(body);calls.push(request.model);const prompt=JSON.parse(request.messages[0].content);const content=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Flow fixture result',reason:'Controlled exact-text fixture'}]}):'Flow fixture result';res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:request.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content}}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}}));});
 provider.listen(0,'127.0.0.1');await once(provider,'listening');t.after(async()=>{provider.closeAllConnections();await new Promise<void>(resolve=>provider.close(()=>resolve()));});const providerAddress=provider.address();assert.ok(providerAddress&&typeof providerAddress==='object');
 const profiles=['executor','reviewer'].map(id=>({id,label:'Fixture '+id,backend:'model-provider' as const,providerKind:'fixture',protocol:'openai-chat-completions/v1',model:'fixture-'+id,endpoint:`http://127.0.0.1:${providerAddress.port}/v1/chat/completions`,revision:'1',enabled:true,auth:{method:'none'},capabilities:['text-output'],usage:{inputTokens:'reported' as const,outputTokens:'reported' as const,cost:'unknown' as const},limits:{maxInputBytes:32768,maxOutputTokens:8,maxResponseBytes:32768,timeoutMs:2000}}));
 const catalog=new ConnectionCatalog(profiles,[chatProfileFactory({mode:'local-http-mock',transport:fetch})]);const permissions=catalog.list().map(p=>({profileId:p.id,configHash:p.configHash}));const grants=[{id:'fixture-grant',scope:'fixture-only',mode:'mock-http' as const,executor:permissions,verifier:permissions,maxOutputTokensPerCall:8}];
 const transport=durable?createHttpRpcTransport({endpoint:process.env.MASSION_TEST_SURREAL_RPC!,namespace:'massion_storage_tests',database:'massion_storage_tests'}):undefined;if(transport)await initializeSurrealSchema(transport);
 const freshStore=()=>transport?new SurrealStore<Mission>(transport):new InMemoryStore<Mission>();let store=freshStore();
 const host=()=>createWorkbench(store,root,{runtime:new SelectableTextRuntime(store,catalog,grants,new TextArtifactStore(join(root,'artifacts')))});let server=host();let base='';
 const listen=async()=>{server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');base=`http://127.0.0.1:${address.port}`;};await listen();t.after(async()=>{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));});
 const handler:Handler=async(path,options)=>{const response=await fetch(base+path,options);return reply(await response.json(),response.status);};
 const app=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID()});await eventually(()=>app.node('provider-notice').textContent.includes('Choose configured'));
 assert.match(app.node('work-budget-label').textContent,/output tokens/);assert.match(app.node('work-budget-hint').textContent,/at least twice/);
 app.node('purpose').value='Exercise a bounded fixture flow';app.node('scope').value='fixture-only';app.node('criteria').value='Return controlled fixture text';app.node('criteria-oracle').value='bounded-text-review/v1';await app.submit('mission-form');
 app.node('work-title').value='Review a fixture';app.node('work-budget').value='12';await app.submit('work-form');const snapshot=JSON.parse(app.node('snapshot-json').textContent);const missionId=snapshot.value.id;const workId=snapshot.value.works[0].id;assert.equal(snapshot.revision,2);assert.equal(calls.length,0);
 for(const [id,value] of [['executor-profile-','executor'],['verifier-profile-','reviewer'],['authorization-','fixture-grant'],['output-cap-','4']]){const field=selectionField(app,id+workId);field.value=value!;await field.fire('change');}
 await app.all().find(n=>n.textContent==='Check selection')!.fire('click');assert.match(selectionField(app,'selection-check-'+workId).textContent,/Checked at revision 2/);assert.equal(calls.length,0);assert.equal((await store.load(missionId))!.revision,2);
 const form=app.all().find(n=>n.className==='execution-form')!;await form.fire('submit');await settle();assert.deepEqual(calls,['fixture-executor','fixture-reviewer']);assert.match(app.node('work-list').textContent,/Acceptance: accepted/);assert.match(app.node('work-list').textContent,/fixture evidence/);
 const accepted=(await store.load(missionId))!;const completed=accepted.value.works[0]!;assert.equal(completed.record!.evidenceClass,'fixture');assert.equal(completed.runtimeRun!.connectionBindings!.executor.profileId,'executor');assert.equal(completed.runtimeRun!.connectionBindings!.verifier.profileId,'reviewer');
 const journalBefore=await store.readEvents(0,1000);server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));if(durable)store=freshStore();server=host();await listen();
 const reference=app.node('mission-link').attributes.get('href')!;assert.equal(reference,'#mission='+encodeURIComponent(missionId));const reloaded=harness(handler,{},undefined,{network:true,fragment:reference,identity:crypto.randomUUID()});assert.notEqual(reloaded.storage,app.storage);await eventually(()=>reloaded.node('work-list').textContent.includes('Acceptance: accepted'));
 assert.deepEqual(await store.load(missionId),accepted);assert.deepEqual(await store.readEvents(0,1000),journalBefore);assert.deepEqual(calls,['fixture-executor','fixture-reviewer']);assert.equal(reloaded.calls.filter(c=>c.options.method==='POST').length,0);assert.equal(reloaded.all().some(n=>n.className==='execution-form'),false);
});

test('actual SurrealDB separate client stores follow one linked Mission with explicit conflict and no replay',{skip:!process.env.MASSION_TEST_SURREAL_RPC},async t=>{
 const {mkdtemp,rm}=await import('node:fs/promises'),{join}=await import('node:path'),{tmpdir}=await import('node:os');const {SurrealStore,createHttpRpcTransport,initializeSurrealSchema}=await import('../src/storage.ts');const {createWorkbench}=await import('../src/server.ts');
 const root=await mkdtemp(join(tmpdir(),'massion-linked-clients-'));t.after(()=>rm(root,{recursive:true,force:true}));const database='links_'+crypto.randomUUID().replaceAll('-','');const transport=createHttpRpcTransport({endpoint:process.env.MASSION_TEST_SURREAL_RPC!,namespace:process.env.MASSION_TEST_SURREAL_NAMESPACE!,database});await transport.query('DEFINE DATABASE '+database+';',{});await initializeSurrealSchema(transport);let store=new SurrealStore<Mission>(transport),server=createWorkbench(store,root),base='';
 async function listen(){server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');base='http://127.0.0.1:'+address.port;}
 async function close(){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}await listen();t.after(close);
 const handler:Handler=async(path,init)=>{const response=await fetch(base+path,init);return reply(await response.json(),response.status);};const first=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID()});await eventually(()=>first.node('provider-notice').textContent.includes('unavailable'));
 first.node('purpose').value='Follow durable Work on one authoritative host';first.node('scope').value='linked-clients';first.node('criteria').value='Controls are retained without provider dispatch';await first.submit('mission-form');await eventually(()=>first.node('mission-panel').hidden===false);first.node('work-title').value='Bounded responsibility';await first.submit('work-form');await eventually(()=>JSON.parse(first.node('snapshot-json').textContent).revision===2);
 const reference=first.node('mission-link').attributes.get('href')!,id=JSON.parse(first.node('snapshot-json').textContent).value.id;const second=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID(),fragment:reference});await eventually(()=>second.node('snapshot-json').textContent.includes('Bounded responsibility'));assert.notEqual(first.storage,second.storage);assert.equal(second.calls.filter(c=>c.options.method==='POST').length,0);
 const steer=(app:ReturnType<typeof harness>,text:string)=>{const form=app.all().find(n=>n.className==='steer-form')!;form.children.find(n=>n.tagName==='TEXTAREA')!.value=text;return form.fire('submit');};await steer(first,'First owner direction');await eventually(()=>JSON.parse(first.node('snapshot-json').textContent).revision===3);await steer(second,'Stale second direction');await eventually(()=>second.calls.filter(c=>c.options.method==='POST').length===1&&JSON.parse(second.node('snapshot-json').textContent).revision===3);assert.equal(second.calls.filter(c=>c.options.method==='POST').length,1);assert.equal((await store.load(id))!.value.works[0]!.instructions!.length,1);
 await steer(first,'A later owner direction');await eventually(()=>JSON.parse(first.node('snapshot-json').textContent).revision===4);await second.tick();await eventually(()=>JSON.parse(second.node('snapshot-json').textContent).revision===4);const preserved=(await store.load(id))!,events=await store.readEvents(0,1000);assert.equal(preserved.value.works[0]!.effects.length,0);
 first.node('work-title').value='A retained draft';const firstWrites=first.calls.filter(c=>c.options.method==='POST').length;await close();await first.tick();await eventually(()=>!first.node('sync-notice').hidden);await first.submit('work-form');assert.equal(first.calls.filter(c=>c.options.method==='POST').length,firstWrites);assert.equal(first.node('load-mission').disabled,false);
 store=new SurrealStore<Mission>(transport);server=createWorkbench(store,root);await listen();const third=harness(handler,{},undefined,{network:true,fragment:reference,identity:crypto.randomUUID()});await eventually(()=>third.node('snapshot-json').textContent.includes('A later owner direction')&&third.node('sync-notice').hidden);assert.equal(third.calls.filter(c=>c.options.method==='POST').length,0);assert.deepEqual(await store.load(id),preserved);assert.deepEqual(await store.readEvents(0,1000),events);
 await steer(third,'Direction while the first client was disconnected');await eventually(()=>JSON.parse(third.node('snapshot-json').textContent).revision===5);await first.windowEvent('online');await eventually(()=>first.node('sync-notice').hidden&&JSON.parse(first.node('snapshot-json').textContent).revision===5);assert.equal(first.node('work-title').value,'A retained draft');assert.equal(first.calls.filter(c=>c.options.method==='POST').length,firstWrites);const before=await store.readEvents(0,1000);await first.submit('work-form');await eventually(()=>JSON.parse(first.node('snapshot-json').textContent).revision===6);assert.equal(first.calls.filter(c=>c.options.method==='POST').length,firstWrites+1);assert.equal((await store.readEvents(0,1000)).events.length,before.events.length+1);assert.equal((await store.load(id))!.value.works.every(work=>work.effects.length===0),true);
});

for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory'} owner instruction conflicts retain drafts for explicit revision submission across clients and restart`,{skip:durable&&!process.env.MASSION_TEST_SURREAL_RPC},async t=>{
 const {mkdtemp,rm}=await import('node:fs/promises'),{join}=await import('node:path'),{tmpdir}=await import('node:os');
 const {InMemoryStore,SurrealStore,createHttpRpcTransport,initializeSurrealSchema}=await import('../src/storage.ts');const {createWorkbench}=await import('../src/server.ts');
 const root=await mkdtemp(join(tmpdir(),'massion-instruction-conflicts-'));t.after(()=>rm(root,{recursive:true,force:true}));
 let transport:ReturnType<typeof createHttpRpcTransport>|undefined;
 if(durable){const database='instructions_'+crypto.randomUUID().replaceAll('-','');transport=createHttpRpcTransport({endpoint:process.env.MASSION_TEST_SURREAL_RPC!,namespace:process.env.MASSION_TEST_SURREAL_NAMESPACE!,database});await transport.query('DEFINE DATABASE '+database+';',{});await initializeSurrealSchema(transport);}
 let store=transport?new SurrealStore<Mission>(transport):new InMemoryStore<Mission>(),server=createWorkbench(store,root),base='';
 async function listen(){server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');base='http://127.0.0.1:'+address.port;}
 async function close(){server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}await listen();t.after(close);
 const handler:Handler=async(path,init)=>{const response=await fetch(base+path,init);return reply(await response.json(),response.status);};
 const first=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID()});await eventually(()=>first.node('sync-notice').hidden);
 first.node('purpose').value='Continue owner directions across clients';first.node('scope').value='instruction-conflict';first.node('criteria').value='Only explicit current revision instructions commit';await first.submit('mission-form');await eventually(()=>first.node('mission-panel').hidden===false);
 for(const title of ['Work A','Work B']){const revision=JSON.parse(first.node('snapshot-json').textContent).revision;first.node('work-title').value=title;await first.submit('work-form');await eventually(()=>JSON.parse(first.node('snapshot-json').textContent).revision===revision+1);}
 const initial=JSON.parse(first.node('snapshot-json').textContent),id=initial.value.id,a=initial.value.works[0].id,b=initial.value.works[1].id,reference=first.node('mission-link').attributes.get('href')!;
 const second=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID(),fragment:reference});await eventually(()=>second.node('sync-notice').hidden&&second.node('snapshot-json').textContent.includes('Work B'));
 const rev=(app:ReturnType<typeof harness>)=>JSON.parse(app.node('snapshot-json').textContent).revision;
 const posts=()=>second.calls.filter(call=>call.options.method==='POST');
 const form=(app:ReturnType<typeof harness>,workId:string)=>app.all().find(node=>node.className==='steer-form'&&node.children.some(child=>child.id==='steer-'+workId))!;
 const draft=async(app:ReturnType<typeof harness>,workId:string,text:string)=>{const input=selectionField(app,'steer-'+workId);input.value=text;await input.fire('input');};
 const steer=async(app:ReturnType<typeof harness>,workId:string,text:string)=>{await draft(app,workId,text);await form(app,workId).fire('submit');};
 await steer(first,a,'Canonical direction one');await eventually(()=>rev(first)===4);
 await steer(second,a,'My unrecorded direction');await eventually(()=>rev(second)===4&&second.node('status').textContent.includes('Revision conflict'));
 assert.equal(posts().length,1);assert.match(second.node('work-list').textContent,/My unrecorded direction/);assert.match(second.node('work-list').textContent,/owner: Canonical direction one/);assert.equal(selectionField(second,'steer-'+a).value,'My unrecorded direction');
 await draft(second,a,'Edited after comparison');await draft(second,b,'Separate Work B draft');
 await steer(first,a,'Canonical direction two');await eventually(()=>rev(first)===5);
 await form(second,a).fire('submit');await eventually(()=>rev(second)===5&&posts().length===2&&second.node('status').textContent.includes('Revision conflict'));
 assert.match(second.node('work-list').textContent,/submission at revision 4 conflicted/);assert.match(second.node('work-list').textContent,/owner: Canonical direction two/);assert.equal(selectionField(second,'steer-'+a).value,'Edited after comparison');assert.equal(selectionField(second,'steer-'+b).value,'Separate Work B draft');
 const oldForm=form(second,a);await close();await second.tick();await eventually(()=>!second.node('sync-notice').hidden);await oldForm.fire('submit');assert.equal(posts().length,2);
 if(transport)store=new SurrealStore<Mission>(transport);server=createWorkbench(store,root);await listen();
 const third=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID(),fragment:reference});await eventually(()=>third.node('sync-notice').hidden&&rev(third)===5);assert.equal(third.calls.filter(call=>call.options.method==='POST').length,0);
 await steer(third,a,'Direction committed during disconnection');await eventually(()=>rev(third)===6);
 await second.windowEvent('online');await eventually(()=>second.node('sync-notice').hidden&&rev(second)===6);
 assert.equal(posts().length,2);assert.match(second.node('work-list').textContent,/current revision 6/);assert.match(second.node('work-list').textContent,/Direction committed during disconnection/);assert.equal(selectionField(second,'steer-'+a).value,'Edited after comparison');assert.equal(selectionField(second,'steer-'+b).value,'Separate Work B draft');
 await oldForm.fire('submit');assert.equal(posts().length,2);assert.match(form(second,a).textContent,/Submit revised instruction at revision 6/);
 await form(second,a).fire('submit');await eventually(()=>rev(second)===7);assert.equal(posts().length,3);const sent=JSON.parse(posts()[2]!.options.body);assert.equal(sent.expectedRevision,6);assert.equal(sent.command.instruction,'Edited after comparison');assert.notEqual(sent.commandId,JSON.parse(posts()[1]!.options.body).commandId);assert.equal(selectionField(second,'steer-'+a).value,'');assert.equal(second.all().some(node=>node.className==='instruction-conflict'),false);assert.equal(selectionField(second,'steer-'+b).value,'Separate Work B draft');
 await third.tick();await eventually(()=>rev(third)===7);await steer(third,a,'Last recorded direction');await eventually(()=>rev(third)===8);
 await steer(second,a,'Keep this draft after cancellation');await eventually(()=>rev(second)===8&&posts().length===4);const cancelledForm=form(second,a);
 await form(third,a).children.find(node=>node.className==='row')!.children.find(node=>node.textContent==='Cancel Work')!.fire('click');await eventually(()=>rev(third)===9);
 await second.tick();await eventually(()=>rev(second)===9);assert.match(second.node('work-list').textContent,/This Work is closed/);assert.match(second.node('work-list').textContent,/Keep this draft after cancellation/);assert.equal(form(second,a),undefined);await cancelledForm.fire('submit');assert.equal(posts().length,4);assert.equal(selectionField(second,'steer-'+b).value,'Separate Work B draft');
 const final=(await store.load(id))!;assert.deepEqual(final.value.works[0]!.instructions!.map(item=>item.text),['Canonical direction one','Canonical direction two','Direction committed during disconnection','Edited after comparison','Last recorded direction']);assert.equal(final.value.works[0]!.execution,'cancelled');assert.equal(final.value.works.every(work=>work.effects.length===0),true);
 const fresh=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID(),fragment:reference});await eventually(()=>fresh.node('sync-notice').hidden&&rev(fresh)===9);assert.equal(fresh.calls.filter(call=>call.options.method==='POST').length,0);assert.match(fresh.node('work-list').textContent,/Last recorded direction/);assert.doesNotMatch(fresh.node('work-list').textContent,/Keep this draft after cancellation/);
});
