import {SurrealStore} from '../src/storage.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {hash,workInputHash} from '../src/domain.ts';
import {ProductService} from '../src/product.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {validateConversationSources} from '../src/conversation-work.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} selected original owner message admits only separate reviewed Work with immutable lineage and no execution`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,durable);await f.product.appendWorkMessage('mission',{commandId:'note',expectedRevision:(await f.current()).revision,workId:'work',messageId:'note',replyTo:null,text:'  Original <img src=x> 원문 😀  '});const before=await f.current(),message=before.value.conversations![0]!.messages[0]!,selection={workId:'work',messageId:message.id,messageHash:hash(message)},input={commandId:'derived',expectedRevision:before.revision,workId:'derived',title:'Edited bounded task',budget:8,conversationSource:selection};assert.equal((await f.product.admit('mission',input)).status,'committed');const now=await f.current(),w=now.value.works.find(w=>w.id==='derived')!;assert.deepEqual(now.value.works.filter(w=>w.id!=='derived'),before.value.works);assert.deepEqual(now.value.conversations,before.value.conversations);assert.deepEqual(w.conversationSource!.message,message);assert.equal(w.conversationSource!.actorId,'local-owner');assert.equal(w.runtimeRun,undefined);assert.deepEqual(w.effects,[]);assert.equal(f.calls.length,0);validateConversationSources(now.value);validateMissionJournalLineage(await f.journal());const journal=await f.journal();assert.equal((await new ProductService(f.store,f.product.providers,f.runtime).admit('mission',input)).status,'replayed');assert.equal((await f.product.admit('mission',{...input,title:'Changed same identity'})).status,'conflict');assert.deepEqual(await f.journal(),journal);const without=structuredClone(w);delete without.conversationSource;assert.notEqual(workInputHash(w),workInputHash(without));const bad=structuredClone(now.value);bad.works.find(w=>w.id==='derived')!.conversationSource!.message.text='Forged';assert.throws(()=>validateConversationSources(bad));
 if(durable){assert.ok(f.store instanceof SurrealStore);const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{store}=await growthStore(true);assert.ok(store instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),store,f.root+'/derived-restore');assert.deepEqual((await store.load('mission'))!.value,now.value);}
});
test('source selection rejects forged/cross-thread/extra fields and stale admission without modifying originals',async t=>{
 const f=await lifetimeFixture(t);await f.product.appendWorkMessage('mission',{commandId:'note',expectedRevision:(await f.current()).revision,workId:'work',messageId:'note',replyTo:null,text:'Original'});const before=await f.current(),m=before.value.conversations![0]!.messages[0]!,base={commandId:'bad',expectedRevision:before.revision,workId:'derived',title:'New task',budget:8};for(const selection of [{workId:'fresh',messageId:'note',messageHash:hash(m)},{workId:'work',messageId:'absent',messageHash:hash(m)},{workId:'work',messageId:'note',messageHash:'0'.repeat(64)},{workId:'work',messageId:'note',messageHash:hash(m),actorId:'forged'}])await assert.rejects(f.product.admit('mission',{...base,conversationSource:selection}));assert.deepEqual(await f.current(),before);assert.equal((await f.product.admit('mission',{...base,expectedRevision:before.revision-1,conversationSource:{workId:'work',messageId:'note',messageHash:hash(m)}})).status,'conflict');assert.equal(f.calls.length,0);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} only separate explicit Run invokes executor/verifier and seals original conversation provenance in Record`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,durable);await f.product.appendWorkMessage('mission',{commandId:'original',expectedRevision:(await f.current()).revision,workId:'work',messageId:'original',replyTo:null,text:'Untrusted original discussion, not task instructions'});const before=await f.current(),m=before.value.conversations![0]!.messages[0]!;await f.product.admit('mission',{commandId:'new',expectedRevision:before.revision,workId:'derived',title:'Original bounded lifetime fixture',budget:8,conversationSource:{workId:'work',messageId:m.id,messageHash:hash(m)}});assert.equal(f.calls.length,0);const result=await f.product.run('mission','derived','explicit-derived',(await f.current()).revision);assert.equal(result.status,'settled');const current=await f.current(),w=current.value.works.find(w=>w.id==='derived')!;assert.equal(f.calls.length,2);assert.deepEqual(f.calls[0]!.input.work.conversationSource,w.conversationSource);assert.deepEqual(f.calls[1]!.input.requirements.conversationSource,w.conversationSource);assert.deepEqual(w.record!.conversationSource,w.conversationSource);assert.deepEqual(current.value.works.filter(w=>w.id!=='derived'),before.value.works);validateMissionJournalLineage(await f.journal());const {readRecordArtifact}=await import('../src/record-artifact.ts');const read=await readRecordArtifact(f.store,f.artifacts,'mission','derived',{recordId:w.record!.id,artifactVersion:w.artifact!.version,artifactSha256:w.artifact!.sha256});assert.match(read!.content,/Original bounded/);
});
test('admission freezes selected message and edited task before asynchronous lookup',async t=>{
 const f=await lifetimeFixture(t);await f.product.appendWorkMessage('mission',{commandId:'original',expectedRevision:(await f.current()).revision,workId:'work',messageId:'original',replyTo:null,text:'Original'});const m=(await f.current()).value.conversations![0]!.messages[0]!;let reached!:()=>void,release!:()=>void;const ready=new Promise<void>(r=>reached=r),gate=new Promise<void>(r=>release=r);let held=false;const store=new Proxy(f.store,{get(target,key){if(key==='load')return async(id:string)=>{if(!held){held=true;reached();await gate;}return target.load(id);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),input={commandId:'frozen',expectedRevision:(await f.current()).revision,workId:'frozen',title:'Original edited task',budget:8,conversationSource:{workId:'work',messageId:m.id,messageHash:hash(m)}},service=new ProductService(store,f.product.providers,f.runtime),pending=service.admit('mission',input);await ready;input.title='Mutated';input.conversationSource.workId='fresh';release();assert.equal((await pending).status,'committed');const w=(await f.current()).value.works.at(-1)!;assert.equal(w.title,'Original edited task');assert.equal(w.conversationSource!.workId,'work');assert.equal(f.calls.length,0);
});
test('new responsibility from unknown Work discussion preserves its original unknown claims and never replays it',async t=>{
 const f=await lifetimeFixture(t,false,{hold:'executor',runTimeoutMs:80});assert.equal((await f.product.run('mission','fresh','unknown-original',(await f.current()).revision)).status,'blocked');await f.product.appendWorkMessage('mission',{commandId:'note-unknown',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'note-unknown',replyTo:null,text:'Discuss a separate follow-up; do not retry original'});const before=await f.current(),m=before.value.conversations![0]!.messages[0]!;await f.product.admit('mission',{commandId:'separate',expectedRevision:before.revision,workId:'separate',title:'New separate responsibility',budget:8,conversationSource:{workId:'fresh',messageId:m.id,messageHash:hash(m)}});assert.deepEqual((await f.current()).value.works.filter(w=>w.id!=='separate'),before.value.works);assert.equal(f.calls.length,1);const journal=await f.journal();f.release();await new Promise(r=>setTimeout(r,20));assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,1);
});
