import {harness,reply} from './support/workbench-client.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {runInContext} from 'node:vm';
import {correctionFixture} from './support/owner-correction-fixture.ts';
import {workInputHash} from '../src/domain.ts';
async function fixture(t:any,durable=false,mode?:any){const f=await correctionFixture(t,durable,mode);await f.product.appendWorkMessage('mission',{commandId:'source-message',expectedRevision:(await f.current()).revision,workId:'work',messageId:'source-message',replyTo:null,text:'Literal original <img src=x> 원문 😀'});return f;}
async function choose(app:any){app.node('conversation-work-source').value=JSON.stringify(['work','source-message']);await app.node('conversation-work-source').fire('change');app.node('conversation-work-title').value='Edited requested new task';await app.node('conversation-work-title').fire('input');app.node('conversation-work-budget').value='8';await app.node('conversation-work-budget').fire('input');await app.node('conversation-work-review').fire('click');}
for(const durable of [false,true]){
 const options={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} owner original selection/edit/review/private cancel/save preserves original and exact sequence/prerequisite hash`,options,async t=>{const f=await fixture(t,durable),app=await f.client(),before=await f.current();await choose(app);assert.equal(app.node('conversation-work-save').disabled,false);assert.match(app.node('conversation-work-original').textContent,/Literal original/);await app.node('conversation-work-cancel').fire('click');assert.equal(f.writes(),0);assert.deepEqual(await f.current(),before);await choose(app);await app.submit('conversation-work-form');const now=await f.current(),w=now.value.works.at(-1)!;assert.deepEqual(now.value.works.slice(0,-1),before.value.works);assert.deepEqual(now.value.conversations,before.value.conversations);assert.equal(w.title,'Edited requested new task');assert.equal(w.runtimeRun,undefined);assert.equal(f.writes(),1);assert.equal(f.calls.length,2);assert.match(app.node('conversation-work-status').textContent,/confirmed/);const clientHash=await runInContext('sequenceHash(sequenceInput(snapshot.value.works.at(-1)))',app.context);assert.equal(clientHash,workInputHash(w));assert.equal(app.all().some(n=>n.tagName==='IMG'),false);});
 test(`${durable?'actual DB':'memory'} stale revision retains private draft and requires explicit review`,options,async t=>{const f=await fixture(t,durable),app=await f.client();await choose(app);await f.product.admit('mission',{commandId:'peer',expectedRevision:(await f.current()).revision,workId:'peer',title:'Peer separate Work',budget:8});const r=(await f.current()).revision;await app.tick();await f.until(()=>runInContext('snapshot.revision',app.context)===r&&!runInContext('loading',app.context));await app.submit('conversation-work-form');assert.equal(f.writes(),0);assert.equal(app.node('conversation-work-title').value,'Edited requested new task');await app.node('conversation-work-review').fire('click');await app.submit('conversation-work-form');assert.equal(f.writes(),1);});
 test(`${durable?'actual DB':'memory'} lost ACK settles by exact receipt with no reload replay`,options,async t=>{const f=await fixture(t,durable,'unknown'),app=await f.client();await choose(app);await app.submit('conversation-work-form');await app.tick();await f.until(()=>runInContext('unknownOperation',app.context)===null);assert.equal(f.writes(),1);assert.equal((await f.current()).value.works.filter(w=>w.conversationSource).length,1);const fresh=await f.client();await fresh.submit('conversation-work-form');assert.equal(f.writes(),1);});
}
test('late committed response preserves later private edits and moved focus',async t=>{const f=await fixture(t,false,'held'),app=await f.client();await choose(app);const pending=app.submit('conversation-work-form');await f.until(()=>f.writes()===1);app.node('conversation-work-title').value='Later private task';await app.node('conversation-work-title').fire('input');app.node('sequence-summary').focus();f.release();await pending;assert.equal(app.node('conversation-work-title').value,'Later private task');assert.equal(runInContext('document.activeElement.id',app.context),'sequence-summary');});
for(const mode of ['held','held-unknown','held-rejected'])test(`${mode} reply does not restore a previously selected Mission`,async t=>{const f=await fixture(t,false,mode),app=await f.client();await choose(app);const pending=app.submit('conversation-work-form');await f.until(()=>f.writes()===1);await runInContext("loadMission('other',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='other');f.release();await pending;assert.equal(app.node('loaded-id').textContent,'other');assert.equal(f.writes(),1);});
test('wrong-feed response uses original receipt readback and never repeats admission',async t=>{const f=await fixture(t,false,'wrong-feed'),app=await f.client();await choose(app);await app.submit('conversation-work-form');assert.equal(f.writes(),1);assert.equal((await f.current()).value.works.filter(w=>w.conversationSource).length,1);assert.match(app.node('conversation-work-status').textContent,/confirmed/);await app.submit('conversation-work-form');assert.equal(f.writes(),1);assert.equal(f.calls.length,2);});

for(const durable of [false,true])test(`${durable?'actual DB':'memory'} same-ID database replacement invalidates reviewed source while retaining private task and performs no write`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const first=await fixture(t,durable),second=await fixture(t,durable);let base=first.base,writes=0;const app=harness(async(path:string,options:any)=>{if(path.endsWith('/work')&&options.method==='POST')writes++;const response=await fetch(base+path,options);return reply(await response.json(),response.status);},{},undefined,{network:true,fragment:'#mission=mission'});await first.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);await choose(app);const one=await first.journal(),two=await second.journal();base=second.base;await app.windowEvent('online');await app.tick();const deadline=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('conversation-work-fields').disabled){assert.ok(Date.now()<deadline,'Replacement feed did not recover');await app.tick();await new Promise(r=>setTimeout(r,10));}assert.equal(app.node('conversation-work-title').value,'Edited requested new task');assert.equal(app.node('conversation-work-save').disabled,true);await app.submit('conversation-work-form');assert.equal(writes,0);assert.deepEqual(await first.journal(),one);assert.deepEqual(await second.journal(),two);
});
