import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createWorkbench} from '../src/server.ts';
import {documentUsageFixture} from './support/document-usage-fixture.ts';
import {harness,reply,selectionField} from './support/workbench-client.ts';
async function setup(t:import('node:test').TestContext,durable=false){
 const f=await documentUsageFixture(t,durable);await f.product.create({id:'other',purpose:'Other Mission',scope:'other',constraints:[],criteria:{version:1,description:'Other source',oracle:'manual-review/v1'}},'other');const server=createWorkbench(f.store,f.root,{artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port;let mode='',held=false,release!:()=>void;
 const handler=async(path:string,options:any)=>{const response=await fetch(base+path,options),body=await response.json();if(path.includes('/document-usage?')){if(mode==='hold'){held=true;await new Promise<void>(r=>release=r);}if(mode==='feed')body.feedId='wrong';if(mode==='hash')body.document.content='Tampered';if(mode==='omit'){body.uses=[];body.totalUses=0;}if(mode==='reason')body.uses[0].decision.reason='Forged';if(mode==='record')body.uses[0].record.checksum='0'.repeat(64);if(mode==='extra')body.uses[0].authority='grant';if(mode==='failure')return reply({error:'Owned exact use unavailable'},503);}return reply(body,response.status);};const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission',identity:'use-client'});
 async function until(check:()=>boolean){const deadline=Date.now()+10000;while(!check()){assert.ok(Date.now()<deadline,'source-use panel deadline');await new Promise(r=>setTimeout(r,5));}}await until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('document-fields').disabled);
 async function choose(version=1){const q=f.query(version);app.node('document-choice').value=JSON.stringify([q.id,q.version,q.contentSha256]);await app.node('document-choice').fire('change');}
 return {...f,app,choose,until,node:(id:string)=>selectionField(app,id),mode(v:string){mode=v;held=false;},held:()=>held,release(){mode='';release();}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} source-use panel checks v1/Record/v2 pins, literal decisions and navigation to exact accepted text without writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),journal=await f.journal();f.app.node('work-title').value='Private draft retained';assert.equal(f.app.calls.some(c=>c.path.includes('/document-usage?')),false);await f.choose();f.app.node('document-usage').focus();await f.app.node('document-usage').fire('click');assert.match(f.app.node('document-usage-results').textContent,/1 Work uses.*source-accepted.*record-source-accepted/s);assert.match(f.app.node('document-usage-results').textContent,/Owner original decision source-accepted <img src=x>/);assert.equal(f.app.all().some(n=>n.tagName==='IMG'),false);assert.equal((f.app.context as any).document.activeElement.id,'document-usage');await f.node('document-usage-work-source-accepted').fire('click');assert.equal((f.app.context as any).document.activeElement.id,'work-heading-source-accepted');assert.equal(f.node('work-evidence-summary-source-accepted').parentElement!.open,true);await f.node('document-usage-record-source-accepted').fire('click');assert.equal((f.app.context as any).document.activeElement.id,'work-record-text-read-source-accepted');assert.equal(f.app.calls.some(c=>c.path.includes('/record-artifact?')),false);await f.node('work-record-text-read-source-accepted').fire('click');assert.match(f.node('work-record-text-content-source-accepted').textContent,/Exact accepted fixture/);await f.choose(2);await f.app.node('document-usage').fire('click');assert.match(f.app.node('document-usage-results').textContent,/source-later.*No accepted Record/s);assert.doesNotMatch(f.app.node('document-usage-results').textContent,/source-accepted/);assert.equal(f.app.node('work-title').value,'Private draft retained');assert.equal(f.app.calls.some(c=>c.options?.method==='POST'),false);assert.deepEqual(await f.journal(),journal);
});
test('source-use reply rejects omitted uses, hash/feed/decision/Record forgery and failure without fallback',async t=>{
 const f=await setup(t),journal=await f.journal();for(const mode of ['feed','hash','omit','reason','record','extra','failure']){await f.choose();f.mode(mode);await f.app.node('document-usage').fire('click');assert.match(f.app.node('document-read-status').textContent,/not verified/);assert.equal(f.app.node('document-usage-results').textContent,'');assert.equal(f.app.node('document-usage').disabled,false);}f.mode('');await f.app.node('document-usage').fire('click');assert.match(f.app.node('document-usage-results').textContent,/record-source-accepted/);assert.deepEqual(await f.journal(),journal);
});
test('held source-use cancel suppresses duplicate and late ignored-abort response and preserves moved focus/private source draft',async t=>{
 const f=await setup(t),journal=await f.journal();await f.choose();f.app.node('document-content').value='Private next source';await f.app.node('document-content').fire('input');const draft=f.app.node('document-base').textContent;f.mode('hold');f.app.node('document-usage').focus();const pending=f.app.node('document-usage').fire('click');await f.until(f.held);assert.equal(f.app.node('document-usage').disabled,true);await f.app.node('document-usage').fire('click');assert.equal(f.app.calls.filter(c=>c.path.includes('/document-usage?')).length,1);f.app.node('work-title').focus();await f.app.node('document-read-cancel').fire('click');const call=f.app.calls.find(c=>c.path.includes('/document-usage?'))!;assert.equal(call.options.signal.aborted,true);f.release();await pending;assert.equal(f.app.node('document-usage-results').textContent,'');assert.match(f.app.node('document-read-status').textContent,/cancelled/);assert.equal((f.app.context as any).document.activeElement.id,'work-title');assert.equal(f.app.node('document-content').value,'Private next source');assert.equal(f.app.node('document-base').textContent,draft);assert.deepEqual(await f.journal(),journal);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} source-use reply after new snapshot/Mission/source/reconnect is discarded until deliberate new exact read`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable);await f.choose();let sequence=0;for(const change of ['source','mission','snapshot','reconnect']){f.mode('hold');const pending=f.app.node('document-usage').fire('click');await f.until(f.held);const old=f.app.calls.filter(c=>c.path.includes('/document-usage?')).at(-1)!;
  if(change==='source')await f.choose(2);
  if(change==='mission'){await f.app.navigateFragment('#mission=other');await f.until(()=>f.app.node('loaded-id').textContent==='other'&&!f.app.node('document-fields').disabled);}
  if(change==='snapshot'){await f.product.admit('mission',{commandId:'snapshot-'+(++sequence),expectedRevision:(await f.store.load('mission'))!.revision,workId:'new-'+sequence,title:'Other owner responsibility',budget:0});const revision=(await f.store.load('mission'))!.revision;await f.app.submit('load-form');await f.until(()=>JSON.parse(f.app.node('snapshot-json').textContent || '{}').revision===revision&&!f.app.node('document-fields').disabled);}
  if(change==='reconnect'){await f.app.windowEvent('offline');await f.app.windowEvent('online');await f.until(()=>f.app.node('sync-notice').hidden&&!f.app.node('document-fields').disabled);}
  assert.equal(old.options.signal.aborted,true,change);f.release();await pending;assert.equal(f.app.node('document-usage-results').textContent,'');if(change==='mission'){await f.app.navigateFragment('#mission=mission');await f.until(()=>f.app.node('loaded-id').textContent==='mission'&&!f.app.node('document-fields').disabled);}await f.choose();assert.equal(f.app.node('document-usage').disabled,false);
 }const before=await f.journal();await f.app.node('document-usage').fire('click');assert.match(f.app.node('document-usage-results').textContent,/record-source-accepted/);assert.deepEqual(await f.journal(),before);assert.equal(f.app.calls.some(c=>c.options?.method==='POST'),false);
});
test('source-use keyboard cancel focus returns to usage button and zero-use evidence is explicit',async t=>{
 const f=await setup(t);await f.choose();f.mode('hold');const pending=f.app.node('document-usage').fire('click');await f.until(f.held);f.app.node('document-read-cancel').focus();await f.app.node('document-read-cancel').fire('click');assert.equal((f.app.context as any).document.activeElement.id,'document-usage');f.release();await pending;await f.product.captureDocument('mission',{commandId:'unused',expectedRevision:(await f.store.load('mission'))!.revision,document:{id:'document:unused',version:1,title:'Unused',content:'Unused source',source:'Owner'}});await f.app.submit('load-form');await f.until(()=>!f.app.node('document-fields').disabled);const d=(await f.store.load('mission'))!.value.documents!.at(-1)!;f.app.node('document-choice').value=JSON.stringify([d.id,d.version,d.contentSha256]);await f.app.node('document-choice').fire('change');await f.app.node('document-usage').fire('click');assert.match(f.app.node('document-usage-results').textContent,/0 Work uses/);
});
test('direct source-use Record navigation opens both closed ancestors before focusing visible read control',async t=>{
 const f=await setup(t);await f.choose();await f.app.node('document-usage').fire('click');const outer=f.node('work-evidence-summary-source-accepted').parentElement!,inner=f.node('work-record-text-summary-source-accepted').parentElement!;outer.open=false;inner.open=false;await f.node('document-usage-record-source-accepted').fire('click');assert.equal(outer.open,true);assert.equal(inner.open,true);assert.equal((f.app.context as any).document.activeElement.id,'work-record-text-read-source-accepted');assert.equal(f.app.calls.some(c=>c.path.includes('/record-artifact?')),false);await f.node('work-record-text-read-source-accepted').fire('click');assert.match(f.node('work-record-text-content-source-accepted').textContent,/Exact accepted fixture/);
});
