import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {join} from 'node:path';
import {Application} from '../src/application.ts';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {readDocumentUsage} from '../src/documents.ts';
import {hash} from '../src/domain.ts';
import type {Mission,Command} from '../src/domain.ts';
import type {Store} from '../src/storage.ts';
import {SurrealStore} from '../src/storage.ts';
import {exportPortableBackup,restorePortableBackup} from '../src/portable-backup.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {documentUsageFixture as fixture,usageDocument as doc} from './support/document-usage-fixture.ts';
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal exact source-use query binds original Work/accepted Record and v2 separately with no writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port,feed=(await f.store.readState()).feedId,journal=await f.journal(),state=(await f.store.load('mission'))!;
 const get=async(version:number,identity=feed,sha?:string)=>{const q=f.query(version),r=await fetch(base+'/missions/mission/document-usage?id='+q.id+'&version='+q.version+'&sha256='+(sha??q.contentSha256),{headers:{'X-Massion-Feed':identity}});return {status:r.status,body:await r.json()};};const first=await get(1);assert.equal(first.status,200);assert.equal(first.body.totalUses,1);assert.equal(first.body.uses[0].workId,'source-accepted');assert.equal(first.body.uses[0].decision.reason,'Owner original decision source-accepted <img src=x>');assert.equal(first.body.uses[0].record.id,'record-source-accepted');assert.equal(first.body.uses[0].record.checksum,state.value.works[1]!.record!.checksum);assert.equal(first.body.uses[0].record.evidenceClass,'fixture');assert.equal(first.body.document.content,doc().content);assert.equal(first.body.revision,state.revision);const second=await get(2);assert.equal(second.body.uses[0].workId,'source-later');assert.equal(second.body.uses[0].record,undefined);assert.equal((await get(1,feed,'0'.repeat(64))).status,409);assert.equal((await get(1,'wrong')).status,409);
 for(const suffix of ['&version=2','&path=/etc/passwd','&query=anything']){const q=f.query(),r=await fetch(base+'/missions/mission/document-usage?id='+q.id+'&version=1&sha256='+q.contentSha256+suffix);assert.equal(r.status,400);}assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.store.load('mission'))!.value.works[0],f.original.value.works[0]);
 if(durable){assert.ok(f.store instanceof SurrealStore);const backup=await exportPortableBackup(f.store,f.artifacts),{store:restored}=await growthStore(true);assert.ok(restored instanceof SurrealStore);await restorePortableBackup(backup,restored,join(f.root,'restored'));const read=(await readDocumentUsage(restored,'mission',f.query()))!;assert.deepEqual(read.uses,first.body.uses);assert.deepEqual(read.document,first.body.document);assert.deepEqual(await restored.exportJournal(),await f.store.exportJournal());}
});
test('source use rejects missing/tampered originals or record/source decisions and never returns substituted or inferred uses',async t=>{
 const f=await fixture(t),state=await f.store.readState('mission'),before=await f.journal();for(const mutate of [(m:Mission)=>m.documents![0]!.content='Changed',(m:Mission)=>m.documents!.shift(),(m:Mission)=>m.works[1]!.sourceDocuments![0]!.document=m.documents![1]!,(m:Mission)=>m.works[1]!.record!.sourceDocuments![0]!.reason='Forged',(m:Mission)=>{delete m.works[1]!.record!.sourceDocuments;const {checksum,...bundle}=m.works[1]!.record!;m.works[1]!.record!.checksum=hash(bundle);}]){const copy=structuredClone(state);mutate(copy.snapshot!.value);await assert.rejects(readDocumentUsage({readState:async()=>copy} as Store<Mission>,'mission',f.query()),/integrity/);}const copied=structuredClone(state);copied.snapshot!.value.relations.push({from:'inferred-only',to:'document:source',type:'depends-on',fromVersion:1,toVersion:1,provenance:'Not actual Work input',inferred:true});const read=(await readDocumentUsage({readState:async()=>copied} as Store<Mission>,'mission',f.query()))!;assert.equal(read.totalUses,1);assert.deepEqual(await f.journal(),before);
});
test('source-use results are bounded with explicit total, valid unused source reports zero and another Mission is isolated',async t=>{
 const f=await fixture(t);for(let n=0;n<20;n++)await f.work('bounded-'+n);const read=(await readDocumentUsage(f.store,'mission',f.query()))!;assert.equal(read.totalUses,21);assert.equal(read.uses.length,20);assert.equal(read.limit,20);await f.product.captureDocument('mission',{commandId:'unused',expectedRevision:(await f.store.load('mission'))!.revision,document:{...doc(),id:'document:unused'}});const d=(await f.store.load('mission'))!.value.documents!.at(-1)!;assert.equal((await readDocumentUsage(f.store,'mission',{id:d.id,version:1,contentSha256:d.contentSha256}))!.totalUses,0);await f.product.create({id:'other',purpose:'Other Mission',scope:'other',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'other');assert.equal(await readDocumentUsage(f.store,'other',f.query()),null);for(const q of [{...f.query(),version:0},{...f.query(),id:'file:///etc/passwd'},{...f.query(),contentSha256:'invalid'}])await assert.rejects(readDocumentUsage(f.store,'mission',q));
});
test('actual SurrealDB normal CLI exact source-use and original accepted Record survive owned process restart with no query writes',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const {spawn}=await import('node:child_process'),{createServer}=await import('node:net'),{fileURLToPath}=await import('node:url'),{stopOwnedChild}=await import('./support/owned-process.ts');let child:ReturnType<typeof spawn>|undefined,log='',cwd='';const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry];async function stop(){if(child)await stopOwnedChild(child,{cwd,argv});}t.after(stop);const f=await fixture(t,true,true);cwd=f.root;assert.ok(f.store instanceof SurrealStore);const transport=f.transport!;const database=(await transport.query('RETURN $session.db;',{}))[0] as string,probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const a=probe.address();assert.ok(a&&typeof a==='object');const port=a.port;await new Promise<void>(r=>probe.close(()=>r()));const base='http://127.0.0.1:'+port;
 async function start(){child=spawn(process.execPath,[entry],{cwd,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',b=>log+=b);child.stderr!.on('data',b=>log+=b);const deadline=Date.now()+10000;while(true){try{if((await fetch(base+'/health')).ok)return;}catch{}assert.ok(child.exitCode===null&&Date.now()<deadline,log);await new Promise(r=>setTimeout(r,10));}}
 const q=f.query(),path='/missions/mission/document-usage?id='+q.id+'&version=1&sha256='+q.contentSha256,journal=await f.journal();await start();const first=child!.pid,read=await (await fetch(base+path)).json();assert.equal(read.uses[0].record.id,'record-source-accepted');await stop();await start();assert.notEqual(child!.pid,first);assert.deepEqual(await (await fetch(base+path)).json(),read);assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.store.load('mission'))!.value.works[0],f.original.value.works[0]);t.diagnostic(JSON.stringify({distinctNormalCliPids:true,sourceV1AndRecordRetained:true,readOnlyJournalUnchanged:true,liveCalls:0}));
});
