import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {ConfiguredTextRuntime} from '../src/configured-runtime.ts';
import {Application} from '../src/application.ts';
import {apply} from '../src/domain.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {createWorkbench} from '../src/server.ts';
import {readWorkInterventionHistory} from '../src/work-budget-history.ts';
async function stranded(t:import('node:test').TestContext,durable:boolean,stage:'activation'|'pending'|'unknown'|'succeeded'='pending'){
 const f=await fixture(t,durable,{runTimeoutMs:durable?1500:150});const base=f.store;
 const store=new Proxy(base,{get(target,key){if(key==='commit')return async(input:any)=>{const result=await target.commit(input);if(stage==='activation'&&input.commandId==='stranded-run')throw Error('Controlled committed activation ACK loss');return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new ConfiguredTextRuntime(store,f.config),internal=runtime as any;
 if(stage!=='activation'){const send=internal.dispatch.bind(runtime);internal.dispatch=async(id:string,command:any,...rest:any[])=>{const result=await send(id,command,...rest);if(command.type==='claim-provider-dispatch')throw Error('Controlled committed claim ACK loss');return result;};}
 await assert.rejects(runtime.run('mission','fresh','stranded-run',(await f.current()).revision));assert.equal(f.calls.length,0);
 if(stage==='unknown'||stage==='succeeded'){const w=(await f.current()).value.works.find(w=>w.id==='fresh')!,effect=w.effects[0]!,app=new Application(base,[{id:'host-executor',roles:['executor']}]);await app.dispatch({missionId:'mission',commandId:'original-receipt',expectedRevision:(await f.current()).revision,actorId:'host-executor',command:{type:'receipt',workId:'fresh',effectId:effect.id,providerDispatchId:effect.providerDispatch!.id,outcome:stage,receipt:'Original controlled receipt',usage:stage==='unknown'?null:1}});}
 const current=await f.current(),w=current.value.works.find(w=>w.id==='fresh')!,o=w.runtimeRun!.ownership!;return {...f,before:current,command:()=>({type:'close-expired-runtime' as const,workId:'fresh',runId:w.runtimeRun!.id,dispatchId:o.dispatchId,hostSessionId:o.hostSessionId,deadlineAt:o.deadlineAt,observedAt:Date.now(),reason:'Owner inspected original expired run; no replay',acknowledgeUncertainOutcome:true as const}),elapsed:async()=>{await new Promise(r=>setTimeout(r,Math.max(0,o.deadlineAt-Date.now())+10));}};
}
for(const durable of [false,true])for(const stage of ['activation','pending','unknown','succeeded'] as const)test(`${durable?'actual SurrealDB':'memory'} owner expired ${stage} closure preserves originals and never dispatches`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await stranded(t,durable,stage);await f.elapsed();const command=f.command(),input={commandId:'owner-expired',expectedRevision:f.before.revision,command},result=await f.product.intervene('mission',input);assert.equal(result.status,'committed');const after=await f.current(),w=after.value.works.find(w=>w.id==='fresh')!,old=f.before.value.works.find(w=>w.id==='fresh')!;
 assert.deepEqual(w.runtimeRun,old.runtimeRun);assert.equal(w.execution,'blocked');assert.equal(w.runtimeInterruption?.reason,'deadline');assert.equal(w.runtimeInterruption?.observedAt,command.observedAt);assert.deepEqual(w.effects.map(e=>e.providerDispatch),old.effects.map(e=>e.providerDispatch));assert.deepEqual(w.budget,{...old.budget,measured:stage==='pending'?null:old.budget.measured});assert.deepEqual(w.effects,old.effects.map(e=>e.status==='pending'?{...e,status:'unknown'}:e));assert.equal(w.record,undefined);assert.deepEqual(after.value.works[0],f.before.value.works[0]);assert.deepEqual(after.value.conversations,f.before.value.conversations);assert.equal(f.calls.length,0);
 const journal=await f.journal();validateMissionJournalLineage(journal);assert.equal((await f.product.intervene('mission',input)).status,'replayed');assert.equal((await f.product.intervene('mission',{...input,command:{...command,reason:'Changed decision'}})).status,'conflict');assert.deepEqual(await f.journal(),journal);assert.equal((await new ConfiguredTextRuntime(f.store,f.config).run('mission','fresh','never-replay',after.revision)).status,'already-started');assert.deepEqual(await f.journal(),journal);
 const history=await readWorkInterventionHistory(f.store,'mission','fresh',{after:0,limit:100});assert.equal(history!.changes.at(-1)!.action,'close-expired-runtime');assert.equal(history!.changes.at(-1)!.reason,command.reason);assert.throws(()=>apply(after.value,{type:'block-work',workId:'fresh',blocker:{code:'runtime_unavailable',detail:'late progression'}},{id:'rep',roles:['representative']}));
 if(durable){const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{SurrealStore}=await import('../src/storage.ts'),{store:target}=await growthStore(true);assert.ok(f.store instanceof SurrealStore&&target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/restored');assert.deepEqual((await target.load('mission'))!.value,after.value);}
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'memory'} exact binding/time/ack/role/CAS gates reject without journal changes; cancelled remains cancelled`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await stranded(t,durable),original=await f.journal(),input=()=>({commandId:crypto.randomUUID(),expectedRevision:f.before.revision,command:f.command()});await assert.rejects(f.product.intervene('mission',{...input(),command:{...f.command(),observedAt:f.before.value.works.find(w=>w.id==='fresh')!.runtimeRun!.ownership!.startedAt}}),/time mismatch/);await f.elapsed();
 for(const change of [{runId:'other'},{dispatchId:'other'},{hostSessionId:'other'},{deadlineAt:f.command().deadlineAt+1},{observedAt:f.command().deadlineAt-1},{observedAt:Date.now()+60000},{acknowledgeUncertainOutcome:false},{reason:''},{extra:true}])await assert.rejects(f.product.intervene('mission',{...input(),command:{...f.command(),...change} as any}));
 const app=new Application(f.store,[{id:'host-rep',roles:['representative']}]);await assert.rejects(app.dispatch({missionId:'mission',commandId:'wrong-role',expectedRevision:f.before.revision,actorId:'host-rep',command:f.command()}));assert.deepEqual(await f.journal(),original);
 await f.product.intervene('mission',{commandId:'cancel-original',expectedRevision:f.before.revision,command:{type:'cancel',workId:'fresh'}});assert.equal((await f.product.intervene('mission',input())).status,'conflict');await f.product.intervene('mission',{commandId:'close-cancelled',expectedRevision:(await f.current()).revision,command:f.command()});assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.execution,'cancelled');validateMissionJournalLineage(await f.journal());assert.equal(f.calls.length,0);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'memory'} normal HTTP owner closure and lost committed ACK reconcile exact identity`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await stranded(t,durable,'activation');await f.elapsed();let lost=false;const store=new Proxy(f.store,{get(target,key){if(key==='commit')return async(input:any)=>{const result=await target.commit(input);if(input.commandId==='ack-closure'&&!lost){lost=true;throw Object.assign(Error('Controlled committed ACK loss'),{name:'CommitOutcomeUnknownError'});}return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),server=createWorkbench(store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const body={commandId:'ack-closure',expectedRevision:f.before.revision,command:f.command()},call=async(value:any)=>{const r=await fetch(`http://127.0.0.1:${address.port}/missions/mission/commands`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});return {status:r.status,body:await r.json()};};assert.equal((await call({...body,command:{...body.command,observedAt:Date.now()+60000}})).status,400);const first=await call(body);assert.equal(first.status,503);assert.equal(first.body.outcome,'unknown');const journal=await f.journal();assert.equal((await call(body)).body.status,'replayed');assert.deepEqual(await f.journal(),journal);assert.equal((await call({...body,commandId:'other-owner'})).status,409);assert.equal(f.calls.length,0);validateMissionJournalLineage(journal);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'memory'} two explicit owner contenders commit one closure; closed/accepted/unowned originals reject`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await stranded(t,durable,'activation');await f.elapsed();const command=f.command(),results=await Promise.all(['owner-a','owner-b'].map(commandId=>f.product.intervene('mission',{commandId,expectedRevision:f.before.revision,command})));assert.equal(results.filter(r=>r.status==='committed').length,1);assert.equal(results.filter(r=>r.status==='conflict').length,1);const current=await f.current(),journal=await f.journal();await assert.rejects(f.product.intervene('mission',{commandId:'closed-again',expectedRevision:current.revision,command}),/Closed or accepted/);
 for(const modify of [(w:any)=>{delete w.runtimeRun.ownership;},(w:any)=>{w.acceptance='accepted';},(w:any)=>{w.runtimeRecovery={runId:command.runId,actorId:'local-owner',reason:'Earlier quarantine',pendingEffectIds:[],unknownEffectIds:[]};}]){const value=structuredClone(f.before.value);modify(value.works.find(w=>w.id==='fresh'));assert.throws(()=>apply(value,command,{id:'local-owner',roles:['owner']}));}
 assert.deepEqual(await f.journal(),journal);validateMissionJournalLineage(journal);assert.equal(f.calls.length,0);
});
