/** Actual normal CLI processes, disposable durable state and credential-free loopback providers. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import type {ChildProcess} from 'node:child_process';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHttpRpcTransport} from '../src/storage.ts';
import {harness,reply} from './support/workbench-client.ts';
const entrypoint=fileURLToPath(new URL('../src/server.ts',import.meta.url));
async function freePort(){const socket=createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const address=socket.address();assert.ok(address&&typeof address==='object');const port=address.port;await new Promise<void>(r=>socket.close(()=>r()));return port;}
async function stop(child:ChildProcess){if(child.exitCode!==null||child.signalCode!==null)return;const exit=once(child,'exit');child.kill('SIGTERM');const timer=setTimeout(()=>child.kill('SIGKILL'),3000);try{await exit;}finally{clearTimeout(timer);}}
async function until<T>(read:()=>Promise<T>,ready:(value:T)=>boolean){const end=Date.now()+10000;while(true){const value=await read();if(ready(value))return value;assert.ok(Date.now()<end,'CLI state deadline');await new Promise(r=>setTimeout(r,10));}}

test('invalid normal CLI manifest fails before database access and does not log raw fields',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-cli-invalid-'));t.after(()=>rm(root,{recursive:true,force:true}));const file=join(root,'invalid.json');await writeFile(file,JSON.stringify({version:1,revision:'bad',mode:'https',connections:[],apiKey:'synthetic-private-sentinel'}));
 const child=spawn(process.execPath,[entrypoint,'--host-config',file],{cwd:root,env:{MASSION_SURREAL_RPC:'http://127.0.0.1:1/rpc'},stdio:['ignore','pipe','pipe']});t.after(()=>stop(child));let output='';child.stdout!.on('data',data=>output+=String(data));child.stderr!.on('data',data=>output+=String(data));const [code]=await once(child,'exit');assert.notEqual(code,0);assert.match(output,/Host configuration/);assert.doesNotMatch(output,/synthetic-private-sentinel|fetch failed|ECONNREFUSED/);
});

test('normal CLI host setup reaches native fixture Work and preserves accepted/cancelled/unknown state on restart without replay',{skip:!process.env.MASSION_TEST_SURREAL_RPC},async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-cli-work-'));t.after(()=>rm(root,{recursive:true,force:true}));const db='host_cli_'+crypto.randomUUID().replaceAll('-','');const rpc=process.env.MASSION_TEST_SURREAL_RPC!;const namespace=process.env.MASSION_TEST_SURREAL_NAMESPACE!;const transport=createHttpRpcTransport({endpoint:rpc,namespace,database:db});await transport.query('DEFINE DATABASE '+db+';',{});
 const sends:string[]=[],discovery:string[]=[];let releaseExecutor:(()=>void)|undefined;t.after(()=>releaseExecutor?.());
 const provider=createServer(async(req,res)=>{
  res.setHeader('content-type','application/json');assert.equal(req.headers.authorization,undefined);assert.equal(req.headers['x-api-key'],undefined);assert.equal(req.headers['x-goog-api-key'],undefined);
  const gemini=req.url!.startsWith('/gemini/');if(req.method==='GET'){discovery.push(req.url!);res.end(JSON.stringify(gemini?{models:[{name:'models/review',displayName:'Review',supportedGenerationMethods:['generateContent'],outputTokenLimit:16}]}:{data:['exec','slow','unknown','undeclared'].map(id=>({id,display_name:id}))}));return;}
  let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw),model=gemini?'review':body.model;const prompt=JSON.parse(gemini?body.contents[0].parts[0].text:body.messages[0].content);sends.push(model);
  if(model==='exec')await new Promise<void>(resolve=>releaseExecutor=resolve);
  if(model==='unknown'){req.socket.destroy();return;}
  if(model==='slow'){const timer=setTimeout(()=>res.end('{}'),20000);res.once('close',()=>clearTimeout(timer));return;}
  const output=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'CLI fixture result',reason:'Synthetic exact evidence'}]}):'CLI fixture result';
  res.end(JSON.stringify(gemini?{responseId:'fixture',modelVersion:model,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:output}]}}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:2,totalTokenCount:5}}:{id:'fixture',type:'message',role:'assistant',model,stop_reason:'end_turn',content:[{type:'text',text:output}],usage:{input_tokens:3,output_tokens:2}}));
 });provider.listen(0,'127.0.0.1');await once(provider,'listening');t.after(async()=>{provider.closeAllConnections();await new Promise<void>(r=>provider.close(()=>r()));});const address=provider.address();assert.ok(address&&typeof address==='object');
 const file=join(root,'host.json');const manifest={version:1,revision:'fixture-v1',mode:'local-http-mock',connections:[{id:'executor',label:'Native fixture',providerType:'anthropic',baseUrl:`http://127.0.0.1:${address.port}/anthropic/v1/`,models:['exec','slow','unknown']},{id:'verifier',label:'Reviewer fixture',providerType:'gemini',baseUrl:`http://127.0.0.1:${address.port}/gemini/v1beta/`,models:['review']}]};await writeFile(file,JSON.stringify(manifest));
 async function start(configured:boolean){
  const port=await freePort();let logs='';const child=spawn(process.execPath,[entrypoint,...(configured?['--host-config',file]:[])],{cwd:root,env:{MASSION_SURREAL_RPC:rpc,MASSION_SURREAL_NAMESPACE:namespace,MASSION_SURREAL_DATABASE:db,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});t.after(()=>stop(child));child.stdout!.on('data',data=>logs+=String(data));child.stderr!.on('data',data=>logs+=String(data));const end=Date.now()+10000;
  while(!logs.includes('Massion development workbench:')){assert.equal(child.exitCode,null,logs);assert.ok(Date.now()<end,'CLI startup deadline: '+logs);await new Promise(r=>setTimeout(r,10));}
  const base='http://127.0.0.1:'+port;
  async function call(path:string,body?:unknown){const response=await fetch(base+path,{...(body===undefined?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),signal:AbortSignal.timeout(10000)});const value=await response.json();return {status:response.status,value};}
  return {child,base,call,logs:()=>logs};
 }
 const defaultHost=await start(false);assert.equal((await defaultHost.call('/connections')).value.host,null);assert.equal((await defaultHost.call('/connections')).value.runtime.connections.length,0);assert.equal(sends.length,0);await stop(defaultHost.child);
 let host=await start(true);let catalog=(await host.call('/connections')).value;assert.equal(catalog.host.revision,'fixture-v1');assert.equal(catalog.liveExecutionEnabled,false);assert.equal(catalog.runtime.connections.length,4);assert.equal(sends.length,0);assert.equal(discovery.length,0);
 const originalIds=catalog.connections.map((c:any)=>c.id);for(const connection of catalog.connections){const discovered=await host.call('/connections/'+connection.id+'/models',{expectedConfigHash:connection.configHash});assert.equal(discovered.status,200);assert.equal(discovered.value.status,'listed');assert.equal(discovered.value.models.some((m:any)=>m.id==='undeclared'),false);}
 assert.equal(discovery.length,2);assert.equal(sends.length,0);const executorConnection=catalog.connections[0];assert.equal((await host.call('/connections',{id:executorConnection.id,label:'Tampered',providerType:'compatible',baseUrl:'https://attacker.example/v1/',mode:'https',secretRef:'fake-reference'})).status,400);assert.equal((await host.call('/connections/'+executorConnection.id+'/profiles',{model:'undeclared',label:'Other',expectedConfigHash:executorConnection.configHash})).status,400);
 const selected=await host.call('/connections/'+executorConnection.id+'/profiles',{model:'exec',label:'Owner selection',expectedConfigHash:executorConnection.configHash});assert.equal(selected.status,200);catalog=(await host.call('/connections')).value;
 async function prepare(id:string,model:string){
  const exec=catalog.runtime.connections.find((p:any)=>p.model===model),verify=catalog.runtime.connections.find((p:any)=>p.model==='review');const grant=await host.call('/connection-authorizations',{id:'grant-'+id,scope:id,executorProfileId:exec.id,verifierProfileId:verify.id,maxOutputTokensPerCall:8,expectedConfigHash:catalog.configHash});assert.equal(grant.status,200);catalog=grant.value;
  assert.equal((await host.call('/missions',{id,commandId:'create-'+id,purpose:'Normal CLI fixture',scope:id,constraints:[],criteria:{version:1,description:'CLI fixture result',oracle:'bounded-text-review/v1'}})).status,201);
  assert.equal((await host.call('/missions/'+id+'/work',{commandId:'admit-'+id,expectedRevision:1,workId:'work',title:'Explicit CLI Work',budget:16})).status,201);
  const selection={executorProfileId:exec.id,verifierProfileId:verify.id,authorizationId:'grant-'+id,outputTokenCap:8};const checked=await host.call('/missions/'+id+'/preflight',{commandId:'check-'+id,expectedRevision:2,workId:'work',selection});assert.equal(checked.status,200);assert.equal(checked.value.diagnostics.length,0);return selection;
 }
 const acceptedChoice=await prepare('accepted','exec');assert.equal(sends.length,0);const stale=await host.call('/missions/accepted/run',{commandId:'stale',expectedRevision:1,workId:'work',selection:acceptedChoice});assert.equal(stale.status,409);assert.equal(sends.length,0);
 const acceptedPending=host.call('/missions/accepted/run',{commandId:'run-accepted',expectedRevision:2,workId:'work',selection:acceptedChoice});void acceptedPending.catch(()=>{});await until(async()=>sends.includes('exec'),Boolean);const gracefulExit=once(host.child,'exit');host.child.kill('SIGTERM');await new Promise(r=>setTimeout(r,100));assert.equal(host.child.exitCode,null,'Graceful shutdown must wait for the admitted provider result');releaseExecutor!();const acceptedRun=await acceptedPending;assert.equal(acceptedRun.status,200);const [exitCode,exitSignal]=await gracefulExit;assert.equal(exitCode,0);assert.equal(exitSignal,null);host=await start(true);catalog=(await host.call('/connections')).value;assert.equal(catalog.runtime.authorizations.length,0);const accepted=(await host.call('/missions/accepted')).value;assert.equal(accepted.value.works[0].acceptance,'accepted');assert.equal(accepted.value.works[0].record.evidenceClass,'fixture');assert.deepEqual(sends,['exec','review']);
 const cancelledChoice=await prepare('cancelled','slow');const pending=host.call('/missions/cancelled/run',{commandId:'run-cancelled',expectedRevision:2,workId:'work',selection:cancelledChoice});await until(async()=>sends.includes('slow'),Boolean);const active=(await host.call('/missions/cancelled')).value;assert.equal((await host.call('/missions/cancelled/commands',{commandId:'cancel',expectedRevision:active.revision,command:{type:'cancel',workId:'work'}})).status,200);await pending;const cancelled=await until(async()=>(await host.call('/missions/cancelled')).value,s=>s.value.works[0].effects.some((e:any)=>e.status==='unknown'));assert.equal(cancelled.value.works[0].execution,'cancelled');assert.equal(cancelled.value.works[0].budget.measured,null);assert.equal(sends.filter(model=>model==='review').length,1);
 const unknownChoice=await prepare('unknown','unknown');await host.call('/missions/unknown/run',{commandId:'run-unknown',expectedRevision:2,workId:'work',selection:unknownChoice});const unknown=(await host.call('/missions/unknown')).value;assert.equal(unknown.value.works[0].effects[0].status,'unknown');assert.equal(unknown.value.works[0].record,undefined);assert.equal(unknown.value.works[0].budget.measured,null);assert.deepEqual(sends,['exec','review','slow','unknown']);
 await stop(host.child);manifest.revision='fixture-v2';await writeFile(file,JSON.stringify(manifest));const restarted=await start(true);const reload=(await restarted.call('/connections')).value;assert.equal(reload.runtime.authorizations.length,0);assert.notDeepEqual(reload.connections.map((c:any)=>c.id),originalIds);assert.deepEqual(sends,['exec','review','slow','unknown']);
 for(const [id,state,selection] of [['accepted',accepted,acceptedChoice],['cancelled',cancelled,cancelledChoice],['unknown',unknown,unknownChoice]] as const){assert.deepEqual((await restarted.call('/missions/'+id)).value,state);const result=await restarted.call('/missions/'+id+'/run',{commandId:'restart-'+id,expectedRevision:state.revision,workId:'work',selection});assert.equal(result.value.status,'already-started');assert.deepEqual((await restarted.call('/missions/'+id)).value,state);}
 const app=harness(async(path,init)=>{const response=await fetch(restarted.base+path,init);return reply(await response.json(),response.status);},{'massion.workbench.mission':'accepted'},undefined,{network:true});await until(async()=>app.node('work-list').textContent,text=>text.includes('Acceptance: accepted'));assert.equal(app.node('connection-fields').disabled,true);assert.equal(app.calls.filter(c=>c.options.method==='POST').length,0);assert.deepEqual(sends,['exec','review','slow','unknown']);assert.doesNotMatch(JSON.stringify(reload),/"secretRef"|"environment"/);await stop(restarted.child);
});
