import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createConnection} from 'node:net';
import {Application} from '../src/application.ts';
import {ConfiguredTextRuntime} from '../src/configured-runtime.ts';
import {createWorkbench} from '../src/server.ts';
import {HOST_SESSION_ID} from '../src/runtime-lifetime.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {growthStore} from './support/growth-fixture.ts';
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} owned drain settles ignored abort with original uncertainty, conversation and accepted Record intact`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:'executor'});await f.product.appendWorkMessage('mission',{commandId:'original-message',expectedRevision:(await f.current()).revision,workId:'work',messageId:'original-message',replyTo:null,text:'Original discussion <img src=x>'});const original=structuredClone((await f.current()).value),run=f.runtime.run('mission','fresh','drain-run',(await f.current()).revision);await f.until(()=>f.calls.length===1);const before=(await f.current()).value.works.find(w=>w.id==='fresh')!;f.runtime.beginDrain();const result=await run,w=result.snapshot.value.works.find(w=>w.id==='fresh')!;assert.equal(result.status,'blocked');assert.equal(w.runtimeInterruption?.reason,'host-shutdown');assert.ok(w.runtimeInterruption!.observedAt<w.runtimeRun!.ownership!.deadlineAt);assert.equal(w.runtimeRun?.ownership?.hostSessionId,HOST_SESSION_ID);assert.equal(w.effects[0]!.status,'unknown');assert.deepEqual(w.effects[0]!.providerDispatch,before.effects[0]!.providerDispatch);assert.equal(w.budget.reserved,4);assert.equal(w.budget.measured,null);assert.equal(w.record,undefined);assert.equal(f.calls[0]!.signal.aborted,true);assert.deepEqual(result.snapshot.value.conversations,original.conversations);assert.deepEqual(result.snapshot.value.works[0],original.works[0]);const journal=await f.journal();validateMissionJournalLineage(journal);f.runtime.beginDrain();f.release();await pause(30);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,1);const fresh=new ConfiguredTextRuntime(f.store,f.config);assert.equal((await fresh.run('mission','fresh','not-replayed',(await f.current()).revision)).status,'already-started');assert.equal(f.calls.length,1);
 if(durable){const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{SurrealStore}=await import('../src/storage.ts'),{store:target}=await growthStore(true);assert.ok(f.store instanceof SurrealStore&&target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/drain-restored');assert.deepEqual((await target.load('mission'))!.value,(await f.current()).value);}
});
for(const durable of [false,true])for(const stage of ['before-activation','activation-inflight','activation-ack-loss','before-call','before-claim'])test(`${durable?'actual SurrealDB':'in-memory fixture'} owned drain at ${stage} admits no provider call and fences async progression`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable);let held=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const base=f.store;
 const store=new Proxy(base,{get(target,key){if(stage==='before-activation'&&key==='lookupOperation')return async(input:any)=>{if(!held&&input.commandId==='boundary-run'){held=true;await gate;}return target.lookupOperation(input);};if(['activation-inflight','activation-ack-loss'].includes(stage)&&key==='commit')return async(input:any)=>{const result=await target.commit(input);if(!held&&input.commandId==='boundary-run'){held=true;await gate;if(stage==='activation-ack-loss')throw Error('Owned fixture committed activation ACK lost');}return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new ConfiguredTextRuntime(store,f.config),internal=runtime as any;
 if(stage==='before-call'||stage==='before-claim'){const send=internal.dispatch.bind(runtime);internal.dispatch=async(id:string,command:any,...rest:any[])=>{const result=await send(id,command,...rest);if(!held&&command.type===(stage==='before-call'?'claim-provider-dispatch':'admit-effect')){held=true;await gate;}return result;};}
 const before=await f.journal(),run=runtime.run('mission','fresh','boundary-run',(await f.current()).revision);void run.catch(()=>{});await f.until(()=>held);runtime.beginDrain();release();if(stage==='before-activation'){await assert.rejects(run,/draining/);assert.deepEqual(await f.journal(),before);}else{const result=await run,w=result.snapshot.value.works.find(w=>w.id==='fresh')!;assert.equal(result.status,'blocked');assert.equal(w.runtimeInterruption?.reason,'host-shutdown');if(stage==='before-claim'){assert.equal(w.effects[0]!.status,'failed');assert.equal(w.effects[0]!.providerDispatch,undefined);assert.equal(w.budget.measured,0);assert.match(w.effects[0]!.receipt!,/adapter was not called/);}else{assert.ok(w.effects.every(e=>e.status==='unknown'));assert.ok(w.effects.every(e=>!Object.hasOwn(e,'receipt')));}if(stage==='before-call')assert.ok(w.effects[0]?.providerDispatch);validateMissionJournalLineage(await f.journal());}assert.equal(f.calls.length,0);
});
test('only internal representative exact original host/run/dispatch/time may close unaccepted Work; owner endpoint rejects it',async t=>{
 const f=await fixture(t,false,{hold:'executor'}),run=f.runtime.run('mission','fresh','bound-run',(await f.current()).revision);await f.until(()=>f.calls.length===1);const current=await f.current(),w=current.value.works.find(w=>w.id==='fresh')!,command={type:'stop-owned-runtime' as const,workId:w.id,runId:w.runtimeRun!.id,dispatchId:w.runtimeRun!.ownership!.dispatchId,hostSessionId:HOST_SESSION_ID,observedAt:Date.now()},rep=new Application(f.store,[{id:'trusted-host',roles:['representative']}]),journal=await f.journal();for(const change of [{hostSessionId:'other-host'},{dispatchId:'other-dispatch'},{runId:'other-run'},{observedAt:w.runtimeRun!.ownership!.startedAt-1},{extra:true}])await assert.rejects(rep.dispatch({missionId:'mission',commandId:crypto.randomUUID(),expectedRevision:current.revision,actorId:'trusted-host',command:{...command,...change}}));await assert.rejects(f.product.app.dispatch({missionId:'mission',commandId:'owner-spoof',expectedRevision:current.revision,actorId:'local-owner',command}));await assert.rejects(f.product.intervene('mission',{commandId:'owner-http',expectedRevision:current.revision,command}));assert.deepEqual(await f.journal(),journal);f.runtime.beginDrain();await run;
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal HTTP drain is idempotent and waits for original durable run settlement`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:'executor'}),server=createWorkbench(f.store,f.root,{runtime:f.runtime,providers:f.product.providers,drainTimeoutMs:3000});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>server.closeAllConnections());const address=server.address();assert.ok(address&&typeof address==='object');const response=fetch(`http://127.0.0.1:${address.port}/missions/mission/run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({commandId:'http-drain',workId:'fresh',expectedRevision:(await f.current()).revision})});await f.until(()=>f.calls.length===1);const drain=server.drain();assert.equal(server.drain(),drain);const r=await response;assert.equal(r.status,200);assert.equal((await r.json()).status,'blocked');assert.deepEqual(await drain,{status:'drained',timedOut:false});assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.runtimeInterruption?.reason,'host-shutdown');assert.equal(f.calls.length,1);
});
test('bounded drain classifies held socket as unsettled instead of false clean shutdown',async t=>{
 const f=await fixture(t),server=createWorkbench(f.store,f.root,{drainTimeoutMs:50});server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');const socket=createConnection(address.port,'127.0.0.1');socket.on('error',()=>{});await once(socket,'connect');socket.write(`POST /missions HTTP/1.1\r\nHost: 127.0.0.1:${address.port}\r\nContent-Type: application/json\r\nContent-Length: 1000\r\n\r\n{`);await pause(20);const before=await f.journal();assert.deepEqual(await server.drain(),{status:'unsettled',timedOut:true});socket.destroy();assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,0);
});
test('durable shutdown closure failure surfaces admitted-unsettled and cannot be reported as drained',async t=>{
 const f=await fixture(t,false,{hold:'executor'}),store=new Proxy(f.store,{get(target,key){if(key==='commit')return async(input:any)=>{if(input.events.some((e:any)=>e.type==='stop-owned-runtime'))throw Error('Owned fixture unavailable during drain closure');return target.commit(input);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new ConfiguredTextRuntime(store,f.config),server=createWorkbench(store,f.root,{runtime,drainTimeoutMs:3000});server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');const response=fetch(`http://127.0.0.1:${address.port}/missions/mission/run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({commandId:'unsettled-drain',workId:'fresh',expectedRevision:(await f.current()).revision})});await f.until(()=>f.calls.length===1);const drain=server.drain(),r=await response;assert.equal(r.status,503);assert.equal((await r.json()).outcome,'admitted-unsettled');assert.deepEqual(await drain,{status:'unsettled',timedOut:false});assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.runtimeInterruption,undefined);
});

test('admission unknown without exact readback reports unsettled shutdown, never false clean',async t=>{
 const f=await fixture(t);let held=false,closed=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=new Proxy(f.store,{get(target,key){if(key==='commit')return async(input:any)=>{const result=await target.commit(input);if(!held&&input.commandId==='unknown-activation'){held=true;await gate;closed=true;throw Error('Owned committed activation ACK lost');}return result;};if(key==='load')return async(id:string)=>{if(closed)throw Error('Owned readback unavailable');return target.load(id);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new ConfiguredTextRuntime(store,f.config),server=createWorkbench(store,f.root,{runtime,drainTimeoutMs:3000});server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');const response=fetch(`http://127.0.0.1:${address.port}/missions/mission/run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({commandId:'unknown-activation',workId:'fresh',expectedRevision:(await f.current()).revision})});await f.until(()=>held);const drain=server.drain();release();const r=await response;assert.equal(r.status,503);assert.equal((await r.json()).outcome,'unknown');assert.deepEqual(await drain,{status:'unsettled',timedOut:false});assert.equal(f.calls.length,0);assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.runtimeRun!.id,'unknown-activation');
});

test('host drain waits for its owned runtime even when no HTTP response socket remains',async t=>{
 const f=await fixture(t,false,{hold:'executor'}),server=createWorkbench(f.store,f.root,{runtime:f.runtime,drainTimeoutMs:3000});server.listen(0,'127.0.0.1');await once(server,'listening');const run=f.runtime.run('mission','fresh','headless-drain',(await f.current()).revision);await f.until(()=>f.calls.length===1);assert.deepEqual(await server.drain(),{status:'drained',timedOut:false});assert.equal((await run).snapshot.value.works.find(w=>w.id==='fresh')!.runtimeInterruption?.reason,'host-shutdown');const journal=await f.journal();f.release();await pause(30);assert.deepEqual(await f.journal(),journal);
});

for(const committed of [false,true])test(`drain during final acceptance ${committed?'ACK hold preserves accepted original':'async admission refuses late Record'}`,async t=>{
 const f=await fixture(t);let held=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=new Proxy(f.store,{get(target,key){if(!committed&&key==='lookupOperation')return async(input:any)=>{const w=(await target.load('mission'))!.value.works.find(w=>w.id==='fresh')!;if(!held&&w.tasks.find(task=>task.id==='fresh:root')?.status==='settled'){held=true;await gate;}return target.lookupOperation(input);};if(committed&&key==='commit')return async(input:any)=>{const result=await target.commit(input);if(!held&&input.value.works.find((w:any)=>w.id==='fresh')?.acceptance==='accepted'){held=true;await gate;}return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new ConfiguredTextRuntime(store,f.config),run=runtime.run('mission','fresh','accept-drain',(await f.current()).revision);await f.until(()=>held);const before=structuredClone((await f.current()).value.works.find(w=>w.id==='fresh')!),drain=runtime.drain();release();await drain;const result=await run,w=result.snapshot.value.works.find(w=>w.id==='fresh')!;assert.equal(result.status,committed?'settled':'blocked');assert.equal(w.acceptance,committed?'accepted':'pending');assert.equal(!!w.record,committed);if(committed)assert.deepEqual(w,before);else assert.equal(w.runtimeInterruption?.reason,'host-shutdown');assert.equal(f.calls.length,2);validateMissionJournalLineage(await f.journal());assert.deepEqual(result.snapshot.value.works[0],f.original.value.works[0]);
});

test('owner mutation waiting at asynchronous lookup is refused at commit call after drain begins',async t=>{
 const f=await fixture(t);let held=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=new Proxy(f.store,{get(target,key){if(key==='lookupOperation')return async(input:any)=>{if(input.commandId==='pending-owner'&&!held){held=true;await gate;}return target.lookupOperation(input);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),server=createWorkbench(store,f.root,{drainTimeoutMs:3000});server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');const before=await f.journal(),response=fetch(`http://127.0.0.1:${address.port}/missions/mission/work-message`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({commandId:'pending-owner',expectedRevision:(await f.current()).revision,workId:'work',messageId:'pending-owner',replyTo:null,text:'Must not commit after drain'})});await f.until(()=>held);const drain=server.drain();release();const r=await response;assert.equal(r.status,503);assert.equal((await r.json()).outcome,'rejected');assert.deepEqual(await drain,{status:'drained',timedOut:false});assert.deepEqual(await f.journal(),before);
});
test('HTTP mutation with already-started incomplete body is rejected when body completes during drain',async t=>{
 const f=await fixture(t),server=createWorkbench(f.store,f.root,{drainTimeoutMs:3000});server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');const body=JSON.stringify({commandId:'late-body',expectedRevision:(await f.current()).revision,workId:'work',messageId:'late-body',replyTo:null,text:'Never submitted after drain'}),socket=createConnection(address.port,'127.0.0.1');let response='';socket.on('data',d=>response+=String(d));socket.on('error',()=>{});await once(socket,'connect');socket.write(`POST /missions/mission/work-message HTTP/1.1\r\nHost: 127.0.0.1:${address.port}\r\nContent-Type: application/json\r\nContent-Length: ${Buffer.byteLength(body)}\r\n\r\n`+body.slice(0,1));await pause(20);const before=await f.journal(),closed=once(socket,'close'),drain=server.drain();socket.end(body.slice(1));await closed;assert.match(response,/503/);assert.match(response,/rejected/);assert.deepEqual(await drain,{status:'drained',timedOut:false});assert.deepEqual(await f.journal(),before);
});
for(const kind of ['domain','rollback'])test(`definite ${kind} rejection at activation never becomes an uncertain admitted run during drain`,async t=>{
 const f=await fixture(t),{DomainError}=await import('../src/domain.ts');let held=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=new Proxy(f.store,{get(target,key){if(key==='commit')return async(input:any)=>{if(input.commandId==='definite-activation'){held=true;await gate;const error=kind==='domain'?new DomainError('Definite original input binding rejection'):Object.assign(new Error('Definite fixture transaction rollback'),{name:'StorageContentionError'});throw error;}return target.commit(input);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new ConfiguredTextRuntime(store,f.config),before=await f.journal(),run=runtime.run('mission','fresh','definite-activation',(await f.current()).revision);void run.catch(()=>{});await f.until(()=>held);const drain=runtime.drain();release();await assert.rejects(run,/Definite/);await drain;assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,0);assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.runtimeRun,undefined);
});
