import test from 'node:test';
import assert from 'node:assert/strict';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {ConfiguredTextRuntime} from '../src/configured-runtime.ts';
import {ConnectionWorkbench} from '../src/connection-workbench.ts';
import {ProductService} from '../src/product.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'memory'} a distinct fresh Work waits without admission while another owned Work runs`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:'executor'});await f.product.admit('mission',{commandId:'second-work',expectedRevision:(await f.current()).revision,workId:'second',title:'Explicit later Work',budget:8});const run=f.runtime.run('mission','fresh','first-run',(await f.current()).revision);await f.until(()=>f.calls.length===1);try{const current=await f.current(),journal=await f.journal(),check=f.runtime.preflight(current,'second',current.revision);assert.equal(check.ready,false);assert.ok(check.diagnostics.some(d=>d.code==='host_busy'));const rejected=await f.runtime.run('mission','second','busy-run',current.revision);assert.equal(rejected.status,'blocked');assert.match(rejected.reason!,/local host/i);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,1);assert.equal((await f.runtime.run('mission','work','old-record-not-replayed',current.revision)).status,'already-started');assert.deepEqual(await f.journal(),journal);f.release();assert.equal((await run).status,'settled');const after=await f.current();assert.equal(after.value.works.find(w=>w.id==='second')!.runtimeRun,undefined);assert.equal(f.calls.length,2);const accepted=structuredClone(after.value.works.find(w=>w.id==='fresh'));assert.equal((await f.runtime.run('mission','second','explicit-later',after.revision)).status,'settled');assert.equal(f.calls.length,4);assert.deepEqual((await f.current()).value.works.find(w=>w.id==='fresh'),accepted);validateMissionJournalLineage(await f.journal());if(durable){const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{SurrealStore}=await import('../src/storage.ts'),{store:target}=await growthStore(true);assert.ok(f.store instanceof SurrealStore&&target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/admission-restored');assert.deepEqual((await target.load('mission'))!.value,(await f.current()).value);}}finally{f.release();await run;}
});
async function second(f:Awaited<ReturnType<typeof fixture>>,missionId='mission'){
 if(missionId!=='mission')await f.product.create({id:missionId,purpose:'Same owned local host',scope:'local',constraints:[],criteria:{version:2,description:'Original bounded lifetime fixture',oracle:'bounded-text-review/v1'}},'other-mission');
 const current=(await f.store.load(missionId))!;await f.product.admit(missionId,{commandId:'admit-second',expectedRevision:current.revision,workId:'second',title:'Later fresh Work',budget:8});
}
for(const durable of [false,true])for(const stage of ['snapshot','activation-ack','claim-ack'] as const)test(`${durable?'actual SurrealDB':'memory'} reserve before ${stage} suspension; busy Work remains exact and explicit admission releases after uncertainty`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable);await second(f);let held=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=new Proxy(f.store,{get(target,key){if(stage==='snapshot'&&key==='load')return async(id:string)=>{if(!held){held=true;await gate;}return target.load(id);};if(stage==='activation-ack'&&key==='commit')return async(input:any)=>{const result=await target.commit(input);if(!held&&input.commandId==='held-run'){held=true;await gate;throw Error('Controlled original activation ACK lost');}return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new ConfiguredTextRuntime(store,f.config),internal=runtime as any;
 if(stage==='claim-ack'){const dispatch=internal.dispatch.bind(runtime);internal.dispatch=async(id:string,command:any,...rest:any[])=>{const result=await dispatch(id,command,...rest);if(!held&&command.type==='claim-provider-dispatch'){held=true;await gate;throw Error('Controlled original claim ACK lost');}return result;};}
 const run=runtime.run('mission','fresh','held-run',(await f.current()).revision);void run.catch(()=>{});await f.until(()=>held);const before=await f.current(),journal=await f.journal();assert.equal(runtime.preflight(before,'second',before.revision).diagnostics.at(-1)!.code,'host_busy');assert.equal((await runtime.run('mission','second','not-queued',before.revision)).status,'blocked');assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);release();if(stage==='snapshot')assert.equal((await run).status,'settled');else await assert.rejects(run,/Run admission committed/);const settled=await f.current(),original=structuredClone(settled.value.works.find(w=>w.id==='fresh'));assert.equal(settled.value.works.find(w=>w.id==='second')!.runtimeRun,undefined);assert.equal(runtime.preflight(settled,'second',settled.revision).ready,true);assert.equal((await runtime.run('mission','fresh','never-replay',settled.revision)).status,'already-started');assert.deepEqual((await f.current()).value.works.find(w=>w.id==='fresh'),original);assert.equal((await runtime.run('mission','second','explicit-after-settlement',settled.revision)).status,'settled');assert.deepEqual((await f.current()).value.works.find(w=>w.id==='fresh'),original);validateMissionJournalLineage(await f.journal());
});
for(const durable of [false,true])for(const outcome of ['cancel','deadline','rejected'] as const)test(`${durable?'actual SurrealDB':'memory'} capacity releases after ${outcome} while original unknown effects never replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:outcome==='rejected'?undefined:'executor',runTimeoutMs:outcome==='deadline'?1500:undefined});await second(f);const runtime=outcome==='deadline'?new ConfiguredTextRuntime(new Proxy(f.store,{get(target,key){if(key==='commit')return async(input:any)=>{const result=await target.commit(input);if(input.commandId==='explicit-second')throw Error('Controlled explicit later activation committed ACK loss');return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),f.config):f.runtime;
 if(outcome==='rejected'){assert.equal((await runtime.run('mission','fresh','stale-rejected',1)).status,'conflict');assert.equal(f.calls.length,0);}else{const run=runtime.run('mission','fresh','interrupted',(await f.current()).revision);await f.until(()=>f.calls.length===1);if(outcome==='cancel')await f.product.intervene('mission',{commandId:'cancel-first',expectedRevision:(await f.current()).revision,command:{type:'cancel',workId:'fresh'}});await run;}
 const current=await f.current(),original=structuredClone(current.value.works.find(w=>w.id==='fresh')),journal=await f.journal();assert.equal(current.value.works.find(w=>w.id==='second')!.runtimeRun,undefined);assert.equal(runtime.preflight(current,'second',current.revision).ready,true);assert.deepEqual(await f.journal(),journal);if(outcome!=='rejected'){if(outcome==='deadline')assert.ok(original!.runtimeInterruption!.observedAt>=original!.runtimeRun!.ownership!.deadlineAt);assert.equal(original!.effects[0]!.status,'unknown');assert.equal(original!.budget.reserved,4);assert.equal(original!.budget.measured,null);assert.equal((await runtime.run('mission','fresh','no-replay',current.revision)).status,'already-started');assert.deepEqual(await f.journal(),journal);}f.release();if(outcome==='deadline'){await assert.rejects(runtime.run('mission','second','explicit-second',current.revision),/Run admission committed/);const fresh=(await f.current()).value.works.find(w=>w.id==='second')!;assert.equal(fresh.runtimeRun!.id,'explicit-second');assert.equal(fresh.effects.length,0);assert.equal(fresh.budget.reserved,0);assert.equal(f.calls.length,1);}else assert.equal((await runtime.run('mission','second','explicit-second',current.revision)).status,'settled');assert.deepEqual((await f.current()).value.works.find(w=>w.id==='fresh'),original);validateMissionJournalLineage(await f.journal());
});
async function managerFixture(t:import('node:test').TestContext,durable:boolean,storeHold=false){
 const f=await fixture(t,durable),calls:any[]=[];await second(f,'other');let release!:()=>void,held=false;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=storeHold?new Proxy(f.store,{get(target,key){if(key==='load')return async(id:string)=>{if(id==='mission'&&!held){held=true;await gate;}return target.load(id);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}):f.store;
 const manager=new ConnectionWorkbench(store,f.artifacts,{allowFixture:true,transport:async(_url,init)=>{const body=JSON.parse(String(init.body)),prompt=JSON.parse(body.messages[0].content);calls.push({workId:prompt.binding.workId,model:body.model});if(!prompt.artifact&&!storeHold){held=true;await gate;}const content=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Original bounded',reason:'Controlled exact fixture'}]}):'Original bounded lifetime fixture';return new Response(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:body.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}),{headers:{'content-type':'application/json'}});}});
 manager.connect({id:'owned',label:'Controlled admission',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});const connection=manager.list().connections[0]!,executor=manager.selectModel(connection.id,{model:'executor',label:'Executor',expectedConfigHash:connection.configHash}),verifier=manager.selectModel(connection.id,{model:'verifier',label:'Verifier',expectedConfigHash:connection.configHash});manager.authorize({id:'controlled-grant',scope:'local',executorProfileId:executor.profileId,verifierProfileId:verifier.profileId,maxOutputTokensPerCall:4,expectedConfigHash:manager.list().configHash});const choice={executorProfileId:executor.profileId,verifierProfileId:verifier.profileId,authorizationId:'controlled-grant',outputTokenCap:4},product=new ProductService(store,undefined,manager);return {...f,manager,choice,product,calls,held:()=>held,release:()=>release()};
}
for(const durable of [false,true])for(const hold of [false,true])test(`${durable?'actual SurrealDB':'memory'} normal connection host shares slot across Mission/router/profile choices at ${hold?'initial async snapshot':'held mock invocation'}`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await managerFixture(t,durable,hold),run=f.manager.run('mission','fresh','manager-first',(await f.current()).revision,f.choice);await f.until(f.held);try{const other=(await f.store.load('other'))!,journal=await f.journal(),check=await f.product.preflight('other','second',other.revision,{...f.choice,executorProfileId:f.choice.verifierProfileId});assert.equal(check!.ready,false);assert.equal(check!.diagnostics.at(-1)!.code,'host_busy');assert.equal((await f.manager.run('other','second','blocked-other',other.revision,f.choice)).status,'blocked');assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,hold?0:1);f.release();assert.equal((await run).status,'settled');assert.equal((await f.store.load('other'))!.value.works[0]!.runtimeRun,undefined);assert.equal(f.calls.length,2);const original=(await f.current()).value;assert.equal((await f.manager.run('other','second','explicit-other',other.revision,f.choice)).status,'settled');assert.equal(f.calls.length,4);assert.deepEqual((await f.current()).value,original);validateMissionJournalLineage(await f.journal());}finally{f.release();await run;}
});
for(const durable of [false,true])for(const stage of ['first-read','busy-read','drain-read'] as const)test(`${durable?'actual SurrealDB':'memory'} standalone selectable ${stage} retains synchronous reservation and cannot auto-acquire after async reads`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await managerFixture(t,durable),{SelectableTextRuntime}=await import('../src/selectable-runtime.ts');let held=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=new Proxy(f.store,{get(target,key){if(key==='load')return async(id:string)=>{if(!held&&id===(stage==='busy-read'?'other':'mission')){held=true;await gate;}return target.load(id);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=new SelectableTextRuntime(store,(f.manager as any).catalog(),f.manager.configuration().authorizations,f.artifacts),run=runtime.run('mission','fresh','selectable-first',(await f.current()).revision,f.choice);void run.catch(()=>{});let secondRun:Promise<any>|undefined;
 try{if(stage==='busy-read'){await f.until(()=>f.calls.length===1);const beforeOther=(await f.store.load('other'))!;secondRun=runtime.run('other','second','not-later-acquired',beforeOther.revision,f.choice);await f.until(()=>held);f.release();assert.equal((await run).status,'settled');const journal=await f.journal();release();assert.equal((await secondRun).status,'blocked');assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,2);assert.equal((await f.store.load('other'))!.value.works[0]!.runtimeRun,undefined);assert.equal((await runtime.run('other','second','explicit-later',beforeOther.revision,f.choice)).status,'settled');assert.equal(f.calls.length,4);}else{await f.until(()=>held);const before=(await f.store.load('other'))!,journal=await f.journal();assert.equal(runtime.preflight(before,'second',before.revision,f.choice).diagnostics.at(-1)!.code,'host_busy');assert.equal((await runtime.run('other','second','not-queued',before.revision,f.choice)).status,'blocked');assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);if(stage==='drain-read'){let settled=false;const drain=runtime.drain().then(()=>settled=true);await new Promise(r=>setImmediate(r));assert.equal(settled,false);release();f.release();assert.equal((await run).status,'blocked');await drain;assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);}else{release();f.release();assert.equal((await run).status,'settled');assert.equal(f.calls.length,2);assert.equal((await f.store.load('other'))!.value.works[0]!.runtimeRun,undefined);}}validateMissionJournalLineage(await f.journal());}finally{release();f.release();await run;await secondRun;}
});
