import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';
test('actual DB normal CLI Chrome keyboard exact neighborhood pages, literal LF/CR and restart preserve Work/Record/authority',{skip:!process.env.SURREAL_TEST_RUNTIME||!process.env.MASSION_PLAYWRIGHT_PATH,timeout:45000},async t=>{
 const f=await lifetimeFixture(t,true,{cli:true});await f.product.captureDocument('mission',{commandId:'graph-document',expectedRevision:(await f.current()).revision,document:{id:'document:original',version:1,title:'Original document',content:'Original untrusted reference',source:'Owner original'}});
 const add=async(from:string,fromVersion:number,to:string,toVersion:number,type:'depends-on'|'evidenced-by'|'contains'='evidenced-by')=>f.product.recordRelation('mission',{commandId:'browser-edge:'+crypto.randomUUID(),expectedRevision:(await f.current()).revision,relation:{from,fromVersion,to,toVersion,type,provenance:'Original <img src=x> 원문 😀'}});
 for(let i=0;i<22;i++)await add('work',1,'reference:'+i,1);await add('work',1,'document:original',1);await add('document:original',1,'absent',1,'contains');await add('incoming',1,'work',1,'depends-on');await add('work',1,'work',1);await add('work',2,'older-distinct',1);await add('line\nfeed',1,'absent',1);await add('carriage\rreturn',1,'absent',1);
 const original=await f.current(),journal=await f.journal(),database=(await f.transport!.query('RETURN $session.db;',{}))[0] as string,{chromium}=await import(process.env.MASSION_PLAYWRIGHT_PATH!),probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const address=probe.address();assert.ok(address&&typeof address==='object');await new Promise<void>(r=>probe.close(()=>r()));const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry],env={MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database,MASSION_PORT:String(address.port)};let child:ReturnType<typeof spawn>|undefined,logs='',browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 const start=async()=>{logs='';child=spawn(process.execPath,argv.slice(1),{cwd:f.root,env,stdio:['ignore','pipe','pipe']});child.stdout!.on('data',d=>logs+=d);child.stderr!.on('data',d=>logs+=d);await f.until(()=>{assert.equal(child!.exitCode,null,logs);return logs.includes('Massion development workbench:');});};
 try{browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});await start();const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();let posts=0,reads=0;page.on('request',(r:any)=>{if(r.method()==='POST')posts++;if(r.url().includes('/neighborhood?'))reads++;});await page.goto('http://127.0.0.1:'+address.port+'/#mission=mission');await page.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission'&&document.getElementById('sync-notice')?.hidden);await page.locator('#neighborhood-panel > summary').focus();await page.keyboard.press('Enter');await page.locator('#neighborhood-choice').selectOption(JSON.stringify(['work',1]));assert.equal(reads,0);await page.locator('#neighborhood-read').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('[data-neighborhood-ordinal]').length===20);assert.equal(await page.locator('#neighborhood-results img').count(),0);await page.locator('#neighborhood-next').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!!document.querySelector('[data-neighborhood-ordinal="22"]'));assert.equal(await page.locator('[data-neighborhood-ordinal]').count(),5);await page.locator('[data-neighborhood-ordinal="22"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('[data-neighborhood-ordinal]').length===2);assert.equal(await page.locator('#neighborhood-id').inputValue(),'document:original');assert.match((await page.locator('#neighborhood-results').textContent())!,/absent@1/);assert.equal(reads,3);await page.locator('#neighborhood-close').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#neighborhood-results').isVisible(),false);
 await page.locator('#neighborhood-choice').selectOption(JSON.stringify(['line\nfeed',1]));assert.equal(await page.locator('#neighborhood-id').inputValue(),'line\nfeed');await page.locator('#neighborhood-read').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('[data-neighborhood-ordinal]').length===1);assert.equal(reads,4);await page.locator('#neighborhood-choice').selectOption(JSON.stringify(['carriage\rreturn',1]));assert.match((await page.locator('#neighborhood-status').textContent())!,/cannot round-trip/);assert.equal(await page.locator('#neighborhood-id').inputValue(),'');assert.equal(reads,4);assert.equal(await page.locator('#neighborhood-results').isVisible(),false);const raw=await fetch('http://127.0.0.1:'+address.port+'/missions/mission/neighborhood?entity='+encodeURIComponent('carriage\rreturn')+'&version=1');assert.equal(raw.status,200);const rawPage=await raw.json();assert.equal(rawPage.items[0].from,'carriage\rreturn');assert.equal(rawPage.reference.id,'carriage\rreturn');assert.equal(posts,0);assert.equal(f.calls.length,0);assert.deepEqual(await f.current(),original);assert.deepEqual(await f.journal(),journal);
 const owned=await verifyOwnedChild(child!,{cwd:f.root,argv});await context.close();await stopOwnedChild(child!,{cwd:f.root,argv});child=undefined;await start();const fresh=await browser.newContext(),freshPage=await fresh.newPage();let restartReads=0;freshPage.on('request',(r:any)=>{if(r.url().includes('/neighborhood?'))restartReads++;});await freshPage.goto('http://127.0.0.1:'+address.port+'/#mission=mission');await freshPage.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission'&&document.getElementById('sync-notice')?.hidden);assert.equal(await freshPage.locator('#neighborhood-results').isVisible(),false);assert.equal(restartReads,0);for(const width of [390,1280]){await freshPage.setViewportSize({width,height:844});assert.equal(await freshPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}assert.deepEqual(await f.journal(),journal);assert.deepEqual(await f.current(),original);assert.equal(f.calls.length,0);t.diagnostic(JSON.stringify({...owned,normalCLI:true,keyboardReadNextNeighborClose:true,LFExact:true,CRRefusedWithoutChangedQuery:true,nativeCRExact:true,browserGets:4,posts:0,providerCalls:0,restartAutomaticReads:0,originalWorkRecordJournalExact:true}));await fresh.close();
 }finally{if(browser)await browser.close();if(child)await stopOwnedChild(child,{cwd:f.root,argv});}
});
