import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {SurrealNeighborhood} from '../src/knowledge-neighborhood.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function fixture(t:any,durable=false,mode='normal'){
 const f=await lifetimeFixture(t,durable);for(const [from,fromVersion,to,toVersion,type] of [['work',1,'document:original 원문',1,'evidenced-by'],['document:original 원문',1,'reference:absent',1,'contains'],['incoming',1,'work',1,'depends-on'],['work',2,'different-version',1,'contains']] as const)await f.product.recordRelation('mission',{commandId:'graph:'+from+to,expectedRevision:(await f.current()).revision,relation:{from,fromVersion,to,toVersion,type,provenance:'Original <img src=x> 원문 😀'}});await f.product.create({id:'other',purpose:'Other',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'graph-other');const reader=new SurrealNeighborhood(f.transport??{async query(_query,vars){const packet=await f.store.readState(String(vars.missionId));if(vars.feedId&&packet.feedId!==vars.feedId)return [{changed:'feed'}];if(Number(vars.cursor)>=0&&packet.cursor!==vars.cursor)return [{changed:'cursor'}];if(!packet.snapshot)return [{missing:true,missionId:vars.missionId,feedId:packet.feedId,cursor:packet.cursor}];if(Number(vars.revision)>=1&&packet.snapshot.revision!==vars.revision)return [{changed:'revision'}];const rows=packet.snapshot.value.relations.map((r:any,ordinal:number)=>({...r,ordinal})).filter((r:any)=>r.ordinal>Number(vars.after)&&(r.from===vars.referenceId&&r.fromVersion===vars.version||r.to===vars.referenceId&&r.toVersion===vars.version)).slice(0,Number(vars.fetchLimit));return [{missionId:vars.missionId,revision:packet.snapshot.revision,feedId:packet.feedId,cursor:packet.cursor,reference:{id:vars.referenceId,version:vars.version},relationCount:packet.snapshot.value.relations.length,rows}];}}),server=createWorkbench(f.store,f.root,{neighborhood:reader});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});let base='http://127.0.0.1:'+(server.address() as any).port,writes=0,reads=0,release!:()=>void;const gate=new Promise<void>(r=>release=r),app=harness(async(path:string,options:any)=>{if(options.method==='POST')writes++;if(path.includes('/neighborhood?'))reads++;const res=await fetch(base+path,options),body=await res.json();if(path.includes('/neighborhood?')){if(mode==='held')await gate;if(mode==='wrong-feed')body.feedId='different-feed';if(mode==='wrong-edge'&&body.items?.length)body.items[0].provenance='Changed original';}return reply(body,res.status);},{},undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden&&!app.node('neighborhood-read').disabled);return {...f,app,base,replaceBase:(b:string)=>base=b,writes:()=>writes,reads:()=>reads,release:()=>release()};
}
async function choose(app:any,id='work',version=1){app.node('neighborhood-choice').value=JSON.stringify([id,version]);await app.node('neighborhood-choice').fire('change');}
function neighbor(app:any,ordinal:number){return app.all().find((n:any)=>n.attributes.get('data-neighborhood-ordinal')===String(ordinal));}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} deliberate direct knowledge read/neighbor/close preserves exact declarations and old Work/Record with no commands`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await fixture(t,durable),app=f.app,original=await f.current(),journal=await f.journal();assert.equal(f.reads(),0);await choose(app);assert.equal(f.reads(),0);await app.node('neighborhood-read').fire('click');assert.match(app.node('neighborhood-results').textContent,/Incoming declaration|Outgoing declaration/);assert.match(app.node('neighborhood-results').textContent,/Original <img src=x>/);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);await neighbor(app,0).fire('click');await f.until(()=>app.node('neighborhood-status').textContent.includes('exact relationship declarations shown')&&!app.node('neighborhood-read').disabled);assert.equal(app.node('neighborhood-id').value,'document:original 원문');assert.match(app.node('neighborhood-results').textContent,/reference:absent/);assert.equal(f.reads(),2);await app.node('neighborhood-close').fire('click');assert.equal(app.node('neighborhood-results').hidden,true);assert.deepEqual(await f.current(),original);assert.deepEqual(await f.journal(),journal);assert.equal(f.writes(),0);assert.equal(f.calls.length,0);});
for(const action of ['close','edit-ABA','mission','disconnect'])test(`held neighborhood reply cannot reinstall after ${action}`,async t=>{const f=await fixture(t,false,'held'),app=f.app;await choose(app);const pending=app.node('neighborhood-read').fire('click');await f.until(()=>f.reads()===1);if(action==='close')await app.node('neighborhood-close').fire('click');if(action==='edit-ABA'){app.node('neighborhood-id').value='Later';await app.node('neighborhood-id').fire('input');app.node('neighborhood-id').value='work';await app.node('neighborhood-id').fire('input');}if(action==='mission')await runInContext("loadMission('other',false)",app.context);if(action==='disconnect')await app.windowEvent('offline');f.release();await pending;assert.equal(app.node('neighborhood-results').hidden,true);assert.equal(f.writes(),0);});
for(const mode of ['wrong-feed','wrong-edge'])test(`${mode} does not expose substituted neighborhood declarations`,async t=>{const f=await fixture(t,false,mode),app=f.app;await choose(app);await app.node('neighborhood-read').fire('click');assert.equal(app.node('neighborhood-results').hidden,true);assert.equal(f.reads(),1);assert.equal(f.writes(),0);});
test('old neighbor button after revision/Close cannot perform another read, while unknown receipt write barrier remains',async t=>{const f=await fixture(t),app=f.app;await choose(app);await app.node('neighborhood-read').fire('click');const old=neighbor(app,0);await app.node('neighborhood-close').fire('click');await old.fire('click');assert.equal(f.reads(),1);await runInContext("unknownOperation={commandId:'original-unknown',missionId:'mission',reconcileCursor:0};controls()",app.context);await app.node('neighborhood-read').fire('click');assert.equal(f.reads(),2);assert.equal(runInContext('unknownOperation.commandId',app.context),'original-unknown');assert.equal(app.node('mission-fields').disabled,true);assert.equal(f.writes(),0);});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} replaced same-ID feed discards prior neighbor button without a query/write`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await fixture(t,durable),other=await fixture(t,durable),app=f.app;await choose(app);await app.node('neighborhood-read').fire('click');const old=neighbor(app,0),one=await f.journal(),two=await other.journal();f.replaceBase(other.base);await app.windowEvent('online');const end=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('neighborhood-read').disabled){assert.ok(Date.now()<end);await app.tick();await new Promise(r=>setTimeout(r,10));}const reads=f.reads();await old.fire('click');assert.equal(f.reads(),reads);assert.equal(app.node('neighborhood-results').hidden,true);assert.equal(f.writes(),0);assert.deepEqual(await f.journal(),one);assert.deepEqual(await other.journal(),two);});
test('normal neighborhood route rejects unsupported host, mutation, duplicate/extra fields and unpinned Next before a reader call',async t=>{const f=await lifetimeFixture(t),before=await f.journal();let calls=0;const start=async(enabled:boolean)=>{const server=createWorkbench(f.store,f.root,enabled?{neighborhood:{async readNeighborhood(){calls++;return null;}}}:{});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});return 'http://127.0.0.1:'+(server.address() as any).port;},unsupported=await start(false),base=await start(true),path='/missions/mission/neighborhood';assert.equal((await fetch(unsupported+path+'?entity=work&version=1')).status,503);assert.equal((await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,404);for(const query of ['entity=work&version=1&version=2','entity=work&version=1&content=forbidden','entity=work&version=0','entity=work&version=1&after=0&cursor=0&revision=1','entity=work&version=1&cursor=0','entity=work&version=1&revision=-1','version=1'])assert.equal((await fetch(base+path+'?'+query)).status,400,query);assert.equal(calls,0);assert.equal((await fetch(base+path+'?entity=work&version=1')).status,404);assert.equal(calls,1);assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,0);});
