import test from 'node:test';
import assert from 'node:assert/strict';
import {SurrealNeighborhood,NeighborhoodChangedError,neighborhoodInput} from '../src/knowledge-neighborhood.ts';
import {StorageProtocolError} from '../src/storage.ts';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
const row=(ordinal:number,patch={})=>({ordinal,from:'work',fromVersion:1,to:'document:original 원문',toVersion:1,type:'evidenced-by',provenance:'Original <img src=x> owner declaration 😀',inferred:false,...patch}),payload=(rows:any[])=>({missionId:'mission',revision:2,feedId:'feed',cursor:4,reference:{id:'work',version:1},relationCount:24,rows});
test('strict native neighborhood retains duplicate original edges, exact boundary and rejects malformed metadata',async()=>{for(const i of [{missionId:'mission',referenceId:'work',version:1,after:0},{missionId:'mission',referenceId:'work',version:1,cursor:2},{missionId:'mission',referenceId:'\ud800',version:1},{missionId:'mission',referenceId:'work',version:0},{missionId:'mission',referenceId:'work',version:1,limit:21}])assert.throws(()=>neighborhoodInput(i));const reader=new SurrealNeighborhood({async query(){return [null,payload([row(0),row(1),row(2)]),null];}}),page=await reader.readNeighborhood({missionId:'mission',referenceId:'work',version:1,limit:2});assert.equal(page!.items.length,2);assert.equal(page!.nextAfter,1);for(const rows of [[row(1),row(1)],[row(0,{content:'Forbidden body'})],[row(0,{fromVersion:2})],[row(0,{inferred:'false'})],[row(0,{provenance:'\ud800'})]])await assert.rejects(new SurrealNeighborhood({async query(){return [payload(rows)];}}).readNeighborhood({missionId:'mission',referenceId:'work',version:1}),StorageProtocolError);for(const changed of ['feed','cursor','revision'])await assert.rejects(new SurrealNeighborhood({async query(){return [{changed}];}}).readNeighborhood({missionId:'mission',referenceId:'work',version:1}),NeighborhoodChangedError);});
test('actual DB exact incoming/outgoing/self-loop/duplicate/older versions and bounded pages preserve original Work/Record/journal',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await lifetimeFixture(t,true),reader=new SurrealNeighborhood(f.transport!);for(let i=0;i<22;i++)await f.product.recordRelation('mission',{commandId:'neighbor:'+i,expectedRevision:(await f.current()).revision,relation:{from:'work',fromVersion:1,to:'document:source:'+i,toVersion:1,type:'evidenced-by',provenance:'Original '+i}});for(const [from,fromVersion,to,toVersion] of [['work',1,'work',1],['incoming',1,'work',1],['work',2,'other-version',1]] as const)await f.product.recordRelation('mission',{commandId:'neighbor:'+from+fromVersion+to,expectedRevision:(await f.current()).revision,relation:{from,fromVersion,to,toVersion,type:'depends-on',provenance:'Exact original'}});const original=await f.current(),journal=await f.journal(),first=await reader.readNeighborhood({missionId:'mission',referenceId:'work',version:1});assert.equal(first!.items.length,20);assert.equal(first!.nextAfter,19);const second=await reader.readNeighborhood({missionId:'mission',referenceId:'work',version:1,after:first!.nextAfter!,cursor:first!.cursor,feedId:first!.feedId,revision:first!.revision});assert.deepEqual(second!.items.map(x=>x.ordinal),[20,21,22,23]);assert.equal(second!.nextAfter,null);assert.equal(second!.items.filter(x=>x.from===x.to).length,1);assert.deepEqual((await reader.readNeighborhood({missionId:'mission',referenceId:'work',version:2}))!.items.map(x=>x.ordinal),[24]);assert.deepEqual((await reader.readNeighborhood({missionId:'mission',referenceId:'missing',version:1}))!.items,[]);assert.equal(await reader.readNeighborhood({missionId:'missing',referenceId:'work',version:1}),null);assert.deepEqual(await f.current(),original);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);});

test('native boundary freezes input while awaiting response',async()=>{let release!:()=>void,seen:any;const gate=new Promise<void>(r=>release=r),input={missionId:'mission',referenceId:'work',version:1,limit:2},reader=new SurrealNeighborhood({async query(_query,vars){seen=structuredClone(vars);await gate;return [payload([row(0)])];}}),pending=reader.readNeighborhood(input);input.referenceId='changed';input.version=2;release();assert.equal((await pending)!.reference.id,'work');assert.equal(seen.referenceId,'work');});
test('actual DB original inferred duplicates, cycles, Mission separation and restored feed remain declarations only',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,true),{Application}=await import('../src/application.ts'),{FIXTURE_ACTORS}=await import('../src/scenario.ts'),fixture=new Application(f.store,FIXTURE_ACTORS),reader=new SurrealNeighborhood(f.transport!);
 for(let i=0;i<2;i++)await fixture.dispatch({missionId:'mission',commandId:'inferred:'+i,expectedRevision:(await f.current()).revision,actorId:'representative',command:{type:'relate',relation:{from:'work',fromVersion:1,to:'missing',toVersion:1,type:'contains',provenance:'Original inferred declaration',inferred:true}}});await f.product.recordRelation('mission',{commandId:'cycle',expectedRevision:(await f.current()).revision,relation:{from:'missing',fromVersion:1,to:'work',toVersion:1,type:'depends-on',provenance:'Original reverse'}});
 const first=(await reader.readNeighborhood({missionId:'mission',referenceId:'work',version:1}))!;assert.deepEqual(first.items.map(x=>x.ordinal),[0,1,2]);assert.equal(first.items.filter(x=>x.inferred).length,2);await f.product.create({id:'other',purpose:'Other graph',scope:'local',constraints:[],criteria:{version:1,description:'Original',oracle:'manual-review/v1'}},'graph-other');await f.product.recordRelation('other',{commandId:'other-edge',expectedRevision:1,relation:{from:'work',fromVersion:1,to:'other-only',toVersion:1,type:'contains',provenance:'Other Mission only'}});assert.deepEqual((await reader.readNeighborhood({missionId:'other',referenceId:'work',version:1}))!.items.map(x=>x.to),['other-only']);assert.deepEqual((await reader.readNeighborhood({missionId:'mission',referenceId:'work',version:1}))!.items,first.items);await assert.rejects(reader.readNeighborhood({missionId:'mission',referenceId:'work',version:1,after:0,cursor:first.cursor,feedId:first.feedId,revision:first.revision}),e=>e instanceof NeighborhoodChangedError&&e.reason==='cursor');await assert.rejects(reader.readNeighborhood({missionId:'mission',referenceId:'work',version:1,revision:first.revision-1}),e=>e instanceof NeighborhoodChangedError&&e.reason==='revision');
 const {growthStore}=await import('./support/growth-fixture.ts'),{SurrealStore}=await import('../src/storage.ts'),{exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{store,transport}=await growthStore(true);assert.ok(store instanceof SurrealStore);assert.ok(f.store instanceof SurrealStore);const original=await f.current(),journal=await f.journal();await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),store,f.root+'/neighborhood-restore');const restored=new SurrealNeighborhood(transport!),page=(await restored.readNeighborhood({missionId:'mission',referenceId:'work',version:1}))!;assert.deepEqual(page.items,first.items);assert.notEqual(page.feedId,first.feedId);await assert.rejects(restored.readNeighborhood({missionId:'mission',referenceId:'work',version:1,feedId:first.feedId}),e=>e instanceof NeighborhoodChangedError&&e.reason==='feed');assert.deepEqual((await store.load('mission'))!.value,original.value);assert.deepEqual(await f.current(),original);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);
});
test('actual DB max1000 retained graph is bounded, oversized negative fixture never truncates',{skip:!process.env.SURREAL_TEST_RUNTIME},async()=>{
 const {growthStore}=await import('./support/growth-fixture.ts'),{ProductService}=await import('../src/product.ts'),{NeighborhoodLimitError}=await import('../src/knowledge-neighborhood.ts'),{store,transport}=await growthStore(true),product=new ProductService(store);await product.create({id:'limit',purpose:'Owned negative fixture only',scope:'local',constraints:[],criteria:{version:1,description:'Original',oracle:'manual-review/v1'}},'limit');
 // Dedicated disposable malformed-state fixture: never alter the Work/Record preservation fixture.
 const relation={from:'work',fromVersion:1,to:'missing',toVersion:1,type:'contains',provenance:'Original duplicate',inferred:false},reader=new SurrealNeighborhood(transport!);await transport!.query('UPDATE massion_state SET value.relations=array::repeat($relation,1000) WHERE aggregateId=$missionId;',{relation,missionId:'limit'});const page=(await reader.readNeighborhood({missionId:'limit',referenceId:'work',version:1,limit:20}))!;assert.equal(page.relationCount,1000);assert.equal(page.items.length,20);assert.equal(page.nextAfter,19);const last=(await reader.readNeighborhood({missionId:'limit',referenceId:'work',version:1,limit:20,after:979,cursor:page.cursor,feedId:page.feedId,revision:page.revision}))!;assert.equal(last.items.at(-1)!.ordinal,999);assert.equal(last.nextAfter,null);await transport!.query('UPDATE massion_state SET value.relations=array::repeat($relation,1001) WHERE aggregateId=$missionId;',{relation,missionId:'limit'});await assert.rejects(reader.readNeighborhood({missionId:'limit',referenceId:'work',version:1}),NeighborhoodLimitError);
});
