import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {literalMemoryFixture,NEAR_MEMORY_ID} from './support/memory-usage-literal-fixture.ts';
import {readMemoryUsage} from '../src/memory-usage.ts';
import {createWorkbench} from '../src/server.ts';
import {SurrealStore} from '../src/storage.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} literal ID/version/hash normal read returns exact historical Work/Record pins without writes or aliasing`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await literalMemoryFixture(t,durable),before=await f.current(),journal=await f.journal(),q=await f.query(),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port,feed=(await f.store.readState()).feedId,path=(query=q)=>'/missions/mission/memory-usage?id='+encodeURIComponent(query.id)+'&version='+query.version+'&hash='+query.versionHash,response=await fetch(base+path(),{headers:{'X-Massion-Feed':feed}}),body=await response.json();t.diagnostic(JSON.stringify({httpStatus:response.status,literalID:q.id,error:body.error??null,snapshotUnchanged:JSON.stringify(await f.current())===JSON.stringify(before),journalUnchanged:JSON.stringify(await f.journal())===JSON.stringify(journal),readWrites:0,modelCalls:0}));assert.equal(response.status,200,JSON.stringify(body));assert.equal(body.memory.id,q.id);assert.equal(body.versionHash,q.versionHash);assert.equal(body.memory.effective,false);assert.deepEqual(body.uses.map((u:any)=>u.workId),['literal-accepted']);assert.equal(body.uses[0].record.id,'literal-record');assert.deepEqual(body.uses[0].record.memoryVersions,before.value.works.find(w=>w.id==='literal-accepted')!.record!.memoryVersions);assert.equal((await readMemoryUsage(f.store,'mission',await f.query(f.id,2)))!.uses[0]!.workId,'literal-fresh');
 for(const id of [NEAR_MEMORY_ID,'é','e\u0301','long literal '+'x'.repeat(150)]){const query=await f.query(id),r=await readMemoryUsage(f.store,'mission',query);assert.equal(r!.memory.id,id);assert.equal(r!.versionHash,query.versionHash);assert.equal(r!.memory.content,before.value.memories.find(m=>m.id===id)!.content);}
 assert.equal((await fetch(base+path({...q,version:3}))).status,404);assert.equal((await fetch(base+path({...q,versionHash:'0'.repeat(64)}))).status,409);assert.equal((await fetch(base+path(),{headers:{'X-Massion-Feed':'another-feed'}})).status,409);for(const suffix of ['&extra=x','&id='+encodeURIComponent(f.id),'&hash='+q.versionHash])assert.equal((await fetch(base+path()+suffix)).status,400);assert.deepEqual(await f.current(),before);assert.deepEqual(await f.journal(),journal);
 if(durable){assert.ok(f.store instanceof SurrealStore);const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{store:target}=await growthStore(true);assert.ok(target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/literal-restored');assert.deepEqual((await readMemoryUsage(target,'mission',q))!.memory,body.memory);assert.deepEqual((await readMemoryUsage(target,'mission',q))!.uses,body.uses);assert.deepEqual((await target.load('mission'))!.value,before.value);}
});
test('stored ID exact 16000-unit boundary and invalid IDs reject before store access; original query is frozen',async t=>{
 const f=await literalMemoryFixture(t),id='x'.repeat(16000);await f.product.saveMemory('mission',{commandId:'literal-max',expectedRevision:(await f.current()).revision,memory:{id,version:1,content:'Exact maximum identity',source:'Owner'}});const q=await f.query(id),journal=await f.journal(),state=await f.current();assert.equal((await readMemoryUsage(f.store,'mission',q))!.memory.id,id);assert.equal((await readMemoryUsage(f.store,'mission',q))!.totalUses,0);let reads=0;const counted=new Proxy(f.store,{get(target,key){if(key==='readState')return async(...args:any[])=>{reads++;return (target.readState as any)(...args);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}});for(const id of ['', ' \r\n ', '\ud800', 'x\udfff', 'x'.repeat(16001),null,5,{}])await assert.rejects(readMemoryUsage(counted,'mission',{...q,id} as any),/Exact memory/);assert.equal(reads,0);for(const patch of [{version:0},{version:1.2},{version:'1'},{versionHash:'bad'},{extra:'other'}])await assert.rejects(readMemoryUsage(counted,'mission',{...q,...patch} as any),/Exact memory/);assert.equal(reads,0);
 let release!:()=>void,reached!:()=>void;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),held=new Proxy(f.store,{get(target,key){if(key==='readState')return async(mission:string)=>{reached();await gate;return target.readState(mission);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}}),input=await f.query(),original=structuredClone(input),pending=readMemoryUsage(held,'mission',input);await arrival;input.id=NEAR_MEMORY_ID;input.version=2;input.versionHash='0'.repeat(64);release();const result=await pending;assert.equal(result!.memory.id,original.id);assert.equal(result!.versionHash,original.versionHash);assert.deepEqual(await f.current(),state);assert.deepEqual(await f.journal(),journal);
});
