import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {memoryUsagePagesFixture as fixture} from './support/memory-usage-pages-fixture.ts';
import {readMemoryUsage} from '../src/memory-usage.ts';
import {createWorkbench} from '../src/server.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} explicit GET pages retain 22 original uses as 20 plus 2 and exact Work/Record/unknown with no writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),q=await f.query(),before=await f.current(),journal=await f.journal(),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port,path='/missions/mission/memory-usage?id='+encodeURIComponent(q.id)+'&version='+q.version+'&hash='+q.versionHash+'&revision='+q.revision,get=async(suffix='',feed=q.feedId)=>{const r=await fetch(base+path+suffix,{headers:{'X-Massion-Feed':feed}});return {status:r.status,body:await r.json()};},first=await get(),last=await get('&after=20');assert.equal(first.status,200);assert.equal(last.status,200);assert.equal(first.body.uses.length,20);assert.equal(last.body.uses.length,2);assert.equal(first.body.nextAfter,20);assert.equal(last.body.nextAfter,null);assert.equal(last.body.offset,20);assert.equal(first.body.totalUses,22);assert.deepEqual([...first.body.uses,...last.body.uses].map(u=>u.workId),Array.from({length:22},(_,i)=>'use-'+String(i).padStart(2,'0')));assert.equal(new Set([...first.body.uses,...last.body.uses].map(u=>u.workId)).size,22);assert.equal(first.body.memory.id,q.id);assert.equal(last.body.versionHash,q.versionHash);assert.equal(first.body.uses[0].record.id,'page-record');assert.deepEqual(first.body.uses[0].record.memoryVersions,before.value.works.find(w=>w.id==='use-00')!.record!.memoryVersions);assert.deepEqual(first.body.memory,last.body.memory);
 for(const suffix of ['&after=0','&after=1','&after=40','&after=-20','&after=1e2','&after=20&after=20','&extra=x','&revision='+q.revision])assert.equal((await get(suffix)).status,400);assert.equal((await get('&after=20','wrong-feed')).status,409);assert.equal((await fetch(base+path.replace('&revision='+q.revision,'')+'&after=20',{headers:{'X-Massion-Feed':q.feedId}})).status,400);assert.equal((await fetch(base+path+'&after=20')).status,400);assert.equal((await fetch(base+path.replace(q.versionHash,'0'.repeat(64))+'&after=20',{headers:{'X-Massion-Feed':q.feedId}})).status,409);assert.deepEqual(await f.current(),before);assert.deepEqual(await f.journal(),journal);
 await f.product.saveMemory('mission',{commandId:'page-peer',expectedRevision:q.revision,memory:{id:'peer',version:1,content:'Deliberate peer change',source:'Owner'}});const afterPeer=await f.journal();assert.equal((await get('&after=20')).status,409);assert.deepEqual(await f.journal(),afterPeer);assert.deepEqual((await f.current()).value.works,before.value.works);
});
test('usage page boundaries 0/1/20/21/22/40 and caller freeze reject invalid contexts before reads',async t=>{
 for(const count of [0,1,20,21,22,40]){const f=await fixture(t,false,false,count),q=await f.query(),journal=await f.journal(),first=await readMemoryUsage(f.store,'mission',q);assert.equal(first!.uses.length,Math.min(20,count));assert.equal(first!.nextAfter,count>20?20:null);if(count>20){const second=await readMemoryUsage(f.store,'mission',{...q,after:20});assert.equal(second!.uses.length,count-20);assert.equal(second!.nextAfter,null);}assert.deepEqual(await f.journal(),journal);}
 const f=await fixture(t),q=await f.query();let reads=0;const counted=new Proxy(f.store,{get(target,key){if(key==='readState')return async(id:string)=>{reads++;return target.readState(id);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}});for(const patch of [{after:0},{after:-20},{after:1},{after:20.5},{after:20,revision:undefined},{after:20,feedId:undefined},{after:20,revision:0},{after:20,revision:'1'},{revision:NaN}])await assert.rejects(readMemoryUsage(counted,'mission',{...q,...patch} as any));assert.equal(reads,0);
 let release!:()=>void,reached!:()=>void;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),held=new Proxy(f.store,{get(target,key){if(key==='readState')return async(id:string)=>{reached();await gate;return target.readState(id);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}}),input={...q,after:20},pending=readMemoryUsage(held,'mission',input);await arrival;input.id='changed';input.after=40;input.revision=1;release();const result=await pending;assert.equal(result!.offset,20);assert.equal(result!.memory.id,q.id);assert.equal(result!.uses.length,2);
});
