import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {memoryContentSearchFixture as fixture,SEARCH_ID_A,SEARCH_ID_B} from './support/memory-content-search-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {searchMemoryContent} from '../src/memory-content-search.ts';
import {memoryVersionHash} from '../src/domain.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} literal content search discovers 22 explicit originals across IDs as 20 plus 2 without writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),state=await f.store.readState('mission'),before=await f.current(),journal=await f.journal(),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port,path='/missions/mission/memory-search?text='+encodeURIComponent(f.text)+'&revision='+state.snapshot!.revision;
 const get=async(suffix='')=>{const r=await fetch(base+path+suffix,{headers:{'X-Massion-Feed':state.feedId}});return {status:r.status,body:await r.json()};};const first=await get(),last=await get('&after=20');assert.equal(first.status,200);assert.equal(last.status,200);assert.equal(first.body.versions.length,20);assert.equal(last.body.versions.length,2);assert.deepEqual(first.body.versions.map((m:any)=>[m.memory.id,m.memory.version]),Array.from({length:20},(_,i)=>[f.id,i+1]));assert.deepEqual(last.body.versions.map((m:any)=>m.memory.id),[SEARCH_ID_A,SEARCH_ID_B]);assert.equal(last.body.versions[0].memory.effective,false);for(const e of [...first.body.versions,...last.body.versions]){assert.equal(e.memory.authority,'explicit');assert.equal(e.versionHash,memoryVersionHash(e.memory));}assert.equal(first.body.totalVersions,22);assert.equal(first.body.nextAfter,20);assert.equal(last.body.nextAfter,null);assert.equal(last.body.versions[1].memory.effective,true);
 for(const suffix of ['&after=0','&after=1','&after=40','&after=-20','&after=1e2','&after=20&after=20','&text=Original','&extra=x','&revision='+state.snapshot!.revision])assert.equal((await get(suffix)).status,400);
 for(const [text,total] of [['missing',0],['original',0],['Original ',22],[' A\r\n원문',1],[' A\n원문',0]] as const){const r=await fetch(base+path.replace(encodeURIComponent(f.text),encodeURIComponent(text)),{headers:{'X-Massion-Feed':state.feedId}});assert.equal(r.status,200);const body=await r.json();assert.equal(body.totalVersions,total);assert.equal(body.text,text);}
 assert.equal((await fetch(base+path)).status,400);assert.equal((await fetch(base+path,{headers:{'X-Massion-Feed':'wrong'}})).status,409);assert.equal((await fetch(base+path.replace('revision='+state.snapshot!.revision,'revision=1'),{headers:{'X-Massion-Feed':state.feedId}})).status,409);assert.equal((await searchMemoryContent(f.store,'other',{text:f.text,feedId:state.feedId,revision:(await f.store.load('other'))!.revision}))!.totalVersions,1);
 const boundary='계'.repeat(512);await f.product.saveMemory('mission',{commandId:'search-boundary',expectedRevision:before.revision,memory:{id:'boundary',version:1,content:boundary,source:'Owner'}});const s2=await f.store.readState('mission'),boundaryPath='/missions/mission/memory-search?text='+encodeURIComponent(boundary)+'&revision='+s2.snapshot!.revision,r=await fetch(base+boundaryPath,{headers:{'X-Massion-Feed':s2.feedId}});assert.equal(r.status,200);assert.equal((await r.json()).totalVersions,1);assert.equal((await fetch(base+boundaryPath.replace(encodeURIComponent(boundary),encodeURIComponent(boundary+'계')),{headers:{'X-Massion-Feed':s2.feedId}})).status,400);const after=await f.journal();assert.equal((await get('&after=20')).status,409);assert.deepEqual(await f.journal(),after);assert.deepEqual((await f.current()).value.works,before.value.works);
});
test('literal fragment Unicode/space bounds, frozen input and invalid lineage fail closed',async t=>{
 const f=await fixture(t),s=await f.store.readState('mission'),q={text:f.text,revision:s.snapshot!.revision,feedId:s.feedId};let reads=0;const counted=new Proxy(f.store,{get(target,key){if(key==='readState')return async(id:string)=>{reads++;return target.readState(id);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}});for(const patch of [{text:''},{text:' '},{text:'x'.repeat(513)},{text:'\ud800'},{revision:0},{feedId:''},{after:0},{after:1},{after:20.5},{extra:true}])await assert.rejects(searchMemoryContent(counted,'mission',{...q,...patch} as any));assert.equal(reads,0);
 for(const [id,content] of [['composed','Exact é end'],['decomposed','Exact e\u0301 end'],['spaces',' leading trailing ']])await f.product.saveMemory('mission',{commandId:'search-literal-'+id,expectedRevision:(await f.current()).revision,memory:{id:id!,version:1,content:content!,source:'Owner'}});const now=await f.store.readState('mission');for(const [text,id] of [['é','composed'],['e\u0301','decomposed'],[' leading trailing ','spaces']]){const r=(await searchMemoryContent(f.store,'mission',{...q,text:text!,revision:now.snapshot!.revision}))!;assert.equal(r.totalVersions,1);assert.equal(r.versions[0]!.memory.id,id);assert.equal(r.text,text);}
 const corrupt=structuredClone(now);corrupt.snapshot!.value.works.find(w=>w.id==='use-00')!.record!.checksum='0'.repeat(64);const bad=new Proxy(f.store,{get(target,key){if(key==='readState')return async()=>corrupt;const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}});await assert.rejects(searchMemoryContent(bad,'mission',{...q,revision:now.snapshot!.revision}),/lineage invalid/);
 let release!:()=>void,reached!:()=>void;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),held=new Proxy(f.store,{get(target,key){if(key==='readState')return async(id:string)=>{reached();await gate;return target.readState(id);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}}),input={...q,revision:now.snapshot!.revision,after:20},pending=searchMemoryContent(held,'mission',input);await arrival;input.text='changed';input.after=40;release();assert.equal((await pending)!.versions.length,2);
});
