import test from 'node:test';
import type {TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdtemp,rm,realpath} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import type {ChildProcess} from 'node:child_process';
import {createServer} from 'node:net';
import {createWorkbench} from '../src/server.ts';
import {ProductService} from '../src/product.ts';
import {Application} from '../src/application.ts';
import type {Mission} from '../src/domain.ts';
import {pinnedMemoryInput} from '../src/memory-input.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {InMemoryStore,SurrealStore,createHttpRpcTransport,initializeSurrealSchema} from '../src/storage.ts';
import type {Store} from '../src/storage.ts';
import {verifyDisposableDatabase,verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';

async function fixture(t:TestContext,durable=false,provided?:Store<Mission>){
 let transport;if(durable&&!provided){await verifyDisposableDatabase();const database='retirement_'+crypto.randomUUID().replaceAll('-','');transport=createHttpRpcTransport({endpoint:process.env.MASSION_TEST_SURREAL_RPC!,namespace:process.env.MASSION_TEST_SURREAL_NAMESPACE!,database});await transport.query('DEFINE DATABASE '+database+';',{});await initializeSurrealSchema(transport);}
 const store=provided??(transport?new SurrealStore<Mission>(transport):new InMemoryStore<Mission>()),product=new ProductService(store),root=await mkdtemp(join(tmpdir(),'massion-retirement-http-'));t.after(()=>rm(root,{recursive:true,force:true}));
 let server=createWorkbench(store,root),base='';async function start(){server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address==='object');base='http://127.0.0.1:'+address.port;}async function stop(){if(!server.listening)return;server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}await start();t.after(stop);
 const id='mission:retirement',other='mission:other-retirement',feed=(await store.readState()).feedId;
 async function post(path:string,body:unknown,identity=feed){const res=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':identity},body:JSON.stringify(body)});return {status:res.status,body:await res.json()};}
 for(const missionId of [id,other])assert.equal((await post('/missions',{id:missionId,commandId:'create-'+missionId,purpose:'Retain old memory and stop future use',scope:missionId===id?'owned':'other-scope',constraints:[],criteria:{version:1,description:'Preserve original task data',oracle:'manual-review/v1'}})).status,201);
 const memory={id:'instruction',version:1,content:'Original immutable instruction',source:'Original owner source'};assert.equal((await post('/missions/'+id+'/memory',{commandId:'memory-v1',expectedRevision:1,memory})).status,201);assert.equal((await post('/missions/'+id+'/work',{commandId:'old-work',expectedRevision:2,workId:'old',title:'Old Work',budget:0})).status,201);
 const journal=async()=>store instanceof SurrealStore?(await store.exportJournal()).operations:(store as InMemoryStore<Mission>).inspect();
 return {store,product,id,other,feed,memory,post,journal,route:'/missions/'+id+'/memory-retirement',retirement:{commandId:'retire-v1',expectedRevision:3,memoryId:'instruction',version:1,reason:'Owner stops future application'},stop,async freshHost(){await stop();server=createWorkbench(store,root);await start();},async read(){return (await (await fetch(base+'/missions/'+id)).json());}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} retirement API rejects forged/unauthorized scope and preserves historical input through future exclusion and reactivation`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),before=await f.store.load(f.id),other=await f.store.load(f.other),journal=await f.journal(),old=before!.value.works[0]!,input=pinnedMemoryInput(before!.value,old);
 for(const b of [{...f.retirement,actorId:'owner'},{...f.retirement,scope:'other'},{...f.retirement,authority:'explicit'},{...f.retirement,effective:false},{...f.retirement,missionId:f.other},{...f.retirement,version:0},{...f.retirement,version:2},{...f.retirement,memoryId:'missing'},{...f.retirement,reason:''},{...f.retirement,reason:' '},{...f.retirement,reason:'x'.repeat(16001)}])assert.equal((await f.post(f.route,b)).status,400);
 assert.equal((await f.post('/missions/'+f.other+'/memory-retirement',{...f.retirement,expectedRevision:1})).status,400);assert.deepEqual(await f.store.load(f.other),other);assert.deepEqual(await f.journal(),journal);
 const app=new Application(f.store,[{id:'representative',roles:['representative']},{id:'executor',roles:['executor']}]);for(const actorId of ['representative','executor'])await assert.rejects(app.dispatch({missionId:f.id,commandId:'denied-'+actorId,expectedRevision:3,actorId,command:{type:'retire-memory',memoryId:'instruction',version:1,reason:'Forbidden'}}),/role/);assert.deepEqual(await f.journal(),journal);
 assert.equal((await f.post(f.route,f.retirement,'wrong-feed')).status,409);assert.deepEqual(await f.journal(),journal);
 const changed=await f.post(f.route,f.retirement);assert.equal(changed.status,200);assert.equal(changed.body.status,'committed');let current=(await f.store.load(f.id))!;assert.deepEqual(current.value.works[0],old);assert.deepEqual(current.value.memories,[{...before!.value.memories[0]!,effective:false}]);assert.deepEqual(pinnedMemoryInput(current.value,old),input);assert.deepEqual(await f.store.load(f.other),other);
 const retiredJournal=await f.journal();assert.equal((retiredJournal.at(-1)!.events[0] as any).command.reason,f.retirement.reason);validateMissionJournalLineage(retiredJournal);
 assert.equal((await f.post(f.route,f.retirement)).body.status,'replayed');assert.equal((await f.post(f.route,{...f.retirement,reason:'Different payload'})).status,409);assert.equal((await f.post(f.route,{...f.retirement,commandId:'inactive',expectedRevision:4})).status,400);assert.equal((await f.post(f.route,{...f.retirement,commandId:'stale'})).status,409);assert.deepEqual(await f.journal(),retiredJournal);
 assert.equal((await f.post('/missions/'+f.id+'/work',{commandId:'future-work',expectedRevision:4,workId:'future',title:'Future excluded instruction',budget:0})).status,201);current=(await f.store.load(f.id))!;assert.deepEqual(current.value.works[1]?.appliedMemoryVersions,[]);assert.deepEqual(current.value.works[0],old);
 assert.equal((await f.post('/missions/'+f.id+'/memory',{commandId:'reactivate-v2',expectedRevision:5,memory:{...f.memory,version:2,content:'Deliberate new version'}})).status,201);assert.equal((await f.post(f.route,{...f.retirement,commandId:'superseded',expectedRevision:6})).status,400);assert.equal((await f.post('/missions/'+f.id+'/work',{commandId:'reactivated-work',expectedRevision:6,workId:'reactivated',title:'Future explicit v2',budget:0})).status,201);
 await f.product.app.dispatch({missionId:f.id,commandId:'learned-fixture',expectedRevision:7,actorId:'local-owner',command:{type:'save-memory',memory:{id:'learned',version:1,scope:'owned',authority:'learned',content:'Inactive candidate',source:'Fixture proposal',effective:false}}});const learnedJournal=await f.journal();assert.equal((await f.post(f.route,{...f.retirement,commandId:'retire-learned',expectedRevision:8,memoryId:'learned'})).status,400);assert.deepEqual(await f.journal(),learnedJournal);
 current=(await f.store.load(f.id))!;assert.deepEqual(current.value.works[0],old);assert.deepEqual(current.value.works.map(w=>w.appliedMemoryVersions),[['instruction@1'],[],['instruction@2']]);validateMissionJournalLineage(await f.journal());await f.freshHost();assert.deepEqual(await f.read(),current);assert.deepEqual(await f.journal(),learnedJournal);assert.ok(current.value.works.every(w=>!w.runtimeRun&&!w.effects.length));
 t.diagnostic(JSON.stringify({store:durable?'actual SurrealDB3.3.0':'in-memory fixture',oldWorkAndInputUnchanged:true,futureExcluded:true,deliberateReactivation:true,scopeAndRoleRejection:true,exactReplay:true,providerCalls:0}));
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} concurrent retirement/save and duplicate retirement commit one atomic exact outcome`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),old=(await f.store.load(f.id))!.value.works[0];
 const outcomes=await Promise.all([f.post(f.route,f.retirement),f.post('/missions/'+f.id+'/memory',{commandId:'concurrent-save',expectedRevision:3,memory:{...f.memory,version:2,content:'Concurrent version'}})]);assert.equal(outcomes.filter(r=>r.body.status==='committed').length,1);for(const r of outcomes.filter(r=>r.body.status!=='committed'))assert.ok(r.status===409||r.status===503&&r.body.outcome==='rejected');const current=(await f.store.load(f.id))!;assert.equal(current.revision,4);assert.deepEqual(current.value.works[0],old);assert.equal(current.value.memories[0]?.effective,false);assert.equal(current.value.memories.length,outcomes[0]!.body.status==='committed'?1:2);if(current.value.memories.length===2)assert.equal(current.value.memories[1]?.effective,true);validateMissionJournalLineage(await f.journal());
 const memoryId='duplicate';await f.product.saveMemory(f.id,{commandId:'duplicate-memory',expectedRevision:4,memory:{...f.memory,id:memoryId}});const request={...f.retirement,commandId:'duplicate-retire',expectedRevision:5,memoryId};const duplicates=await Promise.all([f.post(f.route,request),f.post(f.route,request)]);assert.ok(duplicates.some(r=>r.body.status==='committed'));assert.ok(duplicates.every(r=>['committed','replayed'].includes(r.body.status)||r.status===503&&r.body.outcome==='rejected'));const final=(await f.store.load(f.id))!;assert.equal(final.revision,6);const journal=await f.journal();assert.equal(journal.filter(o=>o.commandId==='duplicate-retire').length,1);assert.equal((await f.post(f.route,request)).body.status,'replayed');assert.deepEqual(await f.store.load(f.id),final);assert.deepEqual(await f.journal(),journal);validateMissionJournalLineage(journal);
 t.diagnostic(JSON.stringify({concurrentOutcomes:outcomes.map(r=>({http:r.status,status:r.body.status,outcome:r.body.outcome})),duplicateOutcomes:duplicates.map(r=>({http:r.status,status:r.body.status,outcome:r.body.outcome})),atomicOneCommit:true}));
});

test('owned actual SurrealDB process restart and fresh HTTP host retain retirement journal and old/future pins',{skip:!process.env.SURREAL_TEST_RUNTIME||process.platform!=='linux'},async t=>{
 await verifyDisposableDatabase();const root=await realpath(await mkdtemp(join(tmpdir(),'massion-owned-retirement-db-'))),binary=await realpath(process.env.MASSION_TEST_SURREAL_BINARY!);const listener=createServer();listener.listen(0,'127.0.0.1');await once(listener,'listening');const address=listener.address();assert.ok(address&&typeof address==='object');const port=address.port;await new Promise<void>(r=>listener.close(()=>r()));
 const argv=[binary,'start','surrealkv://'+join(root,'data'),'--bind','127.0.0.1:'+port,'--unauthenticated','--no-banner','--log','error','--default-namespace','retirement','--default-database','retirement','--deny-net','--deny-scripting'];let child:ChildProcess;const children:ChildProcess[]=[];
 t.after(async()=>{for(const owned of children)await stopOwnedChild(owned,{cwd:root,argv});await rm(root,{recursive:true,force:true});});
 async function start(){child=spawn(binary,argv.slice(1),{cwd:root,env:{PATH:'/usr/bin:/bin'},stdio:'ignore'});children.push(child);await once(child,'spawn');await verifyOwnedChild(child,{cwd:root,argv});const deadline=Date.now()+10000;while(true){assert.equal(child.exitCode,null);try{if((await fetch('http://127.0.0.1:'+port+'/ready')).ok)break;}catch{}assert.ok(Date.now()<deadline);await new Promise(r=>setTimeout(r,20));}}
 await start();const originalPid=child!.pid,transport=createHttpRpcTransport({endpoint:'http://127.0.0.1:'+port+'/rpc',namespace:'retirement',database:'retirement'});await initializeSurrealSchema(transport);const store=new SurrealStore<Mission>(transport),f=await fixture(t,false,store);assert.equal((await f.post(f.route,f.retirement)).body.status,'committed');assert.equal((await f.post('/missions/'+f.id+'/work',{commandId:'future-restart',expectedRevision:4,workId:'future',title:'After retirement',budget:0})).status,201);
 const before=await store.load(f.id),journal=await store.exportJournal(),events=await store.readEvents(0,1000),state=await store.readState(f.id);await f.stop();await stopOwnedChild(child!,{cwd:root,argv});await start();assert.notEqual(child!.pid,originalPid);const fresh=new SurrealStore<Mission>(transport);assert.deepEqual(await fresh.load(f.id),before);assert.deepEqual(await fresh.exportJournal(),journal);assert.deepEqual(await fresh.readEvents(0,1000),events);assert.deepEqual(await fresh.readState(f.id),state);await f.freshHost();assert.deepEqual(await f.read(),before);assert.equal((await f.post(f.route,f.retirement)).body.status,'replayed');assert.deepEqual(await fresh.exportJournal(),journal);assert.deepEqual(before!.value.works.map(w=>w.appliedMemoryVersions),[['instruction@1'],[]]);assert.equal(pinnedMemoryInput(before!.value,before!.value.works[0]!)[0]?.content,f.memory.content);validateMissionJournalLineage(journal.operations);
 t.diagnostic(JSON.stringify({originalOwnedDbPid:originalPid,restartedOwnedDbPid:child!.pid,actualDbProcessRestart:true,normalHttpFreshHost:true,snapshotEventsFeedJournalEqual:true,oldInputRetained:true,futureExcluded:true,providerCalls:0}));
});
