import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {memoryFindFixture as fixture} from './support/memory-find-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function setup(t:any,durable=false,mode='normal'){
 const f=await fixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});let base='http://127.0.0.1:'+(server.address() as any).port,posts=0,reads=0,usage=0,release!:()=>void,reached!:()=>void;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),app=harness(async(path:string,options:any)=>{if(options.method==='POST')posts++;const find=path.includes('/memory-versions?'),next=find&&path.includes('&after=20');if(find)reads++;if(path.includes('/memory-usage?'))usage++;const res=await fetch(base+path,options),body=await res.json();if(next&&mode==='held'){reached();await gate;}if(next&&mode==='offset')body.offset=0;if(next&&mode==='repeat')body.versions=[body.versions[0],body.versions[0]];if(next&&mode==='hash')body.versions[0].versionHash='0'.repeat(64);return reply(body,res.status);},{},undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden&&!app.node('memory-find-id').disabled);app.node('memory-find-id').value=JSON.stringify(f.id);await app.node('memory-find-id').fire('input');return {...f,app,base,posts:()=>posts,reads:()=>reads,usage:()=>usage,release,arrival,replaceBase:(b:string)=>base=b};
}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} explicit discovery 20 plus 2 selects exact inactive original for separate usage with no automatic reads/writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),before=await f.current(),journal=await f.journal();assert.equal(f.reads(),0);await f.app.node('memory-find-read').fire('click');assert.match(f.app.node('memory-find-status').textContent,/showing 20/);await f.app.tick();assert.equal(f.reads(),1);await f.app.node('memory-find-more').fire('click');assert.match(f.app.node('memory-find-status').textContent,/positions 21–22/);assert.equal(f.app.node('memory-find-more').disabled,true);assert.equal(f.reads(),2);assert.equal(f.usage(),0);const button=f.app.node('memory-find-results').children.find(n=>n.tagName==='BUTTON')!;await button.fire('click');assert.equal(f.app.node('memory-usage-target').value,JSON.stringify([f.id,21]));assert.equal(f.usage(),0);await f.app.node('memory-usage-read').fire('click');const result=JSON.parse(f.app.node('memory-usage-result').textContent);assert.equal(result.memory.id,f.id);assert.equal(result.memory.version,21);assert.equal(result.memory.effective,false);assert.equal(result.uses.length,0);assert.equal(f.usage(),1);assert.equal(f.posts(),0);assert.deepEqual(await f.current(),before);assert.deepEqual(await f.journal(),journal);
});
for(const action of ['cancel','input','selection','mission','revision','offline'])test(`held discovery next rejected after ${action}; duplicate click makes no extra GET`,async t=>{
 const f=await setup(t,false,'held'),app=f.app,before=await f.current();await app.node('memory-find-read').fire('click');const pending=app.node('memory-find-more').fire('click');await f.arrival;await app.node('memory-find-more').fire('click');assert.equal(f.reads(),2);if(action==='cancel')await app.node('memory-find-cancel').fire('click');if(action==='input'){app.node('memory-find-id').value=JSON.stringify('missing');await app.node('memory-find-id').fire('input');}if(action==='selection')await app.node('memory-usage-target').fire('change');if(action==='mission')await runInContext("loadMission('other',false)",app.context);if(action==='revision'){await f.product.saveMemory('mission',{commandId:'find-peer',expectedRevision:(await f.current()).revision,memory:{id:'peer',version:1,content:'Peer',source:'Owner'}});await runInContext("loadMission('mission',false)",app.context);}if(action==='offline')await app.windowEvent('offline');const journal=await f.journal(),state=await f.current();f.release();await pending;assert.equal(app.node('memory-find-results').hidden,true);assert.equal(app.node('memory-find-more').disabled,true);assert.equal(f.reads(),2);assert.equal(f.usage(),0);assert.equal(f.posts(),0);assert.deepEqual(await f.journal(),journal);assert.deepEqual(await f.current(),state);assert.deepEqual(state.value.works,before.value.works);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} old-feed held discovery cannot populate replacement Mission`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable,'held'),second=await setup(t,durable),app=f.app,one=await f.journal(),two=await second.journal();await app.node('memory-find-read').fire('click');const pending=app.node('memory-find-more').fire('click');await f.arrival;f.replaceBase(second.base);await app.windowEvent('online');const end=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('memory-find-id').disabled){assert.ok(Date.now()<end);await app.tick();await new Promise(r=>setTimeout(r,5));}f.release();await pending;assert.equal(app.node('memory-find-id').value,'');assert.equal(app.node('memory-find-results').hidden,true);assert.equal(f.posts(),0);assert.equal(f.usage(),0);assert.deepEqual(await f.journal(),one);assert.deepEqual(await second.journal(),two);
});
for(const mode of ['offset','repeat','hash'])test(`forged discovery ${mode} clears page instead of choosing substituted original`,async t=>{const f=await setup(t,false,mode),journal=await f.journal();await f.app.node('memory-find-read').fire('click');await f.app.node('memory-find-more').fire('click');assert.equal(f.app.node('memory-find-results').hidden,true);assert.equal(f.app.node('memory-find-more').disabled,true);assert.match(f.app.node('memory-find-status').textContent,/failed exact binding/);assert.equal(f.usage(),0);assert.equal(f.posts(),0);assert.deepEqual(await f.journal(),journal);});
test('completed discovery cleared immediately offline; JSON input missing/malformed never fetches and no-match is explicit',async t=>{const f=await setup(t),journal=await f.journal();await f.app.node('memory-find-read').fire('click');await f.app.windowEvent('offline');assert.equal(f.app.node('memory-find-results').hidden,true);assert.equal(f.reads(),1);await f.app.windowEvent('online');await f.until(()=>f.app.node('sync-notice').hidden&&!f.app.node('memory-find-id').disabled);for(const value of ['',f.id,'" "','"\\ud800"']){f.app.node('memory-find-id').value=value;await f.app.node('memory-find-id').fire('input');await f.app.node('memory-find-read').fire('click');assert.equal(f.reads(),1);}f.app.node('memory-find-id').value=JSON.stringify('missing');await f.app.node('memory-find-id').fire('input');await f.app.node('memory-find-read').fire('click');assert.match(f.app.node('memory-find-results').textContent,/No exact explicit/);assert.equal(f.reads(),2);assert.equal(f.posts(),0);assert.deepEqual(await f.journal(),journal);});
