import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {memoryConflictFixture} from './support/memory-conflict-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function setup(t:any,durable=false,mode='normal'){
 const f=await memoryConflictFixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});let base='http://127.0.0.1:'+(server.address() as any).port,posts=0,release!:()=>void,held=false,failEvents=false,receiptsUnavailable=false;const gate=new Promise<void>(r=>release=r),handler=async(path:string,options:any)=>{const write=path.endsWith('/memory-expiry')&&options.method==='POST';if(write){posts++;if(mode==='wrong-feed')receiptsUnavailable=true;if(mode==='unknown')return reply({outcome:'unknown',error:'Original unresolved receipt'},503);}if(path.startsWith('/events')&&receiptsUnavailable)throw Error('Controlled receipt unavailable');if(path.startsWith('/events')&&failEvents){failEvents=false;throw Error('Controlled delayed receipt');}const res=await fetch(base+path,options),body=await res.json();if(write){if(mode==='held'){held=true;await gate;}if(mode==='lost'){failEvents=true;throw Error('Committed ACK lost');}if(mode==='wrong-feed')body.feedId='another-db';}return reply(body,res.status);},client=async(storage:any={},locked=false)=>{const app=harness(handler,storage,undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>locked?app.storage.has('massion.workbench.pending')&&app.node('memory-expiry-fields').disabled:app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden&&!app.node('memory-expiry-fields').disabled);if(locked)await app.tick();const fields=app.node('memory-expiry-fields');app.node('memory-expiry-form').append(fields);for(const id of ['memory-expiry-first','memory-expiry-deadline','memory-expiry-reason','memory-expiry-review','memory-expiry-save','memory-expiry-cancel'])fields.append(app.node(id));return app;},app=await client();return {...f,app,client,posts:()=>posts,held:()=>held,release:()=>release(),replaceBase:(b:string)=>base=b,base};
}
async function edit(app:any,reason='Owner exact reason <img src=x> 원문 😀',first='a',deadline='2099-01-01T00:00:00.000Z'){for(const [id,value] of [['memory-expiry-first',JSON.stringify([first,1])],['memory-expiry-deadline',deadline],['memory-expiry-reason',reason]]){app.node(id).value=value;await app.node(id).fire('input');}}
async function review(app:any){await app.node('memory-expiry-review').fire('click');}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} exact expiry Review/Cancel/Declare preserves originals and sends once`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await setup(t,durable),app=f.app,before=await f.current();await edit(app);await app.submit('memory-expiry-form');assert.equal(f.posts(),0);await review(app);assert.equal(app.node('memory-expiry-save').disabled,false);assert.match(app.node('memory-expiry-original').textContent,/\\r\\n/);await app.node('memory-expiry-cancel').fire('click');assert.equal(f.posts(),0);await edit(app);await review(app);await app.submit('memory-expiry-form');assert.equal(f.posts(),1);assert.match(app.node('memory-expiry-status').textContent,/confirmed/);assert.deepEqual((await f.current()).value.works,before.value.works);assert.equal((await f.current()).value.memoryExpiries![0]!.memory.id,'a');assert.equal(app.all().some(n=>n.tagName==='IMG'),false);await edit(app);await review(app);assert.equal(app.node('memory-expiry-save').disabled,true);await app.submit('memory-expiry-form');assert.equal(f.posts(),1);});
test('edit ABA, current revision and disconnect invalidate Review and retain private Mission drafts',async t=>{
 const f=await setup(t),app=f.app;await edit(app);await review(app);await edit(app,'ABA');await edit(app);await app.submit('memory-expiry-form');assert.equal(f.posts(),0);await review(app);await f.product.saveMemory('mission',{commandId:'peer-memory',expectedRevision:(await f.current()).revision,memory:{id:'peer',version:1,content:'Other exact memory',source:'Owner'}});await runInContext("loadMission('mission',false)",app.context);assert.equal(app.node('memory-expiry-save').disabled,true);assert.equal(app.node('memory-expiry-reason').value,'Owner exact reason <img src=x> 원문 😀');await app.submit('memory-expiry-form');assert.equal(f.posts(),0);await runInContext("loadMission('other',false)",app.context);await edit(app,'Other Mission private');await runInContext("loadMission('mission',false)",app.context);assert.equal(app.node('memory-expiry-reason').value,'Owner exact reason <img src=x> 원문 😀');await review(app);await app.windowEvent('offline');assert.equal(app.node('memory-expiry-save').disabled,true);
});
test('stale declaration returns CAS conflict once and requires explicit new Review',async t=>{
 const f=await setup(t),app=f.app;await edit(app);await review(app);await f.product.saveMemory('mission',{commandId:'peer-cas',expectedRevision:(await f.current()).revision,memory:{id:'peer',version:1,content:'Other',source:'Other'}});await app.submit('memory-expiry-form');assert.equal(f.posts(),1);assert.match(app.node('status').textContent,/Revision conflict/);assert.equal(app.node('memory-expiry-save').disabled,true);await app.submit('memory-expiry-form');assert.equal(f.posts(),1);await review(app);await app.submit('memory-expiry-form');assert.equal(f.posts(),2);assert.equal((await f.current()).value.memoryExpiries!.length,1);
});
for(const mode of ['unknown','wrong-feed'])test(`${mode} declaration without durable receipt keeps pending marker and locks Cancel/repeated save/restart`,async t=>{
 const f=await setup(t,false,mode),app=f.app;await edit(app);await review(app);await app.submit('memory-expiry-form');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('memory-expiry-fields').disabled,true);await app.node('memory-expiry-cancel').fire('click');await app.submit('memory-expiry-form');assert.equal(f.posts(),1);assert.equal(app.node('memory-expiry-reason').value,'Owner exact reason <img src=x> 원문 😀');const marker=app.storage.get('massion.workbench.pending'),journal=await f.journal(),fresh=await f.client(Object.fromEntries(app.storage),true);assert.equal(fresh.storage.get('massion.workbench.pending'),marker);assert.equal(fresh.node('memory-expiry-fields').disabled,true);assert.equal(f.posts(),1);assert.deepEqual(await f.journal(),journal);
});
for(const laterEdit of [false,true])test(`lost exact receipt clears only unchanged draft (later edit ${laterEdit}) without replay`,async t=>{
 const f=await setup(t,false,'lost'),app=f.app;await edit(app);await review(app);await app.submit('memory-expiry-form');assert.ok(app.storage.has('massion.workbench.pending'));if(laterEdit)await edit(app,'Later private reason');await app.tick();await f.until(()=>!app.storage.has('massion.workbench.pending'));assert.match(app.node('memory-expiry-status').textContent,/confirmed/);assert.equal(app.node('memory-expiry-reason').value,laterEdit?'Later private reason':'');assert.equal(f.posts(),1);assert.equal((await f.current()).value.memoryExpiries!.length,1);
});
test('held response locks duplicate/Cancel/navigation and cannot replace later selected Mission or moved focus',async t=>{
 const f=await setup(t,false,'held'),app=f.app;await edit(app);await review(app);app.node('memory-expiry-save').focus();const pending=app.submit('memory-expiry-form');await f.until(f.held);await app.submit('memory-expiry-form');await app.node('memory-expiry-cancel').fire('click');await app.navigateFragment('#mission=other');assert.equal(app.node('loaded-id').textContent,'mission');await runInContext("loadMission('other',false)",app.context);app.node('memory-expiry-current').focus();f.release();await pending;assert.equal(app.node('loaded-id').textContent,'other');assert.equal((app.context as any).document.activeElement.id,'memory-expiry-current');assert.equal(f.posts(),1);assert.equal((await f.current()).value.memoryExpiries!.length,1);assert.equal((await f.store.load('other'))!.value.memoryExpiries,undefined);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} same-ID replacement DB retains draft and revokes Review without any declaration`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),second=await setup(t,durable),app=f.app;await edit(app);await review(app);const journal=await second.journal();f.replaceBase(second.base);await app.windowEvent('online');const end=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('memory-expiry-fields').disabled){assert.ok(Date.now()<end,'Replacement feed deadline');await app.tick();await new Promise(r=>setTimeout(r,5));}assert.equal(app.node('memory-expiry-save').disabled,true);assert.equal(app.node('memory-expiry-reason').value,'Owner exact reason <img src=x> 원문 😀');await app.submit('memory-expiry-form');assert.equal(f.posts(),0);assert.deepEqual(await second.journal(),journal);
});
test('actual DB held old-feed declaration cannot clear unknown marker or rewrite replacement Mission',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,true,'held'),second=await setup(t,true),app=f.app,replacement=await second.current(),journal=await second.journal();await edit(app);await review(app);const pending=app.submit('memory-expiry-form');await f.until(f.held);f.replaceBase(second.base);await app.windowEvent('offline');f.release();await pending;assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('memory-expiry-fields').disabled,true);assert.equal(f.posts(),1);assert.deepEqual(await second.current(),replacement);assert.deepEqual(await second.journal(),journal);
});
test('asynchronous digest review cannot survive private edit ABA and late acknowledgement preserves deliberately moved focus',async t=>{
 const f=await setup(t,false,'held'),app=f.app;await edit(app);let release!:()=>void;(app.context as any).digestGate=new Promise<void>(r=>release=r);await runInContext('const originalConflictDigest=sequenceHash;sequenceHash=async v=>{await digestGate;return originalConflictDigest(v);}',app.context);const pendingReview=review(app);await edit(app,'Digest-time edit');await edit(app);release();await pendingReview;assert.equal(app.node('memory-expiry-save').disabled,true);assert.equal(f.posts(),0);await runInContext('sequenceHash=originalConflictDigest;',app.context);await review(app);app.node('memory-expiry-save').focus();const pending=app.submit('memory-expiry-form');await f.until(f.held);app.node('memory-expiry-current').focus();f.release();await pending;assert.equal((app.context as any).document.activeElement.id,'memory-expiry-current');assert.match(app.node('memory-expiry-status').textContent,/confirmed/);assert.equal(f.posts(),1);
});
test('past/malformed UTC, literal identity and invalidated review reject without automatic writes',async t=>{const f=await setup(t),app=f.app;for(const deadline of ['2000-01-01T00:00:00.000Z','2099-02-30T00:00:00.000Z','2099-01-01T00:00:00Z']){await edit(app,'Owner','a',deadline);await review(app);await app.submit('memory-expiry-form');assert.equal(f.posts(),0);}const id='literal\r\n원문😀';await f.product.saveMemory('mission',{commandId:'literal-id',expectedRevision:(await f.current()).revision,memory:{id,version:1,content:'Original literal identity',source:'Owner'}});await runInContext("loadMission('mission',false)",app.context);await edit(app,'Literal expiry',id);await review(app);await app.submit('memory-expiry-form');assert.equal((await f.current()).value.memoryExpiries![0]!.memory.id,id);assert.equal(f.posts(),1);});
