import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {memoryConflictFixture as fixture} from './support/memory-conflict-fixture.ts';
import {apply,hash,memoryVersionHash,workInputHash} from '../src/domain.ts';
import {Application} from '../src/application.ts';
import {ProductService} from '../src/product.ts';
import {applicableMemoryConflicts,validateMemoryConflicts,memoryConflictPair} from '../src/memory-conflicts.ts';
import {validateMissionJournalLineage,validateMissionLineage} from '../src/backup-lineage.ts';
import {workAdmissionPreflight} from '../src/configured-runtime.ts';
import {SurrealStore} from '../src/storage.ts';
import {growthStore} from './support/growth-fixture.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} declaration blocks only new Work; retirement permits new pins, old Work/Record/unknown unchanged and portable restore exact`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),before=await f.current(),other=await f.store.load('other'),input=await f.input(),oldHash=workInputHash(before.value.works.find(w=>w.id==='old')!),ready=workAdmissionPreflight(before,'old',before.revision);assert.equal((await f.product.declareMemoryConflict('mission',input)).status,'committed');const declared=await f.current();assert.deepEqual(declared.value.works,before.value.works);assert.equal(workInputHash(declared.value.works.find(w=>w.id==='old')!),oldHash);assert.equal(workAdmissionPreflight(declared,'old',declared.revision).ready,ready.ready);assert.equal(applicableMemoryConflicts(declared.value).length,1);assert.deepEqual(declared.value.memoryConflicts![0]!,{id:input.conflictId,first:input.first,second:input.second,actorId:'local-owner',reason:input.reason});const journal=await f.journal();await assert.rejects(f.product.admit('mission',{commandId:'blocked-new',expectedRevision:declared.revision,workId:'new',title:'New requested responsibility',budget:8}),/New Work admission blocked/);assert.deepEqual(await f.journal(),journal);assert.deepEqual(await f.current(),declared);
 const model={provider:'fixture',model:'data-only',configVersion:'v1',reason:'Existing Work transition remains available',evidenceClass:'fixture' as const};assert.doesNotThrow(()=>apply(declared.value,{type:'assign',workId:'old',assignment:{id:'old-assignment',actorId:'executor',role:'executor',taskId:'old:root',model,extensionVersion:'v1'}},{id:'local-owner',roles:['owner']}));
 await f.product.retireMemory('mission',{commandId:'retire-b',expectedRevision:declared.revision,memoryId:'b',version:1,reason:'Exclude exact conflicting B from future Work'});const retired=await f.current();assert.equal(applicableMemoryConflicts(retired.value).length,0);assert.deepEqual(retired.value.memoryConflicts,declared.value.memoryConflicts);await f.product.admit('mission',{commandId:'explicit-new',expectedRevision:retired.revision,workId:'new',title:'Explicit new responsibility after retirement',budget:8});const now=await f.current();assert.deepEqual(now.value.works.slice(0,-1),before.value.works);assert.deepEqual(now.value.works.at(-1)!.appliedMemoryVersions,['a@1']);assert.equal(now.value.works.at(-1)!.runtimeRun,undefined);assert.deepEqual(await f.store.load('other'),other);validateMissionLineage(now.value);validateMissionJournalLineage(await f.journal());
 if(durable){assert.ok(f.store instanceof SurrealStore);const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{store:target}=await growthStore(true);assert.ok(target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/conflict-restored');assert.deepEqual((await target.load('mission'))!.value,now.value);assert.equal(applicableMemoryConflicts((await target.load('mission'))!.value).length,0);assert.notEqual((await target.readState()).feedId,(await f.store.readState()).feedId);}
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} owner exact conflict API rejects forged/cross-Mission/stale/hash/duplicate pairs and preserves replay/feed`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),input=await f.input(),{createWorkbench}=await import('../src/server.ts'),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port,feed=(await f.store.readState()).feedId,post=async(body:any,identity=feed,mission='mission')=>{const res=await fetch(base+'/missions/'+mission+'/memory-conflict',{method:'POST',headers:{'content-type':'application/json','x-massion-feed':identity},body:JSON.stringify(body)});return {status:res.status,body:await res.json()};},journal=await f.journal();
 for(const patch of [{actorId:'executor'},{role:'owner'},{workId:'old'},{first:input.second},{first:{...input.first,hash:'0'.repeat(64)}},{first:{...input.first,version:2}},{first:{...input.first,scope:'local'}},{reason:''},{reason:'\ud800'},{reason:'x'.repeat(2001)}])assert.equal((await post({...input,...patch})).status,400);assert.equal((await post(input,'other-feed')).status,409);assert.equal((await post({...input,expectedRevision:(await f.store.load('other'))!.revision},feed,'other')).status,400);assert.deepEqual(await f.journal(),journal);const untrusted=new Application(f.store,[{id:'representative',roles:['representative']}]);await assert.rejects(untrusted.dispatch({missionId:'mission',commandId:'denied',expectedRevision:input.expectedRevision,actorId:'representative',command:{type:'declare-memory-conflict',conflictId:input.conflictId,first:input.first,second:input.second,reason:input.reason}}));assert.equal((await post(input)).status,200);const after=await f.journal();assert.equal((await post(input)).body.status,'replayed');assert.equal((await post({...input,reason:'Changed payload'})).status,409);assert.equal((await post({...input,commandId:'stale'})).status,409);
 const reversed={commandId:'reversed',expectedRevision:(await f.current()).revision,conflictId:'conflict:reverse',first:{hash:input.second.hash,version:input.second.version,id:input.second.id},second:{version:input.first.version,id:input.first.id,hash:input.first.hash},reason:'Reversed pair'};assert.equal(memoryConflictPair(reversed.first,reversed.second),memoryConflictPair(input.first,input.second));assert.equal((await post(reversed)).status,400);assert.deepEqual(await f.journal(),after);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} frozen caller and concurrent declaration/admission/retirement serialize truthfully`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),input=await f.input(),original=structuredClone(input);let reached!:()=>void,release!:()=>void,held=false;const arrival=new Promise<void>(r=>reached=r),gate=new Promise<void>(r=>release=r),store=new Proxy(f.store,{get(target,key){if(key==='lookupOperation')return async(value:any)=>{if(!held){held=true;reached();await gate;}return target.lookupOperation(value);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}}),pending=new ProductService(store).declareMemoryConflict('mission',input);await arrival;input.first.id='mutated';input.second.hash='0'.repeat(64);input.reason='Mutated';input.commandId='mutated';release();assert.equal((await pending).status,'committed');assert.deepEqual((await f.current()).value.memoryConflicts![0]!.first,original.first);assert.equal((await f.product.declareMemoryConflict('mission',original)).status,'replayed');
 const fresh=await fixture(t,durable),declaration=await fresh.input(),revision=declaration.expectedRevision,results=await Promise.all([fresh.product.declareMemoryConflict('mission',declaration),fresh.product.admit('mission',{commandId:'race-work',expectedRevision:revision,workId:'race',title:'Concurrent admission',budget:8})]);assert.equal(results.filter(r=>r.status==='committed').length,1);assert.equal(results.filter(r=>r.status==='conflict').length,1);validateMissionJournalLineage(await fresh.journal());
 const retirement=await fixture(t,durable),declare=await retirement.input(),r=await Promise.all([retirement.product.declareMemoryConflict('mission',declare),retirement.product.retireMemory('mission',{commandId:'race-retire',expectedRevision:declare.expectedRevision,memoryId:'b',version:1,reason:'Concurrent retirement'})]);assert.equal(r.filter(v=>v.status==='committed').length,1);assert.equal(r.filter(v=>v.status==='conflict').length,1);validateMissionJournalLineage(await retirement.journal());
});
test('learned/inactive/history tamper and exact bounded conflict arrays fail closed without old Work mutation',async t=>{
 const f=await fixture(t),input=await f.input(),state=(await f.current()).value;for(const mutate of [(m:any)=>m.memories.find((x:any)=>x.id==='b').effective=false,(m:any)=>m.memories.find((x:any)=>x.id==='b').authority='learned']){const changed=structuredClone(state);mutate(changed);const m=changed.memories.find(x=>x.id==='b')!,c={type:'declare-memory-conflict' as const,conflictId:input.conflictId,first:input.first,second:{id:'b',version:1,hash:memoryVersionHash(m)},reason:input.reason};assert.throws(()=>apply(changed,c,{id:'local-owner',roles:['owner']}));assert.equal(changed.memoryConflicts,undefined);}
 await f.product.declareMemoryConflict('mission',input);const original=(await f.current()).value;for(const mutate of [(m:any)=>m.memoryConflicts[0].first.hash='0'.repeat(64),(m:any)=>m.memoryConflicts[0].reason='\ud800',(m:any)=>m.memoryConflicts.push({...m.memoryConflicts[0],id:'duplicate-pair'}),(m:any)=>m.memoryConflicts[0].extra=true,(m:any)=>m.memoryConflicts.extra='not JSON',(m:any)=>delete m.memories[0]]){const changed=structuredClone(original);mutate(changed);assert.throws(()=>validateMemoryConflicts(changed));assert.throws(()=>validateMissionLineage(changed));}const sparse=structuredClone(original);sparse.memoryConflicts=Array(2);assert.throws(()=>validateMemoryConflicts(sparse));const large=structuredClone(original);large.memoryConflicts=Array(101).fill(original.memoryConflicts![0]!);assert.throws(()=>validateMemoryConflicts(large));assert.deepEqual((await f.current()).value,original);
});
test('declaration history does not follow advancing versions or label retirement as semantic resolution; exact old hash survives',async t=>{
 const f=await fixture(t),input=await f.input();await f.product.declareMemoryConflict('mission',input);const declared=await f.current(),original=structuredClone(declared.value.memoryConflicts);await f.product.saveMemory('mission',{commandId:'advance-b',expectedRevision:declared.revision,memory:{id:'b',version:2,content:'Owner edited B v2; not an automatic semantic certificate',source:'Explicit new version'}});const advanced=await f.current();assert.deepEqual(advanced.value.memoryConflicts,original);assert.equal(applicableMemoryConflicts(advanced.value).length,0);assert.equal(memoryVersionHash(advanced.value.memories.find(m=>m.id==='b'&&m.version===1)!),input.second.hash);await f.product.admit('mission',{commandId:'after-advance',expectedRevision:advanced.revision,workId:'after-advance',title:'Owner admits current versions separately',budget:8});assert.deepEqual((await f.current()).value.works.at(-1)!.appliedMemoryVersions,['a@1','b@2']);assert.deepEqual((await f.current()).value.works.slice(0,-1),declared.value.works);validateMissionJournalLineage(await f.journal());
});
test('exact history count and UTF-8 total bytes bound are independently enforced',async t=>{
 const f=await fixture(t),mission=structuredClone((await f.current()).value),a=mission.memories.find(m=>m.id==='a')!;for(let i=0;i<100;i++)mission.memories.push({...a,id:'other-'+i});mission.memoryConflicts=Array.from({length:100},(_,i)=>{const second=mission.memories.find(m=>m.id==='other-'+i)!;return {id:'conflict:'+i,first:{id:a.id,version:a.version,hash:memoryVersionHash(a)},second:{id:second.id,version:second.version,hash:memoryVersionHash(second)},actorId:'local-owner',reason:'Owner reason'};});validateMemoryConflicts(mission);for(const c of mission.memoryConflicts)c.reason='한'.repeat(500);assert.throws(()=>validateMemoryConflicts(mission),/bounded array contract/);
});
