import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {memoryFindFixture as fixture} from './support/memory-find-fixture.ts';
import {findMemoryVersions} from '../src/memory-find.ts';
import {memoryVersionHash} from '../src/domain.ts';
import {NEAR_MEMORY_ID} from './support/memory-usage-literal-fixture.ts';
import {createWorkbench} from '../src/server.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} exact literal ID finds 22 original explicit versions as 20 plus 2 without writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),state=await f.store.readState('mission'),before=await f.current(),journal=await f.journal(),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port,path='/missions/mission/memory-versions?id='+encodeURIComponent(f.id)+'&revision='+state.snapshot!.revision;
 const get=async(suffix='')=>{const r=await fetch(base+path+suffix,{headers:{'X-Massion-Feed':state.feedId}});return {status:r.status,body:await r.json()};};const first=await get(),last=await get('&after=20');assert.equal(first.status,200);assert.equal(last.status,200);assert.equal(first.body.versions.length,20);assert.equal(last.body.versions.length,2);assert.deepEqual([...first.body.versions,...last.body.versions].map(m=>m.memory.version),Array.from({length:22},(_,i)=>i+1));assert.equal(first.body.versions[0].memory.id,f.id);assert.equal(first.body.versions[0].memory.effective,false);assert.equal(first.body.totalVersions,22);assert.equal(first.body.nextAfter,20);assert.equal(last.body.nextAfter,null);for(const e of [...first.body.versions,...last.body.versions]){assert.equal(e.memory.authority,'explicit');assert.equal(e.versionHash,memoryVersionHash(e.memory));}assert.equal(last.body.versions[1].memory.effective,true);
 for(const suffix of ['&after=0','&after=1','&after=40','&after=-20','&after=1e2','&after=20&after=20','&id='+encodeURIComponent(f.id),'&extra=x','&revision='+state.snapshot!.revision])assert.equal((await get(suffix)).status,400);
 for(const [id,total] of [['missing',0],[f.id.trim(),0],[NEAR_MEMORY_ID,1]] as const){const r=await fetch(base+path.replace(encodeURIComponent(f.id),encodeURIComponent(id)),{headers:{'X-Massion-Feed':state.feedId}});assert.equal(r.status,200);assert.equal((await r.json()).totalVersions,total);}
 assert.equal((await fetch(base+path)).status,400);assert.equal((await fetch(base+path,{headers:{'X-Massion-Feed':'wrong'}})).status,409);assert.equal((await fetch(base+path.replace('revision='+state.snapshot!.revision,'revision=1'),{headers:{'X-Massion-Feed':state.feedId}})).status,409);assert.equal((await findMemoryVersions(f.store,'other',{id:f.id,feedId:state.feedId,revision:(await f.store.load('other'))!.revision}))!.totalVersions,1);
 assert.deepEqual(await f.current(),before);assert.deepEqual(await f.journal(),journal);
 await f.product.saveMemory('mission',{commandId:'find-peer',expectedRevision:before.revision,memory:{id:'peer',version:1,content:'Peer change',source:'Owner'}});const after=await f.journal();assert.equal((await get('&after=20')).status,409);assert.deepEqual(await f.journal(),after);assert.deepEqual((await f.current()).value.works,before.value.works);
});
test('memory discovery bounds, frozen input, malformed queries and invalid lineage fail closed',async t=>{
 const f=await fixture(t),s=await f.store.readState('mission'),q={id:f.id,revision:s.snapshot!.revision,feedId:s.feedId};let reads=0;const counted=new Proxy(f.store,{get(target,key){if(key==='readState')return async(id:string)=>{reads++;return target.readState(id);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}});
 for(const patch of [{id:''},{id:' '},{id:'x'.repeat(16001)},{id:'\ud800'},{revision:0},{revision:NaN},{feedId:''},{after:0},{after:1},{after:20.5},{extra:true}])await assert.rejects(findMemoryVersions(counted,'mission',{...q,...patch} as any));assert.equal(reads,0);
 for(const id of ['é','e\u0301','x'.repeat(16000)])await f.product.saveMemory('mission',{commandId:'boundary-'+id,expectedRevision:(await f.current()).revision,memory:{id,version:1,content:'Exact boundary',source:'Owner'}});const now=await f.store.readState('mission');for(const id of ['é','e\u0301','x'.repeat(16000)])assert.equal((await findMemoryVersions(f.store,'mission',{...q,id,revision:now.snapshot!.revision}))!.versions[0]!.memory.id,id);
 const corrupt=structuredClone(now);corrupt.snapshot!.value.works.find(w=>w.id==='use-00')!.record!.checksum='0'.repeat(64);const bad=new Proxy(f.store,{get(target,key){if(key==='readState')return async()=>corrupt;const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}});await assert.rejects(findMemoryVersions(bad,'mission',{...q,revision:now.snapshot!.revision}),/lineage invalid/);
 let release!:()=>void,reached!:()=>void;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),held=new Proxy(f.store,{get(target,key){if(key==='readState')return async(id:string)=>{reached();await gate;return target.readState(id);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}}),input={...q,revision:now.snapshot!.revision,after:20},pending=findMemoryVersions(held,'mission',input);await arrival;input.id='changed';input.after=40;release();assert.equal((await pending)!.versions.length,2);
});
test('exact discovery 1/20/21/40 boundaries and absent ID have truthful bounded continuation',async t=>{for(const count of [1,20,21,40]){const f=await fixture(t,false,false,count),s=await f.store.readState('mission'),q={id:f.id,feedId:s.feedId,revision:s.snapshot!.revision},journal=await f.journal(),first=(await findMemoryVersions(f.store,'mission',q))!;assert.equal(first.totalVersions,count);assert.equal(first.versions.length,Math.min(20,count));assert.equal(first.nextAfter,count>20?20:null);if(count>20){const last=(await findMemoryVersions(f.store,'mission',{...q,after:20}))!;assert.equal(last.versions.length,count-20);assert.equal(last.nextAfter,null);}assert.equal((await findMemoryVersions(f.store,'mission',{...q,id:'missing'}))!.totalVersions,0);assert.deepEqual(await f.journal(),journal);}});
