import test from 'node:test';
import {once} from 'node:events';
import assert from 'node:assert/strict';
import {memoryConflictFixture as fixture} from './support/memory-conflict-fixture.ts';
import {Application} from '../src/application.ts';
import {apply,memoryVersionHash,workInputHash} from '../src/domain.ts';
import {validateMemoryExpiries} from '../src/memory-expiry.ts';
import {validateMissionJournalLineage,validateMissionLineage} from '../src/backup-lineage.ts';
const start=Date.parse('2026-10-08T00:00:00.000Z'),deadline=start+1000;
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} exact expiry boundary, rollback, replay, retirement, old Work/Record/unknown and portable replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),before=await f.current(),old=before.value.works.map(workInputHash);let now=start,calls=0;const app=new Application(f.store,[{id:'local-owner',roles:['owner']}],()=>{calls++;return now;}),memory=before.value.memories.find(m=>m.id==='a')!,command={type:'declare-memory-expiry' as const,expiryId:'expiry:a',memory:{id:memory.id,version:memory.version,hash:memoryVersionHash(memory)},deadline:new Date(deadline).toISOString(),reason:'Exact original expiry <img src=x>\r\n원문 😀'},envelope={missionId:'mission',commandId:'expiry-declare',expectedRevision:before.revision,actorId:'local-owner',command},send=async(c:any,id:string)=>app.dispatch({missionId:'mission',commandId:id,expectedRevision:(await f.current()).revision,actorId:'local-owner',command:c});
 assert.equal((await app.dispatch(envelope)).status,'committed');const declared=await f.current();assert.deepEqual(declared.value.works,before.value.works);assert.equal(declared.value.memoryTimeWatermark,start);now=deadline-1;const admission={missionId:'mission',commandId:'before-expiry',expectedRevision:declared.revision,actorId:'local-owner',command:{type:'admit-work' as const,workId:'before-expiry',title:'One millisecond before',budget:8}};assert.equal((await app.dispatch(admission)).status,'committed');const admitted=await f.current(),journal=await f.journal(),count=calls;now=deadline;assert.equal((await app.dispatch(admission)).status,'replayed');assert.equal((await app.dispatch(envelope)).status,'replayed');assert.equal(calls,count);await assert.rejects(send({type:'admit-work',workId:'at-expiry',title:'At expiry',budget:8},'at-expiry'),/explicit memory expiry/);assert.deepEqual(await f.journal(),journal);now=start;await assert.rejects(send({type:'admit-work',workId:'rollback',title:'Rollback',budget:8},'rollback'),/moved backwards/);assert.deepEqual(await f.journal(),journal);
 now=deadline+100;await f.product.retireMemory('mission',{commandId:'retire-expired',expectedRevision:admitted.revision,memoryId:'a',version:1,reason:'Owner retires exact expired version'});assert.equal((await send({type:'admit-work',workId:'after-retirement',title:'Separate explicit admission',budget:8},'after-retirement')).status,'committed');const final=await f.current();assert.deepEqual(final.value.works.slice(0,before.value.works.length),before.value.works);assert.deepEqual(final.value.works.slice(0,before.value.works.length).map(workInputHash),old);assert.deepEqual(final.value.works.at(-1)!.appliedMemoryVersions,['b@1']);assert.deepEqual(final.value.memoryExpiries,declared.value.memoryExpiries);validateMissionLineage(final.value);validateMissionJournalLineage(await f.journal());
 const restart=new Application(f.store,[{id:'local-owner',roles:['owner']}],()=>{throw Error('Replay must not resample clock');});assert.equal((await restart.dispatch(envelope)).status,'replayed');assert.equal((await restart.dispatch(admission)).status,'replayed');
 if(durable){const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{store:target}=await growthStore(true);await restorePortableBackup(await exportPortableBackup(f.store as any,f.artifacts),target as any,f.root+'/expiry-restored');assert.deepEqual((await target.load('mission'))!.value,final.value);const restored=new Application(target,[{id:'local-owner',roles:['owner']}],()=>{throw Error('Restored replay must not sample clock');});assert.equal((await restored.dispatch(admission)).status,'replayed');}
});
test('exact fields, future canonical deadline, authority, duplicates, history tamper and missing clock fail closed',async t=>{
 const f=await fixture(t),s=(await f.current()).value,m=s.memories.find(m=>m.id==='a')!,command={type:'declare-memory-expiry' as const,expiryId:'expiry:a',memory:{id:m.id,version:m.version,hash:memoryVersionHash(m)},deadline:new Date(deadline).toISOString(),reason:'Owner reason'},owner={id:'local-owner',roles:['owner'] as const};
 for(const patch of [{deadline:'2026-10-08T00:00:01Z'},{deadline:'2026-02-30T00:00:01.000Z'},{deadline:new Date(start).toISOString()},{reason:''},{reason:'\ud800'},{reason:'x'.repeat(2001)},{memory:{...command.memory,hash:'0'.repeat(64)}},{memory:{...command.memory,version:2}},{observedAt:start},{actorId:'other'}])assert.throws(()=>apply(s,{...command,...patch} as any,{...owner,roles:['owner']},{observedAt:start}));assert.throws(()=>apply(s,command,{...owner,roles:['owner']}));assert.throws(()=>apply(s,command,{id:'rep',roles:['representative']},{observedAt:start}));
 for(const change of ['inactive','learned']){const v=structuredClone(s),memory=v.memories.find(m=>m.id==='a')!;if(change==='inactive')memory.effective=false;else memory.authority='learned';assert.throws(()=>apply(v,{...command,memory:{...command.memory,hash:memoryVersionHash(memory)}},{...owner,roles:['owner']},{observedAt:start}));}
 const state=apply(s,command,{...owner,roles:['owner']},{observedAt:start}).value;assert.throws(()=>apply(state,{...command,expiryId:'duplicate'},{...owner,roles:['owner']},{observedAt:start}));for(const mutate of [(m:any)=>m.memoryExpiries[0].deadline=new Date(start).toISOString(),(m:any)=>m.memoryExpiries[0].memory.hash='0'.repeat(64),(m:any)=>delete m.memoryTimeWatermark,(m:any)=>m.memoryExpiries.extra=true,(m:any)=>m.memoryExpiries[0].extra=true,(m:any)=>m.memoryTimeWatermark=start-1]){const changed=structuredClone(state);mutate(changed);assert.throws(()=>validateMemoryExpiries(changed));assert.throws(()=>validateMissionLineage(changed));}assert.deepEqual((await f.current()).value,s);
});
test('expiry observation is server-owned, frozen, replay fingerprints immutable and CAS retains only one competing admission',async t=>{
 const f=await fixture(t),s=await f.current(),m=s.value.memories.find(m=>m.id==='a')!,command={type:'declare-memory-expiry' as const,expiryId:'expiry:a',memory:{id:m.id,version:m.version,hash:memoryVersionHash(m)},deadline:new Date(deadline).toISOString(),reason:'Owner'},envelope={missionId:'mission',commandId:'freeze',expectedRevision:s.revision,actorId:'local-owner',command};let release!:()=>void,reached!:()=>void,once=false;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),store=new Proxy(f.store,{get(target,key){if(key==='lookupOperation')return async(v:any)=>{if(!once){once=true;reached();await gate;}return target.lookupOperation(v);};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}}),app=new Application(store,[{id:'local-owner',roles:['owner']}],()=>start),original=structuredClone(envelope),pending=app.dispatch(envelope);await arrival;envelope.command.memory.id='mutated';envelope.command.deadline='invalid';release();assert.equal((await pending).status,'committed');assert.equal((await app.dispatch(original)).status,'replayed');assert.equal((await app.dispatch({...original,command:{...original.command,reason:'changed'}})).status,'conflict');await assert.rejects(app.dispatch({...original,time:{observedAt:start}} as any),/envelope fields/);
 const fresh=await fixture(t),snapshot=await fresh.current(),racing=new Application(fresh.store,[{id:'local-owner',roles:['owner']}],()=>start),results=await Promise.all([racing.dispatch({...original,commandId:'race-expiry',expectedRevision:snapshot.revision}),racing.dispatch({missionId:'mission',commandId:'race-admit',expectedRevision:snapshot.revision,actorId:'local-owner',command:{type:'admit-work',workId:'race',title:'Racing explicit admission',budget:8}})]);assert.equal(results.filter(r=>r.status==='committed').length,1);assert.equal(results.filter(r=>r.status==='conflict').length,1);validateMissionJournalLineage(await fresh.journal());
});
test('advancing a version does not inherit expiry; journal clock tamper and history bounds fail closed',async t=>{
 const f=await fixture(t),before=await f.current(),m=before.value.memories.find(m=>m.id==='a')!,command={type:'declare-memory-expiry' as const,expiryId:'expiry:a',memory:{id:'a',version:1,hash:memoryVersionHash(m)},deadline:new Date(deadline).toISOString(),reason:'Original v1 deadline'},app=new Application(f.store,[{id:'local-owner',roles:['owner']}],()=>start);await app.dispatch({missionId:'mission',commandId:'version-expiry',expectedRevision:before.revision,actorId:'local-owner',command});const original=(await f.current()).value.memoryExpiries;await f.product.saveMemory('mission',{commandId:'advance-expiry-memory',expectedRevision:(await f.current()).revision,memory:{id:'a',version:2,content:'Owner edited v2, independent of v1 deadline',source:'Owner'}});const later=new Application(f.store,[{id:'local-owner',roles:['owner']}],()=>deadline+1);await later.dispatch({missionId:'mission',commandId:'after-version',expectedRevision:(await f.current()).revision,actorId:'local-owner',command:{type:'admit-work',workId:'after-version',title:'Explicit v2 admission',budget:8}});const state=(await f.current()).value;assert.deepEqual(state.memoryExpiries,original);assert.deepEqual(state.works.at(-1)!.appliedMemoryVersions,['b@1','a@2']);validateMissionJournalLineage(await f.journal());const journal=structuredClone(await f.journal()),last=journal.at(-1)!;((last.events[0] as any).time).observedAt=start;assert.throws(()=>validateMissionJournalLineage(journal));
 const bounded=structuredClone(state);bounded.memoryExpiries=[];for(let i=0;i<100;i++){const version={...m,id:'bounded-'+i};bounded.memories.push(version);bounded.memoryExpiries.push({id:'expiry:'+i,memory:{id:version.id,version:1,hash:memoryVersionHash(version)},deadline:new Date(deadline).toISOString(),actorId:'local-owner',reason:'Owner',declaredAt:start});}validateMemoryExpiries(bounded);bounded.memoryExpiries.push({...bounded.memoryExpiries[0]!,id:'too-many'});assert.throws(()=>validateMemoryExpiries(bounded));bounded.memoryExpiries.pop();for(const e of bounded.memoryExpiries)e.reason='한'.repeat(500);assert.throws(()=>validateMemoryExpiries(bounded),/bounded array/);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} normal expiry HTTP rejects forged context/fields/feed/hash and records exact identity without replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const {createWorkbench}=await import('../src/server.ts'),f=await fixture(t,durable),s=await f.current(),memory=s.value.memories.find(m=>m.id==='a')!,server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port,feed=(await f.store.readState()).feedId,input={commandId:'http-expiry',expectedRevision:s.revision,expiryId:'expiry:http',memory:{id:memory.id,version:1,hash:memoryVersionHash(memory)},deadline:new Date(Date.now()+60000).toISOString(),reason:'Exact owner HTTP request'},post=async(body:any,identity=feed)=>{const r=await fetch(base+'/missions/mission/memory-expiry',{method:'POST',headers:{'content-type':'application/json','x-massion-feed':identity},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};},journal=await f.journal();for(const patch of [{observedAt:0},{time:{observedAt:0}},{actorId:'other'},{memory:{...input.memory,hash:'0'.repeat(64)}},{memory:{...input.memory,scope:'local'}},{deadline:'2000-01-01T00:00:00.000Z'}])assert.equal((await post({...input,...patch})).status,400);assert.equal((await post(input,'other-feed')).status,409);assert.deepEqual(await f.journal(),journal);assert.equal((await post(input)).body.status,'committed');const saved=await f.journal();assert.equal((await post(input)).body.status,'replayed');assert.equal((await post({...input,reason:'Changed original'})).status,409);assert.equal((await post({...input,commandId:'stale-new'})).status,409);assert.deepEqual(await f.journal(),saved);assert.deepEqual((await f.current()).value.works,s.value.works);validateMissionJournalLineage(saved);
});
