import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {literalMemoryFixture,NEAR_MEMORY_ID} from './support/memory-usage-literal-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function setup(t:any,durable=false,held=false){
 const f=await literalMemoryFixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});let base='http://127.0.0.1:'+(server.address() as any).port,posts=0,release!:()=>void,reached!:()=>void;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),app=harness(async(path:string,options:any)=>{if(options.method==='POST')posts++;const r=await fetch(base+path,options),body=await r.json();if(held&&path.includes('/memory-usage?')){reached();await gate;}return reply(body,r.status);},{},undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden&&!app.node('memory-usage-target').disabled);return {...f,app,base,replaceBase:(b:string)=>base=b,posts:()=>posts,arrival,release};
}
async function select(app:any,id:string,version=1){app.node('memory-usage-target').value=JSON.stringify([id,version]);await app.node('memory-usage-target').fire('change');}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} literal normal panel reads original/near/NFC/NFD versions separately and Cancel writes nothing`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),before=await f.current(),journal=await f.journal();for(const id of [f.id,NEAR_MEMORY_ID,'é','e\u0301']){await select(f.app,id);await f.app.node('memory-usage-read').fire('click');assert.equal(f.app.node('memory-usage-result').hidden,false,f.app.node('memory-usage-status').textContent);const result=JSON.parse(f.app.node('memory-usage-result').textContent);assert.equal(result.memory.id,id);assert.equal(result.versionHash,(await f.query(id)).versionHash);if(id===f.id)assert.equal(result.uses[0].record.id,'literal-record');}await f.app.node('memory-usage-cancel').fire('click');assert.equal(f.app.node('memory-usage-result').hidden,true);assert.equal(f.posts(),0);assert.deepEqual(await f.current(),before);assert.deepEqual(await f.journal(),journal);
});
for(const action of ['cancel','selection','mission','revision','offline'])test(`late literal memory use response discarded after ${action} without a write or Record change`,async t=>{
 const f=await setup(t,false,true),app=f.app,before=await f.current();await select(app,f.id);const pending=app.node('memory-usage-read').fire('click');await f.arrival;if(action==='cancel')await app.node('memory-usage-cancel').fire('click');if(action==='selection')await select(app,NEAR_MEMORY_ID);if(action==='mission')await runInContext("loadMission('other',false)",app.context);if(action==='revision'){await f.product.saveMemory('mission',{commandId:'peer-revision',expectedRevision:(await f.current()).revision,memory:{id:'peer',version:1,content:'Deliberate peer fixture change',source:'Owner'}});await runInContext("loadMission('mission',false)",app.context);}if(action==='offline')await app.windowEvent('offline');const journal=await f.journal(),state=await f.current();f.release();await pending;assert.equal(app.node('memory-usage-result').hidden,true);assert.equal(f.posts(),0);assert.deepEqual(await f.journal(),journal);assert.deepEqual(await f.current(),state);assert.deepEqual(state.value.works,before.value.works);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} held literal response from old feed cannot populate a same-ID replacement Mission`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable,true),second=await setup(t,durable),app=f.app,firstState=await f.current(),secondState=await second.current(),one=await f.journal(),two=await second.journal();await select(app,f.id);const pending=app.node('memory-usage-read').fire('click');await f.arrival;f.replaceBase(second.base);await app.windowEvent('online');const end=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('memory-usage-target').disabled){assert.ok(Date.now()<end,'Replacement feed deadline');await app.tick();await new Promise(r=>setTimeout(r,5));}f.release();await pending;assert.equal(app.node('memory-usage-target').value,'');assert.equal(app.node('memory-usage-result').hidden,true);assert.equal(f.posts(),0);assert.deepEqual(await f.current(),firstState);assert.deepEqual(await second.current(),secondState);assert.deepEqual(await f.journal(),one);assert.deepEqual(await second.journal(),two);
});
