import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {memoryUsagePagesFixture as fixture} from './support/memory-usage-pages-fixture.ts';
import {NEAR_MEMORY_ID} from './support/memory-usage-literal-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function setup(t:any,durable=false,mode='normal'){
 const f=await fixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});let base='http://127.0.0.1:'+(server.address() as any).port,posts=0,reads=0,release!:()=>void,reached!:()=>void;const gate=new Promise<void>(r=>release=r),arrival=new Promise<void>(r=>reached=r),app=harness(async(path:string,options:any)=>{if(options.method==='POST')posts++;const page=path.includes('/memory-usage?'),next=page&&path.includes('&after=20');if(page)reads++;const res=await fetch(base+path,options),body=await res.json();if(next&&mode==='held'){reached();await gate;}if(next&&mode==='offset')body.offset=0;if(next&&mode==='repeat')body.uses=[body.uses[0],body.uses[0]];if(next&&mode==='next')body.nextAfter=40;return reply(body,res.status);},{},undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden&&!app.node('memory-usage-target').disabled);app.node('memory-usage-target').value=JSON.stringify([f.id,1]);await app.node('memory-usage-target').fire('change');return {...f,app,base,posts:()=>posts,reads:()=>reads,release,arrival,replaceBase:(b:string)=>base=b};
}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} UI initial 20 and explicit next 2 with no automatic GET/write/mixed Record`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),before=await f.current(),journal=await f.journal();assert.equal(f.reads(),0);assert.equal(f.app.node('memory-usage-more').disabled,true);await f.app.node('memory-usage-read').fire('click');const first=JSON.parse(f.app.node('memory-usage-result').textContent);assert.equal(first.uses.length,20);assert.equal(first.uses[0].record.id,'page-record');assert.equal(f.reads(),1);await f.app.tick();assert.equal(f.reads(),1);await f.app.node('memory-usage-more').fire('click');const last=JSON.parse(f.app.node('memory-usage-result').textContent);assert.equal(last.uses.length,2);assert.equal(last.offset,20);assert.equal(last.memory.id,f.id);assert.equal(last.versionHash,first.versionHash);assert.deepEqual([...first.uses,...last.uses].map(u=>u.workId),Array.from({length:22},(_,i)=>'use-'+String(i).padStart(2,'0')));assert.equal(f.app.node('memory-usage-more').disabled,true);await f.app.node('memory-usage-more').fire('click');assert.equal(f.reads(),2);await f.app.node('memory-usage-cancel').fire('click');assert.equal(f.app.node('memory-usage-result').hidden,true);assert.equal(f.posts(),0);assert.deepEqual(await f.current(),before);assert.deepEqual(await f.journal(),journal);
});
for(const action of ['cancel','selection','mission','revision','offline'])test(`held next page discarded after ${action}; duplicate click adds no GET`,async t=>{
 const f=await setup(t,false,'held'),app=f.app,before=await f.current();await app.node('memory-usage-read').fire('click');const pending=app.node('memory-usage-more').fire('click');await f.arrival;await app.node('memory-usage-more').fire('click');assert.equal(f.reads(),2);if(action==='cancel')await app.node('memory-usage-cancel').fire('click');if(action==='selection'){app.node('memory-usage-target').value=JSON.stringify([NEAR_MEMORY_ID,1]);await app.node('memory-usage-target').fire('change');}if(action==='mission')await runInContext("loadMission('other',false)",app.context);if(action==='revision'){await f.product.saveMemory('mission',{commandId:'page-peer',expectedRevision:(await f.current()).revision,memory:{id:'peer',version:1,content:'Deliberate peer fixture change',source:'Owner'}});await runInContext("loadMission('mission',false)",app.context);}if(action==='offline')await app.windowEvent('offline');const journal=await f.journal(),state=await f.current();f.release();await pending;assert.equal(app.node('memory-usage-result').hidden,true);assert.equal(app.node('memory-usage-more').disabled,true);assert.equal(f.posts(),0);assert.equal(f.reads(),2);assert.deepEqual(await f.journal(),journal);assert.deepEqual(await f.current(),state);assert.deepEqual(state.value.works,before.value.works);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} held old-feed next page cannot populate same-ID replacement Mission`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable,'held'),second=await setup(t,durable),app=f.app,one=await f.journal(),two=await second.journal();await app.node('memory-usage-read').fire('click');const pending=app.node('memory-usage-more').fire('click');await f.arrival;f.replaceBase(second.base);await app.windowEvent('online');const end=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('memory-usage-target').disabled){assert.ok(Date.now()<end,'Replacement feed deadline');await app.tick();await new Promise(r=>setTimeout(r,5));}f.release();await pending;assert.equal(app.node('memory-usage-target').value,'');assert.equal(app.node('memory-usage-result').hidden,true);assert.equal(app.node('memory-usage-more').disabled,true);assert.equal(f.posts(),0);assert.deepEqual(await f.journal(),one);assert.deepEqual(await second.journal(),two);
});
for(const mode of ['offset','repeat','next'])test(`forged continuation ${mode} clears boundary and requires explicit initial read`,async t=>{
 const f=await setup(t,false,mode),journal=await f.journal();await f.app.node('memory-usage-read').fire('click');await f.app.node('memory-usage-more').fire('click');assert.equal(f.app.node('memory-usage-result').hidden,true);assert.equal(f.app.node('memory-usage-more').disabled,true);assert.match(f.app.node('memory-usage-status').textContent,/failed exact binding/);assert.equal(f.posts(),0);assert.equal(f.reads(),2);assert.deepEqual(await f.journal(),journal);
});
test('peer revision without local refresh rejects next page and does not automatically restart inspection',async t=>{
 const f=await setup(t),before=await f.current();await f.app.node('memory-usage-read').fire('click');await f.product.saveMemory('mission',{commandId:'page-unseen-peer',expectedRevision:before.revision,memory:{id:'peer',version:1,content:'Deliberate peer change',source:'Owner'}});const journal=await f.journal();await f.app.node('memory-usage-more').fire('click');assert.equal(f.app.node('memory-usage-result').hidden,true);assert.equal(f.app.node('memory-usage-more').disabled,true);assert.match(f.app.node('memory-usage-status').textContent,/Mission revision changed/);assert.equal(f.reads(),2);assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.current()).value.works,before.value.works);
});
test('offline after a completed initial page immediately clears visible page and next boundary',async t=>{
 const f=await setup(t),journal=await f.journal();await f.app.node('memory-usage-read').fire('click');assert.equal(f.app.node('memory-usage-result').hidden,false);await f.app.windowEvent('offline');assert.equal(f.app.node('memory-usage-result').hidden,true);assert.equal(f.app.node('memory-usage-more').disabled,true);assert.equal(f.reads(),1);assert.equal(f.posts(),0);assert.deepEqual(await f.journal(),journal);
});
