import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import {memoryConflictFixture} from './support/memory-conflict-fixture.ts';
import {verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';
import {memoryVersionHash,workInputHash} from '../src/domain.ts';
test('actual DB normal CLI Chrome keyboard Review/Cancel/Declare blocks new Work, retirement permits new pins; host restart no automatic calls',{skip:!process.env.SURREAL_TEST_RUNTIME||!process.env.MASSION_PLAYWRIGHT_PATH,timeout:45000},async t=>{
 const f=await memoryConflictFixture(t,true,true),original=await f.current(),oldHashes=original.value.works.map(workInputHash),database=(await f.transport!.query('RETURN $session.db;',{}))[0] as string,{chromium}=await import(process.env.MASSION_PLAYWRIGHT_PATH!),probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const address=probe.address();assert.ok(address&&typeof address==='object');await new Promise<void>(r=>probe.close(()=>r()));const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry],env={MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database,MASSION_PORT:String(address.port)};let child:ReturnType<typeof spawn>|undefined,logs='',browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 const start=async()=>{logs='';child=spawn(process.execPath,argv.slice(1),{cwd:f.root,env,stdio:['ignore','pipe','pipe']});child.stdout!.on('data',d=>logs+=d);child.stderr!.on('data',d=>logs+=d);await f.until(()=>{assert.equal(child!.exitCode,null,logs);return logs.includes('Massion development workbench:');});};
 try{browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});await start();let context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();let posts=0;const track=(p:any)=>p.on('request',(r:any)=>{if(r.method()==='POST')posts++;});track(page);const base='http://127.0.0.1:'+address.port;await page.goto(base+'/#mission=mission');await page.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission'&&document.getElementById('sync-notice')?.hidden);await page.locator('#memory-conflict-panel > summary').focus();await page.keyboard.press('Enter');const choose=async()=>{await page.locator('#memory-conflict-first').focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.locator('#memory-conflict-second').focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.locator('#memory-conflict-reason').fill('Owner declares original A and B conflict <img src=x> 원문 😀');await page.locator('#memory-conflict-review').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!(document.getElementById('memory-conflict-save') as HTMLButtonElement).disabled);};const journal=await f.journal();await choose();assert.match((await page.locator('#memory-conflict-original').textContent())!,/\\r\\n/);await page.locator('#memory-conflict-cancel').focus();await page.keyboard.press('Enter');assert.equal(posts,0);assert.deepEqual(await f.journal(),journal);await choose();await page.locator('#memory-conflict-save').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('memory-conflict-status')?.textContent?.includes('confirmed')&&!(document.getElementById('memory-conflict-fields') as HTMLFieldSetElement).disabled);assert.equal(posts,1);const declared=await f.current(),conflict=declared.value.memoryConflicts![0]!;assert.equal(conflict.first.id,'a');assert.equal(conflict.second.id,'b');assert.equal(conflict.first.hash,memoryVersionHash(original.value.memories.find(m=>m.id==='a')!));assert.deepEqual(declared.value.works,original.value.works);assert.equal(await page.locator('#memory-conflict-panel img').count(),0);
 await page.locator('#work-title').fill('Blocked new responsibility');await page.locator('#work-budget').fill('8');await page.locator('#admit-work').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('status')?.textContent?.includes('New Work admission blocked'));assert.equal(posts,2);assert.deepEqual((await f.current()).value.works,original.value.works);await page.locator('#memory-panel > summary').focus();await page.keyboard.press('Enter');await page.locator('#retirement-target').focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.equal(await page.locator('#retirement-target').inputValue(),JSON.stringify(['b',1]));await page.locator('#retirement-reason').fill('Stop exact conflicting B for future Work');await page.locator('#review-retirement').focus();await page.keyboard.press('Enter');await page.locator('#stop-memory').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('retirement-status')?.textContent?.includes('Confirmed:')&&!(document.getElementById('work-fields') as HTMLFieldSetElement).disabled);assert.equal(posts,3);assert.match((await page.locator('#memory-conflict-history').textContent())!,/"bothExactVersionsCurrentlyApply": false/);await page.locator('#work-title').fill('Explicit new responsibility after retirement');await page.locator('#admit-work').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('.work-title').length===4);assert.equal(posts,4);const now=await f.current();assert.deepEqual(now.value.works.slice(0,-1),original.value.works);assert.deepEqual(now.value.works.slice(0,-1).map(workInputHash),oldHashes);assert.deepEqual(now.value.works.at(-1)!.appliedMemoryVersions,['a@1']);assert.deepEqual(now.value.memoryConflicts,declared.value.memoryConflicts);assert.equal(now.value.works.at(-1)!.runtimeRun,undefined);
 const beforeRestart=await f.journal();await context.close();await stopOwnedChild(child!,{cwd:f.root,argv});child=undefined;await start();context=await browser.newContext({viewport:{width:390,height:844}});page=await context.newPage();track(page);await page.goto(base+'/#mission=mission');await page.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission'&&document.getElementById('sync-notice')?.hidden);await page.locator('#memory-conflict-panel > summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#memory-conflict-first').inputValue(),'');assert.equal(await page.locator('#memory-conflict-reason').inputValue(),'');assert.deepEqual(await f.journal(),beforeRestart);assert.deepEqual((await f.current()).value,now.value);assert.equal(posts,4);for(const width of [390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}t.diagnostic(JSON.stringify({...await verifyOwnedChild(child!,{cwd:f.root,argv}),normalCLI:true,keyboardReviewCancelDeclare:true,blockedNewAdmissionNoMutation:true,retirementThenExplicitAdmission:true,originalWorkRecordUnknownExact:true,hostRestartFreshChrome:true,posts,automaticPosts:0,modelCalls:0,liveCalls:0}));
 }finally{if(browser)await browser.close();if(child)await stopOwnedChild(child,{cwd:f.root,argv});}
});
