import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {SurrealMissionCatalog} from '../src/mission-catalog.ts';
import {InMemoryStore} from '../src/storage.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function fixture(t:any,durable=false,mode='normal'){
 const f=await lifetimeFixture(t,durable);await f.product.create({id:'other',purpose:'Other stored Mission <img src=x> 원문 😀',scope:'local',constraints:[],criteria:{version:1,description:'Original',oracle:'manual-review/v1'}},'catalog-other');const catalog=new SurrealMissionCatalog(f.transport??{async query(_query,vars){assert.ok(f.store instanceof InMemoryStore);const state=await f.store.readState();if(vars.feedId&&state.feedId!==vars.feedId)return [{changed:'feed'}];if(Number(vars.cursor)>=0&&state.cursor!==vars.cursor)return [{changed:'cursor'}];const latest=new Map();for(const op of f.store.inspect())latest.set(op.aggregateId,op);const rows=[...latest.values()].filter(op=>op.aggregateId>String(vars.after)).sort((a,b)=>a.aggregateId<b.aggregateId?-1:1).slice(0,Number(vars.fetchLimit)).map(op=>({aggregateId:op.aggregateId,missionId:op.value.id,revision:op.revision,version:op.value.version,purpose:op.value.purpose,scope:op.value.scope,workCount:op.value.works.length}));return [{feedId:state.feedId,cursor:state.cursor,rows}];}});const server=createWorkbench(f.store,f.root,{catalog,providers:f.product.providers,runtime:f.runtime,artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port;let release!:()=>void,writes=0,catalogReads=0;const gate=new Promise<void>(r=>release=r);
 const handler=async(path:string,options:any)=>{if(options.method==='POST')writes++;if(path.startsWith('/mission-catalog'))catalogReads++;const response=await fetch(base+path,options),body=await response.json();if(path.startsWith('/mission-catalog')){if(mode==='held')await gate;if(mode==='wrong-feed')body.feedId='different-feed';if(mode==='wrong-identity')body.items[0].missionId='bad id';}return reply(body,response.status);};async function client(){const app=harness(handler,{},undefined,{network:true});await f.until(()=>app.node('sync-notice').hidden&&!app.node('mission-catalog-refresh').disabled);return app;}return {...f,base,client,release:()=>release(),writes:()=>writes,catalogReads:()=>catalogReads};
}
function selection(app:any,id:string){return app.all().find((n:any)=>n.attributes.get('data-catalog-mission')===id);}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} fresh client finds stored Missions without ID and explicitly loads original Work without a command`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await fixture(t,durable),app=await f.client(),journal=await f.journal();assert.equal(app.node('mission-id').value,'');assert.equal(f.catalogReads(),0);await app.node('mission-catalog-refresh').fire('click');assert.match(app.node('mission-catalog-results').textContent,/Other stored Mission/);assert.equal(f.catalogReads(),1);assert.equal(f.writes(),0);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);await selection(app,'mission').fire('click');assert.equal(app.node('loaded-id').textContent,'mission');assert.deepEqual(runInContext('JSON.parse(JSON.stringify(snapshot.value))',app.context),(await f.current()).value);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);await app.node('mission-catalog-close').fire('click');assert.equal(app.node('mission-catalog-results').hidden,true);assert.equal(f.writes(),0);});
test('late closed or disconnected catalog read cannot restore a list or overwrite the Mission',async t=>{const f=await fixture(t,false,'held'),app=await f.client();const pending=app.node('mission-catalog-refresh').fire('click');await f.until(()=>f.catalogReads()===1);await runInContext("loadMission('mission',false)",app.context);await app.node('mission-catalog-close').fire('click');f.release();await pending;assert.equal(app.node('mission-catalog-results').hidden,true);assert.equal(app.node('loaded-id').textContent,'mission');assert.equal(f.writes(),0);});
for(const mode of ['wrong-feed','wrong-identity'])test(`${mode} catalog is not selectable or reused`,async t=>{const f=await fixture(t,false,mode),app=await f.client();await app.node('mission-catalog-refresh').fire('click');assert.equal(app.node('mission-catalog-results').hidden,true);assert.equal(selection(app,'mission'),undefined);assert.equal(app.node('loaded-id').textContent,'');assert.equal(f.writes(),0);assert.equal(f.catalogReads(),1);});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} same-ID replaced database invalidates an old catalog button without a load or write`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const one=await fixture(t,durable),two=await fixture(t,durable);let base=one.base,missionReads=0,writes=0;const app=harness(async(path:string,options:any)=>{if(path.startsWith('/read-state?mission=')||path.startsWith('/missions/'))missionReads++;if(options.method==='POST')writes++;const response=await fetch(base+path,options);return reply(await response.json(),response.status);},{},undefined,{network:true});await one.until(()=>app.node('sync-notice').hidden&&!app.node('mission-catalog-refresh').disabled);await app.node('mission-catalog-refresh').fire('click');const old=selection(app,'mission'),beforeOne=await one.journal(),beforeTwo=await two.journal();base=two.base;await app.windowEvent('online');await app.tick();const deadline=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('mission-catalog-refresh').disabled){assert.ok(Date.now()<deadline);await app.tick();await new Promise(r=>setTimeout(r,10));}const reads=missionReads;await old.fire('click');assert.equal(missionReads,reads);assert.equal(app.node('mission-catalog-results').hidden,true);assert.equal(writes,0);assert.deepEqual(await one.journal(),beforeOne);assert.deepEqual(await two.journal(),beforeTwo);});
test('catalog read/selection retains an original unknown operation and its write barrier',async t=>{const f=await fixture(t),app=await f.client();await runInContext("unknownOperation={commandId:'original-unknown',missionId:'mission',reconcileCursor:0};controls()",app.context);await app.node('mission-catalog-refresh').fire('click');await selection(app,'other').fire('click');assert.equal(app.node('loaded-id').textContent,'other');assert.equal(runInContext('unknownOperation.commandId',app.context),'original-unknown');assert.equal(app.node('mission-fields').disabled,true);assert.equal(f.writes(),0);assert.equal(f.calls.length,0);});
test('catalog selection reads newer authoritative Work rather than the displayed revision',async t=>{const f=await fixture(t),app=await f.client();await app.node('mission-catalog-refresh').fire('click');const row=selection(app,'mission');await f.product.admit('mission',{commandId:'after-catalog',expectedRevision:(await f.current()).revision,workId:'later',title:'New responsibility after catalog read',budget:8});await row.fire('click');assert.equal(runInContext('snapshot.revision',app.context),(await f.current()).revision);assert.ok(runInContext('snapshot.value.works.some(w=>w.id==="later")',app.context));assert.equal(f.writes(),0);assert.equal(f.calls.length,0);});
test('disconnect aborts a pending first-page read and prevents its late rendering',async t=>{const f=await fixture(t,false,'held'),app=await f.client();const pending=app.node('mission-catalog-refresh').fire('click');await f.until(()=>f.catalogReads()===1);await app.windowEvent('offline');f.release();await pending;assert.equal(app.node('mission-catalog-results').hidden,true);assert.equal(app.node('mission-catalog-refresh').disabled,true);assert.equal(f.writes(),0);});
