import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {growthStore} from './support/growth-fixture.ts';
import {ProductService} from '../src/product.ts';
import {hash,workInputHash} from '../src/domain.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {SurrealStore} from '../src/storage.ts';
import {beforeWork} from './support/mission-conversation-fixture.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} Mission discussion precedes first Work; original source, separate explicit run and portable lineage remain exact`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,durable);await beforeWork(f);const old=await f.current(),current=async()=>(await f.store.load('before'))!;
 const input={commandId:'mission-original',expectedRevision:1,messageId:'mission-original',replyTo:null,text:'  Original <img src=x>\r\n원문 😀\rnext  '};assert.equal((await f.product.appendMissionMessage('before',input)).status,'committed');
 await f.product.appendMissionMessage('before',{commandId:'mission-reply',expectedRevision:(await current()).revision,messageId:'mission-reply',replyTo:input.messageId,text:'Separate owner reply'});
 const before=await current(),message=before.value.conversations![0]!.messages[0]!;assert.deepEqual(before.value.works,[]);assert.equal(before.value.conversations![0]!.workId,null);assert.equal(message.text,input.text);assert.equal(f.calls.length,0);assert.deepEqual(await f.current(),old);
 const source={workId:null,messageId:message.id,messageHash:hash(message)};await assert.rejects(f.product.admit('before',{commandId:'bad-source',expectedRevision:before.revision,workId:'first',title:'Edited bounded responsibility',budget:8,conversationSource:{...source,messageHash:'0'.repeat(64)}}));
 await f.product.admit('before',{commandId:'first-admission',expectedRevision:before.revision,workId:'first',title:'Edited bounded responsibility',budget:8,conversationSource:source});const admitted=await current(),work=admitted.value.works[0]!;assert.equal(work.runtimeRun,undefined);assert.equal(work.conversationSource!.message.text,input.text);assert.equal(work.conversationSource!.workId,null);assert.equal(f.calls.length,0);
 const result=await f.product.run('before','first','explicit-first-run',admitted.revision);assert.equal(result.status,'settled');assert.equal(f.calls.length,2);const settled=await current(),pin=workInputHash(settled.value.works[0]!);await f.product.appendMissionMessage('before',{commandId:'later-discussion',expectedRevision:settled.revision,messageId:'later-discussion',replyTo:'mission-reply',text:'Later discussion grants no authority'});assert.deepEqual((await current()).value.works,settled.value.works);assert.equal(workInputHash((await current()).value.works[0]!),pin);assert.deepEqual(await f.current(),old);validateMissionJournalLineage(await f.journal());
 if(durable){assert.ok(f.store instanceof SurrealStore);const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{store:target}=await growthStore(true);assert.ok(target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/mission-discussion-restored');assert.deepEqual((await target.load('before'))!.value,(await current()).value);assert.deepEqual((await target.load('mission'))!.value,old.value);assert.notEqual((await target.readState()).feedId,(await f.store.readState()).feedId);assert.equal(f.calls.length,2);}
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} Mission messages enforce CAS, owner fields, same-thread replies, exact replay and feed`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,durable);await beforeWork(f);const current=async()=>(await f.store.load('before'))!,base={commandId:'one',expectedRevision:1,messageId:'one',replyTo:null,text:'Original'},other={...base,commandId:'two',messageId:'two'},results=await Promise.all([f.product.appendMissionMessage('before',base),f.product.appendMissionMessage('before',other)]);assert.equal(results.filter(r=>r.status==='committed').length,1);assert.equal(results.filter(r=>r.status==='conflict').length,1);const winner=results[0]!.status==='committed'?base:other;assert.equal((await f.product.appendMissionMessage('before',winner)).status,'replayed');assert.equal((await f.product.appendMissionMessage('before',{...winner,text:'Altered'})).status,'conflict');await f.product.appendWorkMessage('mission',{commandId:'foreign',expectedRevision:(await f.current()).revision,workId:'work',messageId:'foreign',replyTo:null,text:'Foreign original'});const journal=await f.journal(),valid={commandId:'next',expectedRevision:(await current()).revision,messageId:'next',replyTo:null,text:'Original'};
 for(const patch of [{workId:'work'},{role:'executor'},{actorId:'provider'},{replyTo:'foreign'},{replyTo:'next'},{messageId:winner.messageId},{text:''},{text:'\ud800'},{text:'😀'.repeat(1025)}])await assert.rejects(f.product.appendMissionMessage('before',{...valid,...patch} as any));assert.deepEqual(await f.journal(),journal);
 const {createWorkbench}=await import('../src/server.ts'),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const url=`http://127.0.0.1:${address.port}/missions/before`,get=await fetch(url+'/mission-conversation');assert.equal(get.status,200);assert.equal((await get.json()).conversation.workId,null);assert.equal((await fetch(url+'/mission-conversation?work=work')).status,400);assert.equal((await fetch(url+'/mission-conversation',{headers:{'x-massion-feed':'other'}})).status,409);assert.equal((await fetch(url+'/mission-message',{method:'POST',headers:{'content-type':'application/json','x-massion-feed':'other'},body:JSON.stringify(valid)})).status,409);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);
});
test('Mission message caller is frozen before asynchronous operation lookup; no Work scope can be injected',async t=>{
 const f=await lifetimeFixture(t);await beforeWork(f);let reached!:()=>void,release!:()=>void;const arrival=new Promise<void>(r=>reached=r),gate=new Promise<void>(r=>release=r);let held=false;const store=new Proxy(f.store,{get(target,key){if(key==='lookupOperation')return async(input:any)=>{if(!held){held=true;reached();await gate;}return target.lookupOperation(input);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),input={commandId:'frozen-mission',expectedRevision:1,messageId:'frozen-mission',replyTo:null,text:'Original frozen'},pending=new ProductService(store).appendMissionMessage('before',input);await arrival;input.text='Mutated';input.messageId='mutated';(input as any).workId='work';release();assert.equal((await pending).status,'committed');const thread=(await f.store.load('before'))!.value.conversations![0]!;assert.equal(thread.workId,null);assert.equal(thread.messages[0]!.text,'Original frozen');assert.equal(thread.messages[0]!.id,'frozen-mission');assert.equal(f.calls.length,0);
});
