import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {Application} from '../src/application.ts';
import {apply,hash,workInputHash} from '../src/domain.ts';
import {SurrealStore} from '../src/storage.ts';
import {createWorkbench} from '../src/server.ts';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {growthStore} from './support/growth-fixture.ts';
const constraints=['Retain original <img src=x> 원문 😀','Exact LF\nsecond line','Exact CR\rthird line','Duplicate original','Duplicate original'];
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} owner constraint revision advances only future Mission input, rejects forged/invalid state and freezes replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,durable),original=await f.current(),oldWork=structuredClone(original.value.works),oldHash=workInputHash(oldWork.find(w=>w.id==='fresh')!),originalRecord=oldWork.find(w=>w.id==='work')!.record,server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port,feedId=(await f.store.readState()).feedId,route='/missions/mission/mission-constraints';const post=async(body:unknown,feed=feedId)=>{const response=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json','X-Massion-Feed':feed},body:JSON.stringify(body)});return {response,body:await response.json()};},input={commandId:'constraints-v2',expectedRevision:original.revision,constraints,reason:'Owner future requirements; grants unchanged'};
 const before=await f.journal();const extra=Object.assign(['Original'],{hidden:'Not JSON truth'});await assert.rejects(f.product.reviseMissionConstraints('mission',{...input,constraints:extra}));await assert.rejects(f.product.reviseMissionConstraints('mission',{...input,constraints:Array(2)}));assert.deepEqual(await f.journal(),before);for(const patch of [{actorId:'executor'},{scope:'other'},{criteria:{version:99}},{policy:'full-access'},{constraints:original.value.constraints},{reason:''},{reason:'\ud800'},{constraints:['\ud800']},{constraints:['']},{constraints:'not-array'},{constraints:Array(101).fill('Original')},{constraints:['x'.repeat(2001)]},{constraints:Array(10).fill('한'.repeat(1000))}])assert.equal((await post({...input,...patch})).response.status,400,JSON.stringify(patch).slice(0,120));assert.deepEqual(await f.journal(),before);assert.equal((await post(input,'wrong-feed')).response.status,409);assert.deepEqual(await f.journal(),before);
 const untrusted=new Application(f.store,[{id:'representative',roles:['representative']}]);await assert.rejects(untrusted.dispatch({missionId:'mission',commandId:'denied',expectedRevision:original.revision,actorId:'representative',command:{type:'revise-mission-constraints',constraints,reason:'Untrusted role'}}));const changed=await post(input);assert.equal(changed.response.status,200);assert.equal(changed.body.value.version,original.value.version+1);assert.deepEqual(changed.body.value.constraints,constraints);for(const key of ['purpose','scope','criteria','works','memories','conversations','relations'] as const)assert.deepEqual(changed.body.value[key],original.value[key]);assert.deepEqual(changed.body.value.works.find((w:any)=>w.id==='work').record,originalRecord);assert.equal(workInputHash(changed.body.value.works.find((w:any)=>w.id==='fresh')),oldHash);
 const journal=await f.journal();assert.equal((await post(input)).body.status,'replayed');assert.deepEqual(await f.journal(),journal);assert.equal((await post({...input,reason:'Changed original command'})).response.status,409);assert.equal((await post({...input,commandId:'stale'})).response.status,409);assert.deepEqual(await f.journal(),journal);
 await f.product.admit('mission',{commandId:'future',expectedRevision:(await f.current()).revision,workId:'future',title:'Future exact constraints',budget:8});const current=await f.current(),future=current.value.works.find(w=>w.id==='future')!;assert.deepEqual(future.missionSnapshot!.constraints,constraints);assert.equal(future.missionVersion,original.value.version+1);assert.deepEqual(current.value.works.slice(0,2),oldWork);assert.notEqual(workInputHash(future),oldHash);assert.deepEqual(future.criteria,original.value.criteria);assert.equal(f.calls.length,0);
 const reducer=structuredClone(current.value);reducer.version=Number.MAX_SAFE_INTEGER;assert.throws(()=>apply(reducer,{type:'revise-mission-constraints',constraints:[],reason:'Cannot overflow'},{id:'owner',roles:['owner']}));
 if(durable){assert.ok(f.store instanceof SurrealStore);const exported=await f.store.exportJournal(),last=exported.operations.find(o=>o.commandId==='constraints-v2')!;assert.deepEqual((last.events[0] as any).command,{type:'revise-mission-constraints',constraints,reason:input.reason});const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{store}=await growthStore(true);assert.ok(store instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),store,f.root+'/constraints-restored');assert.deepEqual((await store.load('mission'))!.value,current.value);assert.notEqual((await store.readState()).feedId,feedId);}
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} caller mutation and concurrent owner constraints preserve exact command identity then explicit empty list`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,durable),input={commandId:'frozen',expectedRevision:(await f.current()).revision,constraints:['Original submitted\r\nexact'],reason:'Original owner reason'},submitted=structuredClone(input),pending=f.product.reviseMissionConstraints('mission',input);input.constraints[0]='Caller mutation';input.reason='Changed';input.commandId='different';await pending;assert.deepEqual((await f.current()).value.constraints,submitted.constraints);const journal=await f.journal();assert.equal((await f.product.reviseMissionConstraints('mission',submitted)).status,'replayed');assert.deepEqual(await f.journal(),journal);const revision=(await f.current()).revision,results=await Promise.all([f.product.reviseMissionConstraints('mission',{commandId:'concurrent-a',expectedRevision:revision,constraints:['A'],reason:'A'}),f.product.reviseMissionConstraints('mission',{commandId:'concurrent-b',expectedRevision:revision,constraints:['B'],reason:'B'})]);assert.equal(results.filter(r=>r.status==='committed').length,1);assert.equal(results.filter(r=>r.status==='conflict').length,1);await f.product.reviseMissionConstraints('mission',{commandId:'explicit-empty',expectedRevision:(await f.current()).revision,constraints:[],reason:'Owner explicitly removes future text constraints'});assert.deepEqual((await f.current()).value.constraints,[]);assert.equal(f.calls.length,0);
});
test('actual DB separately explicit old/new Run receives original versus revised constraints in both roles without rewriting earlier Record',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,true),originalWork=(await f.current()).value.works.find(w=>w.id==='work')!,oldFresh=(await f.current()).value.works.find(w=>w.id==='fresh')!,oldHash=workInputHash(oldFresh);await f.product.reviseMissionConstraints('mission',{commandId:'future-constraint',expectedRevision:(await f.current()).revision,constraints,reason:'Future input only'});assert.equal(f.calls.length,0);assert.equal((await f.product.run('mission','fresh','explicit-old-run',(await f.current()).revision)).status,'settled');assert.deepEqual(f.calls[0]!.input.mission.constraints,oldFresh.missionSnapshot!.constraints);assert.deepEqual(f.calls[1]!.input.requirements.mission.constraints,oldFresh.missionSnapshot!.constraints);assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.runtimeRun!.inputHash,oldHash);await f.product.admit('mission',{commandId:'new-run-work',expectedRevision:(await f.current()).revision,workId:'new',title:'Original bounded lifetime fixture',budget:8});assert.equal((await f.product.run('mission','new','explicit-new-run',(await f.current()).revision)).status,'settled');assert.deepEqual(f.calls[2]!.input.mission.constraints,constraints);assert.deepEqual(f.calls[3]!.input.requirements.mission.constraints,constraints);assert.deepEqual((await f.current()).value.works.find(w=>w.id==='work'),originalWork);assert.equal(f.calls.length,4);
});
