import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {beforeWork} from './support/mission-conversation-fixture.ts';
import {harness,reply} from './support/workbench-client.ts';
async function fixture(t:any,durable=false,mode='normal'){
 const f=await lifetimeFixture(t,durable);await beforeWork(f);const {createWorkbench}=await import('../src/server.ts'),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const base=`http://127.0.0.1:${address.port}`;let writes=0,release!:()=>void;const gate=new Promise<void>(r=>release=r);const storage={};
 const handler=async(path:string,options:any)=>{const write=options.method==='POST';if(write)writes++;const response=await fetch(base+path,options),body=await response.json();if(write&&mode==='held')await gate;if(write&&mode==='unknown')throw Error('Lost owned acknowledgement');return reply(body,response.status);};
 async function client(){const app=harness(handler,storage,undefined,{network:true,fragment:'#mission=before'});await f.until(()=>app.node('loaded-id').textContent==='before'&&app.node('sync-notice').hidden);app.node('conversation-scope').value='mission';await app.node('conversation-scope').fire('change');return app;}
 return {...f,base,client,handler,release:()=>release(),writes:()=>writes,before:async()=>(await f.store.load('before'))!};
}
async function draft(app:any,text='Owner discussion <img src=x> 원문 😀'){app.node('conversation-text').value=text;await app.node('conversation-text').fire('input');}
async function source(app:any,id:string){app.node('conversation-work-source').value=JSON.stringify([null,id]);await app.node('conversation-work-source').fire('change');app.node('conversation-work-title').value='Edited first responsibility';await app.node('conversation-work-title').fire('input');app.node('conversation-work-budget').value='8';await app.node('conversation-work-budget').fire('input');await app.node('conversation-work-review').fire('click');}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} zero-Work Mission draft/review/cancel/message/reply then source-reviewed separate Work admission`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),app=await f.client(),old=await f.current();await draft(app);await app.node('conversation-cancel').fire('click');assert.equal(f.writes(),0);assert.equal(app.node('conversation-text').value,'');await draft(app);await app.node('conversation-review').fire('click');await app.submit('conversation-form');const first=(await f.before()).value.conversations![0]!.messages[0]!;assert.deepEqual((await f.before()).value.works,[]);assert.equal(first.text,'Owner discussion <img src=x> 원문 😀');app.node('conversation-reply').value=first.id;await app.node('conversation-reply').fire('change');await draft(app,'Explicit reply');await app.submit('conversation-form');assert.equal((await f.before()).value.conversations![0]!.messages[1]!.replyTo,first.id);await source(app,first.id);await app.node('conversation-work-cancel').fire('click');assert.equal(f.writes(),2);await source(app,first.id);await app.submit('conversation-work-form');const work=(await f.before()).value.works[0]!;assert.equal(work.title,'Edited first responsibility');assert.equal(work.conversationSource!.workId,null);assert.deepEqual(work.conversationSource!.message,first);assert.equal(work.runtimeRun,undefined);assert.equal(f.writes(),3);assert.equal(f.calls.length,0);assert.deepEqual(await f.current(),old);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);const fresh=await f.client();assert.equal(fresh.node('conversation-text').value,'');assert.equal(fresh.node('conversation-work-source').value,'');assert.equal(f.writes(),3);
});
for(const mode of ['held','unknown'])test(`${mode} Mission message keeps later draft/focus, resolves exact receipt and never replays`,async t=>{
 const f=await fixture(t,false,mode),app=await f.client();await draft(app,'Submitted exact text');const pending=app.submit('conversation-form');await f.until(()=>f.writes()===1);if(mode==='held'){await draft(app,'Later private draft');app.node('sequence-summary').focus();f.release();}await pending;await app.tick();await f.until(()=>runInContext('unknownOperation',app.context)===null);assert.equal(f.writes(),1);assert.equal((await f.before()).value.conversations![0]!.messages.length,1);if(mode==='held'){assert.equal(app.node('conversation-text').value,'Later private draft');assert.equal(runInContext('document.activeElement.id',app.context),'sequence-summary');}await f.client();assert.equal(f.writes(),1);
});
test('late Mission message response never restores a different selected Mission',async t=>{const f=await fixture(t,false,'held'),app=await f.client();await draft(app);const pending=app.submit('conversation-form');await f.until(()=>f.writes()===1);await runInContext("loadMission('mission',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='mission');f.release();await pending;assert.equal(app.node('loaded-id').textContent,'mission');assert.equal(f.writes(),1);});
test('Mission original CR/LF stays exact while editable Work draft displays normalized newlines; stale review is invalidated',async t=>{const f=await fixture(t);await f.product.appendMissionMessage('before',{commandId:'raw',expectedRevision:1,messageId:'raw',replyTo:null,text:'Original\r\nline\rnext'});const app=await f.client();app.node('conversation-work-source').value=JSON.stringify([null,'raw']);await app.node('conversation-work-source').fire('change');assert.equal(app.node('conversation-work-title').value,'Original\nline\nnext');await source(app,'raw');await f.product.appendMissionMessage('before',{commandId:'peer',expectedRevision:(await f.before()).revision,messageId:'peer',replyTo:null,text:'New discussion'});await app.tick();await f.until(()=>runInContext('snapshot.revision',app.context)===(3));await app.submit('conversation-work-form');assert.equal(f.writes(),0);assert.equal(app.node('conversation-work-title').value,'Edited first responsibility');await app.node('conversation-work-review').fire('click');await app.submit('conversation-work-form');assert.equal((await f.before()).value.works[0]!.conversationSource!.message.text,'Original\r\nline\rnext');});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} replacement database invalidates Mission draft and source review without writing either feed`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const first=await fixture(t,durable),second=await fixture(t,durable);for(const f of [first,second])await f.product.appendMissionMessage('before',{commandId:'same-id',expectedRevision:1,messageId:'same-id',replyTo:null,text:'Original same ID'});let base=first.base,writes=0;const app=harness(async(path:string,options:any)=>{if(options.method==='POST')writes++;const response=await fetch(base+path,options);return reply(await response.json(),response.status);},{},undefined,{network:true,fragment:'#mission=before'});await first.until(()=>app.node('loaded-id').textContent==='before'&&app.node('sync-notice').hidden);app.node('conversation-scope').value='mission';await app.node('conversation-scope').fire('change');await draft(app,'Private Mission draft');await source(app,'same-id');const one=await first.journal(),two=await second.journal();base=second.base;await app.windowEvent('online');await app.tick();const deadline=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('conversation-work-fields').disabled){assert.ok(Date.now()<deadline,'Replacement feed did not recover');await app.tick();await new Promise(r=>setTimeout(r,10));}assert.equal(app.node('conversation-text').value,'Private Mission draft');assert.equal(app.node('conversation-send').disabled,true);assert.equal(app.node('conversation-work-save').disabled,true);await app.submit('conversation-form');await app.submit('conversation-work-form');assert.equal(writes,0);assert.deepEqual(await first.journal(),one);assert.deepEqual(await second.journal(),two);
});
test('private Mission and exact Work drafts never share a null scope or leak across Mission selection',async t=>{
 const f=await fixture(t),app=await f.client();await draft(app,'Before Work private');await runInContext("loadMission('mission',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='mission');app.node('conversation-target').value='fresh';await app.node('conversation-target').fire('change');await draft(app,'Exact Work private');app.node('conversation-scope').value='mission';await app.node('conversation-scope').fire('change');assert.equal(app.node('conversation-text').value,'');await draft(app,'Other Mission private');app.node('conversation-scope').value='work';await app.node('conversation-scope').fire('change');assert.equal(app.node('conversation-text').value,'Exact Work private');await runInContext("loadMission('before',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='before');assert.equal(app.node('conversation-text').value,'Before Work private');assert.equal(f.writes(),0);
});
