import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeProfileFactory,parseNativeCompletion} from '../src/native-model-providers.ts';
import type {NativeProtocol} from '../src/native-model-providers.ts';
import type {ModelConnectionProfile} from '../src/provider-profiles.ts';
import {ConnectionCatalog} from '../src/provider-profiles.ts';
import {registerProviderConformance} from './support/provider-conformance.ts';
const profile=(protocol:NativeProtocol):ModelConnectionProfile=>({id:'native',label:'Native fixture',backend:'model-provider',providerKind:'fixture',protocol,model:'exact-model',endpoint:protocol==='anthropic-messages/v1'?'https://api.anthropic.com/v1/messages':'https://generativelanguage.googleapis.com/v1beta/models/exact-model:generateContent',revision:'one',enabled:true,auth:{method:protocol==='anthropic-messages/v1'?'anthropic-api-key':'google-api-key',secretRef:'synthetic-ref'},capabilities:['text-output'],usage:{inputTokens:'reported',outputTokens:'reported',cost:'unknown'},limits:{maxInputBytes:8192,maxOutputTokens:8,maxResponseBytes:8192,timeoutMs:50}});
const response=(protocol:NativeProtocol,model='exact-model',text='Fixture result')=>protocol==='anthropic-messages/v1'?{id:'msg-fixture',type:'message',role:'assistant',model,stop_reason:'end_turn',content:[{type:'text',text}],usage:{input_tokens:3,output_tokens:2}}:{responseId:'fixture',modelVersion:model,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text}]}}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:2,totalTokenCount:5}};
for(const protocol of ['anthropic-messages/v1','gemini-generate-content/v1'] as const){
 registerProviderConformance(protocol,behavior=>{let sends=0;const p=profile(protocol);const factory=nativeProfileFactory(protocol,{mode:'https',resolveCredential:async()=> 'synthetic-test-key',transport:async(url,init)=>{sends++;assert.equal(url,p.endpoint);assert.equal(init.redirect,'error');assert.equal(new Headers(init.headers).get(protocol==='anthropic-messages/v1'?'x-api-key':'x-goog-api-key'),'synthetic-test-key');if(behavior==='unknown')throw Error('synthetic-secret-error');return new Response(JSON.stringify(response(protocol,behavior==='model-mismatch'?'wrong-model':p.model)),{headers:{'content-type':'application/json'}});}});const selected=new ConnectionCatalog([p],[factory]).resolve(p.id,['text-output']);assert.equal(selected.status,'selected');return {adapter:(selected as Extract<typeof selected,{status:'selected'}>).adapter,sends:()=>sends};});
 test(protocol+' fails closed on tool output, truncation, unknown usage and over-bound tokens',()=>{
  const good=response(protocol);assert.equal(parseNativeCompletion(protocol,good,'exact-model',8).status,'completed');
  for(const mutate of [(v:any)=>{if(protocol==='anthropic-messages/v1')delete v.usage.output_tokens;else delete v.usageMetadata.candidatesTokenCount;},(v:any)=>{if(protocol==='anthropic-messages/v1')v.usage.output_tokens=9;else {v.usageMetadata.candidatesTokenCount=9;v.usageMetadata.totalTokenCount=12;}}]){const v=structuredClone(good);mutate(v);assert.throws(()=>parseNativeCompletion(protocol,v,'exact-model',8));}
  const truncated=structuredClone(good) as any;if(protocol==='anthropic-messages/v1')truncated.stop_reason='max_tokens';else truncated.candidates[0].finishReason='MAX_TOKENS';assert.equal(parseNativeCompletion(protocol,truncated,'exact-model',8).status,'failed');const tool=structuredClone(good) as any;if(protocol==='anthropic-messages/v1')tool.content.push({type:'tool_use',name:'unsafe'});else tool.candidates[0].content.parts.push({functionCall:{name:'unsafe'}});assert.equal(parseNativeCompletion(protocol,tool,'exact-model',8).status,'failed');
 });
 test(protocol+' credential failure/timeout never leaks secrets or retries; input bounds send nothing',async()=>{
  let sends=0;const p=profile(protocol);const request={invocationId:'invoke',workId:'work',instruction:'fixture',inputReferences:[],maxOutputTokens:8,signal:new AbortController().signal};const noKey=nativeProfileFactory(protocol,{mode:'https',resolveCredential:async()=>{throw Error('private-secret');},transport:async()=>{sends++;throw Error();}}).create(p);const failure=await noKey.invoke(request);assert.equal(failure.status,'failed');assert.equal(sends,0);assert.doesNotMatch(JSON.stringify(failure),/private-secret/);
  const hangs=nativeProfileFactory(protocol,{mode:'https',resolveCredential:async()=> 'synthetic-test-key',transport:async()=>{sends++;return new Promise(()=>{});}}).create(p);const timed=await hangs.invoke(request);assert.equal(timed.status,'unknown');assert.equal(sends,1);assert.equal(timed.usage.outputTokens,null);const oversized=await hangs.invoke({...request,instruction:'x'.repeat(9000)});assert.equal(oversized.status,'failed');assert.equal(sends,1);
 });
}

test('Gemini mixed text/code/file payload cannot satisfy bounded text completion',()=>{for(const key of ['executableCode','codeExecutionResult','fileData','inlineData','functionCall']){const v=response('gemini-generate-content/v1') as any;v.candidates[0].content.parts[0][key]={payload:'fixture'};assert.equal(parseNativeCompletion('gemini-generate-content/v1',v,'exact-model',8).status,'failed');}const v=response('anthropic-messages/v1','exact-model','\ud800');assert.throws(()=>parseNativeCompletion('anthropic-messages/v1',v,'exact-model',8));});

test('direct native factory creation requires every explicit byte/token/timeout limit',()=>{for(const protocol of ['anthropic-messages/v1','gemini-generate-content/v1'] as const){const factory=nativeProfileFactory(protocol,{mode:'https',resolveCredential:async()=> 'synthetic',transport:async()=>{assert.fail('Configuration must not send');}});for(const key of ['maxInputBytes','maxOutputTokens','maxResponseBytes','timeoutMs']){const p=profile(protocol) as any;delete p.limits[key];assert.throws(()=>factory.create(p),/Invalid native profile/);}}});
