import test from 'node:test';
import assert from 'node:assert/strict';
import {runInContext} from 'node:vm';
import {correctionFixture,chooseCorrection} from './support/owner-correction-fixture.ts';
for(const durable of [false,true]){
 const opts={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} owner reviews original and new inputs, privately cancels, then admits new correction without execution`,opts,async t=>{const f=await correctionFixture(t,durable),app=await f.client(),original=await f.current();await chooseCorrection(app,'Fixed <img src=x onerror=alert(1)>');await app.node('correction-review').fire('click');assert.equal(app.node('correction-save').disabled,false);assert.match(app.node('correction-evidence').textContent,/original|reviewed/);await app.node('correction-cancel').fire('click');assert.equal(f.writes(),0);assert.deepEqual(await f.current(),original);await chooseCorrection(app);await app.node('correction-review').fire('click');await app.submit('correction-form');const current=await f.current();assert.equal(current.value.works.find(w=>w.id==='fixed')!.runtimeRun,undefined);assert.equal(current.value.works.find(w=>w.id==='fixed')!.correction!.workId,'fresh');assert.deepEqual(current.value.works.filter(w=>w.id!=='fixed'),original.value.works);assert.equal(f.calls.length,2);assert.match(app.node('correction-status').textContent,/confirmed/);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);assert.equal(app.node('correction-id').value,'');const fresh=await f.client();await fresh.submit('correction-form');assert.equal(f.writes(),1);});
 test(`${durable?'actual DB':'memory'} changed revision requires deliberate new review and keeps original correction selection`,opts,async t=>{const f=await correctionFixture(t,durable),app=await f.client();await chooseCorrection(app);await app.node('correction-review').fire('click');await f.product.admit('mission',{commandId:'other-admit',expectedRevision:(await f.current()).revision,workId:'later',title:'Other owner action',budget:8});const revision=(await f.current()).revision;await app.tick();await f.until(()=>runInContext('snapshot.revision',app.context)===revision&&!runInContext('loading',app.context));assert.equal(app.node('correction-id').value,'fixed');await app.submit('correction-form');assert.equal(f.writes(),0);await app.node('correction-review').fire('click');await app.submit('correction-form');assert.equal(f.writes(),1);assert.equal(f.calls.length,2);});
 test(`${durable?'actual DB':'memory'} lost committed correction reply settles exact receipt with no duplicate or reload replay`,opts,async t=>{const f=await correctionFixture(t,durable,'unknown'),app=await f.client();await chooseCorrection(app);await app.node('correction-review').fire('click');await app.submit('correction-form');await app.tick();await f.until(()=>runInContext('unknownOperation',app.context)===null);assert.equal(f.writes(),1);assert.equal((await f.current()).value.works.filter(w=>w.id==='fixed').length,1);const fresh=await f.client();assert.equal(fresh.node('correction-id').value,'');await fresh.submit('correction-form');assert.equal(f.writes(),1);assert.equal(f.calls.length,2);});
 test(`${durable?'actual DB':'memory'} late committed admission preserves later private edits and moved focus`,opts,async t=>{const f=await correctionFixture(t,durable,'held'),app=await f.client();await chooseCorrection(app);await app.node('correction-review').fire('click');const pending=app.submit('correction-form');await f.until(()=>f.writes()===1);app.node('correction-title').value='Later private correction';await app.node('correction-title').fire('input');app.node('sequence-summary').focus();f.release();await pending;assert.equal(app.node('correction-title').value,'Later private correction');assert.equal(runInContext('document.activeElement.id',app.context),'sequence-summary');assert.equal(f.calls.length,2);});
}
for(const mode of ['held','held-unknown','held-rejected'] as const)test(`${mode} correction reply cannot restore previous Mission`,async t=>{const f=await correctionFixture(t,false,mode),app=await f.client();await chooseCorrection(app);await app.node('correction-review').fire('click');const pending=app.submit('correction-form');await f.until(()=>f.writes()===1);await runInContext("loadMission('other',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='other');f.release();await pending;assert.equal(app.node('loaded-id').textContent,'other');assert.equal(f.writes(),1);assert.equal(f.calls.length,2);});
