import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {ConnectionWorkbench} from '../src/connection-workbench.ts';
import {createWorkbench} from '../src/server.ts';
import {hash,workInputHash} from '../src/domain.ts';
import {harness,reply} from './support/workbench-client.ts';
async function setup(t:import('node:test').TestContext,durable=false,mode?:'unknown'|'held-review'|'wrong-feed'|'malformed'){
 const f=await fixture(t,durable),calls:any[]=[];await f.product.admit('mission',{commandId:'second',expectedRevision:(await f.current()).revision,workId:'second',title:'Causal successor <img src=x>',budget:8});let s=await f.current(),first=s.value.works.find(w=>w.id==='fresh')!;await f.product.attachWorkPrerequisite('mission',{commandId:'pin',expectedRevision:s.revision,workId:'second',prerequisiteId:'fresh',criteriaHash:hash(first.criteria),inputHash:workInputHash(first),reason:'Original dependency <img src=x>'});await f.product.admit('mission',{commandId:'third',expectedRevision:(await f.current()).revision,workId:'third',title:'Unrequested fresh Work',budget:8});await f.product.create({id:'other',purpose:'Other private draft',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'bounded-text-review/v1'}},'other');
 const manager=new ConnectionWorkbench(f.store,f.artifacts,{allowFixture:true,transport:async(_url,init)=>{const body=JSON.parse(String(init.body)),prompt=JSON.parse(body.messages[0].content);calls.push({model:body.model,prompt});const content=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Original bounded',reason:'Owned fixture verifier'}]}):'Original bounded lifetime fixture';return new Response(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:body.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}),{headers:{'content-type':'application/json'}});}});manager.connect({id:'owned',label:'Owned fixture',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});const connection=manager.list().connections[0]!,executor=manager.selectModel(connection.id,{model:'executor',label:'Executor',expectedConfigHash:connection.configHash}),verifier=manager.selectModel(connection.id,{model:'verifier',label:'Verifier',expectedConfigHash:connection.configHash});manager.authorize({id:'owned-grant',scope:'local',executorProfileId:executor.profileId,verifierProfileId:verifier.profileId,maxOutputTokensPerCall:4,expectedConfigHash:manager.list().configHash});const choice={executorProfileId:executor.profileId,verifierProfileId:verifier.profileId,authorizationId:'owned-grant',outputTokenCap:4},server=createWorkbench(f.store,f.root,{connections:manager,artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port;
 async function until(check:()=>boolean){const end=Date.now()+10000;while(!check()){assert.ok(Date.now()<end,'sequence panel deadline');await new Promise(r=>setTimeout(r,10));}}let releaseReview!:(()=>void);const reviewGate=new Promise<void>(r=>releaseReview=r);const handler=async(path:string,options:any)=>{const res=await fetch(base+path,options),body=await res.json();if(mode==='held-review'&&path.endsWith('/preflight'))await reviewGate;if(mode==='unknown'&&path.endsWith('/run-sequence'))throw Error('Controlled lost final reply');if(mode==='wrong-feed'&&path.endsWith('/run-sequence'))body.feedId='other-database';if(mode==='malformed'&&path.endsWith('/run-sequence'))body.completedWorkIds=['third'];return reply(body,res.status);};async function client(){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission'});await until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);return app;}return {...f,manager,choice,calls,client,until,releaseReview,base};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'memory'} normal GUI exposes exact private sequence review/cancel/start`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await setup(t,durable),app=await f.client();assert.ok(app.node('sequence-work-1'),'normal owner sequence panel missing');assert.ok(app.node('sequence-review'));assert.ok(app.node('sequence-start'));assert.equal(f.calls.length,0);});
async function choose(f:Awaited<ReturnType<typeof setup>>,app:Awaited<ReturnType<Awaited<ReturnType<typeof setup>>['client']>>,ids=['fresh','second']){
 for(const [id,value] of Object.entries({'sequence-work-1':ids[0]||'','sequence-work-2':ids[1]||'','sequence-work-3':ids[2]||'','sequence-executor':f.choice.executorProfileId,'sequence-verifier':f.choice.verifierProfileId,'sequence-authorization':f.choice.authorizationId,'sequence-cap':'4'})){app.node(id).value=value;await app.node(id).fire('change');}
}
for(const durable of [false,true]){
 const options={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} sequence review and private cancellation preserve all Work`,options,async t=>{const f=await setup(t,durable),app=await f.client(),before=await f.current();await choose(f,app);await app.node('sequence-review').fire('click');assert.equal(app.node('sequence-start').disabled,false);assert.equal(f.calls.length,0);await app.node('sequence-cancel').fire('click');assert.equal(app.node('sequence-start').disabled,true);assert.deepEqual(await f.current(),before);assert.equal(app.calls.filter(c=>c.path.endsWith('/run-sequence')).length,0);});
 test(`${durable?'actual DB':'memory'} explicit sequence start accepts exact causal order once`,options,async t=>{const f=await setup(t,durable),app=await f.client();await choose(f,app);await app.node('sequence-review').fire('click');assert.equal(app.node('sequence-start').disabled,false);await app.submit('sequence-form');const s=await f.current();assert.deepEqual(s.value.works.filter(w=>['fresh','second'].includes(w.id)&&w.acceptance==='accepted').map(w=>w.id),['fresh','second']);assert.equal(s.value.works.find(w=>w.id==='third')!.execution,'queued');assert.equal(f.calls.length,4);assert.match(app.node('sequence-status').textContent,/Sequence completed/);await app.submit('sequence-form');assert.equal(f.calls.length,4);});
 test(`${durable?'actual DB':'memory'} reverse prerequisite order never starts`,options,async t=>{const f=await setup(t,durable),app=await f.client();await choose(f,app,['second','fresh']);await app.node('sequence-review').fire('click');assert.equal(app.node('sequence-start').disabled,true);assert.match(app.node('sequence-status').textContent,/prerequisite/);await app.submit('sequence-form');assert.equal(f.calls.length,0);});
}
for(const durable of [false,true]){
 const options={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} lost final reply reads admission without replay or whole completion`,options,async t=>{const f=await setup(t,durable,'unknown'),app=await f.client();await choose(f,app);await app.node('sequence-review').fire('click');await app.submit('sequence-form');assert.equal(f.calls.length,4);assert.match(app.node('sequence-status').textContent,/completion.*unconfirmed|completion is not confirmed/i);await app.tick();await app.submit('sequence-form');assert.equal(f.calls.length,4);assert.equal(app.calls.filter(c=>c.path.endsWith('/run-sequence')).length,1);const fresh=await f.client();assert.equal(fresh.node('sequence-work-1').value,'');assert.equal(fresh.node('sequence-start').disabled,true);assert.equal(f.calls.length,4);});
 test(`${durable?'actual DB':'memory'} cancelled held review cannot restore cancelled plan`,options,async t=>{const f=await setup(t,durable,'held-review'),app=await f.client();await choose(f,app);const review=app.node('sequence-review').fire('click');await f.until(()=>app.calls.some(c=>c.path.endsWith('/preflight')));await app.node('sequence-cancel').fire('click');f.releaseReview();await review;assert.equal(app.node('sequence-work-1').value,'');assert.equal(app.node('sequence-start').disabled,true);assert.equal(f.calls.length,0);});
 test(`${durable?'actual DB':'memory'} stale reviewed revision blocks transmission without replacement`,options,async t=>{const f=await setup(t,durable),app=await f.client();await choose(f,app);await app.node('sequence-review').fire('click');await f.product.admit('mission',{commandId:'advance',expectedRevision:(await f.current()).revision,workId:'advance',title:'Concurrent owner change',budget:8});await app.tick();await f.until(()=>app.node('sequence-start').disabled);assert.equal(app.node('sequence-work-1').value,'fresh');assert.equal(app.node('sequence-start').disabled,true);await app.submit('sequence-form');assert.equal(f.calls.length,0);});
}
test('owned headless browser keyboard review cancel and explicit causal start',{skip:!process.env.MASSION_PLAYWRIGHT_PATH||!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const {chromium}=await import(process.env.MASSION_PLAYWRIGHT_PATH!),f=await setup(t,true),browser=await chromium.launch({headless:true,args:['--no-sandbox']});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:390,height:844}});await page.goto(f.base+'/#mission=mission');await page.locator('#sequence-summary').click();await page.locator('#sequence-work-1').selectOption('fresh');await page.locator('#sequence-work-2').selectOption('second');await page.locator('#sequence-executor').selectOption(f.choice.executorProfileId);await page.locator('#sequence-verifier').selectOption(f.choice.verifierProfileId);await page.locator('#sequence-authorization').selectOption(f.choice.authorizationId);await page.locator('#sequence-cap').fill('4');await page.locator('#sequence-review').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!(document.getElementById('sequence-start') as HTMLButtonElement).disabled);assert.equal(f.calls.length,0);await page.locator('#sequence-cancel').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#sequence-work-1').inputValue(),'');assert.equal(f.calls.length,0);
 for(const [id,value] of Object.entries({'sequence-work-1':'fresh','sequence-work-2':'second','sequence-executor':f.choice.executorProfileId,'sequence-verifier':f.choice.verifierProfileId,'sequence-authorization':f.choice.authorizationId}))await page.locator('#'+id).selectOption(value);await page.locator('#sequence-cap').fill('4');await page.locator('#sequence-review').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!(document.getElementById('sequence-start') as HTMLButtonElement).disabled);await page.locator('#sequence-start').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('sequence-status')?.textContent?.includes('Sequence completed'));assert.equal(f.calls.length,4);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:process.env.MASSION_BROWSER_SCREENSHOT||'/tmp/massion-sequence-browser.png',fullPage:false});await page.reload();await page.waitForSelector('#loaded-id');assert.equal(f.calls.length,4);assert.equal(await page.locator('#sequence-work-1').inputValue(),'');
});
for(const mode of ['wrong-feed','malformed'] as const)test(`sequence ${mode} response cannot certify whole completion`,async t=>{const f=await setup(t,false,mode),app=await f.client();await choose(f,app);await app.node('sequence-review').fire('click');await app.submit('sequence-form');assert.equal(f.calls.length,4);assert.doesNotMatch(app.node('sequence-status').textContent,/Sequence completed:/);assert.match(app.node('sequence-status').textContent,/unconfirmed|not confirmed/);await app.submit('sequence-form');assert.equal(app.calls.filter(c=>c.path.endsWith('/run-sequence')).length,1);});
test('Mission private drafts and separate clients do not substitute selections',async t=>{const f=await setup(t),a=await f.client(),b=await f.client();await choose(f,a);await a.navigateFragment('#mission=other');await f.until(()=>a.node('loaded-id').textContent==='other');assert.equal(a.node('sequence-work-1').value,'');await a.navigateFragment('#mission=mission');await f.until(()=>a.node('loaded-id').textContent==='mission');assert.equal(a.node('sequence-work-1').value,'fresh');assert.equal(b.node('sequence-work-1').value,'');assert.equal(f.calls.length,0);});

test('pretransmission revision change clears pending without inventing unknown receipt',async t=>{const f=await setup(t),app=await f.client();await choose(f,app);await app.node('sequence-review').fire('click');runInContext("navigator.locks={request:async(name,options,callback)=>{snapshot={...snapshot,revision:snapshot.revision+1};return callback({name});}}",app.context);await app.submit('sequence-form');assert.equal(app.calls.filter(c=>c.path.endsWith('/run-sequence')).length,0);assert.equal(runInContext('unknownOperation',app.context),null);assert.equal([...app.storage.keys()].some(key=>key.includes('pending')),false);assert.equal(f.calls.length,0);});
