import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {harness,reply} from './support/workbench-client.ts';
import {SurrealRelationImpact} from '../src/relation-impact.ts';
import {affectedBy} from '../src/domain.ts';
async function setup(t:import('node:test').TestContext,durable=false){
 const {store,transport}=await growthStore(durable),f=await textFixture(t,store),product=new ProductService(store),other='other';await product.create({id:other,purpose:'Separate Mission',scope:'other',constraints:[],criteria:{version:1,description:'Other input',oracle:'manual-review/v1'}},'other-create');const original=(await store.load('mission'))!;
 const server=createWorkbench(store,f.root,{knowledge:transport?new SurrealRelationImpact(transport):{readImpact:async(missionId,entity,version)=>{const s=await store.readState(missionId);return s.snapshot?{missionId,revision:s.snapshot.revision,feedId:s.feedId,cursor:s.cursor,changed:{id:entity,version},affected:affectedBy(s.snapshot.value,entity,version),relations:s.snapshot.value.relations}:null;}}});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');let base='http://127.0.0.1:'+a.port;let sourceMode='',sourceRelease:undefined|(()=>void),lost=false,eventOutage=false,held=false,readHeld=false,releaseWrite:undefined|(()=>void),releaseRead:undefined|(()=>void),rejected=false,race=false;
 const handler=async(path:string,options:any)=>{
  const organization=path.endsWith('/documents')&&options.method==='POST';if(eventOutage&&path.startsWith('/events'))throw Error('Supporting receipt event outage');if(organization&&rejected)return reply({outcome:'rejected',error:'Supporting definite rollback'},503);
  if(organization&&race){race=false;await product.admit('mission',{commandId:'raced-work',expectedRevision:(await store.load('mission'))!.revision,workId:'raced',title:'Another owner write before original CAS',budget:0});}
  const response=await fetch(base+path,options),body=await response.json();if(organization&&held){held=false;await new Promise<void>(r=>releaseWrite=r);}if(readHeld&&path.startsWith('/read-state?')){readHeld=false;await new Promise<void>(r=>releaseRead=r);}if(organization&&lost){lost=false;throw Error('Supporting lost actual committed acknowledgement');}if(path.includes('/document?') || path.includes('/documents?')){if(sourceMode==='hold')await new Promise<void>(r=>sourceRelease=r);if(sourceMode==='wrong-feed')body.feedId='wrong';if(sourceMode==='wrong-hash'&&body.document)body.document.content='Tampered';if(sourceMode==='omitted'&&body.matches){body.matches=[];body.totalMatches=0;}}return reply(body,response.status);
 };
 async function until(check:()=>boolean){const deadline=Date.now()+10000;while(!check()){assert.ok(Date.now()<deadline,'document panel deadline');await new Promise(r=>setTimeout(r,10));}}
 async function client(identity='document-client',storage?:Map<string,string>){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission',identity,storage});if(storage?.has('massion.workbench.pending')){await until(()=>app.node('event-state').textContent==='Disconnected');await app.submit('load-form');}await until(()=>app.node('snapshot-json').textContent.includes('mission')&&(app.node('sync-notice').hidden||!!storage?.has('massion.workbench.pending')));const fields=app.node('document-fields');app.node('document-form').append(fields);for(const name of ['document-id','document-version','document-title','document-source','document-content','save-document','review-document','cancel-document'])fields.append(app.node(name));return app;}
 async function edit(app:Awaited<ReturnType<typeof client>>,content='Original approved local text <img src=x> [literal] evidence',version='1',id='document:source'){for(const [name,value] of [['document-id',id],['document-version',version],['document-title','Original title'],['document-source','Owner local fixture source'],['document-content',content]]){app.node(name!).value=value!;await app.node(name!).fire('input');}}
 async function choose(app:Awaited<ReturnType<typeof client>>,version=1){const d=(await store.load('mission'))!.value.documents!.find(d=>d.version===version)!;app.node('document-choice').value=JSON.stringify([d.id,d.version,d.contentSha256]);await app.node('document-choice').fire('change');}
 return {...f,product,other,original,handler,client,edit,choose,until,journal:()=>growthJournal(store),lose(){lost=true;},outage(value=true){eventOutage=value;},hold(){held=true;releaseWrite=undefined;},holdRead(){readHeld=true;releaseRead=undefined;},writeHeld(){return !!releaseWrite;},readHeld(){return !!releaseRead;},release(){releaseWrite!();},releaseRead(){releaseRead!();},reject(value=true){rejected=value;},race(){race=true;},replaceHost(url:string){base=url;},sourceMode(value:string){sourceMode=value;},sourceHeld(){return !!sourceRelease;},releaseSource(){sourceRelease!();sourceRelease=undefined;}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} document GUI captures/searches/reads exact original source and v2 leaves original Work/v1/native impact unchanged`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client(),other=await f.store.load(f.other);await f.edit(app);app.node('save-document').focus();await app.submit('document-form');assert.match(app.node('document-status').textContent,/Exact document version confirmed/);assert.equal((app.context as any).document.activeElement.id,'save-document');assert.equal(app.node('document-content').value,'');const posted=JSON.parse(app.calls.find(c=>c.path.endsWith('/documents'))!.options.body);assert.equal(posted.expectedRevision,f.original.revision);assert.deepEqual(Object.keys(posted.document).sort(),['content','id','source','title','version']);app.node('document-query').value='[literal]';await app.node('document-query').fire('input');await app.submit('document-search-form');assert.match(app.node('document-search-results').textContent,/1 latest versions match.*document:source/s);await f.choose(app);app.node('document-read').focus();await app.node('document-read').fire('click');assert.match(app.node('document-read-results').textContent,/Original approved local text <img src=x>/);assert.match(app.node('document-read-status').textContent,/UTF-8 content hash checked/);assert.equal((app.context as any).document.activeElement.id,'document-read');assert.equal(app.all().some(n=>n.tagName==='IMG'),false);
 await f.product.recordRelation('mission',{commandId:'doc-relation',expectedRevision:(await f.store.load('mission'))!.revision,relation:{from:'report',fromVersion:1,to:'document:source',toVersion:1,type:'evidenced-by',provenance:'Original local document source v1'}});await app.submit('load-form');await f.until(()=>!app.node('document-fields').disabled);await f.edit(app,'Replacement local source v2','2');await app.node('review-document').fire('click');await app.submit('document-form');assert.equal((await f.store.load('mission'))!.value.documents!.length,2);app.node('document-query').value='[literal]';await app.node('document-query').fire('input');await app.submit('document-search-form');assert.match(app.node('document-search-results').textContent,/0 latest versions match/);await f.choose(app,1);await app.node('document-read').fire('click');assert.match(app.node('document-read-results').textContent,/Original approved local text/);app.node('impact-entity').value='document:source';app.node('impact-version').value='1';await app.submit('impact-form');assert.match(app.node('impact-results').textContent,/report.*Original local document source v1/s);assert.deepEqual((await f.store.load('mission'))!.value.works,f.original.value.works);assert.deepEqual(await f.store.load(f.other),other);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} document stale GUI draft requires explicit review and CAS race preserves original text/version without retry`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.edit(app,'Private original text');await f.product.admit('mission',{commandId:'other-work',expectedRevision:f.original.revision,workId:'other-work',title:'Another owner write',budget:0});await app.submit('load-form');await f.until(()=>!app.node('document-fields').disabled);await app.submit('document-form');assert.equal(app.calls.filter(c=>c.path.endsWith('/documents')).length,0);assert.match(app.node('document-status').textContent,/No command was sent/);await app.node('review-document').fire('click');const revision=(await f.store.load('mission'))!.revision;f.race();await app.submit('document-form');assert.match(app.node('status').textContent,/Revision conflict/);assert.equal(app.calls.filter(c=>c.path.endsWith('/documents')).length,1);assert.equal(JSON.parse(app.calls.find(c=>c.path.endsWith('/documents'))!.options.body).expectedRevision,revision);assert.equal(app.node('document-content').value,'Private original text');assert.equal((await f.store.load('mission'))!.value.documents,undefined);await app.node('review-document').fire('click');await app.submit('document-form');assert.equal((await f.store.load('mission'))!.value.documents![0]!.content,'Private original text');
});
test('document private cancel and invalid text/UTF8/version/ID guards send no command or change Work draft',async t=>{
 const f=await setup(t),app=await f.client();app.node('work-title').value='Untouched Work';const journal=await f.journal();for(const [id,value] of [['document-id','file:///etc/passwd'],['document-version','2'],['document-title',''],['document-content',''],['document-source',String.fromCharCode(0xd800)],['document-content','한'.repeat(6000)],['document-title','x'.repeat(201)]]){await f.edit(app);app.node(id!).value=value!;await app.submit('document-form');assert.match(app.node('document-status').textContent,/No command was sent/);}await app.node('cancel-document').fire('click');assert.equal(app.node('document-content').value,'');assert.equal(app.node('work-title').value,'Untouched Work');assert.deepEqual(await f.journal(),journal);assert.equal(app.calls.filter(c=>c.path.endsWith('/documents')).length,0);
});
test('Mission-private document source drafts survive switches and late old snapshot',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app,'Mission-private source');app.node('document-version').value='';await app.node('document-version').fire('input');const journal=await f.journal();f.holdRead();await app.submit('load-form');await f.until(f.readHeld);await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other'&&!app.node('document-fields').disabled);await f.edit(app,'Other private source');f.releaseRead();await app.navigateFragment('#mission=mission');await f.until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('document-fields').disabled);assert.equal(app.node('document-content').value,'Mission-private source');assert.equal(app.node('document-version').value,'');assert.deepEqual(await f.journal(),journal);
});
test('pending document save locks duplicate/review/cancel/switch and preserves later private text and moved focus',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app);app.node('save-document').focus();f.hold();const saving=app.submit('document-form');await f.until(f.writeHeld);assert.equal(app.node('document-fields').disabled,true);await app.submit('document-form');await app.node('cancel-document').fire('click');await app.node('review-document').fire('click');await app.navigateFragment('#mission=other');assert.equal(app.node('loaded-id').textContent,'mission');app.node('document-content').value='Later private edit';await app.node('document-content').fire('input');app.node('document-status').focus();f.release();await saving;assert.equal((app.context as any).document.activeElement.id,'document-status');assert.equal(app.node('document-content').value,'Later private edit');assert.match(app.node('document-status').textContent,/Later private edits/);assert.equal(app.calls.filter(c=>c.path.endsWith('/documents')).length,1);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} document unknown acknowledgement stays locked until durable read-only receipt; no save replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.edit(app);f.lose();f.outage();await app.submit('document-form');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('document-fields').disabled,true);assert.equal((await f.store.load('mission'))!.value.documents!.length,1);const journal=await f.journal();await app.submit('document-form');await app.node('organization-recheck').fire('click');assert.ok(app.storage.has('massion.workbench.pending'));f.outage(false);await app.node('organization-recheck').fire('click');await f.until(()=>!app.storage.has('massion.workbench.pending')&&!app.node('document-fields').disabled);assert.match(app.node('document-status').textContent,/confirmed/);assert.equal(app.calls.filter(c=>c.path.endsWith('/documents')).length,1);assert.deepEqual(await f.journal(),journal);
});
test('actual SurrealDB fresh browser recovers document unknown identity without POST replay',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,true),app=await f.client();await f.edit(app);f.lose();f.outage();await app.submit('document-form');const journal=await f.journal(),fresh=await f.client('fresh',app.storage);assert.equal(fresh.node('document-fields').disabled,true);f.outage(false);await fresh.node('organization-recheck').fire('click');await f.until(()=>!fresh.storage.has('massion.workbench.pending')&&!fresh.node('document-fields').disabled);assert.equal(fresh.calls.some(c=>c.options?.method==='POST'),false);assert.deepEqual(await f.journal(),journal);await f.choose(fresh);await fresh.node('document-read').fire('click');assert.match(fresh.node('document-read-results').textContent,/Original approved local/);
});
test('document read rejects forged feed/content and omitted search results without replacing exact original',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app);await app.submit('document-form');const journal=await f.journal();for(const mode of ['wrong-feed','wrong-hash']){await f.choose(app);f.sourceMode(mode);await app.node('document-read').fire('click');assert.match(app.node('document-read-status').textContent,/not verified/);assert.equal(app.node('document-read-results').textContent,'');}f.sourceMode('omitted');app.node('document-query').value='[literal]';await app.submit('document-search-form');assert.match(app.node('document-read-status').textContent,/not verified/);assert.equal(app.node('document-search-results').textContent,'');f.sourceMode('');await app.submit('document-search-form');assert.match(app.node('document-search-results').textContent,/1 latest versions match/);assert.deepEqual(await f.journal(),journal);
});
test('document read cancel, changed selection, new snapshot and Mission switch discard late original HTTP responses and preserve drafts/focus',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app);await app.submit('document-form');await f.edit(app,'Private source after save','2');const draft=app.node('document-base').textContent,journal=await f.journal();await f.choose(app);f.sourceMode('hold');app.node('document-read').focus();const reading=app.node('document-read').fire('click');await f.until(f.sourceHeld);assert.equal(app.node('document-read').disabled,true);await app.node('document-read').fire('click');const before=app.calls.filter(c=>c.path.includes('/document?'));assert.equal(before.length,1);app.node('document-read-cancel').focus();await app.node('document-read-cancel').fire('click');assert.equal(before[0]!.options.signal.aborted,true);assert.equal((app.context as any).document.activeElement.id,'document-read');f.sourceMode('');f.releaseSource();await reading;assert.equal(app.node('document-read-results').textContent,'');assert.match(app.node('document-read-status').textContent,/cancelled/);assert.equal(app.node('document-content').value,'Private source after save');assert.equal(app.node('document-base').textContent,draft);
 f.sourceMode('hold');const late=app.node('document-read').fire('click');await f.until(f.sourceHeld);await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other'&&!app.node('document-fields').disabled);f.sourceMode('');f.releaseSource();await late;assert.equal(app.node('document-read-results').textContent,'');assert.deepEqual(await f.journal(),journal);
});
test('definite document rollback retains private original text and focus before deliberate save',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app);app.node('document-content').focus();const journal=await f.journal();f.reject();await app.submit('document-form');assert.equal(app.storage.has('massion.workbench.pending'),false);assert.equal((app.context as any).document.activeElement.id,'document-content');assert.match(app.node('document-content').value,/Original approved/);assert.deepEqual(await f.journal(),journal);f.reject(false);await app.submit('document-form');assert.equal((await f.store.load('mission'))!.value.documents!.length,1);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} same-snapshot reconnect invalidates held exact/search document reads and unlocks deliberate read without late data or save`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.edit(app);await app.submit('document-form');await f.edit(app,'Private source retained','2');const journal=await f.journal(),draft=app.node('document-base').textContent;
 for(const mode of ['exact','search']){await f.choose(app);app.node('document-query').value='[literal]';f.sourceMode('hold');const pending=mode==='exact'?app.node('document-read').fire('click'):app.submit('document-search-form');await f.until(f.sourceHeld);const call=app.calls.filter(c=>c.path.includes('/document?')||c.path.includes('/documents?')).at(-1)!;await app.windowEvent('offline');assert.equal(call.options.signal.aborted,true);assert.equal(app.node('document-read-cancel').disabled,true);assert.equal(app.node('document-read-results').textContent,'');assert.match(app.node('document-read-status').textContent,/Host connection changed/);await app.windowEvent('online');await f.until(()=>app.node('sync-notice').hidden&&!app.node('document-fields').disabled);f.sourceMode('');f.releaseSource();await pending;assert.equal(app.node('document-search').disabled,false);assert.equal(app.node('document-read').disabled,false);assert.equal(app.node('document-read-results').textContent,'');assert.equal(app.node('document-search-results').textContent,'');if(mode==='exact'){await app.node('document-read').fire('click');assert.match(app.node('document-read-results').textContent,/Original approved local/);}else{await app.submit('document-search-form');assert.match(app.node('document-search-results').textContent,/1 latest versions match/);}}
 assert.equal(app.node('document-content').value,'Private source retained');assert.equal(app.node('document-base').textContent,draft);assert.deepEqual(await f.journal(),journal);
});
