import test from 'node:test';
import assert from 'node:assert/strict';
import {hash,workInputHash,apply} from '../src/domain.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {ConfiguredTextRuntime} from '../src/configured-runtime.ts';
import {ProductService} from '../src/product.ts';
import {ProviderRegistry} from '../src/providers.ts';
import type {ProviderAdapter} from '../src/providers.ts';
import {rejectedFixture} from './support/rejected-text-fixture.ts';
for(const durable of [false,true]){
 const opts={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} explicit corrected new Work admission and separate accepted execution retain rejected original and provenance`,opts,async t=>{const f=await rejectedFixture(t,durable),before=await f.current(),original=structuredClone(before.value.works),input={commandId:'new-correction',expectedRevision:before.revision,workId:'fixed',title:'Produce the fixed requested result',budget:8,correction:{workId:'fresh',workHash:hash(f.work),reason:'Correct known incorrect output'}};const admitted=await f.product.admit('mission',input);assert.equal(admitted.status,'committed');assert.equal(f.calls.length,2);let current=await f.current(),w=current.value.works.find(w=>w.id==='fixed')!;assert.equal(w.acceptance,'pending');assert.equal(w.runtimeRun,undefined);assert.equal(w.correction!.workHash,hash(f.work));assert.equal(w.correction!.actorId,'local-owner');assert.equal(w.sourceDocuments,undefined);assert.equal(w.prerequisites,undefined);assert.deepEqual(current.value.works.filter(w=>w.id!=='fixed'),original);const journal=await f.journal();assert.equal((await f.product.admit('mission',input)).status,'replayed');assert.deepEqual(await f.journal(),journal);const prompts:any[]=[];const adapter=(role:'executor'|'verifier'):ProviderAdapter=>({...f.config[role].adapter,async invoke(request){const p=JSON.parse(request.instruction);prompts.push(p);return {status:'completed',output:role==='executor'?'Fixed known output':JSON.stringify({artifactSha256:p.binding.artifactSha256,criteriaVersion:p.criteria.version,criteriaHash:p.binding.criteriaHash,verdict:'passed',checks:[{criterion:p.criteria.description,passed:true,quote:'Fixed known output',reason:'Independent fixed fixture judgment'}]}),usage:{inputTokens:1,outputTokens:1},reason:'Owned fixture only'};}});const executor=adapter('executor'),verifier=adapter('verifier'),runtime=new ConfiguredTextRuntime(f.store,{...f.config,executor:{...f.config.executor,adapter:executor},verifier:{...f.config.verifier,adapter:verifier}}),product=new ProductService(f.store,new ProviderRegistry([executor,verifier]),runtime,f.artifacts);await product.run('mission','fixed','fixed-explicit',(await f.current()).revision);current=await f.current();w=current.value.works.find(w=>w.id==='fixed')!;assert.equal(w.acceptance,'accepted');assert.deepEqual(w.record!.correction,w.correction);assert.ok(w.assignments.every(a=>a.extensionVersion==='massion.builtin.bounded-text@6'));assert.deepEqual(prompts[0].work.correction,w.correction);assert.deepEqual(prompts[1].requirements.correction,w.correction);assert.equal(w.runtimeRun!.inputHash,workInputHash(w));assert.deepEqual(current.value.works.filter(w=>w.id!=='fixed'),original);validateMissionJournalLineage(await f.journal());assert.equal(f.calls.length,2);});
 test(`${durable?'actual DB':'memory'} stale/hash/feed/forged correction admissions reject without changing original or admitting a retry`,opts,async t=>{const f=await rejectedFixture(t,durable),before=await f.journal(),revision=(await f.current()).revision,body={commandId:'http-correction',expectedRevision:revision,workId:'fixed',title:'Fixed',budget:8,correction:{workId:'fresh',workHash:hash(f.work),reason:'Owner fixed instruction'}};for(const bad of [{...body,correction:{...body.correction,workHash:'a'.repeat(64)}},{...body,correction:{...body.correction,actorId:'executor'}},{...body,correction:null},{...body,budget:0},{...body,correction:{...body.correction,reason:''}},{...body,extraAuthority:true}]){const response=await fetch(f.base+'/missions/mission/work',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(bad)});assert.ok(response.status>=400);assert.deepEqual(await f.journal(),before);}const wrong=await fetch(f.base+'/missions/mission/work',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':'other-db'},body:JSON.stringify(body)});assert.equal(wrong.status,409);assert.deepEqual(await f.journal(),before);const stale=await f.product.admit('mission',{...body,expectedRevision:revision-1});assert.equal(stale.status,'conflict');assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,2);});
}
test('unknown/interrupted/cancelled/accepted source cannot create correction even with a recomputed full hash',async t=>{const f=await rejectedFixture(t);for(const mutate of [(w:any)=>w.effects[0].status='unknown',(w:any)=>w.execution='cancelled',(w:any)=>w.acceptance='accepted',(w:any)=>w.runtimeInterruption={runId:'old'},(w:any)=>w.runtimeRecovery={runId:'old'},(w:any)=>w.runtimeRun.inputHash='a'.repeat(64),(w:any)=>w.verdict.artifactSha256='a'.repeat(64)]){const mission=structuredClone((await f.current()).value),source=mission.works.find(w=>w.id==='fresh')!;mutate(source);assert.throws(()=>apply(mission,{type:'admit-work',workId:'fixed',title:'Fixed',budget:8,correction:{workId:'fresh',workHash:hash(source),reason:'Explicit correction'}},{id:'local-owner',roles:['owner']}));}const journal=await f.journal();assert.deepEqual(await f.journal(),journal);});
for(const durable of [false,true]){
 const opts={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} persisted unknown provider effect remains exact and cannot admit a correction or replay`,opts,async t=>{const f=await rejectedFixture(t,durable);await f.product.admit('mission',{commandId:'unknown-admit',expectedRevision:(await f.current()).revision,workId:'uncertain',title:'Owned uncertain fixture',budget:8});let calls=0;const adapter:ProviderAdapter={...f.config.executor.adapter,async invoke(){calls++;return {status:'unknown',output:null,usage:{inputTokens:null,outputTokens:null},reason:'Controlled unknown receipt; no remote invocation'};}};const runtime=new ConfiguredTextRuntime(f.store,{...f.config,executor:{...f.config.executor,adapter}}),product=new ProductService(f.store,f.providers,runtime,f.artifacts);await product.run('mission','uncertain','owned-unknown',(await f.current()).revision);const before=await f.current(),source=before.value.works.find(w=>w.id==='uncertain')!,journal=await f.journal();assert.equal(source.effects[0]!.status,'unknown');await assert.rejects(product.admit('mission',{commandId:'forbidden-correction',expectedRevision:before.revision,workId:'forbidden',title:'Explicit correction attempt',budget:8,correction:{workId:'uncertain',workHash:hash(source),reason:'Cannot turn unknown into retry authority'}}));assert.deepEqual(await f.current(),before);assert.deepEqual(await f.journal(),journal);assert.equal(calls,1);});
 test(`${durable?'actual DB':'memory'} caller mutation during admission lookup cannot change reviewed correction envelope`,opts,async t=>{const f=await rejectedFixture(t,durable);let entered=false,release!:(()=>void);const gate=new Promise<void>(r=>release=r),proxy=new Proxy(f.store,{get(target,key){if(key==='load')return async(...args:Parameters<typeof target.load>)=>{if(!entered){entered=true;await gate;}return target.load(...args);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),product=new ProductService(proxy,f.providers,f.runtime,f.artifacts),input={commandId:'frozen-correction',expectedRevision:(await f.current()).revision,workId:'fixed',title:'Original reviewed new request',budget:8,correction:{workId:'fresh',workHash:hash(f.work),reason:'Original reviewed reason'}},pending=product.admit('mission',input);await f.until(()=>entered);input.workId='substituted';input.title='Mutated caller title';input.correction.reason='Mutated reason';input.correction.workHash='a'.repeat(64);release();assert.equal((await pending).status,'committed');const w=(await f.current()).value.works.find(w=>w.id==='fixed')!;assert.equal(w.title,'Original reviewed new request');assert.equal(w.correction!.reason,'Original reviewed reason');assert.equal(w.correction!.workHash,hash(f.work));assert.equal(f.calls.length,2);});
}
