import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {harness,reply} from './support/workbench-client.ts';
const responsibilities=(name:string)=>[{role:'executor' as const,responsibility:'Original executor '+name,capability:'text-output' as const},{role:'verifier' as const,responsibility:'Independent verifier '+name,capability:'independent-text-review' as const}];
async function setup(t:import('node:test').TestContext,durable=false){
 const {store}=await growthStore(durable),f=await textFixture(t,store),product=new ProductService(store),other='other';await product.create({id:other,purpose:'Separate Mission',scope:'other',constraints:[],criteria:{version:1,description:'Other input',oracle:'manual-review/v1'}},'other-create');await product.reviseOrganization('mission',{commandId:'org1',expectedRevision:(await store.load('mission'))!.revision,version:1,reason:'Original owner reason <img src=x>',responsibilities:responsibilities('v1')});await product.admit('mission',{commandId:'old-pin',expectedRevision:(await store.load('mission'))!.revision,workId:'old-pin',title:'Original organization Work',budget:0});const original=(await store.load('mission'))!;
 const server=createWorkbench(store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');let base='http://127.0.0.1:'+a.port;let lost=false,eventOutage=false,held=false,readHeld=false,releaseWrite:undefined|(()=>void),releaseRead:undefined|(()=>void),rejected=false,race=false;
 const handler=async(path:string,options:any)=>{
  const organization=path.endsWith('/organization')&&options.method==='POST';if(eventOutage&&path.startsWith('/events'))throw Error('Supporting receipt event outage');if(organization&&rejected)return reply({outcome:'rejected',error:'Supporting definite rollback'},503);
  if(organization&&race){race=false;await product.admit('mission',{commandId:'raced-work',expectedRevision:(await store.load('mission'))!.revision,workId:'raced',title:'Another owner write before original CAS',budget:0});}
  const response=await fetch(base+path,options),body=await response.json();if(organization&&held){held=false;await new Promise<void>(r=>releaseWrite=r);}if(readHeld&&path.startsWith('/read-state?')){readHeld=false;await new Promise<void>(r=>releaseRead=r);}if(organization&&lost){lost=false;throw Error('Supporting lost actual committed acknowledgement');}return reply(body,response.status);
 };
 async function until(check:()=>boolean){const deadline=Date.now()+10000;while(!check()){assert.ok(Date.now()<deadline,'organization panel deadline');await new Promise(r=>setTimeout(r,10));}}
 async function client(identity='org-client',storage?:Map<string,string>){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission',identity,storage});if(storage?.has('massion.workbench.pending')){await until(()=>app.node('event-state').textContent==='Disconnected');await app.submit('load-form');}await until(()=>app.node('snapshot-json').textContent.includes('mission')&&(app.node('sync-notice').hidden||!!storage?.has('massion.workbench.pending')));const fields=app.node('organization-fields');app.node('organization-form').append(fields);for(const name of ['organization-target','organization-version','organization-executor','organization-verifier','organization-reason','save-organization','review-organization','cancel-organization'])fields.append(app.node(name));return app;}
 async function choose(app:Awaited<ReturnType<typeof client>>,value='1'){app.node('organization-target').value=value;await app.node('organization-target').fire('change');}
 async function edit(app:Awaited<ReturnType<typeof client>>,executor='New executor <img src=x>',verifier='New independent verifier',reason='Owner GUI rationale'){for(const [name,value] of [['organization-executor',executor],['organization-verifier',verifier],['organization-reason',reason]]){app.node(name!).value=value!;await app.node(name!).fire('input');}}
 return {...f,product,other,original,handler,client,choose,edit,until,journal:()=>growthJournal(store),lose(){lost=true;},outage(value=true){eventOutage=value;},hold(){held=true;releaseWrite=undefined;},holdRead(){readHeld=true;releaseRead=undefined;},writeHeld(){return !!releaseWrite;},readHeld(){return !!releaseRead;},release(){releaseWrite!();},releaseRead(){releaseRead!();},reject(value=true){rejected=value;},race(){race=true;},replaceHost(url:string){base=url;}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} organization GUI selects exact historical evidence, saves normal API, pins future Work and retains earlier accepted and pinned Work`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client(),other=await f.store.load(f.other);assert.match(app.node('organization-current').textContent,/organization v1/);await f.choose(app);assert.match(app.node('organization-evidence').textContent,/Author: local-owner.*Original owner reason <img src=x>.*Original executor v1/s);assert.equal(app.node('organization-version').value,'2');await f.edit(app);app.node('save-organization').focus();await app.submit('organization-form');assert.match(app.node('organization-status').textContent,/revision 2 confirmed/);assert.equal((app.context as any).document.activeElement.id,'organization-target');assert.equal(app.node('organization-target').value,'');assert.equal(app.all().some(n=>n.tagName==='IMG'),false);const posted=JSON.parse(app.calls.find(c=>c.path.endsWith('/organization'))!.options.body);assert.equal(posted.expectedRevision,f.original.revision);assert.equal(posted.version,2);assert.deepEqual(Object.keys(posted).sort(),['commandId','expectedRevision','reason','responsibilities','version']);
 app.node('work-title').value='New organizational responsibility';await app.submit('work-form');const current=(await f.store.load('mission'))!;assert.equal(current.value.works.at(-1)!.organizationSnapshot!.version,2);assert.deepEqual(current.value.works.slice(0,f.original.value.works.length),f.original.value.works);assert.deepEqual(await f.store.load(f.other),other);assert.match(app.node('work-list').textContent,/Original organization responsibilities/);assert.match(app.node('work-list').textContent,/No organization revision pinned/);assert.match(app.node('work-list').textContent,/New executor <img src=x>/);await f.choose(app,'1');assert.equal(app.node('organization-executor').value,'Original executor v1');assert.equal(app.node('organization-version').value,'3');assert.match(app.node('organization-evidence').textContent,/Stored organization v1/);const journal=await f.journal();await app.node('cancel-organization').fire('click');assert.equal(app.node('organization-target').value,'');assert.deepEqual(await f.journal(),journal);const fresh=await f.client('fresh');await f.choose(fresh,'2');assert.match(fresh.node('organization-evidence').textContent,/New executor <img src=x>/);assert.deepEqual(await f.journal(),journal);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} known stale organization draft sends no save until explicit review; a later CAS race preserves original exact source and rejects without retry`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.choose(app);await f.edit(app,'My private executor','My private verifier','My private reason');await f.product.reviseOrganization('mission',{commandId:'other-org2',expectedRevision:f.original.revision,version:2,reason:'Another owner',responsibilities:responsibilities('v2')});await app.submit('load-form');await f.until(()=>app.node('organization-current').textContent.includes('organization v2')&&!app.node('organization-fields').disabled);assert.match(app.node('organization-base').textContent,/Based on aggregate revision .*State changed/);assert.equal(app.node('organization-version').value,'2');await app.submit('organization-form');assert.equal(app.calls.filter(c=>c.path.endsWith('/organization')).length,0);assert.match(app.node('organization-status').textContent,/No command was sent/);assert.equal(app.node('organization-target').value,'1');assert.equal(app.node('organization-executor').value,'My private executor');await app.node('review-organization').fire('click');assert.equal(app.node('organization-version').value,'3');const reviewed=(await f.store.load('mission'))!.revision;f.race();await app.submit('organization-form');assert.match(app.node('status').textContent,/Revision conflict/);assert.equal(app.calls.filter(c=>c.path.endsWith('/organization')).length,1);assert.equal(JSON.parse(app.calls.find(c=>c.path.endsWith('/organization'))!.options.body).expectedRevision,reviewed);assert.equal(app.node('organization-executor').value,'My private executor');assert.equal((await f.store.load('mission'))!.value.organizationRevisions!.length,2);await app.node('review-organization').fire('click');await app.submit('organization-form');assert.equal((await f.store.load('mission'))!.value.organizationRevisions!.at(-1)!.responsibilities[0]!.responsibility,'My private executor');assert.deepEqual((await f.store.load('mission'))!.value.works.slice(0,f.original.value.works.length),f.original.value.works);
});
test('organization input guards, new definitions and cancellation keep unrelated Work draft and send no command',async t=>{
 const f=await setup(t),app=await f.client();app.node('work-title').value='Private untouched Work';const before=await f.journal();await f.choose(app,'new');assert.equal(app.node('organization-executor').value,'');for(const values of [['','Review','Reason'],['Produce','','Reason'],['Produce','Review',''],['x'.repeat(2001),'Review','Reason'],[String.fromCharCode(0xd800),'Review','Reason']]){await f.edit(app,...values as [string,string,string]);await app.submit('organization-form');assert.match(app.node('organization-status').textContent,/No command was sent/);}await app.node('cancel-organization').fire('click');assert.equal(app.node('work-title').value,'Private untouched Work');assert.equal(app.calls.filter(c=>c.path.endsWith('/organization')).length,0);assert.deepEqual(await f.journal(),before);
});
test('Mission-private source and responsibility edits survive switches and late old snapshot without cross-Mission writes',async t=>{
 const f=await setup(t),app=await f.client();await f.choose(app);await f.edit(app,'Mission private executor','Mission private verifier','Mission reason');const before=await f.journal();f.holdRead();await app.submit('load-form');await f.until(f.readHeld);await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other'&&!app.node('organization-fields').disabled);await f.choose(app,'new');await f.edit(app,'Other private executor','Other private verifier','Other reason');f.releaseRead();await f.until(()=>app.node('loaded-id').textContent==='other');await app.navigateFragment('#mission=mission');await f.until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('organization-fields').disabled);assert.equal(app.node('organization-target').value,'1');assert.equal(app.node('organization-executor').value,'Mission private executor');assert.match(app.node('organization-base').textContent,new RegExp('revision '+f.original.revision));assert.deepEqual(await f.journal(),before);
});
test('pending actual acknowledgement bars duplicates/cancel/review/Mission switch and retains later edits and moved focus',async t=>{
 const f=await setup(t),app=await f.client();await f.choose(app);await f.edit(app);app.node('save-organization').focus();f.hold();const saving=app.submit('organization-form');await f.until(f.writeHeld);assert.equal(app.node('organization-fields').disabled,true);await app.submit('organization-form');await app.node('cancel-organization').fire('click');await app.node('review-organization').fire('click');await app.navigateFragment('#mission=other');assert.equal(app.node('loaded-id').textContent,'mission');assert.equal(app.node('organization-target').value,'1');app.node('organization-executor').value='Later supporting private edit';await app.node('organization-executor').fire('input');app.node('organization-status').focus();f.release();await saving;assert.equal((app.context as any).document.activeElement.id,'organization-status');assert.equal(app.node('organization-executor').value,'Later supporting private edit');assert.equal(app.node('organization-target').value,'1');assert.match(app.node('organization-status').textContent,/later private edits/);assert.equal(app.calls.filter(c=>c.path.endsWith('/organization')).length,1);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} lost committed organization acknowledgement keeps unknown barrier and manual durable receipt check settles without POST replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.choose(app);await f.edit(app);f.lose();f.outage();await app.submit('organization-form');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('organization-fields').disabled,true);assert.equal(app.node('organization-recheck').disabled,false);assert.match(app.node('organization-status').textContent,/not confirmed/);assert.equal((await f.store.load('mission'))!.value.organizationRevisions!.length,2);const committed=await f.journal();await app.node('organization-recheck').fire('click');assert.ok(app.storage.has('massion.workbench.pending'));assert.deepEqual(await f.journal(),committed);f.outage(false);await app.node('organization-recheck').fire('click');await f.until(()=>!app.storage.has('massion.workbench.pending')&&!app.node('organization-fields').disabled);assert.match(app.node('organization-status').textContent,/revision 2 confirmed/);assert.equal(app.calls.filter(c=>c.path.endsWith('/organization')).length,1);assert.deepEqual(await f.journal(),committed);
});
test('actual SurrealDB fresh browser recovery of organization unknown command clears exact receipt without repeating save',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,true),app=await f.client();await f.choose(app);await f.edit(app);f.lose();f.outage();await app.submit('organization-form');const marker=app.storage.get('massion.workbench.pending');assert.ok(marker);const journal=await f.journal(),fresh=await f.client('reloaded',app.storage);assert.equal(fresh.node('organization-fields').disabled,true);assert.ok(fresh.storage.has('massion.workbench.pending'));f.outage(false);await fresh.node('organization-recheck').fire('click');await f.until(()=>!fresh.storage.has('massion.workbench.pending')&&!fresh.node('organization-fields').disabled);assert.equal(fresh.calls.some(c=>c.options?.method==='POST'),false);assert.deepEqual(await f.journal(),journal);await f.choose(fresh,'2');assert.match(fresh.node('organization-evidence').textContent,/New executor/);
});
test('definite organization rollback retains original draft and focus before deliberate new save',async t=>{
 const f=await setup(t),app=await f.client();await f.choose(app);await f.edit(app);app.node('organization-executor').focus();const before=await f.journal();f.reject();await app.submit('organization-form');assert.equal(app.storage.has('massion.workbench.pending'),false);assert.equal(app.node('organization-executor').value,'New executor <img src=x>');assert.equal((app.context as any).document.activeElement.id,'organization-executor');assert.deepEqual(await f.journal(),before);f.reject(false);await app.submit('organization-form');assert.equal((await f.store.load('mission'))!.value.organizationRevisions!.length,2);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} replacement feed with same Mission ID cannot retain old organization confirmation or rebase an unavailable source`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.choose(app);await f.edit(app);await app.submit('organization-form');assert.match(app.node('organization-status').textContent,/revision 2 confirmed/);await f.choose(app,'1');await f.edit(app,'Old feed private executor','Old feed private verifier','Retained private reason');const oldJournal=await f.journal();const {store:replacement}=await growthStore(durable),product=new ProductService(replacement);await product.create({id:'mission',purpose:'Same ID on different database',scope:'new-scope',constraints:[],criteria:{version:1,description:'Replacement criteria',oracle:'manual-review/v1'}},'replacement-create');const replacementJournal=await growthJournal(replacement),server=createWorkbench(replacement,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');f.replaceHost('http://127.0.0.1:'+a.port);await app.tick();await f.until(()=>app.node('event-state').textContent==='Disconnected');await app.tick();await f.until(()=>app.node('sync-notice').hidden&&app.node('organization-current').textContent.includes('No organization revision stored'));assert.doesNotMatch(app.node('organization-status').textContent,/confirmed/);assert.match(app.node('organization-base').textContent,/State changed.*unavailable/);assert.equal(app.node('save-organization').disabled,true);assert.equal(app.node('review-organization').disabled,true);assert.equal(app.node('organization-executor').value,'Old feed private executor');await app.submit('organization-form');await app.node('review-organization').fire('click');assert.deepEqual(await growthJournal(replacement),replacementJournal);assert.deepEqual(await f.journal(),oldJournal);
});
