import test from 'node:test';
import type {TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createWorkbench} from '../src/server.ts';
import {SurrealStore} from '../src/storage.ts';
import {harness,reply} from './support/workbench-client.ts';
import {growthStore,seedGrowth,growthJournal} from './support/growth-fixture.ts';
async function setup(t:TestContext,durable=false){
 const {store,transport}=await growthStore(durable),f=await seedGrowth(store),other=await seedGrowth(store,'mission:other-growth'),root=await mkdtemp(join(tmpdir(),'massion-growth-panel-'));t.after(()=>rm(root,{recursive:true,force:true}));let server=createWorkbench(store,root),base='';async function start(){server.listen(0,'127.0.0.1');await once(server,'listening');const a=server.address();assert.ok(a&&typeof a==='object');base='http://127.0.0.1:'+a.port;}async function stop(){if(!server.listening)return;server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}await start();t.after(stop);
 let mode='',blocked=false,release!:()=>void,held=false;const handler=async(path:string,options:any)=>{
  if(blocked && path.startsWith('/events'))throw new Error('Labeled supporting event outage');
  if(mode==='hold-read' && path.startsWith('/read-state?mission=')){held=true;await new Promise<void>(r=>release=r);}
  const growth=path.endsWith('/growth')&&options.method==='POST';if(growth && mode==='hold-before'){held=true;await new Promise<void>(r=>release=r);}
  const r=await fetch(base+path,options),body=await r.json();
  if(growth && mode==='loss'){blocked=true;throw new Error('Labeled lost actual committed response');}
  if(growth && mode==='hold-after'){held=true;await new Promise<void>(r=>release=r);}
  return reply(body,r.status);
 };
 async function until(check:()=>boolean){const end=Date.now()+15000;while(!check()){assert.ok(Date.now()<end,'Growth client deadline');await new Promise(r=>setTimeout(r,5));}}
 async function client(saved:Record<string,string>={}){const app=harness(handler,saved,undefined,{network:true,fragment:'#mission='+encodeURIComponent(f.id),identity:'growth-client-'+crypto.randomUUID()});await until(()=>app.node('loaded-id').textContent===f.id&&!app.node('mission-id').disabled);const fields=app.node('growth-fields');app.node('growth-form').append(fields);fields.append(...['adopt-growth','revert-growth','review-growth','cancel-growth'].map(id=>app.node(id)));return app;}
 const select=async(app:Awaited<ReturnType<typeof client>>,id='g')=>{app.node('growth-target').value=id;await app.node('growth-target').fire('change');};
 return {...f,store,other,client,select,until,journal:()=>growthJournal(store),mode(value:string){mode=value;if(value.startsWith('hold'))held=false;},held:()=>held,release(){mode='';release();},resume(){mode='';blocked=false;},async freshHost(){await stop();server=createWorkbench(transport?new SurrealStore(transport):store,root);await start();}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal Growth panel shows literal evaluation and exact versions, deliberately adopts/reverts, preserves old Work`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client(),original=(await f.store.load(f.id))!,old=structuredClone(original.value.works);await f.select(app);const before=await f.journal();assert.match(app.node('growth-evidence').textContent,/rounding@1.*Original baseline.*rounding@2/s);assert.match(app.node('growth-evidence').textContent,/<img src=x>/);assert.match(app.node('growth-evidence').textContent,/growth-evaluator/);assert.match(app.node('growth-evidence').textContent,/held-out evaluation/);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);assert.deepEqual(await f.journal(),before);assert.equal(app.node('adopt-growth').disabled,false);assert.equal(app.node('revert-growth').disabled,true);
 app.node('adopt-growth').focus();await app.node('adopt-growth').fire('click');assert.match(app.node('growth-status').textContent,/Confirmed adopt/);assert.equal((app.context as any).document.activeElement.id,'review-growth');assert.equal(app.node('revert-growth').disabled,true);let current=(await f.store.load(f.id))!;assert.deepEqual(current.value.works,old);const submitted=JSON.parse(app.calls.find(c=>c.path.endsWith('/growth'))!.options.body);assert.deepEqual({...submitted,commandId:'known'},{commandId:'known',expectedRevision:original.revision,growthId:'g',baseline:'rounding@1',candidate:'rounding@2',action:'adopt'});
 await f.product.admit(f.id,{commandId:'future-panel',expectedRevision:current.revision,workId:'future',title:'Future Work',budget:0});await app.tick();current=(await f.store.load(f.id))!;await f.until(()=>JSON.parse(app.node('snapshot-json').textContent).revision===current.revision&&!app.node('mission-id').disabled);assert.deepEqual(current.value.works.at(-1)!.appliedMemoryVersions,['other@1','rounding@2']);await app.node('review-growth').fire('click');assert.equal(app.node('revert-growth').disabled,false);app.node('growth-evidence').focus();await app.node('revert-growth').fire('click');assert.match(app.node('growth-status').textContent,/Confirmed revert/);assert.equal((app.context as any).document.activeElement.id,'growth-evidence');assert.deepEqual((await f.store.load(f.id))!.value.works.slice(0,old.length),old);assert.equal(app.storage.has('massion.workbench.pending'),false);assert.equal(app.calls.filter(c=>c.options.method==='POST').length,2);const final=await f.journal();await app.node('revert-growth').fire('click');assert.deepEqual(await f.journal(),final);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} actual committed Growth response loss keeps unknown barrier and reload recovers receipt without replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.select(app);f.mode('loss');await app.node('adopt-growth').fire('click');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('growth-fields').disabled,true);assert.equal(app.node('growth-target').value,'g');assert.match(app.node('growth-base').textContent,/rounding@1.*rounding@2/);const committed=await f.journal();await app.node('adopt-growth').fire('click');await app.node('review-growth').fire('click');assert.equal(app.calls.filter(c=>c.path.endsWith('/growth')).length,1);await f.freshHost();f.resume();const reloaded=await f.client(Object.fromEntries(app.storage));await reloaded.tick();await f.until(()=>!reloaded.storage.has('massion.workbench.pending'));assert.deepEqual(await f.journal(),committed);assert.equal(reloaded.calls.filter(c=>c.options.method==='POST').length,0);assert.equal((await f.store.load(f.id))!.value.growth[0]!.status,'adopted');await f.select(reloaded);assert.equal(reloaded.node('revert-growth').disabled,false);
});
test('pending Growth commit suppresses duplicates and retains moved focus and a later exact selection',async t=>{
 const f=await setup(t),app=await f.client();await f.send({type:'propose-growth',proposal:{id:'other-g',proposer:'representative',target:'memory',baseline:'rounding@1',candidate:'rounding@2',counterevidence:'Other proposal is distinct',status:'proposed'}},'representative');await app.tick();const revision=(await f.store.load(f.id))!.revision;await f.until(()=>JSON.parse(app.node('snapshot-json').textContent).revision===revision&&!app.node('mission-id').disabled);await f.select(app);f.mode('hold-after');app.node('adopt-growth').focus();const pending=app.node('adopt-growth').fire('click');await f.until(f.held);assert.equal(app.node('growth-fields').disabled,true);await app.node('adopt-growth').fire('click');await app.node('review-growth').fire('click');assert.equal(app.calls.filter(c=>c.path.endsWith('/growth')).length,1);await f.select(app,'other-g');app.node('growth-evidence').focus();f.release();await pending;assert.equal(app.node('growth-target').value,'other-g');assert.match(app.node('growth-status').textContent,/Exact proposal selected/);assert.equal((app.context as any).document.activeElement.id,'growth-evidence');assert.equal(app.node('adopt-growth').disabled,true);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} concurrent revision conflicts retain exact Growth until explicit review; Mission switch restores private selection`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.select(app);const originalBase=app.node('growth-base').textContent;f.mode('hold-before');const pending=app.node('adopt-growth').fire('click');await f.until(f.held);await f.product.admit(f.id,{commandId:'concurrent-work',expectedRevision:(await f.store.load(f.id))!.revision,workId:'concurrent',title:'Concurrent owner Work',budget:0});const committed=await f.journal();f.release();await pending;assert.match(app.node('status').textContent,/Revision conflict/);assert.equal(app.node('growth-target').value,'g');assert.match(app.node('growth-base').textContent,/State changed/);assert.deepEqual(await f.journal(),committed);
 await app.navigateFragment('#mission='+f.other.id);await f.until(()=>app.node('loaded-id').textContent===f.other.id&&!app.node('mission-id').disabled);assert.equal(app.node('growth-target').value,'');await app.navigateFragment('#mission='+f.id);await f.until(()=>app.node('loaded-id').textContent===f.id&&!app.node('mission-id').disabled);assert.equal(app.node('growth-target').value,'g');assert.match(app.node('growth-base').textContent,/State changed/);assert.notEqual(app.node('growth-base').textContent,originalBase);await app.node('review-growth').fire('click');await app.node('adopt-growth').fire('click');assert.equal((await f.store.load(f.id))!.value.growth[0]!.status,'adopted');assert.equal(app.calls.filter(c=>c.path.endsWith('/growth')).length,2);
});

test('same-Mission held refresh restores disabled Growth focus but preserves deliberately moved focus',async t=>{
 const f=await setup(t),app=await f.client();await f.select(app);
 for(const moved of [false,true]){app.node('adopt-growth').focus();f.mode('hold-read');const pending=app.node('load-form').fire('submit');await f.until(f.held);assert.equal(app.node('growth-fields').disabled,true);if(moved)app.node('growth-evidence').focus();else (app.context as any).document.activeElement=(app.context as any).document.createElement('body');f.release();await pending;await f.until(()=>!app.node('growth-fields').disabled);assert.equal((app.context as any).document.activeElement.id,moved?'growth-evidence':'adopt-growth');assert.equal(app.node('growth-fields').disabled,false);}
 assert.equal(app.calls.filter(c=>c.options.method==='POST').length,0);
});
