import test from 'node:test';
import type {TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createWorkbench} from '../src/server.ts';
import {ProductService} from '../src/product.ts';
import {harness,reply} from './support/workbench-client.ts';
import {proposalFixture,orders} from './support/growth-proposal-fixture.ts';
async function setup(t:TestContext,durable=false){const f=await proposalFixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const base='http://127.0.0.1:'+address.port;let mode='',held=false,release!:()=>void,blocked=false;
const handler=async(path:string,options:any)=>{if(blocked&&path.startsWith('/events'))throw Error('Supporting event outage');const response=await fetch(base+path,options),body=await response.json();if(options.method==='POST'&&path.endsWith('/growth-evaluation')){if(mode==='hold'){held=true;await new Promise<void>(r=>release=r);}if(mode==='loss'){blocked=true;throw Error('Supporting lost actual evaluation commit response');}}return reply(body,response.status);};async function until(check:()=>boolean){const deadline=Date.now()+15000;while(!check()){assert.ok(Date.now()<deadline,'Growth creation client deadline');await new Promise(r=>setTimeout(r,5));}}
async function client(saved:Record<string,string>={}){const app=harness(handler,saved,undefined,{network:true,fragment:'#mission=mission',identity:'creation-'+crypto.randomUUID()});await until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('mission-id').disabled);for(const [form,fields,ids] of [['growth-create-form','growth-create-fields',['growth-create-id','growth-create-baseline','growth-create-memory','growth-create-version','growth-create-content','growth-create-source','growth-create-counter','growth-create-review','growth-create-submit']],['growth-evaluate-form','growth-evaluate-fields',['growth-evaluate-cases','growth-evaluate-submit']],['growth-form','growth-fields',['adopt-growth','revert-growth','review-growth','cancel-growth']]] as const){app.node(form).append(app.node(fields));app.node(fields).append(...ids.map(id=>app.node(id)));}return app;}
async function fill(app:Awaited<ReturnType<typeof client>>){const values=[f.proposal.growthId,f.proposal.baseline,f.proposal.candidate.id,String(f.proposal.candidate.version),f.proposal.candidate.content,f.proposal.candidate.source,f.proposal.counterevidence];for(const [i,id] of ['growth-create-id','growth-create-baseline','growth-create-memory','growth-create-version','growth-create-content','growth-create-source','growth-create-counter'].entries()){app.node(id).value=values[i]!;await app.node(id).fire('input');}await app.node('growth-create-review').fire('click');}
async function select(app:Awaited<ReturnType<typeof client>>){app.node('growth-target').value='new-growth';await app.node('growth-target').fire('change');app.node('growth-evaluate-cases').value=JSON.stringify(orders);await app.node('growth-evaluate-cases').fire('input');}
return {...f,handler,until,client,fill,select,mode(value:string){mode=value;held=false;},held:()=>held,release(){mode='';release();},resume(){mode='';blocked=false;}};}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal UI creates user proposal, evaluates exact input orders, adopts and reverts with original pins retained`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
const f=await setup(t,durable),app=await f.client();await f.fill(app);app.node('growth-create-submit').focus();await app.node('growth-create-form').fire('submit');assert.match(app.node('growth-create-status').textContent,/confirmed/);assert.equal(app.node('growth-create-source').value,f.proposal.candidate.source);await f.select(app);assert.match(app.node('growth-evidence').textContent,/<img src=x>/);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);assert.equal(app.node('adopt-growth').disabled,true);assert.equal(app.node('growth-evaluate-submit').disabled,false);await app.node('growth-evaluate-form').fire('submit');assert.match(app.node('growth-evaluate-status').textContent,/confirmed/);assert.match(app.node('growth-evidence').textContent,/host-rounding-oracle/);await app.node('review-growth').fire('click');await app.node('adopt-growth').fire('click');assert.equal((await f.store.load('mission'))!.value.growth[0]!.status,'adopted');await app.node('review-growth').fire('click');await app.node('revert-growth').fire('click');assert.equal((await f.store.load('mission'))!.value.growth[0]!.status,'reverted');assert.deepEqual((await f.store.load('mission'))!.value.works,f.original.value.works);assert.equal(app.calls.filter(c=>c.options.method==='POST').length,4);assert.equal(app.node('growth-evaluate-cases').value,JSON.stringify(orders));assert.equal(app.storage.has('massion.workbench.pending'),false);
});
test('held actual evaluation acknowledgement suppresses duplicate and preserves moved focus and later input draft',async t=>{
const f=await setup(t),app=await f.client();await f.fill(app);await app.node('growth-create-form').fire('submit');await f.select(app);f.mode('hold');app.node('growth-evaluate-submit').focus();const pending=app.node('growth-evaluate-form').fire('submit');await f.until(f.held);await app.node('growth-evaluate-form').fire('submit');assert.equal(app.calls.filter(c=>c.path.endsWith('/growth-evaluation')).length,1);app.node('growth-create-source').focus();app.node('growth-evaluate-cases').value='Later private input';await app.node('growth-evaluate-cases').fire('input');f.release();await pending;assert.equal(app.node('growth-evaluate-cases').value,'Later private input');assert.equal((app.context as any).document.activeElement.id,'growth-create-source');assert.equal(app.node('growth-evaluate-submit').disabled,true);
});
test('actual SurrealDB lost evaluation response retains unknown marker and reload recovers receipt without process or POST replay',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
const f=await setup(t,true),app=await f.client();await f.fill(app);await app.node('growth-create-form').fire('submit');await f.select(app);f.mode('loss');await app.node('growth-evaluate-form').fire('submit');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('growth-evaluate-fields').disabled,true);const journal=await f.journal();f.resume();const fresh=await f.client(Object.fromEntries(app.storage));assert.equal(fresh.storage.has('massion.workbench.pending'),false);assert.equal(fresh.calls.filter(c=>c.options.method==='POST').length,0);assert.deepEqual(await f.journal(),journal);assert.equal((await f.store.load('mission'))!.value.growth[0]!.status,'evaluated');
});
test('concurrent proposal CAS conflict retains original data until review; Mission switching keeps private drafts',async t=>{
const f=await setup(t),app=await f.client();await f.fill(app);await f.product.admit('mission',{commandId:'concurrent-owner',expectedRevision:(await f.store.load('mission'))!.revision,workId:'concurrent',title:'Later owner Work',budget:0});await app.node('growth-create-form').fire('submit');assert.match(app.node('status').textContent,/Revision conflict/);assert.equal((await f.store.load('mission'))!.value.growth.length,0);assert.equal(app.node('growth-create-source').value,f.proposal.candidate.source);await new ProductService(f.store).create({id:'other',purpose:'Separate draft scope',scope:'local',constraints:[],criteria:{version:1,description:'Separate',oracle:'manual/v1'}},'other-create');await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other'&&!app.node('mission-id').disabled);assert.equal(app.node('growth-create-source').value,'');await app.navigateFragment('#mission=mission');await f.until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('mission-id').disabled);assert.equal(app.node('growth-create-source').value,f.proposal.candidate.source);await app.node('growth-create-review').fire('click');await app.node('growth-create-form').fire('submit');assert.equal((await f.store.load('mission'))!.value.growth.length,1);
});
