import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {Application} from '../src/application.ts';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {hash,pinnedOrganization,workInputHash} from '../src/domain.ts';
import type {Mission,Command,OrganizationResponsibility} from '../src/domain.ts';
import type {Store} from '../src/storage.ts';
import {SurrealStore} from '../src/storage.ts';
import {ConfiguredTextRuntime,workAdmissionPreflight} from '../src/configured-runtime.ts';
import type {ProviderAdapter,ProviderRequest} from '../src/providers.ts';
import {ProviderRegistry} from '../src/providers.ts';
import {TextArtifactStore} from '../src/text-artifacts.ts';
import {validateMissionJournalLineage,validateMissionLineage} from '../src/backup-lineage.ts';
import {readRecordArtifact} from '../src/record-artifact.ts';
import {exportPortableBackup,restorePortableBackup,openRestoredArtifacts} from '../src/portable-backup.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {stopOwnedChild} from './support/owned-process.ts';
const roles=(suffix='v1'):OrganizationResponsibility[]=>[{role:'executor',responsibility:'Produce bounded artifact '+suffix,capability:'text-output'},{role:'verifier',responsibility:'Independently review original evidence '+suffix,capability:'independent-text-review'}];
const input=(version:number,expectedRevision:number)=>({commandId:'org-'+version,expectedRevision,version,reason:'Owner rationale '+version+' <img src=x>',responsibilities:roles('v'+version)});
async function fixture(t:import('node:test').TestContext,durable=false,cli=false){const {store,transport}=await growthStore(durable),f=await textFixture(t,store,cli),product=new ProductService(store),original=(await store.load('mission'))!;return {...f,transport,product,original,journal:()=>growthJournal(store)};}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal organization history pins future Work, assignments and Record while original accepted Work remains unchanged`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port,feed=(await f.store.readState()).feedId;
 const post=async(route:string,body:unknown,identity=feed)=>{const r=await fetch(base+'/missions/mission/'+route,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':identity},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 const v1=input(1,f.original.revision);assert.equal((await post('organization',v1)).body.status,'committed');let current=(await f.store.load('mission'))!;assert.equal(current.value.version,f.original.value.version);assert.equal(current.value.organizationRevisions![0]!.actorId,'local-owner');assert.deepEqual(current.value.works,f.original.value.works);assert.equal((await post('work',{commandId:'work-a',expectedRevision:current.revision,workId:'a',title:'Original organization responsibility',budget:2})).status,201);
 current=(await f.store.load('mission'))!;const workA=structuredClone(current.value.works.at(-1)!);assert.equal(workA.organizationSnapshot?.version,1);const hashA=workInputHash(workA);const v2=input(2,current.revision);assert.equal((await post('organization',v2)).body.status,'committed');current=(await f.store.load('mission'))!;assert.deepEqual(current.value.works.at(-1),workA);assert.equal(workInputHash(current.value.works.at(-1)!),hashA);assert.deepEqual(pinnedOrganization(current.value,workA),workA.organizationSnapshot);
 await post('work',{commandId:'work-b',expectedRevision:current.revision,workId:'b',title:'Future responsibility',budget:2});current=(await f.store.load('mission'))!;assert.equal(current.value.works.at(-1)!.organizationSnapshot?.version,2);
 const app=new Application(f.store,[{id:'owner',roles:['owner']},{id:'executor',roles:['executor']},{id:'verifier',roles:['verifier']}]);let sequence=0;const send=async(command:Command,actorId='owner')=>app.dispatch({missionId:'mission',expectedRevision:(await f.store.load('mission'))!.revision,commandId:'org-evidence-'+(++sequence),actorId,command});
 const model={provider:'fixture',model:'data-only',configVersion:'v1',reason:'No model invocation',evidenceClass:'fixture' as const};
 await send({type:'activate-runtime',workId:'a',run:{id:'data-only-run',authorizationId:'fixture-only',criteriaHash:hash(workA.criteria),inputHash:hashA,mode:'mock-http',outputTokenCap:1}});
 for(const role of ['executor','verifier'] as const)await send({type:'assign',workId:'a',assignment:{id:role+'-a',actorId:role,role,taskId:'a:root',model,extensionVersion:'fixture-v1'}});
 await send({type:'admit-effect',workId:'a',effect:{id:'a-effect',taskId:'a:root',status:'pending',target:'fixture bytes',authority:'owner fixture'},reserve:1},'executor').then(async result=>{assert.equal(result.status,'committed');});
 await send({type:'receipt',workId:'a',effectId:'a-effect',outcome:'succeeded',receipt:'Fixture bytes only',usage:1},'executor');const artifact=await f.artifacts.write('a',1,'Organization original pinned result');await send({type:'publish-artifact',workId:'a',artifact},'executor');await send({type:'verify',workId:'a',verdict:{id:'a-verdict',verifierAssignmentId:'verifier-a',artifactSha256:artifact.sha256,artifactVersion:1,criteriaVersion:workA.criteria.version,status:'passed',evidence:[{kind:'fixture',detail:'Data-only independently assigned evidence',source:'test'}]}},'verifier');await send({type:'settle-task',workId:'a',taskId:'a:root',result:'Fixture settled'},'executor');await send({type:'accept',workId:'a',recordId:'a-record',artifactSnapshot:await f.artifacts.snapshot(artifact)});
 current=(await f.store.load('mission'))!;const accepted=current.value.works.find(w=>w.id==='a')!;assert.equal(accepted.record!.organizationSnapshot!.version,1);assert.ok(accepted.assignments.every(a=>a.organizationVersion===1));const {checksum,...bundle}=accepted.record!;assert.equal(hash(bundle),checksum);assert.deepEqual(current.value.works[0],f.original.value.works[0]);const journal=await f.journal();assert.equal((await post('organization',v1)).body.status,'replayed');assert.equal((await post('organization',{...v1,reason:'changed'})).status,409);assert.deepEqual(await f.journal(),journal);assert.deepEqual((await (await fetch(base+'/missions/mission')).json()).value,current.value);validateMissionJournalLineage(journal);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} organization rejects forged grants, invalid roles/capabilities/version, non-owner, wrong feed and stale CAS without writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),initial=await f.journal(),v1=input(1,f.original.revision);for(const forged of [{...v1,actorId:'caller'},{...v1,authority:'owner'},{...v1,version:2},{...v1,reason:''},{...v1,reason:'x'.repeat(2001)},{...v1,responsibilities:[]},{...v1,responsibilities:[roles()[0],roles()[0]]},{...v1,responsibilities:[{...roles()[0],capability:'shell'},roles()[1]]},{...v1,responsibilities:[{...roles()[0],actorId:'chosen-executor'},roles()[1]]},{...v1,responsibilities:[{...roles()[0],responsibility:''},roles()[1]]}])await assert.rejects(f.product.reviseOrganization('mission',forged as typeof v1));assert.deepEqual(await f.journal(),initial);
 const unauthorized=new Application(f.store,[{id:'representative',roles:['representative']}]);await assert.rejects(unauthorized.dispatch({missionId:'mission',commandId:'denied',expectedRevision:v1.expectedRevision,actorId:'representative',command:{type:'revise-organization',version:1,reason:v1.reason,responsibilities:v1.responsibilities}}),/role/);assert.deepEqual(await f.journal(),initial);
 const server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const route='http://127.0.0.1:'+a.port+'/missions/mission/organization';let r=await fetch(route,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':'wrong-feed'},body:JSON.stringify(v1)});assert.equal(r.status,409);assert.deepEqual(await f.journal(),initial);
 await f.product.reviseOrganization('mission',v1);const current=(await f.store.load('mission'))!;assert.equal((await f.product.reviseOrganization('mission',{...input(2,v1.expectedRevision),commandId:'stale'})).status,'conflict');const before=await f.journal();assert.equal((await f.product.reviseOrganization('mission',{...input(1,current.revision),commandId:'nonadvancing'}).catch(e=>e.message)), 'Organization version must advance by one');assert.deepEqual(await f.journal(),before);
 await f.product.admit('mission',{commandId:'version-work',expectedRevision:current.revision,workId:'pinned',title:'Exact version',budget:0});const app=new Application(f.store,[{id:'owner',roles:['owner']}]),snapshot=(await f.store.load('mission'))!,assignment={id:'bad',actorId:'executor',role:'executor' as const,taskId:'pinned:root',model:{provider:'fixture',model:'x',configVersion:'v1',reason:'fixture',evidenceClass:'fixture' as const},extensionVersion:'v1',organizationVersion:2};await assert.rejects(app.dispatch({missionId:'mission',commandId:'wrong-binding',expectedRevision:snapshot.revision,actorId:'owner',command:{type:'assign',workId:'pinned',assignment}}),/organization version/);const tampered=structuredClone(snapshot.value);tampered.works.at(-1)!.organizationSnapshot!.responsibilities[0]!.responsibility='Rewritten old definition';assert.throws(()=>validateMissionLineage(tampered),/pinned organization/);assert.ok(workAdmissionPreflight({revision:snapshot.revision,value:tampered},'pinned',snapshot.revision).diagnostics.some(d=>d.code==='organization_input_unavailable'));validateMissionJournalLineage(await f.journal());
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} concurrent organization CAS and duplicate commands have one atomic outcome`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),v1=input(1,f.original.revision),before=await f.journal();const result=await Promise.all([f.product.reviseOrganization('mission',v1),f.product.reviseOrganization('mission',v1)]);assert.deepEqual(result.map(r=>r.status).sort(),['committed','replayed']);assert.equal((await f.journal()).length,before.length+1);const current=(await f.store.load('mission'))!,v2=input(2,current.revision);const competing=await Promise.all([f.product.reviseOrganization('mission',v2),f.product.reviseOrganization('mission',{...v2,commandId:'other-owner',reason:'Other submitted reason'})]);assert.deepEqual(competing.map(r=>r.status).sort(),['committed','conflict']);assert.equal((await f.store.load('mission'))!.value.organizationRevisions!.length,2);validateMissionJournalLineage(await f.journal());
});
test('actual SurrealDB freezes caller organization at asynchronous admission and exact receipt recovers a lost committed response',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,true);let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>release=r),started=new Promise<void>(r=>ready=r);let first=true;const proxy=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='lookupOperation')return async(...args:unknown[])=>{if(first){first=false;ready();await held;}return fn.apply(target,args);};return typeof fn==='function'?fn.bind(target):fn;}}) as Store<Mission>;
 const original=input(1,f.original.revision),submitted=structuredClone(original),pending=new ProductService(proxy).reviseOrganization('mission',submitted);await started;submitted.version=42;submitted.responsibilities[0]!.responsibility='Later caller edit';submitted.reason='Later reason';release();assert.equal((await pending).status,'committed');assert.deepEqual((await f.store.load('mission'))!.value.organizationRevisions![0]!.responsibilities,original.responsibilities);
 let lost=true;const lostStore=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='commit')return async(...args:unknown[])=>{const result=await fn.apply(target,args);if(lost){lost=false;throw Error('Injected committed response loss');}return result;};return typeof fn==='function'?fn.bind(target):fn;}}) as Store<Mission>;const v2=input(2,(await f.store.load('mission'))!.revision);await assert.rejects(new ProductService(lostStore).reviseOrganization('mission',v2),/response loss/);const journal=await f.journal(),state=await f.store.readState();const receipt=await f.store.lookupOperation({id:'mission',commandId:v2.commandId,fingerprint:hash({actorId:'local-owner',expectedRevision:v2.expectedRevision,command:{type:'revise-organization',version:v2.version,reason:v2.reason,responsibilities:v2.responsibilities}})});assert.equal(receipt.status,'replayed');assert.equal((await f.product.reviseOrganization('mission',v2)).status,'replayed');assert.deepEqual(await f.journal(),journal);assert.deepEqual(await f.store.readState(),state);validateMissionJournalLineage(journal);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} configured credential-free runtime uses original organization in both task inputs and checksummed independent Record`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),prompts:{role:string;input:any}[]=[],adapters=(role:string):ProviderAdapter=>({descriptor:{provider:'controlled-fixture',model:role,configVersion:'fixture-v1',enabled:true,capabilities:['text-output'],evidenceClass:'fixture'},async invoke(request:ProviderRequest){const data=JSON.parse(request.instruction);prompts.push({role,input:data});const output=role==='executor'?'Original bounded result':JSON.stringify({artifactSha256:data.binding.artifactSha256,criteriaVersion:data.criteria.version,criteriaHash:data.binding.criteriaHash,verdict:'passed',checks:[{criterion:data.criteria.description,passed:true,quote:'Original bounded',reason:'Controlled independent-role contract evidence'}]});return {status:'completed',output,usage:{inputTokens:1,outputTokens:1},reason:'Controlled fixture result'};}});
 const executor=adapters('executor'),verifier=adapters('verifier'),runtime=new ConfiguredTextRuntime(f.store,{enabled:true,outputTokenCap:4,authorization:{id:'controlled-data-fixture-only',scope:'local',mode:'mock-http',executor:executor.descriptor,verifier:verifier.descriptor,maxOutputTokensPerCall:4},executor:{identity:'host-executor',adapter:executor},verifier:{identity:'host-verifier',adapter:verifier},artifacts:f.artifacts}),product=new ProductService(f.store,new ProviderRegistry([executor,verifier]),runtime);
 let current=(await f.store.load('mission'))!;await product.reviseMission('mission',{commandId:'runtime-criteria',expectedRevision:current.revision,purpose:current.value.purpose,criteria:{version:2,description:'Original bounded result',oracle:'bounded-text-review/v1'}});current=(await f.store.load('mission'))!;await product.reviseOrganization('mission',input(1,current.revision));current=(await f.store.load('mission'))!;await product.admit('mission',{commandId:'runtime-a',expectedRevision:current.revision,workId:'runtime',title:'Bounded evidence',budget:8});current=(await f.store.load('mission'))!;const pinned=structuredClone(current.value.works.at(-1)!.organizationSnapshot),originalHash=workInputHash(current.value.works.at(-1)!);await product.reviseOrganization('mission',input(2,current.revision));current=(await f.store.load('mission'))!;
 const result=await product.run('mission','runtime','normal-runtime',current.revision);assert.equal(result.status,'settled');const work=result.snapshot.value.works.at(-1)!;assert.equal(work.acceptance,'accepted');assert.equal(prompts.length,2);assert.deepEqual(prompts[0]!.input.work.organization,pinned);assert.deepEqual(prompts[1]!.input.requirements.organization,pinned);assert.equal(prompts[0]!.input.binding.inputHash,originalHash);assert.equal(work.runtimeRun!.inputHash,originalHash);assert.ok(work.assignments.every(a=>a.organizationVersion===1&&a.extensionVersion==='massion.builtin.bounded-text@3'));assert.equal(work.record!.evidenceClass,'fixture');assert.deepEqual(work.record!.organizationSnapshot,pinned);assert.deepEqual(result.snapshot.value.works[0],f.original.value.works[0]);assert.notEqual(work.assignments.find(a=>a.role==='executor')!.actorId,work.assignments.find(a=>a.role==='verifier')!.actorId);validateMissionJournalLineage(await f.journal());
 const state=await f.store.readState('mission'),query={recordId:work.record!.id,artifactVersion:work.artifact!.version,artifactSha256:work.artifact!.sha256};assert.equal((await readRecordArtifact(f.store,f.artifacts,'mission','runtime',query))!.content,'Original bounded result');
 for(const kind of ['missing-record','wrong-record','assignment','missing-history','changed-history']){
  const copy=structuredClone(state),corrupt=copy.snapshot!.value.works.at(-1)!;
  if(kind==='missing-record')delete corrupt.record!.organizationSnapshot;
  if(kind==='wrong-record')corrupt.record!.organizationSnapshot=structuredClone(copy.snapshot!.value.organizationRevisions![1]!);
  if(kind==='assignment'){corrupt.assignments[0]!.organizationVersion=2;corrupt.record!.assignments=structuredClone(corrupt.assignments);}
  if(kind==='missing-history')copy.snapshot!.value.organizationRevisions!.shift();
  if(kind==='changed-history')copy.snapshot!.value.organizationRevisions![0]!.reason='Rewritten original history';
  const {checksum,...bundle}=corrupt.record!;corrupt.record!.checksum=hash(bundle);let reads=0;
  await assert.rejects(readRecordArtifact({readState:async()=>copy} as Store<Mission>,{read:async()=>{reads++;return 'Original bounded result';}},'mission','runtime',query),/exact accepted/);assert.equal(reads,0);
 }
 let reads=0;const later=structuredClone(state);later.snapshot!.value.organizationRevisions![0]!.reason='History changed during artifact read';await assert.rejects(readRecordArtifact({readState:async()=>++reads===1?state:later} as Store<Mission>,f.artifacts,'mission','runtime',query),/exact accepted/);assert.equal(reads,2);
 if(durable){assert.ok(f.store instanceof SurrealStore);const original=await f.store.load('mission'),journal=await f.store.exportJournal(),serialized=await exportPortableBackup(f.store,f.artifacts),{store:restored}=await growthStore(true);assert.ok(restored instanceof SurrealStore);const root=join(f.root,'runtime-restored');await restorePortableBackup(serialized,restored,root);assert.deepEqual(await restored.load('mission'),original);assert.deepEqual(await restored.exportJournal(),journal);assert.equal((await readRecordArtifact(restored,openRestoredArtifacts(serialized,root),'mission','runtime',query))!.content,'Original bounded result');}
});
test('actual SurrealDB organization history and original pinned accepted Record survive inert portable restore',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,true);await f.product.reviseOrganization('mission',input(1,f.original.revision));await f.product.admit('mission',{commandId:'restore-a',expectedRevision:(await f.store.load('mission'))!.revision,workId:'a',title:'Pinned before change',budget:0});await f.product.reviseOrganization('mission',input(2,(await f.store.load('mission'))!.revision));await f.product.admit('mission',{commandId:'restore-b',expectedRevision:(await f.store.load('mission'))!.revision,workId:'b',title:'Pinned after change',budget:0});assert.ok(f.store instanceof SurrealStore);const snapshot=await f.store.load('mission') as import('../src/storage.ts').Snapshot<Mission>,journal=await f.store.exportJournal(),backup=await exportPortableBackup(f.store,f.artifacts),{store:restored}=await growthStore(true);assert.ok(restored instanceof SurrealStore);await restorePortableBackup(backup,restored,join(f.root,'restored'));assert.deepEqual(await restored.load('mission'),snapshot);assert.deepEqual(await restored.exportJournal(),journal);assert.deepEqual(snapshot!.value.works[0],f.original.value.works[0]);assert.deepEqual(snapshot!.value.works.slice(1).map(w=>w.organizationSnapshot!.version),[1,2]);
});
test('actual SurrealDB normal CLI creates organization revision and future pinned Work and preserves exact receipt after process restart',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 let child:ReturnType<typeof spawn>|undefined,log='',cwd='';const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry];async function stop(){if(child)await stopOwnedChild(child,{cwd,argv});}t.after(stop);const f=await fixture(t,true,true);assert.ok(f.transport);cwd=f.root;const database=(await f.transport.query('RETURN $session.db;',{}))[0];assert.equal(typeof database,'string');const probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const a=probe.address();assert.ok(a&&typeof a==='object');const port=a.port;await new Promise<void>(r=>probe.close(()=>r()));const base='http://127.0.0.1:'+port,feed=(await f.store.readState()).feedId;
 async function start(){child=spawn(process.execPath,[entry],{cwd,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database as string,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',b=>log+=b);child.stderr!.on('data',b=>log+=b);const deadline=Date.now()+10000;while(true){try{if((await fetch(base+'/health')).ok)return;}catch{}assert.ok(child.exitCode===null&&Date.now()<deadline,log);await new Promise(r=>setTimeout(r,10));}}
 const post=async(route:string,body:unknown)=>{const r=await fetch(base+'/missions/mission/'+route,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':feed},body:JSON.stringify(body)});assert.equal(r.ok,true);return r.json();};await start();const originalPid=child!.pid,v1=input(1,f.original.revision);assert.equal((await post('organization',v1)).status,'committed');await post('work',{commandId:'cli-a',expectedRevision:(await f.store.load('mission'))!.revision,workId:'a',title:'Original responsibility',budget:0});await post('organization',input(2,(await f.store.load('mission'))!.revision));await post('work',{commandId:'cli-b',expectedRevision:(await f.store.load('mission'))!.revision,workId:'b',title:'Future responsibility',budget:0});const snapshot=await f.store.readState(),journal=await f.journal();await stop();await start();assert.notEqual(child!.pid,originalPid);assert.deepEqual(await (await fetch(base+'/read-state')).json(),snapshot);assert.equal((await post('organization',v1)).status,'replayed');assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.store.load('mission'))!.value.works[0],f.original.value.works[0]);validateMissionJournalLineage(journal);t.diagnostic(JSON.stringify({normalCliProcessesDistinct:true,actualStore:true,organizationPins:[1,2],originalRecordUnchanged:true,liveProviderCalls:0}));
});
