import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdtemp,rm,realpath} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createWorkbench} from '../src/server.ts';
import {createServer} from 'node:net';
import {spawn} from 'node:child_process';
import type {ChildProcess} from 'node:child_process';
import {verifyDisposableDatabase,verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';
import {ProductService} from '../src/product.ts';
import {SurrealStore,createHttpRpcTransport,initializeSurrealSchema} from '../src/storage.ts';
import {pinnedMemoryInput} from '../src/memory-input.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {apply,DomainError} from '../src/domain.ts';
import type {Mission,Command} from '../src/domain.ts';
import {growthStore,seedGrowth,growthJournal} from './support/growth-fixture.ts';

for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal owner Growth adopt/revert binds exact memories, keeps accepted Record pins, replays safely and survives fresh host`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-owner-growth-'));t.after(()=>rm(root,{recursive:true,force:true}));const {store,transport}=await growthStore(durable),f=await seedGrowth(store,'mission:growth',root);const original=(await store.load(f.id))!,old=structuredClone(original.value.works),oldInput=old.map(w=>pinnedMemoryInput(original.value,w));assert.ok(old[0]!.record);
 let server=createWorkbench(store,root),base='';async function start(){server.listen(0,'127.0.0.1');await once(server,'listening');const a=server.address();assert.ok(a&&typeof a==='object');base='http://127.0.0.1:'+a.port;}async function stop(){if(!server.listening)return;server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}await start();t.after(stop);const feed=(await store.readState(f.id)).feedId;
 const route='/missions/'+f.id+'/growth';const post=async(body:unknown,identity=feed)=>{const r=await fetch(base+route,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':identity},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 const adopt={...f.input(),commandId:'owner-adopt',expectedRevision:original.revision,action:'adopt'};
 for(const body of [{...adopt,action:'evaluate',baseline:9,candidate:10},{...adopt,baseline:1},{...adopt,candidate:undefined},{...adopt,scores:{baseline:1,candidate:2}},{...adopt,expectedRevision:0}])assert.equal((await post(body)).status,400);
 assert.equal((await post(adopt,'other-feed')).status,409);assert.deepEqual(await store.load(f.id),original);
 const result=await post(adopt);assert.equal(result.status,200);assert.equal(result.body.status,'committed');let snapshot=(await store.load(f.id))!;assert.equal(snapshot.value.growth[0]!.status,'adopted');assert.deepEqual(snapshot.value.works,old);assert.deepEqual(old.map(w=>pinnedMemoryInput(snapshot.value,w)),oldInput);
 const journal=await growthJournal(store);assert.equal((await post(adopt)).body.status,'replayed');assert.deepEqual(await growthJournal(store),journal);const conflict=await post({...adopt,candidate:'rounding@3'});assert.equal(conflict.status,409);assert.equal(conflict.body.reason,'idempotency');assert.equal((await post({...adopt,commandId:'old-cas'})).status,409);
 await f.product.admit(f.id,{commandId:'new-under-candidate',expectedRevision:snapshot.revision,workId:'future',title:'Future candidate Work',budget:0});snapshot=(await store.load(f.id))!;assert.deepEqual(snapshot.value.works.at(-1)!.appliedMemoryVersions,['other@1','rounding@2']);const candidateWork=structuredClone(snapshot.value.works.at(-1)!),candidateInput=pinnedMemoryInput(snapshot.value,candidateWork);
 const revert={...f.input(),commandId:'owner-revert',expectedRevision:snapshot.revision,action:'revert'};assert.equal((await post(revert)).body.status,'committed');snapshot=(await store.load(f.id))!;assert.deepEqual(snapshot.value.works.slice(0,old.length),old);assert.deepEqual(snapshot.value.works.at(-1),candidateWork);assert.equal(snapshot.value.growth[0]!.status,'reverted');await f.product.admit(f.id,{commandId:'new-after-revert',expectedRevision:snapshot.revision,workId:'after-revert',title:'Future baseline Work',budget:0});snapshot=(await store.load(f.id))!;assert.deepEqual(snapshot.value.works.at(-1)!.appliedMemoryVersions,['rounding@1','other@1']);assert.deepEqual(snapshot.value.works.slice(0,old.length),old);
 const final=await growthJournal(store);const events=await store.readEvents(0,1000),state=await store.readState(f.id);await stop();const fresh=transport?new SurrealStore<Mission>(transport):store;server=createWorkbench(fresh,root);await start();assert.deepEqual(await (await fetch(base+'/missions/'+f.id)).json(),snapshot);assert.deepEqual(await fresh.readEvents(0,1000),events);assert.deepEqual(await fresh.readState(f.id),state);assert.equal((await post(revert)).body.status,'replayed');assert.deepEqual(await growthJournal(fresh),final);assert.deepEqual(pinnedMemoryInput(snapshot.value,candidateWork),candidateInput);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} Growth guards preserve independent evaluation, improvement, stale baseline, exact references and superseded adoption`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async()=>{
 const {store}=await growthStore(durable),f=await seedGrowth(store),original=(await store.load(f.id))!,proposal=original.value.growth[0]!;const input={...f.input(),commandId:'denied',expectedRevision:original.revision};
 for(const bad of [{...input,baseline:'rounding@2'},{...input,candidate:'rounding@9'}])await assert.rejects(f.product.adoptGrowth(f.id,bad),/versions mismatch/);assert.deepEqual(await store.load(f.id),original);
 const command:Command={type:'adopt-growth',growthId:'g',baseline:'rounding@1',candidate:'rounding@2'};assert.throws(()=>apply(original.value,command,{id:'representative',roles:['representative']}),e=>e instanceof DomainError&&e.code==='denied');
 const unevaluated=structuredClone(original.value);unevaluated.growth[0]!.status='proposed';delete unevaluated.growth[0]!.scores;delete unevaluated.growth[0]!.evaluator;assert.throws(()=>apply(unevaluated,command,{id:'local-owner',roles:['owner']}),/improvement/);assert.throws(()=>apply(unevaluated,{type:'evaluate-growth',growthId:'g',baseline:1,candidate:2,heldOut:'fixture'},{id:proposal.proposer,roles:['evaluator']}),/Independent/);
 // Commit a real nonimproving fixture, not a forged successful evaluation through the owner API.
 await f.send({type:'save-memory',memory:{id:'rounding',version:3,scope:original.value.scope,authority:'learned',content:'Nonimproving fixture',source:'fixture',effective:false}},'representative');await f.send({type:'propose-growth',proposal:{id:'no-improvement',proposer:'representative',target:'memory',baseline:'rounding@1',candidate:'rounding@3',counterevidence:'Known nonimproving fixture',status:'proposed'}},'representative');await f.send({type:'evaluate-growth',growthId:'no-improvement',baseline:2,candidate:2,heldOut:'Equal controlled fixture scores'},'growth-evaluator');let before=(await store.load(f.id))!;await assert.rejects(f.product.adoptGrowth(f.id,{commandId:'no-improvement',expectedRevision:before.revision,growthId:'no-improvement',baseline:'rounding@1',candidate:'rounding@3'}),/improvement/);assert.deepEqual(await store.load(f.id),before);
 await f.product.saveMemory(f.id,{commandId:'supersede-baseline',expectedRevision:before.revision,memory:{id:'rounding',version:4,content:'New explicit current instruction',source:'Owner fixture'}});before=(await store.load(f.id))!;await assert.rejects(f.product.adoptGrowth(f.id,{...input,commandId:'stale-baseline',expectedRevision:before.revision}),/baseline/);assert.deepEqual(await store.load(f.id),before);
 const superseded=await seedGrowth(store,'mission:superseded');let current=(await store.load(superseded.id))!;await superseded.product.adoptGrowth(superseded.id,{...superseded.input(),commandId:'adopt-superseded',expectedRevision:current.revision});current=(await store.load(superseded.id))!;await superseded.product.saveMemory(superseded.id,{commandId:'replace-adoption',expectedRevision:current.revision,memory:{id:'rounding',version:3,content:'Later owner instruction',source:'Owner fixture'}});current=(await store.load(superseded.id))!;const unchanged=await growthJournal(store);await assert.rejects(superseded.product.revertGrowth(superseded.id,{...superseded.input(),commandId:'reject-superseded',expectedRevision:current.revision}),/superseded/);assert.deepEqual(await store.load(superseded.id),current);assert.deepEqual(await growthJournal(store),unchanged);
 const adopted=apply(original.value,command,{id:'local-owner',roles:['owner']}).value;adopted.memories.find(m=>m.id==='rounding'&&m.version===2)!.effective=false;assert.throws(()=>apply(adopted,{type:'revert-growth',growthId:'g',baseline:'rounding@1',candidate:'rounding@2'},{id:'local-owner',roles:['owner']}),/superseded/);
});

for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} portable lineage accepts legacy and exact-reference Growth commands`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async()=>{
 const {store}=await growthStore(durable),f=await seedGrowth(store);await f.send({type:'adopt-growth',growthId:'g'});await f.send({type:'revert-growth',growthId:'g'});validateMissionJournalLineage(await growthJournal(store));
 await f.send({type:'propose-growth',proposal:{id:'g2',proposer:'representative',target:'memory',baseline:'rounding@1',candidate:'rounding@2',counterevidence:'Second exact proposal',status:'proposed'}},'representative');await f.send({type:'evaluate-growth',growthId:'g2',baseline:1,candidate:2,heldOut:'Credential-free lineage fixture evaluation'},'growth-evaluator');let revision=(await store.load(f.id))!.revision;await f.product.adoptGrowth(f.id,{commandId:'exact-lineage-adopt',expectedRevision:revision,growthId:'g2',baseline:'rounding@1',candidate:'rounding@2'});validateMissionJournalLineage(await growthJournal(store));revision=(await store.load(f.id))!.revision;await f.product.revertGrowth(f.id,{commandId:'exact-lineage-revert',expectedRevision:revision,growthId:'g2',baseline:'rounding@1',candidate:'rounding@2'});validateMissionJournalLineage(await growthJournal(store));
});

test('owned actual DB process restart and fresh HTTP retain exact Growth receipts, effective memory and old/new pins',{skip:!process.env.SURREAL_TEST_RUNTIME||process.platform!=='linux'},async t=>{
 await verifyDisposableDatabase();const root=await realpath(await mkdtemp(join(tmpdir(),'massion-owned-growth-db-'))),binary=await realpath(process.env.MASSION_TEST_SURREAL_BINARY!);const listener=createServer();listener.listen(0,'127.0.0.1');await once(listener,'listening');const address=listener.address();assert.ok(address&&typeof address==='object');const port=address.port;await new Promise<void>(r=>listener.close(()=>r()));
 const argv=[binary,'start','surrealkv://'+join(root,'data'),'--bind','127.0.0.1:'+port,'--unauthenticated','--no-banner','--log','error','--default-namespace','growth','--default-database','growth','--deny-net','--deny-scripting'];let child:ChildProcess;const children:ChildProcess[]=[];let server:ReturnType<typeof createWorkbench>|undefined;
 t.after(async()=>{if(server?.listening){server.closeAllConnections();await new Promise<void>(r=>server!.close(()=>r()));}for(const owned of children)await stopOwnedChild(owned,{cwd:root,argv});await rm(root,{recursive:true,force:true});});
 async function start(){child=spawn(binary,argv.slice(1),{cwd:root,env:{PATH:'/usr/bin:/bin'},stdio:'ignore'});children.push(child);await once(child,'spawn');await verifyOwnedChild(child,{cwd:root,argv});const end=Date.now()+10000;while(true){assert.equal(child.exitCode,null);try{if((await fetch('http://127.0.0.1:'+port+'/ready')).ok)break;}catch{}assert.ok(Date.now()<end);await new Promise(r=>setTimeout(r,20));}}
 await start();const originalPid=child!.pid,transport=createHttpRpcTransport({endpoint:'http://127.0.0.1:'+port+'/rpc',namespace:'growth',database:'growth'});await initializeSurrealSchema(transport);const store=new SurrealStore<Mission>(transport),f=await seedGrowth(store),original=(await store.load(f.id))!,old=structuredClone(original.value.works);const request={...f.input(),commandId:'restart-adopt',expectedRevision:original.revision};await f.product.adoptGrowth(f.id,request);let current=(await store.load(f.id))!;await f.product.admit(f.id,{commandId:'restart-future',expectedRevision:current.revision,workId:'future',title:'Future candidate',budget:0});const before=(await store.load(f.id))!,journal=await store.exportJournal(),events=await store.readEvents(0,1000),state=await store.readState(f.id);validateMissionJournalLineage(journal.operations);
 await stopOwnedChild(child!,{cwd:root,argv});await start();assert.notEqual(child!.pid,originalPid);const fresh=new SurrealStore<Mission>(transport);assert.deepEqual(await fresh.load(f.id),before);assert.deepEqual(await fresh.exportJournal(),journal);assert.deepEqual(await fresh.readEvents(0,1000),events);assert.deepEqual(await fresh.readState(f.id),state);
 server=createWorkbench(fresh,root);server.listen(0,'127.0.0.1');await once(server,'listening');const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port;const post=async(body:unknown)=>{const r=await fetch(base+'/missions/'+f.id+'/growth',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':state.feedId},body:JSON.stringify(body)});return r.json();};assert.deepEqual(await (await fetch(base+'/missions/'+f.id)).json(),before);assert.equal((await post({...request,action:'adopt'})).status,'replayed');assert.deepEqual(await fresh.exportJournal(),journal);assert.deepEqual(before.value.works.slice(0,old.length),old);assert.deepEqual(before.value.works.at(-1)!.appliedMemoryVersions,['other@1','rounding@2']);const revert={...request,commandId:'restart-revert',expectedRevision:before.revision,action:'revert'};assert.equal((await post(revert)).status,'committed');current=(await fresh.load(f.id))!;await new ProductService(fresh).admit(f.id,{commandId:'post-restart-revert-work',expectedRevision:current.revision,workId:'baseline-work',title:'New baseline Work',budget:0});current=(await fresh.load(f.id))!;assert.deepEqual(current.value.works.slice(0,old.length),old);assert.deepEqual(current.value.works.at(-1)!.appliedMemoryVersions,['rounding@1','other@1']);validateMissionJournalLineage((await fresh.exportJournal()).operations);
 t.diagnostic(JSON.stringify({originalOwnedDbPid:originalPid,restartedOwnedDbPid:child!.pid,actualDbProcessRestart:true,freshHttpHost:true,snapshotEventsFeedJournalEqual:true,oldInputRetained:true,exactReplayNoMutation:true,providerCalls:0}));
});
test('actual DB duplicate exact owner adoption admits one atomic command and retains changed-reference identity conflicts',{skip:!process.env.SURREAL_TEST_RUNTIME},async()=>{
 const {store}=await growthStore(true),f=await seedGrowth(store),revision=(await store.load(f.id))!.revision,input={...f.input(),commandId:'simultaneous-adopt',expectedRevision:revision};const outcomes=await Promise.allSettled([f.product.adoptGrowth(f.id,input),f.product.adoptGrowth(f.id,input)]);assert.ok(outcomes.some(r=>r.status==='fulfilled'&&r.value.status==='committed'));for(const outcome of outcomes)if(outcome.status==='fulfilled')assert.ok(['committed','replayed'].includes(outcome.value.status));else assert.match(String(outcome.reason),/rejected|rollback|conflict|transaction/i);const snapshot=(await store.load(f.id))!,journal=await growthJournal(store);assert.equal(snapshot.revision,revision+1);assert.equal(journal.filter(o=>o.commandId===input.commandId).length,1);assert.equal((await f.product.adoptGrowth(f.id,input)).status,'replayed');const changed=await f.product.adoptGrowth(f.id,{...input,candidate:'rounding@3'});assert.equal(changed.status,'conflict');assert.deepEqual(await growthJournal(store),journal);validateMissionJournalLineage(journal);
});
