import test from 'node:test';
import type {TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createWorkbench} from '../src/server.ts';
import {ProductService} from '../src/product.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {harness,reply,selectionField} from './support/workbench-client.ts';
async function setup(t:TestContext,durable=false){
 const {store}=await growthStore(durable),f=await textFixture(t,store),server=createWorkbench(store,f.root,{artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port;
 let mode='',held=false,release!:()=>void;
 const app=harness(async(path,options)=>{const response=await fetch(base+path,options),body=await response.json();if(mode==='loss'&&path==='/missions/mission/work'&&options.method==='POST'){mode='hold-events';throw Error('Supporting lost actual committed response');}if(mode==='hold-events'&&path.startsWith('/events?')){held=true;await new Promise<void>(r=>release=r);}if(mode==='feed-change'&&path.startsWith('/read-state?'))body.feedId='supporting-replaced-feed';if(path.includes('/record-artifact?')){if(mode==='hold'){held=true;await new Promise<void>(r=>release=r);}if(mode==='bad-hash')body.content='Wrong received bytes';if(mode==='failure')return reply({error:'Labeled supporting read failure'},503);}return reply(body,response.status);},{},undefined,{network:true,fragment:'#mission=mission',identity:'text-reader-'+crypto.randomUUID()});
 async function until(check:()=>boolean){const deadline=Date.now()+10000;while(!check()){assert.ok(Date.now()<deadline,'Accepted-text client deadline');await new Promise(r=>setTimeout(r,5));}}
 await until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('mission-id').disabled);
 const node=(part:string)=>selectionField(app,'work-record-text-'+part+'-work');
 return {...f,app,node,until,journal:()=>growthJournal(store),mode(value:string){mode=value;held=false;},held:()=>held,release(){mode='';release();}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} exact text panel deliberately reads literal hostile Unicode content and independently preserves drafts/history`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),journal=await f.journal();f.app.node('work-title').value='Keep owner draft';f.node('read').focus();assert.equal(f.app.calls.some(c=>c.path.includes('/record-artifact?')),false);await f.node('read').fire('click');assert.equal(f.node('content').textContent,await f.artifacts.read(f.artifact));assert.equal(f.app.all().some(n=>n.tagName==='IMG'),false);assert.match(f.node('status').textContent,/verified|Verified/);assert.equal(f.app.node('work-title').value,'Keep owner draft');assert.deepEqual(await f.journal(),journal);assert.equal(f.app.calls.filter(c=>c.options.method==='POST').length,0);assert.equal((f.app.context as any).document.activeElement.id,f.node('read').id);
});
test('same-Mission supporting feed replacement invalidates held text response and requires a deliberate new context',async t=>{
 const f=await setup(t);f.mode('hold');const pending=f.node('read').fire('click');await f.until(f.held);f.mode('feed-change');await f.app.submit('load-form');await f.until(()=>f.app.node('snapshot-json').textContent==='');f.release();await pending;assert.equal(f.node('content'),undefined);assert.match(f.app.node('status').textContent,/Database or connection changed/);
});
test('actual committed response loss marker survives accepted text read while durable receipt delivery is held, with no write replay',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,true);f.app.node('work-title').value='Actual response loss fixture';f.mode('loss');const write=f.app.node('work-form').fire('submit');await f.until(f.held);const marker=f.app.storage.get('massion.workbench.pending');assert.ok(marker);const journal=await f.journal();assert.equal(f.node('read').disabled,false);await f.node('read').fire('click');assert.match(f.node('content').textContent,/한글/);assert.equal(f.app.storage.get('massion.workbench.pending'),marker);assert.deepEqual(await f.journal(),journal);assert.equal(f.app.calls.filter(c=>c.options.method==='POST').length,1);f.release();await write;assert.equal(f.app.storage.has('massion.workbench.pending'),false);assert.deepEqual(await f.journal(),journal);
});
test('held text read suppresses duplicate, preserves moved focus, cancels ignored-abort late reply and deliberately retries',async t=>{
 const f=await setup(t),journal=await f.journal();f.mode('hold');f.node('read').focus();const pending=f.node('read').fire('click');await f.until(f.held);assert.equal(f.node('read').disabled,true);await f.node('read').fire('click');assert.equal(f.app.calls.filter(c=>c.path.includes('/record-artifact?')).length,1);f.app.node('work-title').focus();await f.node('cancel').fire('click');f.release();await pending;assert.equal(f.node('content').textContent,'');assert.match(f.node('status').textContent,/canceled/);assert.equal((f.app.context as any).document.activeElement.id,'work-title');await f.node('read').fire('click');assert.match(f.node('content').textContent,/한글/);assert.equal((f.app.context as any).document.activeElement.id,'work-title');assert.deepEqual(await f.journal(),journal);
});
test('received hash mismatch and unavailable read display no text and require deliberate retry',async t=>{
 const f=await setup(t);for(const mode of ['bad-hash','failure']){f.mode(mode);await f.node('read').fire('click');assert.equal(f.node('content').textContent,'');assert.match(f.node('status').textContent,/Read not verified/);assert.equal(f.node('read').disabled,false);}assert.equal(f.app.calls.filter(c=>c.path.includes('/record-artifact?')).length,2);f.mode('');await f.node('read').fire('click');assert.match(f.node('content').textContent,/Exact accepted/);
});
test('held accepted text reply after Mission switch is discarded without changing new context or owner draft',async t=>{
 const f=await setup(t),product=new ProductService(f.store);await product.create({id:'other',purpose:'Other Mission',scope:'local',constraints:[],criteria:{version:1,description:'No old text',oracle:'manual/v1'}},'other-create');const journal=await f.journal();f.app.node('work-title').value='Original text draft';f.mode('hold');const pending=f.node('read').fire('click');await f.until(f.held);await f.app.navigateFragment('#mission=other');await f.until(()=>f.app.node('loaded-id').textContent==='other'&&!f.app.node('mission-id').disabled);f.release();await pending;assert.equal(f.app.node('loaded-id').textContent,'other');assert.equal(f.app.all().some(n=>n.id==='work-record-text-content-work'&&n.textContent.includes('Exact accepted')),false);await f.app.navigateFragment('#mission=mission');await f.until(()=>f.app.node('loaded-id').textContent==='mission'&&!f.app.node('mission-id').disabled);assert.equal(f.node('content').textContent,'');assert.equal(f.app.node('work-title').value,'Original text draft');assert.deepEqual(await f.journal(),journal);
});
