import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {fileURLToPath} from 'node:url';
import {Application} from '../src/application.ts';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {apply,documentContentHash,validateDocumentHistory,DOCUMENT_CONTENT_BYTES} from '../src/domain.ts';
import type {Mission} from '../src/domain.ts';
import type {Store} from '../src/storage.ts';
import {SurrealStore} from '../src/storage.ts';
import {SurrealRelationImpact} from '../src/relation-impact.ts';
import {readDocument,searchDocuments} from '../src/documents.ts';
import {validateMissionLineage,validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {exportPortableBackup,restorePortableBackup} from '../src/portable-backup.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {stopOwnedChild} from './support/owned-process.ts';
const doc=(version=1,content='Original approved fixture α <img src=x>\nneedle [literal] evidence')=>({id:'document:source',version,title:'Original source title',content,source:'Owner pasted local fixture source, section 2'});
const input=(revision:number,version=1,commandId='capture-'+version,content?:string)=>({commandId,expectedRevision:revision,document:doc(version,content)});
async function fixture(t:import('node:test').TestContext,durable=false,cli=false){const {store,transport}=await growthStore(durable),f=await textFixture(t,store,cli),product=new ProductService(store);return {...f,transport,product,original:(await store.load('mission'))!,journal:()=>growthJournal(store)};}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal document capture/search/exact read preserves v1 source and original native relation impact through v2 and inert restore`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),server=createWorkbench(f.store,f.root,{...(f.transport?{knowledge:new SurrealRelationImpact(f.transport)}:{})});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port,feed=(await f.store.readState()).feedId;
 const post=async(route:string,body:unknown,identity=feed)=>{const r=await fetch(base+'/missions/mission/'+route,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':identity},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};const get=async(path:string)=>{const r=await fetch(base+'/missions/mission/'+path,{headers:{'X-Massion-Feed':feed}});return {status:r.status,body:await r.json()};};
 const v1=input(f.original.revision);assert.equal((await post('documents',v1)).body.status,'committed');let current=(await f.store.load('mission'))!;const originalDoc=structuredClone(current.value.documents![0]!);assert.equal(originalDoc.actorId,'local-owner');assert.equal(originalDoc.contentSha256,documentContentHash(v1.document.content));const query='[literal]',search=await get('documents?query='+encodeURIComponent(query));assert.equal(search.status,200);assert.equal(search.body.matches[0].version,1);assert.ok(search.body.matches[0].excerpt.includes(query));const exactPath='document?id=document:source&version=1&sha256='+originalDoc.contentSha256;assert.deepEqual((await get(exactPath)).body.document,originalDoc);
 await post('relations',{commandId:'source-relation',expectedRevision:current.revision,relation:{from:'record:fixture',fromVersion:1,to:originalDoc.id,toVersion:1,type:'evidenced-by',provenance:'Owner compared original pasted source v1'}});current=(await f.store.load('mission'))!;await f.product.create({id:'other',purpose:'Separate corpus',scope:'other',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'other-create');assert.equal((await searchDocuments(f.store,'other',{query} ))!.totalMatches,0);
 const impact=f.transport?await (await fetch(base+'/missions/mission/impact?entity=document:source&version=1')).json():undefined;await post('documents',input(current.revision,2,'capture-2','Replacement approved fixture, v2 only'));current=(await f.store.load('mission'))!;assert.equal((await get('documents?query='+encodeURIComponent(query))).body.totalMatches,0);assert.equal((await get('documents?query=Replacement')).body.matches[0].version,2);assert.deepEqual((await get(exactPath)).body.document,originalDoc);assert.equal((await get('document?id=document:source&version=1&sha256='+'0'.repeat(64))).status,409);assert.equal((await get('document?id=document:source&version=3&sha256='+originalDoc.contentSha256)).status,404);assert.deepEqual(current.value.works,f.original.value.works);assert.deepEqual(current.value.documents![0],originalDoc);
 const journal=await f.journal();validateMissionJournalLineage(journal);for(const path of ['documents?query=needle&query=other','documents?query=needle&path=/etc/passwd','document?id=document:source&version=1&sha256='+originalDoc.contentSha256+'&version=2','documents?query='])assert.equal((await get(path)).status,400);assert.equal((await post('documents',v1)).body.status,'replayed');assert.equal((await post('documents',{...v1,document:{...v1.document,source:'changed'}})).status,409);assert.equal((await post('documents',input(current.revision,3),'wrong-feed')).status,409);assert.deepEqual(await f.journal(),journal);
 if(f.transport){const latest=(await new SurrealRelationImpact(f.transport).readImpact('mission',originalDoc.id,1))!;assert.deepEqual(latest.relations,impact.relations);assert.deepEqual(latest.affected,['record:fixture@1']);assert.ok(f.store instanceof SurrealStore);const exported=await f.store.exportJournal(),backup=await exportPortableBackup(f.store,f.artifacts),{store:restored,transport}=await growthStore(true);assert.ok(restored instanceof SurrealStore&&transport);await restorePortableBackup(backup,restored,join(f.root,'restored'));assert.deepEqual(await restored.load('mission'),current);assert.deepEqual(await restored.exportJournal(),exported);assert.deepEqual((await readDocument(restored,'mission',{id:originalDoc.id,version:1,contentSha256:originalDoc.contentSha256}))!.document,originalDoc);assert.deepEqual((await new SurrealRelationImpact(transport).readImpact('mission',originalDoc.id,1))!.relations,impact.relations);t.diagnostic(JSON.stringify({normalApi:true,nativeImpact:true,originalDocumentAndRecordPreserved:true,portableRestored:true,liveCalls:0}));}
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} document strict owner/fields/UTF8/version admission rejects forgeries and concurrent CAS/duplicates atomically`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),v=input(f.original.revision),before=await f.journal();for(const forged of [{...v,actorId:'caller'},{...v,path:'/etc/passwd'},...['actorId','contentSha256','verified','mimeType','url'].map(k=>({...v,document:{...v.document,[k]:'forged'}})),...['id','title','content','source'].flatMap(key=>['',String.fromCharCode(0xd800)].map(value=>({...v,document:{...v.document,[key]:value}}))),{...v,document:{...v.document,id:'file:///etc/passwd'}},{...v,document:{...v.document,title:'x'.repeat(201)}},{...v,document:{...v.document,source:'x'.repeat(2001)}},{...v,document:{...v.document,content:'한'.repeat(6000)}},...[-1,0,1.5,2,Infinity,Number.MAX_SAFE_INTEGER+1].map(version=>({...v,document:{...v.document,version}}))])await assert.rejects(f.product.captureDocument('mission',forged as typeof v));const app=new Application(f.store,[{id:'rep',roles:['representative']}]);await assert.rejects(app.dispatch({missionId:'mission',commandId:'denied',expectedRevision:v.expectedRevision,actorId:'rep',command:{type:'capture-document',document:v.document}}),/role/);assert.deepEqual(await f.journal(),before);
 const same=await Promise.all([f.product.captureDocument('mission',v),f.product.captureDocument('mission',v)]);assert.deepEqual(same.map(r=>r.status).sort(),['committed','replayed']);const next=input((await f.store.load('mission'))!.revision,2);const race=await Promise.all([f.product.captureDocument('mission',next),f.product.captureDocument('mission',{...next,commandId:'other',document:{...next.document,content:'Other CAS'}})]);assert.deepEqual(race.map(r=>r.status).sort(),['committed','conflict']);assert.equal((await f.journal()).length,before.length+2);validateMissionJournalLineage(await f.journal());
});
test('document bounds and portable integrity reject oversized history, hash/author/version corruption without original mutation',async t=>{
 const f=await fixture(t);const owner={id:'owner',roles:['owner' as const]},m=apply(f.original.value,{type:'capture-document',document:doc()},owner).value;for(const mutate of [(d:any)=>d.content='Changed',(d:any)=>d.version=2,(d:any)=>d.actorId='',(d:any)=>d.extra=true]){const copy=structuredClone(m);mutate(copy.documents![0]);assert.throws(()=>validateMissionLineage(copy));}await f.product.captureDocument('mission',input(f.original.revision));const journal=structuredClone(await f.journal());journal.at(-1)!.value.documents![0]!.title='Rewritten retained title';assert.throws(()=>validateMissionJournalLineage(journal),/transition/);const before=structuredClone(m);m.documents=Array.from({length:100},(_,i)=>({...doc(i+1),contentSha256:documentContentHash(doc().content),actorId:'owner'}));assert.throws(()=>apply(m,{type:'capture-document',document:doc(101)},owner),/bound/);assert.equal(m.documents.length,100);const content='x'.repeat(DOCUMENT_CONTENT_BYTES);m.documents=Array.from({length:64},(_,i)=>({...doc(i+1,content),contentSha256:documentContentHash(content),actorId:'owner'}));validateDocumentHistory(m.documents);assert.throws(()=>apply(m,{type:'capture-document',document:doc(65)},owner),/total UTF-8/);assert.equal(before.documents![0]!.content,doc().content);
});
test('literal latest-version search returns explicit bounded hits; invalid/corrupt history never yields substituted content',async t=>{
 const f=await fixture(t);for(let n=0;n<21;n++)await f.product.captureDocument('mission',{commandId:'many-'+n,expectedRevision:(await f.store.load('mission'))!.revision,document:{...doc(),id:'document:n'+n}});const before=await f.journal(),hits=(await searchDocuments(f.store,'mission',{query:'[literal]'}))!;assert.equal(hits.totalMatches,21);assert.equal(hits.limit,20);assert.equal(hits.matches.length,20);assert.equal((await searchDocuments(f.store,'mission',{query:'[Literal]'}))!.totalMatches,0);assert.equal((await searchDocuments(f.store,'mission',{query:'.*'}))!.totalMatches,0);for(const query of ['',' ', 'x'.repeat(201),String.fromCharCode(0xd800)])await assert.rejects(searchDocuments(f.store,'mission',{query}));await assert.rejects(searchDocuments(f.store,'mission',{query:'needle',feedId:'wrong'}));const state=await f.store.readState('mission'),bad=structuredClone(state);bad.snapshot!.value.documents![0]!.content='Tampered';await assert.rejects(searchDocuments({readState:async()=>bad} as Store<Mission>,'mission',{query:'needle'}),/integrity/);await assert.rejects(readDocument({readState:async()=>bad} as Store<Mission>,'mission',{id:'document:n0',version:1,contentSha256:hits.matches[0]!.contentSha256}),/integrity/);assert.deepEqual(await f.journal(),before);
});
test('actual SurrealDB owner document freezes caller before async admission; ambiguous committed response retains original exact content',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,true);let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>release=r),started=new Promise<void>(r=>ready=r);let first=true;const proxy=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='lookupOperation')return async(...args:unknown[])=>{if(first){first=false;ready();await held;}return fn.apply(target,args);};return typeof fn==='function'?fn.bind(target):fn;}}) as Store<Mission>;const original=input(f.original.revision),submitted=structuredClone(original),pending=new ProductService(proxy).captureDocument('mission',submitted);await started;submitted.document.version=7;submitted.document.content='Later private edit';release();assert.equal((await pending).status,'committed');assert.equal((await f.store.load('mission'))!.value.documents![0]!.content,original.document.content);
 let lost=true;const lossy=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='commit')return async(...args:unknown[])=>{const result=await fn.apply(target,args);if(lost){lost=false;throw Error('Injected commit response loss');}return result;};return typeof fn==='function'?fn.bind(target):fn;}}) as Store<Mission>;const v2=input((await f.store.load('mission'))!.revision,2);await assert.rejects(new ProductService(lossy).captureDocument('mission',v2),/response loss/);const journal=await f.journal();assert.equal((await f.product.captureDocument('mission',v2)).status,'replayed');assert.deepEqual(await f.journal(),journal);validateMissionJournalLineage(journal);
});
test('actual SurrealDB normal CLI document exact v1 and latest search survive owned host restart with unchanged original accepted Record',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 let child:ReturnType<typeof spawn>|undefined,cwd='',log='';const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry];async function stop(){if(child)await stopOwnedChild(child,{cwd,argv});}t.after(stop);const f=await fixture(t,true,true);assert.ok(f.transport);cwd=f.root;const database=(await f.transport.query('RETURN $session.db;',{}))[0] as string,probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const a=probe.address();assert.ok(a&&typeof a==='object');const port=a.port;await new Promise<void>(r=>probe.close(()=>r()));const base='http://127.0.0.1:'+port,feed=(await f.store.readState()).feedId;
 async function start(){child=spawn(process.execPath,[entry],{cwd,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',b=>log+=b);child.stderr!.on('data',b=>log+=b);const deadline=Date.now()+10000;while(true){try{if((await fetch(base+'/health')).ok)return;}catch{}assert.ok(child.exitCode===null&&Date.now()<deadline,log);await new Promise(r=>setTimeout(r,10));}}
 const v1=input(f.original.revision);async function post(body:unknown){const r=await fetch(base+'/missions/mission/documents',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':feed},body:JSON.stringify(body)});assert.equal(r.ok,true);return r.json();}await start();const pid=child!.pid;await post(v1);await post(input((await f.store.load('mission'))!.revision,2,'cli-v2','Later CLI local source'));const exact='/missions/mission/document?id=document:source&version=1&sha256='+documentContentHash(v1.document.content),read=await (await fetch(base+exact)).json(),search=await (await fetch(base+'/missions/mission/documents?query=Later')).json(),journal=await f.journal();await stop();await start();assert.notEqual(child!.pid,pid);assert.deepEqual(await (await fetch(base+exact)).json(),read);assert.deepEqual(await (await fetch(base+'/missions/mission/documents?query=Later')).json(),search);assert.equal((await post(v1)).status,'replayed');assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.store.load('mission'))!.value.works,f.original.value.works);t.diagnostic(JSON.stringify({actualNormalCliDistinctProcesses:true,exactV1Retained:true,latestSearchV2:true,oldRecordUnchanged:true,liveCalls:0}));
});
