import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {fileURLToPath} from 'node:url';
import {Application} from '../src/application.ts';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {apply,affectedBy,hash} from '../src/domain.ts';
import type {Mission,Relation} from '../src/domain.ts';
import type {Store} from '../src/storage.ts';
import {SurrealStore} from '../src/storage.ts';
import {SurrealRelationImpact} from '../src/relation-impact.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {exportPortableBackup,restorePortableBackup,openRestoredArtifacts} from '../src/portable-backup.ts';
import {readRecordArtifact} from '../src/record-artifact.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {stopOwnedChild} from './support/owned-process.ts';
const edge=(from='report',to='file:α/"original"',type:Relation['type']='evidenced-by'):Omit<Relation,'inferred'>=>({from,to,type,fromVersion:2,toVersion:3,provenance:'Original owner source <img src=x>\nDocument v3, section 2'});
const input=(revision:number,commandId='relation-1',relation=edge())=>({commandId,expectedRevision:revision,relation});
async function fixture(t:import('node:test').TestContext,durable=false,cli=false){const {store,transport}=await growthStore(durable),f=await textFixture(t,store,cli),product=new ProductService(store);return {...f,transport,product,original:(await store.load('mission'))!,journal:()=>growthJournal(store)};}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal owner relation API preserves mixed exact graph, original Work and isolated Mission; native impact and portable restore`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),legacy=new Application(f.store,[{id:'fixture-rep',roles:['representative']}]);const inferred={...edge('existing'),inferred:true};for(let i=0;i<2;i++)await legacy.dispatch({missionId:'mission',commandId:'legacy-'+i,expectedRevision:(await f.store.load('mission'))!.revision,actorId:'fixture-rep',command:{type:'relate',relation:inferred}});
 await f.product.create({id:'other',purpose:'Separate knowledge',scope:'other',constraints:[],criteria:{version:1,description:'Other criteria',oracle:'manual-review/v1'}},'other-create');const other=await f.store.load('other'),before=await f.journal();
 const server=createWorkbench(f.store,f.root,{...(f.transport?{knowledge:new SurrealRelationImpact(f.transport)}:{})});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port,feed=(await f.store.readState()).feedId;
 const post=async(body:unknown,identity=feed)=>{const r=await fetch(base+'/missions/mission/relations',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':identity},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 const submitted=input((await f.store.load('mission'))!.revision);assert.equal((await post(submitted)).body.status,'committed');let current=(await f.store.load('mission'))!;assert.deepEqual(current.value.relations,[inferred,inferred,{...submitted.relation,inferred:false}]);
 for(const [n,type] of ['depends-on','contains'].entries()){const r=edge('dependent-'+n,'report',type as Relation['type']);r.toVersion=2;await post(input(current.revision,'chain-'+n,r));current=(await f.store.load('mission'))!;}
 const wrong=edge('wrong-version');wrong.toVersion=4;await post(input(current.revision,'wrong-version',wrong));current=(await f.store.load('mission'))!;
 assert.deepEqual(current.value.works,f.original.value.works);assert.deepEqual(await f.store.load('other'),other);const journal=await f.journal();assert.deepEqual(journal.slice(0,before.length),before);validateMissionJournalLineage(journal);assert.equal((await post(submitted)).body.status,'replayed');assert.equal((await post({...submitted,relation:{...submitted.relation,provenance:'Changed'}})).status,409);assert.equal((await post(input(current.revision,'wrong-feed'),'wrong')).status,409);assert.deepEqual(await f.journal(),journal);
 if(f.transport){const r=await fetch(base+'/missions/mission/impact?entity='+encodeURIComponent(submitted.relation.to)+'&version=3'),impact=await r.json();assert.equal(r.status,200);assert.deepEqual(impact.affected,affectedBy(current.value,submitted.relation.to,3));assert.equal(impact.relations.length,5);assert.equal(impact.relations.filter((r:Relation)=>r.inferred).length,2);assert.ok(impact.relations.some((r:Relation)=>r.provenance===submitted.relation.provenance&&!r.inferred));assert.ok(!impact.affected.includes('wrong-version@2'));assert.deepEqual(await f.journal(),journal);
 assert.ok(f.store instanceof SurrealStore);const originalJournal=await f.store.exportJournal(),backup=await exportPortableBackup(f.store,f.artifacts),{store:restored,transport}=await growthStore(true);assert.ok(restored instanceof SurrealStore&&transport);const root=join(f.root,'restored');await restorePortableBackup(backup,restored,root);assert.deepEqual(await restored.load('mission'),current);assert.deepEqual(await restored.exportJournal(),originalJournal);const reread=(await new SurrealRelationImpact(transport).readImpact('mission',submitted.relation.to,3))!;assert.deepEqual(reread.relations,impact.relations);assert.deepEqual(reread.affected,impact.affected);const work=current.value.works[0]!;assert.equal((await readRecordArtifact(restored,openRestoredArtifacts(backup,root),'mission',work.id,{recordId:work.record!.id,artifactVersion:work.artifact!.version,artifactSha256:work.artifact!.sha256}))!.content,'Exact accepted fixture <img src=x onerror=alert(1)>\n한글 🌙\n');
 t.diagnostic(JSON.stringify({nativeImpact:true,portableRestored:true,originalWorkRecord:true,exactVersions:true,inferredAndDuplicatePreserved:true,liveCalls:0}));}
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} owner relations reject inferred/grants/extra fields, invalid text/type/versions and non-owner; CAS duplicates remain atomic`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),v=input(f.original.revision),before=await f.journal();for(const forged of [{...v,actorId:'chosen'},{...v,command:{type:'relate'}},{...v,relation:{...v.relation,inferred:true}},{...v,relation:{...v.relation,verified:true}},...['from','to','provenance'].flatMap(key=>['',' '.repeat(2),'x'.repeat(2001),String.fromCharCode(0xd800)].map(value=>({...v,relation:{...v.relation,[key]:value}}))),...[-1,0,1.5,Infinity,Number.MAX_SAFE_INTEGER+1].flatMap(version=>['fromVersion','toVersion'].map(key=>({...v,relation:{...v.relation,[key]:version}}))),{...v,relation:{...v.relation,type:'invalidates'}},{...v,relation:null}])await assert.rejects(f.product.recordRelation('mission',forged as typeof v));
 const unauthorized=new Application(f.store,[{id:'rep',roles:['representative']}]);await assert.rejects(unauthorized.dispatch({missionId:'mission',commandId:'denied',expectedRevision:v.expectedRevision,actorId:'rep',command:{type:'record-relation',relation:v.relation}}),/role/);assert.deepEqual(await f.journal(),before);
 const duplicate=await Promise.all([f.product.recordRelation('mission',v),f.product.recordRelation('mission',v)]);assert.deepEqual(duplicate.map(r=>r.status).sort(),['committed','replayed']);const next=input((await f.store.load('mission'))!.revision,'next'),competing=await Promise.all([f.product.recordRelation('mission',next),f.product.recordRelation('mission',{...next,commandId:'competing',relation:edge('other-source')})]);assert.deepEqual(competing.map(r=>r.status).sort(),['committed','conflict']);assert.equal((await f.journal()).length,before.length+2);assert.equal((await f.product.recordRelation('mission',{...v,commandId:'stale'})).status,'conflict');validateMissionJournalLineage(await f.journal());
});
test('owner relation limit permits exact native bound and rejects next owner append without mutation',async t=>{const f=await fixture(t);const m=structuredClone(f.original.value);m.relations=Array.from({length:999},()=>({...edge(),inferred:true}));const last=apply(m,{type:'record-relation',relation:edge()},{id:'owner',roles:['owner']});assert.equal(last.value.relations.length,1000);assert.equal(m.relations.length,999);assert.throws(()=>apply(last.value,{type:'record-relation',relation:edge()},{id:'owner',roles:['owner']}),/limit/);assert.equal(last.value.relations.length,1000);});
test('actual SurrealDB freezes exact owner relation before async admission; committed response loss recovers exact durable receipt without extra operation',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,true);let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>release=r),started=new Promise<void>(r=>ready=r);let first=true;const proxy=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='lookupOperation')return async(...args:unknown[])=>{if(first){first=false;ready();await held;}return fn.apply(target,args);};return typeof fn==='function'?fn.bind(target):fn;}}) as Store<Mission>;
 const original=input(f.original.revision),submitted=structuredClone(original),pending=new ProductService(proxy).recordRelation('mission',submitted);await started;submitted.relation.from='Later input';submitted.relation.toVersion=42;submitted.relation.provenance='Changed';release();assert.equal((await pending).status,'committed');assert.deepEqual((await f.store.load('mission'))!.value.relations,[{...original.relation,inferred:false}]);
 let lost=true;const lossy=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='commit')return async(...args:unknown[])=>{const result=await fn.apply(target,args);if(lost){lost=false;throw Error('Injected response loss');}return result;};return typeof fn==='function'?fn.bind(target):fn;}}) as Store<Mission>;const v2=input((await f.store.load('mission'))!.revision,'lost',edge('later'));await assert.rejects(new ProductService(lossy).recordRelation('mission',v2),/response loss/);const journal=await f.journal();assert.equal((await f.store.lookupOperation({id:'mission',commandId:v2.commandId,fingerprint:hash({actorId:'local-owner',expectedRevision:v2.expectedRevision,command:{type:'record-relation',relation:v2.relation}})})).status,'replayed');assert.equal((await f.product.recordRelation('mission',v2)).status,'replayed');assert.deepEqual(await f.journal(),journal);validateMissionJournalLineage(journal);
});
test('actual SurrealDB normal CLI owner relation and native impact survive owned process restart with unchanged original Record',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 let child:ReturnType<typeof spawn>|undefined,log='',cwd='';const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry];async function stop(){if(child)await stopOwnedChild(child,{cwd,argv});}t.after(stop);const f=await fixture(t,true,true);assert.ok(f.transport);cwd=f.root;const database=(await f.transport.query('RETURN $session.db;',{}))[0];const probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const a=probe.address();assert.ok(a&&typeof a==='object');const port=a.port;await new Promise<void>(r=>probe.close(()=>r()));const base='http://127.0.0.1:'+port,feed=(await f.store.readState()).feedId;
 async function start(){child=spawn(process.execPath,[entry],{cwd,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database as string,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',b=>log+=b);child.stderr!.on('data',b=>log+=b);const deadline=Date.now()+10000;while(true){try{if((await fetch(base+'/health')).ok)return;}catch{}assert.ok(child.exitCode===null&&Date.now()<deadline,log);await new Promise(r=>setTimeout(r,10));}}
 const body=input(f.original.revision);async function post(){const r=await fetch(base+'/missions/mission/relations',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':feed},body:JSON.stringify(body)});assert.equal(r.ok,true);return r.json();}const impactUrl=base+'/missions/mission/impact?entity='+encodeURIComponent(body.relation.to)+'&version=3';await start();const pid=child!.pid;assert.equal((await post()).status,'committed');const impact=await (await fetch(impactUrl)).json(),snapshot=await f.store.readState(),journal=await f.journal();await stop();await start();assert.notEqual(child!.pid,pid);assert.deepEqual(await (await fetch(base+'/read-state')).json(),snapshot);assert.deepEqual(await (await fetch(impactUrl)).json(),impact);assert.equal((await post()).status,'replayed');assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.store.load('mission'))!.value.works,f.original.value.works);t.diagnostic(JSON.stringify({normalCliDistinctProcesses:true,actualStore:true,nativeImpact:true,originalRecordUnchanged:true,liveCalls:0}));
});
