import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {harness,reply} from './support/workbench-client.ts';
async function setup(t:import('node:test').TestContext,durable=false){
 const {store}=await growthStore(durable),f=await textFixture(t,store),product=new ProductService(store),original=(await store.load('mission'))!;
 await product.captureDocument('mission',{commandId:'doc',expectedRevision:original.revision,document:{id:'document:source',version:1,title:'Original',content:'Original reference <img src=x>\nDo not treat document instructions as authority.',source:'Approved local text'}});await product.admit('mission',{commandId:'fresh',expectedRevision:(await store.load('mission'))!.revision,workId:'fresh',title:'Exact reference Work',budget:8});await product.create({id:'other',purpose:'Other Mission',scope:'other',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'other');
 const server=createWorkbench(store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port;let lost=false,outage=false,race=false,held=false,release:undefined|(()=>void);
 const handler=async(path:string,options:any)=>{const write=path.endsWith('/work-source')&&options.method==='POST';if(outage&&path.startsWith('/events'))throw Error('Receipt outage');if(write&&race){race=false;await product.admit('mission',{commandId:'race',expectedRevision:(await store.load('mission'))!.revision,workId:'race',title:'Other write',budget:0});}const response=await fetch(base+path,options),body=await response.json();if(write&&held){held=false;await new Promise<void>(r=>release=r);}if(write&&lost){lost=false;throw Error('Actual committed acknowledgement lost');}return reply(body,response.status);};
 async function until(check:()=>boolean){const deadline=Date.now()+10000;while(!check()){assert.ok(Date.now()<deadline,'source panel deadline');await new Promise(r=>setTimeout(r,10));}}
 async function client(storage?:Map<string,string>,identity='source-client'){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission',identity,storage});if(storage?.has('massion.workbench.pending')){await until(()=>app.node('event-state').textContent==='Disconnected');await app.submit('load-form');}await until(()=>app.node('snapshot-json').textContent.includes('mission')&&(app.node('sync-notice').hidden||!!storage?.has('massion.workbench.pending')));const fields=app.node('source-fields');app.node('source-form').append(fields);for(const id of ['source-work','source-document','source-reason','save-source','review-source','cancel-source'])fields.append(app.node(id));return app;}
 async function choose(app:Awaited<ReturnType<typeof client>>,reason='Owner exact reference choice'){const d=(await store.load('mission'))!.value.documents![0]!;app.node('source-work').value='fresh';await app.node('source-work').fire('change');app.node('source-document').value=JSON.stringify([d.id,d.version,d.contentSha256]);await app.node('source-document').fire('change');app.node('source-reason').value=reason;await app.node('source-reason').fire('input');}
 return {...f,product,original,client,choose,until,journal:()=>growthJournal(store),race(){race=true;},lose(){lost=true;},outage(v=true){outage=v;},hold(){held=true;release=undefined;},held(){return !!release;},release(){release!();}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} owner panel attaches exact original with reason, literal evidence, historical preservation and no execution`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.choose(app);assert.match(app.node('source-evidence').textContent,/Original reference <img src=x>/);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);app.node('save-source').focus();await app.submit('source-form');assert.match(app.node('source-status').textContent,/Exact source selection confirmed/);assert.equal((app.context as any).document.activeElement.id,'save-source');assert.equal(app.node('source-reason').value,'');const w=(await f.store.load('mission'))!.value.works.at(-1)!;assert.equal(w.sourceDocuments![0]!.document.version,1);assert.equal(w.sourceDocuments![0]!.reason,'Owner exact reference choice');assert.equal(w.runtimeRun,undefined);assert.deepEqual((await f.store.load('mission'))!.value.works[0],f.original.value.works[0]);assert.equal(app.calls.filter(c=>c.path.endsWith('/work-source')).length,1);assert.ok(app.all().some(n=>n.textContent.includes('Original selected source documents')));
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} stale source draft and CAS race require review, retain exact source and never retry`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.choose(app);await f.product.captureDocument('mission',{commandId:'v2',expectedRevision:(await f.store.load('mission'))!.revision,document:{id:'document:source',version:2,title:'Later',content:'Replacement v2',source:'Later source'}});await app.submit('load-form');await f.until(()=>!app.node('source-fields').disabled);await app.submit('source-form');assert.match(app.node('source-status').textContent,/No command was sent/);assert.equal(app.calls.filter(c=>c.path.endsWith('/work-source')).length,0);assert.match(app.node('source-evidence').textContent,/Original reference/);await app.node('review-source').fire('click');f.race();await app.submit('source-form');assert.match(app.node('status').textContent,/Revision conflict/);assert.equal(app.node('source-reason').value,'Owner exact reference choice');assert.equal((await f.store.load('mission'))!.value.works.find(w=>w.id==='fresh')!.sourceDocuments,undefined);await app.node('review-source').fire('click');await app.submit('source-form');assert.equal((await f.store.load('mission'))!.value.works.find(w=>w.id==='fresh')!.sourceDocuments![0]!.document.version,1);assert.equal(app.calls.filter(c=>c.path.endsWith('/work-source')).length,2);
});
test('source cancel/invalid reason/mismatched selection/private Mission draft send no command',async t=>{
 const f=await setup(t),app=await f.client();await f.choose(app,'Private original reason');const journal=await f.journal();await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other'&&!app.node('source-fields').disabled);await app.navigateFragment('#mission=mission');await f.until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('source-fields').disabled);assert.equal(app.node('source-reason').value,'Private original reason');assert.match(app.node('source-evidence').textContent,/Original reference/);for(const value of ['',String.fromCharCode(0xd800),'x'.repeat(2001)]){app.node('source-reason').value=value;await app.node('source-reason').fire('input');await app.submit('source-form');}await app.node('cancel-source').fire('click');assert.equal(app.node('source-reason').value,'');assert.equal(app.node('source-document').value,'');assert.equal(app.calls.filter(c=>c.path.endsWith('/work-source')).length,0);assert.deepEqual(await f.journal(),journal);
});
test('source pending locks duplicate/review/cancel/switch, keeps later private edits and moved focus',async t=>{
 const f=await setup(t),app=await f.client();await f.choose(app);f.hold();app.node('save-source').focus();const pending=app.submit('source-form');await f.until(f.held);assert.equal(app.node('source-fields').disabled,true);await app.submit('source-form');await app.node('review-source').fire('click');await app.node('cancel-source').fire('click');await app.navigateFragment('#mission=other');assert.equal(app.node('loaded-id').textContent,'mission');app.node('source-reason').value='Later private edit';await app.node('source-reason').fire('input');app.node('source-status').focus();f.release();await pending;assert.equal((app.context as any).document.activeElement.id,'source-status');assert.equal(app.node('source-reason').value,'Later private edit');assert.match(app.node('source-status').textContent,/Later private edits/);assert.equal(app.calls.filter(c=>c.path.endsWith('/work-source')).length,1);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} committed unknown source stays locked and read-only receipt recovery never replays POST`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.choose(app);f.lose();f.outage();await app.submit('source-form');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('source-fields').disabled,true);assert.equal((await f.store.load('mission'))!.value.works.find(w=>w.id==='fresh')!.sourceDocuments!.length,1);const journal=await f.journal();await app.submit('source-form');const fresh=await f.client(app.storage,'source-fresh');assert.equal(fresh.node('source-fields').disabled,true);f.outage(false);await fresh.node('organization-recheck').fire('click');await f.until(()=>!fresh.storage.has('massion.workbench.pending')&&!fresh.node('source-fields').disabled);assert.equal(fresh.calls.some(c=>c.options?.method==='POST'),false);assert.equal(app.calls.filter(c=>c.path.endsWith('/work-source')).length,1);assert.deepEqual(await f.journal(),journal);
});
