import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {harness,reply} from './support/workbench-client.ts';
import {SurrealRelationImpact} from '../src/relation-impact.ts';
import {affectedBy} from '../src/domain.ts';
async function setup(t:import('node:test').TestContext,durable=false){
 const {store,transport}=await growthStore(durable),f=await textFixture(t,store),product=new ProductService(store),other='other';await product.create({id:other,purpose:'Separate Mission',scope:'other',constraints:[],criteria:{version:1,description:'Other input',oracle:'manual-review/v1'}},'other-create');const original=(await store.load('mission'))!;
 const server=createWorkbench(store,f.root,{knowledge:transport?new SurrealRelationImpact(transport):{readImpact:async(missionId,entity,version)=>{const s=await store.readState(missionId);return s.snapshot?{missionId,revision:s.snapshot.revision,feedId:s.feedId,cursor:s.cursor,changed:{id:entity,version},affected:affectedBy(s.snapshot.value,entity,version),relations:s.snapshot.value.relations}:null;}}});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');let base='http://127.0.0.1:'+a.port;let lost=false,eventOutage=false,held=false,readHeld=false,releaseWrite:undefined|(()=>void),releaseRead:undefined|(()=>void),rejected=false,race=false;
 const handler=async(path:string,options:any)=>{
  const organization=path.endsWith('/relations')&&options.method==='POST';if(eventOutage&&path.startsWith('/events'))throw Error('Supporting receipt event outage');if(organization&&rejected)return reply({outcome:'rejected',error:'Supporting definite rollback'},503);
  if(organization&&race){race=false;await product.admit('mission',{commandId:'raced-work',expectedRevision:(await store.load('mission'))!.revision,workId:'raced',title:'Another owner write before original CAS',budget:0});}
  const response=await fetch(base+path,options),body=await response.json();if(organization&&held){held=false;await new Promise<void>(r=>releaseWrite=r);}if(readHeld&&path.startsWith('/read-state?')){readHeld=false;await new Promise<void>(r=>releaseRead=r);}if(organization&&lost){lost=false;throw Error('Supporting lost actual committed acknowledgement');}return reply(body,response.status);
 };
 async function until(check:()=>boolean){const deadline=Date.now()+10000;while(!check()){assert.ok(Date.now()<deadline,'relation panel deadline');await new Promise(r=>setTimeout(r,10));}}
 async function client(identity='relation-client',storage?:Map<string,string>){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission',identity,storage});if(storage?.has('massion.workbench.pending')){await until(()=>app.node('event-state').textContent==='Disconnected');await app.submit('load-form');}await until(()=>app.node('snapshot-json').textContent.includes('mission')&&(app.node('sync-notice').hidden||!!storage?.has('massion.workbench.pending')));const fields=app.node('relation-fields');app.node('relation-form').append(fields);for(const name of ['relation-from','relation-from-version','relation-type','relation-to','relation-to-version','relation-provenance','save-relation','review-relation','cancel-relation'])fields.append(app.node(name));return app;}
 async function edit(app:Awaited<ReturnType<typeof client>>,from='report',to='document',provenance='Original source <img src=x>'){for(const [name,value] of [['relation-from',from],['relation-to',to],['relation-provenance',provenance]]){app.node(name!).value=value!;await app.node(name!).fire('input');}}
 return {...f,product,other,original,handler,client,edit,until,journal:()=>growthJournal(store),lose(){lost=true;},outage(value=true){eventOutage=value;},hold(){held=true;releaseWrite=undefined;},holdRead(){readHeld=true;releaseRead=undefined;},writeHeld(){return !!releaseWrite;},readHeld(){return !!releaseRead;},release(){releaseWrite!();},releaseRead(){releaseRead!();},reject(value=true){rejected=value;},race(){race=true;},replaceHost(url:string){base=url;}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} relation GUI records exact original versions/provenance through normal API, reads impact and retains old Record`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client(),other=await f.store.load(f.other);await f.edit(app);app.node('relation-from-version').value='2';app.node('relation-to-version').value='3';app.node('save-relation').focus();await app.submit('relation-form');assert.match(app.node('relation-status').textContent,/Exact relation confirmed/);assert.equal((app.context as any).document.activeElement.id,'save-relation');assert.equal(app.node('relation-from').value,'');const posted=JSON.parse(app.calls.find(c=>c.path.endsWith('/relations'))!.options.body);assert.equal(posted.expectedRevision,f.original.revision);assert.deepEqual(Object.keys(posted).sort(),['commandId','expectedRevision','relation']);assert.deepEqual(Object.keys(posted.relation).sort(),['from','fromVersion','provenance','to','toVersion','type']);const current=(await f.store.load('mission'))!;assert.deepEqual(current.value.relations,[{...posted.relation,inferred:false}]);assert.deepEqual(current.value.works,f.original.value.works);assert.deepEqual(await f.store.load(f.other),other);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);assert.match(app.node('relation-history').textContent,/Original source <img src=x>/);const before=await f.journal();app.node('impact-entity').value='document';app.node('impact-version').value='3';await app.submit('impact-form');assert.match(app.node('impact-results').textContent,/report.*v2/s);assert.match(app.node('impact-results').textContent,/Inferred: no/);assert.deepEqual(await f.journal(),before);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} relation stale draft sends no POST until explicit review; normal CAS race preserves original references without retry`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.edit(app,'private','source','Owner private reason');await f.product.admit('mission',{commandId:'other-work',expectedRevision:f.original.revision,workId:'other-work',title:'Another owner write',budget:0});await app.submit('load-form');await f.until(()=>!app.node('relation-fields').disabled);assert.match(app.node('relation-base').textContent,/State changed/);await app.submit('relation-form');assert.equal(app.calls.filter(c=>c.path.endsWith('/relations')).length,0);assert.equal(app.node('relation-from').value,'private');await app.node('review-relation').fire('click');const revision=(await f.store.load('mission'))!.revision;f.race();await app.submit('relation-form');assert.match(app.node('status').textContent,/Revision conflict/);assert.equal(app.calls.filter(c=>c.path.endsWith('/relations')).length,1);assert.equal(JSON.parse(app.calls.find(c=>c.path.endsWith('/relations'))!.options.body).expectedRevision,revision);assert.equal(app.node('relation-provenance').value,'Owner private reason');assert.equal((await f.store.load('mission'))!.value.relations.length,0);await app.node('review-relation').fire('click');await app.submit('relation-form');assert.equal((await f.store.load('mission'))!.value.relations[0]!.from,'private');
});
test('relation GUI input guards/cancel do not send command or disturb Work draft',async t=>{
 const f=await setup(t),app=await f.client();app.node('work-title').value='Untouched Work';const journal=await f.journal();for(const [id,value] of [['relation-from',''],['relation-to',''],['relation-provenance',''],['relation-from','x'.repeat(2001)],['relation-to',String.fromCharCode(0xd800)],['relation-from-version','0'],['relation-to-version','1.5'],['relation-type','invalidates']]){await f.edit(app);app.node('relation-from-version').value='1';app.node('relation-to-version').value='1';app.node('relation-type').value='depends-on';app.node(id!).value=value!;await app.submit('relation-form');assert.match(app.node('relation-status').textContent,/No command was sent/);}await app.node('cancel-relation').fire('click');assert.equal(app.node('relation-from').value,'');assert.equal(app.node('work-title').value,'Untouched Work');assert.equal(app.calls.filter(c=>c.path.endsWith('/relations')).length,0);assert.deepEqual(await f.journal(),journal);
});
test('relation drafts are Mission-private across switches and late old snapshot',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app,'mission-private');const before=await f.journal();f.holdRead();await app.submit('load-form');await f.until(f.readHeld);await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other'&&!app.node('relation-fields').disabled);await f.edit(app,'other-private');f.releaseRead();await app.navigateFragment('#mission=mission');await f.until(()=>app.node('loaded-id').textContent==='mission'&&!app.node('relation-fields').disabled);assert.equal(app.node('relation-from').value,'mission-private');await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other'&&!app.node('relation-fields').disabled);assert.equal(app.node('relation-from').value,'other-private');assert.deepEqual(await f.journal(),before);
});
test('pending relation acknowledgement bars duplicate/cancel/review/switch, retains later edits and moved focus',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app);app.node('save-relation').focus();f.hold();const saving=app.submit('relation-form');await f.until(f.writeHeld);assert.equal(app.node('relation-fields').disabled,true);await app.submit('relation-form');await app.node('cancel-relation').fire('click');await app.node('review-relation').fire('click');await app.navigateFragment('#mission=other');assert.equal(app.node('loaded-id').textContent,'mission');app.node('relation-provenance').value='Later private source';await app.node('relation-provenance').fire('input');app.node('relation-status').focus();f.release();await saving;assert.equal((app.context as any).document.activeElement.id,'relation-status');assert.equal(app.node('relation-provenance').value,'Later private source');assert.match(app.node('relation-status').textContent,/Later private edits/);assert.equal(app.calls.filter(c=>c.path.endsWith('/relations')).length,1);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} relation unknown commit remains locked until existing durable receipt readback; no POST replay`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.edit(app);f.lose();f.outage();await app.submit('relation-form');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('relation-fields').disabled,true);assert.equal((await f.store.load('mission'))!.value.relations.length,1);const journal=await f.journal();await app.submit('relation-form');await app.node('organization-recheck').fire('click');assert.ok(app.storage.has('massion.workbench.pending'));f.outage(false);await app.node('organization-recheck').fire('click');await f.until(()=>!app.storage.has('massion.workbench.pending')&&!app.node('relation-fields').disabled);assert.match(app.node('relation-status').textContent,/confirmed/);assert.equal(app.calls.filter(c=>c.path.endsWith('/relations')).length,1);assert.deepEqual(await f.journal(),journal);
});
test('actual SurrealDB fresh browser restores relation unknown identity and checks receipt without save replay',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,true),app=await f.client();await f.edit(app);f.lose();f.outage();await app.submit('relation-form');const journal=await f.journal(),fresh=await f.client('fresh',app.storage);assert.equal(fresh.node('relation-fields').disabled,true);f.outage(false);await fresh.node('organization-recheck').fire('click');await f.until(()=>!fresh.storage.has('massion.workbench.pending')&&!fresh.node('relation-fields').disabled);assert.equal(fresh.calls.some(c=>c.options?.method==='POST'),false);assert.deepEqual(await f.journal(),journal);assert.match(fresh.node('relation-history').textContent,/report@1.*document@1/s);
});
test('definite relation rollback retains exact private draft and focus before deliberate new save',async t=>{
 const f=await setup(t),app=await f.client();await f.edit(app);app.node('relation-from').focus();const journal=await f.journal();f.reject();await app.submit('relation-form');assert.equal(app.storage.has('massion.workbench.pending'),false);assert.equal(app.node('relation-from').value,'report');assert.equal((app.context as any).document.activeElement.id,'relation-from');assert.deepEqual(await f.journal(),journal);f.reject(false);await app.submit('relation-form');assert.equal((await f.store.load('mission'))!.value.relations.length,1);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} replacement feed clears relation confirmation and keeps original private source/CAS until explicit review`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.edit(app);await app.submit('relation-form');assert.match(app.node('relation-status').textContent,/confirmed/);await f.edit(app,'Old feed private reference');const oldJournal=await f.journal();const {store:replacement}=await growthStore(durable),product=new ProductService(replacement);await product.create({id:'mission',purpose:'Different database same ID',scope:'new',constraints:[],criteria:{version:1,description:'New criteria',oracle:'manual-review/v1'}},'replacement-create');const replacementJournal=await growthJournal(replacement),server=createWorkbench(replacement,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');f.replaceHost('http://127.0.0.1:'+a.port);await app.tick();await f.until(()=>app.node('event-state').textContent==='Disconnected');await app.tick();await f.until(()=>app.node('sync-notice').hidden&&app.node('relation-history').textContent.includes('0 stored relations'));assert.doesNotMatch(app.node('relation-status').textContent,/confirmed/);assert.match(app.node('relation-base').textContent,/State changed/);assert.equal(app.node('relation-from').value,'Old feed private reference');const count=app.calls.filter(c=>c.path.endsWith('/relations')).length;await app.submit('relation-form');assert.equal(app.calls.filter(c=>c.path.endsWith('/relations')).length,count);assert.deepEqual(await growthJournal(replacement),replacementJournal);assert.deepEqual(await f.journal(),oldJournal);await app.node('review-relation').fire('click');assert.doesNotMatch(app.node('relation-base').textContent,/State changed/);assert.equal(app.node('relation-from').value,'Old feed private reference');assert.deepEqual(await growthJournal(replacement),replacementJournal);
});
