import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createHash} from 'node:crypto';
import {runInContext} from 'node:vm';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {growthStore,growthJournal} from './support/growth-fixture.ts';
import {textFixture} from './support/record-artifact-fixture.ts';
import {harness,reply} from './support/workbench-client.ts';
async function fixture(t:any,durable=false){const {store}=await growthStore(durable),f=await textFixture(t,store),product=new ProductService(store);await product.create({id:'other',purpose:'Other',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'other');const server=createWorkbench(store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');let base='http://127.0.0.1:'+a.port,writes=0;const app=harness(async(path:string,options:any)=>{if(options.method==='POST')writes++;const r=await fetch(base+path,options);return reply(await r.json(),r.status);},{},undefined,{network:true,fragment:'#mission=mission'});(app.context as any).TextDecoder=TextDecoder;const until=async(check:()=>boolean)=>{const end=Date.now()+10000;while(!check()){assert.ok(Date.now()<end);await new Promise(r=>setTimeout(r,5));}};await until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden&&!app.node('file-document-choice').disabled);return {...f,store,product,app,until,journal:()=>growthJournal(store),writes:()=>writes,replaceBase:(value:string)=>base=value,base};}
function file(name:string,bytes:Uint8Array,read?:()=>Promise<ArrayBuffer>){const raw=Uint8Array.from(bytes);return {name,size:raw.length,arrayBuffer:read||(async()=>raw.buffer)};}
async function choose(app:any,value:any){(app.node('file-document-choice') as any).files=[value];await app.node('file-document-choice').fire('change');}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} local UTF-8 preview/private Cancel/Use/review/separate save preserves original Record and distinct raw normalized hashes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await fixture(t,durable),app=f.app,before=await f.journal(),original=(await f.store.load('mission'))!.value.works,raw=new TextEncoder().encode('\ufeffOriginal <img src=x>\r\n원문 😀\rEnd'),selected=file('source <img>.txt',raw);await choose(app,selected);assert.match(app.node('file-document-preview').textContent,/rawSha256/);assert.equal(f.writes(),0);await app.node('file-document-cancel').fire('click');assert.deepEqual(await f.journal(),before);await choose(app,selected);await app.node('file-document-use').fire('click');assert.equal(f.writes(),0);assert.equal(app.node('document-content').value,'\ufeffOriginal <img src=x>\n원문 😀\nEnd');const source=JSON.parse(app.node('document-source').value);assert.equal(source.rawSha256,createHash('sha256').update(raw).digest('hex'));assert.notEqual(source.rawSha256,source.initialDraftSha256);app.node('document-id').value='document:file';await app.node('document-id').fire('input');app.node('document-version').value='1';await app.node('document-version').fire('input');await app.submit('document-form');assert.equal(f.writes(),0);await app.node('review-document').fire('click');await app.submit('document-form');assert.equal(f.writes(),1);const current=(await f.store.load('mission'))!.value;assert.deepEqual(current.works,original);assert.equal(current.documents![0]!.contentSha256,source.initialDraftSha256);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);});
test('invalid/empty/NUL/oversized UTF-8 file preserves existing private fields and sends no command',async t=>{const f=await fixture(t),app=f.app;app.node('document-content').value='Retained owner draft';await app.node('document-content').fire('input');for(const bytes of [new Uint8Array(),new Uint8Array([0xff]),new Uint8Array([65,0,66]),new TextEncoder().encode(' '.repeat(5)),new Uint8Array(16385)]){await choose(app,file('invalid.txt',bytes));assert.equal(app.node('file-document-use').disabled,true);assert.equal(app.node('document-content').value,'Retained owner draft');assert.equal(f.writes(),0);}});
for(const action of ['file-cancel','document-cancel','edit-ABA','new-file','mission'])test(`late selected file read cannot replace draft after ${action}`,async t=>{const f=await fixture(t),app=f.app;let release!:()=>void;const bytes=new TextEncoder().encode('Late original file'),gate=new Promise<ArrayBuffer>(r=>release=()=>r(Uint8Array.from(bytes).buffer));(app.node('file-document-choice') as any).files=[file('late.txt',bytes,()=>gate)];const pending=app.node('file-document-choice').fire('change');if(action==='file-cancel')await app.node('file-document-cancel').fire('click');if(action==='document-cancel')await app.node('cancel-document').fire('click');if(action==='edit-ABA'){app.node('document-content').value='Later private';await app.node('document-content').fire('input');app.node('document-content').value='';await app.node('document-content').fire('input');}if(action==='new-file')await choose(app,file('new.txt',new TextEncoder().encode('New original')));if(action==='mission'){await runInContext("loadMission('other',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='other');}release();await pending;assert.equal(app.node('document-content').value,'');if(action==='new-file')assert.match(app.node('file-document-preview').textContent,/New original/);else assert.equal(app.node('file-document-preview').hidden,true);assert.equal(f.writes(),0);});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} replacement feed invalidates selected-file preview without installing it in new database`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const first=await fixture(t,durable),second=await fixture(t,durable),app=first.app;await choose(app,file('original.txt',new TextEncoder().encode('First original')));assert.equal(app.node('file-document-preview').hidden,false);const one=await first.journal(),two=await second.journal();first.replaceBase(second.base);await app.windowEvent('online');const end=Date.now()+10000;while(!app.node('sync-notice').hidden||app.node('file-document-choice').disabled){assert.ok(Date.now()<end);await app.tick();await new Promise(r=>setTimeout(r,10));}assert.equal(app.node('file-document-preview').hidden,true);assert.equal(app.node('file-document-use').disabled,true);assert.equal(app.node('document-content').value,'');assert.deepEqual(await first.journal(),one);assert.deepEqual(await second.journal(),two);});
