import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {stopOwnedChild} from './support/owned-process.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {join} from 'node:path';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {SurrealStore} from '../src/storage.ts';
import type {Store} from '../src/storage.ts';
import type {Mission} from '../src/domain.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {exportPortableBackup,restorePortableBackup} from '../src/portable-backup.ts';
import {growthStore} from './support/growth-fixture.ts';
import {proposalFixture,orders} from './support/growth-proposal-fixture.ts';
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal user proposal and independent data evaluation adopt future memory and revert without rewriting old Work`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await proposalFixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port,feed=(await f.store.readState('mission')).feedId;
 const post=async(route:string,body:unknown,identity=feed)=>{const response=await fetch(base+'/missions/mission/'+route,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':identity},body:JSON.stringify(body)});return {status:response.status,body:await response.json()};};
 assert.equal((await post('growth-proposals',{...f.proposal,proposer:'caller'})).status,400);assert.equal((await post('growth-proposals',f.proposal,'other-feed')).status,409);assert.equal((await post('growth-proposals',f.proposal)).body.status,'committed');let current=(await f.store.load('mission'))!;const g=current.value.growth[0]!;assert.equal(g.proposer,'local-owner');assert.equal(g.status,'proposed');assert.equal(current.value.memories.at(-1)!.effective,false);assert.equal(current.value.memories.at(-1)!.source,f.proposal.candidate.source);assert.deepEqual(current.value.works,f.original.value.works);const journal=await f.journal();assert.equal((await post('growth-proposals',f.proposal)).body.status,'replayed');assert.deepEqual(await f.journal(),journal);
 const action={commandId:'premature-adopt',expectedRevision:current.revision,growthId:g.id,baseline:g.baseline,candidate:g.candidate,action:'adopt'};assert.equal((await post('growth',action)).status,400);
 const evaluation={...f.evaluation(),expectedRevision:current.revision};for(const field of ['evaluator','scores','pass','heldOut'])assert.equal((await post('growth-evaluation',{...evaluation,[field]:'caller supplied'})).status,400);
 const result=await post('growth-evaluation',evaluation);assert.equal(result.body.status,'committed');current=(await f.store.load('mission'))!;const evaluated=current.value.growth[0]!;assert.equal(evaluated.evaluator,'host-rounding-oracle/v1');assert.equal(evaluated.scores!.baseline,1);assert.equal(evaluated.scores!.candidate,2);const evidence=JSON.parse(evaluated.scores!.heldOut);assert.deepEqual(evidence.orders,orders);assert.equal(evidence.baseline.ref,g.baseline);assert.match(evidence.scope,/not secret holdout or model learning/);assert.deepEqual(current.value.works,f.original.value.works);
 const evaluatedJournal=await f.journal();assert.equal((await post('growth-evaluation',evaluation)).body.status,'replayed');assert.equal((await post('growth-evaluation',{...evaluation,cases:[orders[1]]})).status,409);assert.deepEqual(await f.journal(),evaluatedJournal);
 assert.equal((await post('growth',{...action,commandId:'owner-adopt',expectedRevision:current.revision})).body.status,'committed');current=(await f.store.load('mission'))!;const adoptedJournal=await f.journal();assert.equal((await post('growth-evaluation',evaluation)).body.status,'replayed');assert.equal((await post('growth-evaluation',{...evaluation,cases:[orders[1]]})).status,409);assert.deepEqual(await f.journal(),adoptedJournal);await f.product.admit('mission',{commandId:'future-under-candidate',expectedRevision:current.revision,workId:'future',title:'Future effective policy',budget:0});current=(await f.store.load('mission'))!;assert.deepEqual(current.value.works.at(-1)!.appliedMemoryVersions,['rounding@2']);const future=structuredClone(current.value.works.at(-1));assert.equal((await post('growth',{...action,commandId:'owner-revert',expectedRevision:current.revision,action:'revert'})).body.status,'committed');current=(await f.store.load('mission'))!;assert.deepEqual(current.value.works.slice(0,f.original.value.works.length),f.original.value.works);assert.deepEqual(current.value.works.at(-1),future);validateMissionJournalLineage(await f.journal());
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} proposal/evaluation guard scope, input bounds, unsupported policy/oracle, nonimprovement and stale baseline without partial writes`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await proposalFixture(t,durable),initial=await f.journal();for(const proposal of [{...f.proposal,baseline:'rounding@9'},{...f.proposal,candidate:{...f.proposal.candidate,version:1}},{...f.proposal,counterevidence:''}])await assert.rejects(f.product.proposeGrowth('mission',proposal));assert.deepEqual(await f.journal(),initial);
 await f.product.proposeGrowth('mission',f.proposal);let current=(await f.store.load('mission'))!;const input={...f.evaluation(),expectedRevision:current.revision},before=await f.journal();
 for(const evaluation of [{...input,oracle:'unknown'},{...input,baseline:'rounding@9'},{...input,cases:[]},{...input,cases:[{...orders[0]!,expected:3}]},{...input,cases:[{items:[{unitPriceCents:1,quantity:0}],discountBasisPoints:5000}]}])await assert.rejects(f.product.evaluateGrowth('mission',evaluation));assert.deepEqual(await f.journal(),before);
 await f.product.evaluateGrowth('mission',{...input,cases:[orders[1]!]});current=(await f.store.load('mission'))!;await assert.rejects(f.product.adoptGrowth('mission',{commandId:'nonimproving-adopt',expectedRevision:current.revision,growthId:'new-growth',baseline:'rounding@1',candidate:'rounding@2'}),/improvement/);
 await f.product.proposeGrowth('mission',{...f.proposal,commandId:'unsupported-proposal',expectedRevision:current.revision,growthId:'unsupported',candidate:{...f.proposal.candidate,version:3,content:'Execute arbitrary user code'}});current=(await f.store.load('mission'))!;await assert.rejects(f.product.evaluateGrowth('mission',{...input,commandId:'unsupported-evaluate',expectedRevision:current.revision,growthId:'unsupported',candidate:'rounding@3'}),/Unsupported calculation memory/);
 await f.product.proposeGrowth('mission',{...f.proposal,commandId:'stale-proposal',expectedRevision:current.revision,growthId:'stale',candidate:{...f.proposal.candidate,version:4}});current=(await f.store.load('mission'))!;await f.product.saveMemory('mission',{commandId:'replace-baseline',expectedRevision:current.revision,memory:{id:'rounding',version:5,content:'Round each line',source:'Later owner policy'}});current=(await f.store.load('mission'))!;const preserved=await f.journal();await assert.rejects(f.product.evaluateGrowth('mission',{...input,commandId:'stale-evaluate',expectedRevision:current.revision,growthId:'stale',candidate:'rounding@4'}),/current scoped baseline/);assert.deepEqual(await f.journal(),preserved);
});
test('actual SurrealDB concurrent evaluations and committed unknown response replay exactly one evaluated operation',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await proposalFixture(t,true);await f.product.proposeGrowth('mission',f.proposal);const input={...f.evaluation(),expectedRevision:(await f.store.load('mission'))!.revision},before=await f.journal();const results=await Promise.all([f.product.evaluateGrowth('mission',input),f.product.evaluateGrowth('mission',input)]);assert.deepEqual(results.map(r=>r.status).sort(),['committed','replayed']);assert.equal((await f.journal()).length,before.length+1);
 const snapshot=(await f.store.load('mission'))!;await f.product.proposeGrowth('mission',{...f.proposal,commandId:'unknown-proposal',expectedRevision:snapshot.revision,growthId:'unknown-eval',candidate:{...f.proposal.candidate,version:3}});let throwOnce=true;const proxy=new Proxy(f.store,{get(target,key){const value=Reflect.get(target,key);if(key==='commit')return async(...args:unknown[])=>{const result=await value.apply(target,args);if(throwOnce){throwOnce=false;throw Error('Supporting lost actual commit response');}return result;};return typeof value==='function'?value.bind(target):value;}}) as Store<Mission>;const unknown={...input,commandId:'unknown-evaluation',expectedRevision:(await f.store.load('mission'))!.revision,growthId:'unknown-eval',candidate:'rounding@3'};await assert.rejects(new ProductService(proxy).evaluateGrowth('mission',unknown),/lost actual commit/);const committed=await f.journal();assert.equal((await new ProductService(f.store).evaluateGrowth('mission',unknown)).status,'replayed');assert.deepEqual(await f.journal(),committed);validateMissionJournalLineage(committed);
});
test('actual SurrealDB proposed and evaluated memories survive portable restore without evaluator replay or old Record changes',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await proposalFixture(t,true);await f.product.proposeGrowth('mission',f.proposal);await f.product.evaluateGrowth('mission',{...f.evaluation(),expectedRevision:(await f.store.load('mission'))!.revision});assert.ok(f.store instanceof SurrealStore);const snapshot=await f.store.load('mission'),journal=await f.store.exportJournal(),serialized=await exportPortableBackup(f.store,f.artifacts),{store:restored}=await growthStore(true);assert.ok(restored instanceof SurrealStore);await restorePortableBackup(serialized,restored,join(f.root,'restored'));assert.deepEqual(await restored.load('mission'),snapshot);assert.deepEqual(await restored.exportJournal(),journal);assert.deepEqual(snapshot!.value.works,f.original.value.works);
});

test('actual SurrealDB normal CLI retains user proposal, independent evaluation and exact receipt after process restart',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 let child:ReturnType<typeof spawn>|undefined,log='',cwd='';const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry];
 async function stop(){if(child)await stopOwnedChild(child,{cwd,argv});}t.after(stop);
 const f=await proposalFixture(t,true,true),{store,transport}=f;assert.ok(transport);await f.product.proposeGrowth('mission',f.proposal);const evaluation={...f.evaluation(),expectedRevision:(await store.load('mission'))!.revision};await f.product.evaluateGrowth('mission',evaluation);const before=await store.readState('mission'),journal=await f.journal();
 cwd=f.root;
 const probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const address=probe.address();assert.ok(address&&typeof address==='object');const port=address.port;await new Promise<void>(r=>probe.close(()=>r()));
 // The fresh database name is taken from this owned transport's creation, never an existing service.
 const database=(await transport.query('RETURN $session.db;',{}))[0];assert.equal(typeof database,'string');
 async function start(){child=spawn(process.execPath,[entry],{cwd:f.root,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database as string,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',b=>log+=b);child.stderr!.on('data',b=>log+=b);const deadline=Date.now()+10000;while(true){try{if((await fetch('http://127.0.0.1:'+port+'/health')).ok)return;}catch{}assert.ok(child.exitCode===null&&Date.now()<deadline,log);await new Promise(r=>setTimeout(r,10));}}
 const get=async()=>{const r=await fetch('http://127.0.0.1:'+port+'/missions/mission');assert.equal(r.status,200);return r.json();};
 await start();const pid=child!.pid,first=await get();assert.equal(first.value.growth[0].status,'evaluated');await stop();await start();assert.notEqual(child!.pid,pid);assert.deepEqual(await get(),first);assert.deepEqual(await store.readState('mission'),before);const reply=await fetch('http://127.0.0.1:'+port+'/missions/mission/growth-evaluation',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':before.feedId},body:JSON.stringify(evaluation)});assert.equal((await reply.json()).status,'replayed');assert.deepEqual(await f.journal(),journal);
});test('asynchronous proposal admission freezes caller candidate source/content and original exact baseline',async t=>{
 const f=await proposalFixture(t);let release!:()=>void,started!:()=>void;const held=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>started=r);let once=true;const proxy=new Proxy(f.store,{get(target,key){const value=Reflect.get(target,key);if(key==='load')return async(...args:unknown[])=>{const snapshot=await value.apply(target,args);if(once){once=false;started();await held;}return snapshot;};return typeof value==='function'?value.bind(target):value;}}) as Store<Mission>;
 const input=structuredClone(f.proposal),pending=new ProductService(proxy).proposeGrowth('mission',input);await ready;input.baseline='other@9';input.candidate.source='Changed after admission';input.candidate.content='Different policy';release();assert.equal((await pending).status,'committed');const current=(await f.store.load('mission'))!;assert.equal(current.value.growth[0]!.baseline,f.proposal.baseline);assert.deepEqual(current.value.memories.at(-1)!.content,f.proposal.candidate.content);assert.deepEqual(current.value.memories.at(-1)!.source,f.proposal.candidate.source);
});
test('actual SurrealDB concurrent owner revision during held evaluation read rejects original CAS without changing old pins or admitting stale scores',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await proposalFixture(t,true);await f.product.proposeGrowth('mission',f.proposal);const original=(await f.store.load('mission'))!,input={...f.evaluation(),expectedRevision:original.revision};let release!:()=>void,started!:()=>void;const held=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>started=r);let once=true;const proxy=new Proxy(f.store,{get(target,key){const value=Reflect.get(target,key);if(key==='load')return async(...args:unknown[])=>{const snapshot=await value.apply(target,args);if(once){once=false;started();await held;}return snapshot;};return typeof value==='function'?value.bind(target):value;}}) as Store<Mission>;
 const evaluating=new ProductService(proxy).evaluateGrowth('mission',input);await ready;input.cases[0]!.items[0]!.unitPriceCents=99;await f.product.admit('mission',{commandId:'during-oracle-read',expectedRevision:original.revision,workId:'concurrent-evaluation',title:'Independent owner update',budget:0});const journal=await f.journal();release();assert.equal((await evaluating).status,'conflict');assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.store.load('mission'))!.value.works.slice(0,f.original.value.works.length),f.original.value.works);assert.equal((await f.store.load('mission'))!.value.growth[0]!.status,'proposed');
});
