import test from 'node:test';
import assert from 'node:assert/strict';
import {runInContext} from 'node:vm';
import {expiredFixture,chooseExpired} from './support/expired-panel-fixture.ts';
for(const durable of [false,true]){
 const opts={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 for(const stage of ['activation','pending','unknown'] as const)test(`${durable?'actual DB':'memory'} owner privately reviews/cancels then closes expired ${stage} without replay`,opts,async t=>{const f=await expiredFixture(t,durable,stage),app=await f.client(),journal=await f.journal();await chooseExpired(app);await app.node('expired-review').fire('click');assert.equal(app.node('expired-save').disabled,false);assert.match(app.node('expired-evidence').textContent,/observedAt|dispatchId/);await app.node('expired-cancel').fire('click');assert.equal(f.writes(),0);assert.deepEqual(await f.journal(),journal);await chooseExpired(app);await app.node('expired-review').fire('click');await app.submit('expired-form');const after=await f.current(),old=f.original.value.works.find(w=>w.id==='fresh')!,w=after.value.works.find(w=>w.id==='fresh')!;assert.deepEqual(w.runtimeRun,old.runtimeRun);assert.deepEqual(w.effects,old.effects.map(e=>e.status==='pending'?{...e,status:'unknown'}:e));assert.equal(w.budget.reserved,old.budget.reserved);assert.deepEqual(after.value.works.filter(w=>w.id!=='fresh'),f.original.value.works.filter(w=>w.id!=='fresh'));assert.equal(w.runtimeInterruption!.observedAt,f.submitted().command.observedAt);assert.equal(f.calls.length,0);assert.equal(f.writes(),1);assert.match(app.node('expired-status').textContent,/confirmed/);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);const fresh=await f.client();await fresh.submit('expired-form');assert.equal(f.writes(),1);});
 test(`${durable?'actual DB':'memory'} changed revision invalidates exact closure; review again explicitly`,opts,async t=>{const f=await expiredFixture(t,durable),app=await f.client();await chooseExpired(app);await app.node('expired-review').fire('click');await f.product.admit('mission',{commandId:'later-work',expectedRevision:(await f.current()).revision,workId:'later',title:'Later',budget:8});await app.tick();await f.until(()=>runInContext('snapshot.revision',app.context)===(f.original.revision+1)&&!runInContext('loading',app.context));assert.equal(app.node('expired-save').disabled,true);await app.submit('expired-form');assert.equal(f.writes(),0);await app.node('expired-review').fire('click');await app.submit('expired-form');assert.equal(f.writes(),1);});
 test(`${durable?'actual DB':'memory'} unknown committed closure uses durable receipt without replay`,opts,async t=>{const f=await expiredFixture(t,durable,'unknown','unknown'),app=await f.client();await chooseExpired(app);await app.node('expired-review').fire('click');await app.submit('expired-form');await app.tick();await f.until(()=>runInContext('unknownOperation',app.context)===null);assert.equal(f.writes(),1);assert.match(app.node('expired-status').textContent,/confirmed/);assert.equal(f.calls.length,0);});
}
for(const mode of ['wrong-feed','wrong-run','before-deadline'])test(`${mode} ownership read cannot enable closure`,async t=>{const f=await expiredFixture(t,false,'activation',mode),app=await f.client();await chooseExpired(app);await app.node('expired-review').fire('click');assert.equal(app.node('expired-save').disabled,true);await app.submit('expired-form');assert.equal(f.writes(),0);});
test('Cancel invalidates late ownership read and retains moved focus',async t=>{const f=await expiredFixture(t,false,'activation','held-read'),app=await f.client();await chooseExpired(app);const p=app.node('expired-review').fire('click');await f.until(()=>f.reads()===1);await app.node('expired-cancel').fire('click');app.node('sequence-summary').focus();f.release();await p;assert.equal(app.node('expired-save').disabled,true);assert.equal(runInContext('document.activeElement.id',app.context),'sequence-summary');assert.equal(f.writes(),0);});
for(const mode of ['held','held-unknown','held-rejected'])test(`${mode} closure response cannot restore previous Mission`,async t=>{const f=await expiredFixture(t,false,'activation',mode),app=await f.client();await chooseExpired(app);await app.node('expired-review').fire('click');const p=app.submit('expired-form');await f.until(()=>f.writes()===1);await runInContext("loadMission('other',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='other');f.release();await p;assert.equal(app.node('loaded-id').textContent,'other');assert.equal(f.writes(),1);assert.equal(f.calls.length,0);});
test('Late committed closure keeps later private edits and focus',async t=>{const f=await expiredFixture(t,false,'activation','held'),app=await f.client();await chooseExpired(app);await app.node('expired-review').fire('click');const p=app.submit('expired-form');await f.until(()=>f.writes()===1);app.node('expired-reason').value='Later private reasoning';await app.node('expired-reason').fire('input');app.node('sequence-summary').focus();f.release();await p;assert.equal(app.node('expired-reason').value,'Later private reasoning');assert.equal(runInContext('document.activeElement.id',app.context),'sequence-summary');assert.equal(f.writes(),1);});

test('Unconfirmed closure stays locked and never reissues the command',async t=>{const f=await expiredFixture(t,false,'pending','unknown-no-commit'),app=await f.client(),journal=await f.journal();await chooseExpired(app);await app.node('expired-review').fire('click');await app.submit('expired-form');await app.tick();assert.ok(runInContext('unknownOperation',app.context));assert.equal(app.node('expired-save').disabled,true);await app.submit('expired-form');assert.equal(f.writes(),1);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);});
test('Late ownership review cannot activate a previous Mission decision',async t=>{const f=await expiredFixture(t,false,'activation','held-read'),app=await f.client();await chooseExpired(app);const p=app.node('expired-review').fire('click');await f.until(()=>f.reads()===1);await runInContext("loadMission('other',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='other');f.release();await p;assert.equal(app.node('loaded-id').textContent,'other');assert.equal(app.node('expired-save').disabled,true);assert.equal(f.writes(),0);});
