import test from 'node:test';
import assert from 'node:assert/strict';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {ConfiguredTextRuntime,RunUnsettledError} from '../src/configured-runtime.ts';
import {Application} from '../src/application.ts';
import {ProductService} from '../src/product.ts';
import {providerRequestHash,validateProviderDispatchClaims} from '../src/provider-dispatch.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {hash} from '../src/domain.ts';
import type {Mission,Command,ProviderDispatchClaim} from '../src/domain.ts';
import type {CommitInput,Store} from '../src/storage.ts';
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} normal configured path owns exact one-shot claims, request hashes, independent receipts and original Records`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),result=await f.product.run('mission','fresh','claimed-run',(await f.current()).revision),w=result.snapshot.value.works.find(w=>w.id==='fresh')!;assert.equal(result.status,'settled');assert.equal(f.calls.length,2);const claims=w.effects.filter(e=>e.providerDispatch);assert.equal(claims.length,2);assert.equal(new Set(claims.map(e=>e.providerDispatch!.id)).size,2);
 for(const [index,e] of claims.entries()){const c=e.providerDispatch!,request={invocationId:e.id,workId:'fresh',instruction:JSON.stringify(f.calls[index]!.input),inputReferences:[],maxOutputTokens:4,signal:f.calls[index]!.signal};assert.equal(c.requestHash,providerRequestHash(request));assert.equal(c.runId,'claimed-run');assert.equal(c.hostSessionId,w.runtimeRun!.ownership!.hostSessionId);assert.equal(c.dispatchId,w.runtimeRun!.ownership!.dispatchId);assert.equal(c.actorId,index===0?'host-executor':'host-verifier');assert.equal(c.claimedAt>=w.runtimeRun!.ownership!.startedAt,true);const receipt=JSON.parse(e.receipt!);assert.equal(receipt.providerDispatchId,c.id);assert.equal(receipt.requestHash,c.requestHash);}
 assert.deepEqual(w.record!.receipts,w.effects);assert.deepEqual(result.snapshot.value.works[0],f.original.value.works[0]);validateProviderDispatchClaims(w);validateMissionJournalLineage(await f.journal());const query=await f.product.readRunOwnership('mission','fresh');assert.equal(query!.providerDispatchClaims.length,2);assert.deepEqual(query!.providerDispatchClaims.map(e=>e.claim),claims.map(e=>e.providerDispatch));
});
async function boundary(t:import('node:test').TestContext,durable=false,mode:'before'|'after'|'lost'|'replayed'='before',runTimeoutMs?:number){
 const f=await fixture(t,durable,{runTimeoutMs});let captured:CommitInput<Mission>|undefined,claimCommand:Extract<Command,{type:'claim-provider-dispatch'}>|undefined,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const base=f.store;
 const store=new Proxy(base,{get(target,key){if(key==='commit')return async(input:CommitInput<Mission>)=>{const command=(input.events[0] as any)?.command;if(command?.type==='claim-provider-dispatch'&&!captured){captured=input;if(mode==='before')await gate;const result=await target.commit(input);if(mode==='lost')throw Error('Committed claim response deliberately lost');if(mode==='replayed'&&result.status!=='conflict')return {...result,status:'replayed' as const};if(mode==='after')await gate;return result;}return target.commit(input);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}});
 const runtime=new ConfiguredTextRuntime(store,f.config),dispatch=(runtime as any).dispatch.bind(runtime);(runtime as any).dispatch=async(missionId:string,command:Command,...rest:any[])=>{if(command.type==='claim-provider-dispatch'&&!claimCommand){claimCommand=command;if(mode==='before'){// Hold before Application admission, not inside an already admitted DB transaction.
 await gate;}}
 return dispatch(missionId,command,...rest);};
 const run=runtime.run('mission','fresh','claim-boundary',(await f.current()).revision);void run.catch(()=>{});return {...f,runtime,run,release,claimCommand:()=>claimCommand,captured:()=>captured};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} two original actor claim contenders CAS once; exact replay and changed identities never invoke`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await boundary(t,durable),owner=new ProductService(f.store);await f.until(()=>!!f.claimCommand());const command=f.claimCommand()!,revision=(await f.current()).revision,app=new Application(f.store,[f.runtime.app.actor('host-executor')]),other={...structuredClone(command),claim:{...command.claim,id:crypto.randomUUID()}};
 const results=await Promise.all([app.dispatch({missionId:'mission',actorId:'host-executor',commandId:command.claim.id,expectedRevision:revision,command}),app.dispatch({missionId:'mission',actorId:'host-executor',commandId:other.claim.id,expectedRevision:revision,command:other})]);assert.equal(results.filter(r=>r.status==='committed').length,1);assert.equal(results.filter(r=>r.status==='conflict').length,1);const winner=results[0]!.status==='committed'?command:other;assert.equal((await app.dispatch({missionId:'mission',actorId:'host-executor',commandId:winner.claim.id,expectedRevision:revision,command:winner})).status,'replayed');assert.equal((await app.dispatch({missionId:'mission',actorId:'host-executor',commandId:winner.claim.id,expectedRevision:revision,command:{...winner,claim:{...winner.claim,requestHash:'f'.repeat(64)}}})).status,'conflict');
 f.release();await assert.rejects(f.run,RunUnsettledError);assert.equal(f.calls.length,0);const w=(await f.current()).value.works.find(w=>w.id==='fresh')!;assert.equal(w.effects[0]!.providerDispatch!.id,winner.claim.id);assert.equal(w.effects[0]!.status,'pending');assert.equal(w.budget.reserved,4);await owner.intervene('mission',{commandId:'claim-cas-quarantine',expectedRevision:(await f.current()).revision,command:{type:'quarantine-runtime',workId:'fresh',runId:'claim-boundary',reason:'Owned fixture claim contender; actual call not observed',acknowledgeUncertainOutcome:true}});assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.effects[0]!.status,'unknown');validateMissionJournalLineage(await f.journal());
});
for(const mode of ['lost','replayed'] as const)test(`${mode} committed claim acknowledgment leaves pending uncertainty and zero calls without fresh-runtime replay`,async t=>{
 const f=await boundary(t,false,mode);await assert.rejects(f.run,RunUnsettledError);assert.ok(f.captured());const w=(await f.current()).value.works.find(w=>w.id==='fresh')!;assert.ok(w.effects[0]!.providerDispatch);assert.equal(w.effects[0]!.status,'pending');assert.equal(w.budget.reserved,4);assert.equal(f.calls.length,0);const before=await f.journal(),other=new ConfiguredTextRuntime(f.store,f.config);assert.equal((await other.run('mission','fresh','restart',(await f.current()).revision)).status,'already-started');assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,0);
});
for(const durable of [false,true])for(const stop of ['cancel','quarantine','deadline'] as const)test(`${durable?'actual SurrealDB':'in-memory fixture'} ${stop} before provider claim admission prevents adapter calls and preserves durable intent`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await boundary(t,durable,'before',stop==='deadline'?(durable?5000:500):undefined);await f.until(()=>!!f.claimCommand());const owner=new ProductService(f.store);if(stop==='deadline'){const deadline=(await f.current()).value.works.find(w=>w.id==='fresh')!.runtimeRun!.ownership!.deadlineAt;await pause(Math.max(0,deadline-Date.now())+30);}else await owner.intervene('mission',{commandId:'other-host-stop',expectedRevision:(await f.current()).revision,command:stop==='cancel'?{type:'cancel',workId:'fresh'}:{type:'quarantine-runtime',workId:'fresh',runId:'claim-boundary',reason:'Other host observed intent; no call proof',acknowledgeUncertainOutcome:true}});f.release();const result=await f.run;assert.equal(result.status,stop==='deadline'?'blocked':'cancelled');const w=result.snapshot.value.works.find(w=>w.id==='fresh')!;assert.equal(f.calls.length,0);assert.equal(w.effects[0]!.providerDispatch,undefined);assert.equal(w.record,undefined);assert.equal(w.budget.reserved,4);if(stop!=='cancel'){assert.equal(w.effects[0]!.status,'unknown');assert.equal(w.budget.measured,null);}validateMissionJournalLineage(await f.journal());
 if(stop==='deadline'){
  if(durable){const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{SurrealStore}=await import('../src/storage.ts'),{growthStore}=await import('./support/growth-fixture.ts');assert.ok(f.store instanceof SurrealStore);const {store:target}=await growthStore(true);assert.ok(target instanceof SurrealStore);const bundle=await exportPortableBackup(f.store,f.artifacts);await restorePortableBackup(bundle,target,f.root+'/deadline-restored');assert.deepEqual((await target.load('mission'))!.value,result.snapshot.value);}
  await owner.intervene('mission',{commandId:'quarantine-expired-intent',expectedRevision:result.snapshot.revision,command:{type:'quarantine-runtime',workId:'fresh',runId:'claim-boundary',reason:'Owner retains declared deadline uncertainty',acknowledgeUncertainOutcome:true}});validateMissionJournalLineage(await f.journal());assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.effects[0]!.receipt,undefined);
 }
});
test('other host cancellation after committed claim acknowledgment is held prevents zero-start dispatch without reclaim',async t=>{
 const f=await boundary(t,false,'after');await f.until(()=>!!f.captured());const owner=new ProductService(f.store);await owner.intervene('mission',{commandId:'cancel-claimed',expectedRevision:(await f.current()).revision,command:{type:'cancel',workId:'fresh'}});f.release();assert.equal((await f.run).status,'cancelled');assert.equal(f.calls.length,0);assert.ok((await f.current()).value.works.find(w=>w.id==='fresh')!.effects[0]!.providerDispatch);
});
test('wrong owner/assignment/model/request fields, owner authority and injected admission claim are rejected without writes',async t=>{
 const f=await boundary(t);await f.until(()=>!!f.claimCommand());const original=f.claimCommand()!,revision=(await f.current()).revision,journal=await f.journal(),app=new Application(f.store,[f.runtime.app.actor('host-executor'),f.runtime.app.actor('host-verifier'),f.runtime.app.actor('local-owner')]);
 for(const patch of [{hostSessionId:'other-host'},{dispatchId:'other-dispatch'},{runId:'other-run'},{actorId:'host-verifier'},{assignmentId:'claim-boundary:verifier:assignment'},{provider:'other-provider'},{model:'other-model'},{configVersion:'other-config'},{requestHash:'bad'},{claimedAt:0},{extra:true}])await assert.rejects(app.dispatch({missionId:'mission',actorId:'host-executor',commandId:crypto.randomUUID(),expectedRevision:revision,command:{...original,claim:{...original.claim,...patch}} as any}));await assert.rejects(app.dispatch({missionId:'mission',actorId:'local-owner',commandId:'owner-not-provider',expectedRevision:revision,command:original}));const pending=(await f.current()).value.works.find(w=>w.id==='fresh')!.effects[0]!;await assert.rejects(app.dispatch({missionId:'mission',actorId:'host-executor',commandId:'injected-claim',expectedRevision:revision,command:{type:'admit-effect',workId:'fresh',effect:{...pending,id:'injected',providerDispatch:original.claim},reserve:0}}),/unclaimed/);assert.deepEqual(await f.journal(),journal);f.release();assert.equal((await f.run).status,'settled');
});
test('checksummed tampered claim cannot substitute original host binding in lineage, accepted read or causal prerequisites',async t=>{
 const f=await fixture(t),result=await f.product.run('mission','fresh','binding',(await f.current()).revision),target=result.snapshot.value.works.find(w=>w.id==='fresh')!,{workInputHash}=await import('../src/domain.ts');
 await f.product.admit('mission',{commandId:'claim-consumer',expectedRevision:result.snapshot.revision,workId:'consumer',title:'Exact accepted claim prerequisite',budget:8});await f.product.attachWorkPrerequisite('mission',{commandId:'claim-consumer-pin',expectedRevision:(await f.current()).revision,workId:'consumer',prerequisiteId:'fresh',criteriaHash:hash(target.criteria),inputHash:workInputHash(target),reason:'Original accepted provider claim evidence'});
 const mission=structuredClone((await f.current()).value),w=mission.works.find(w=>w.id==='fresh')!;w.effects[0]!.providerDispatch!.hostSessionId='other-host';w.record!.receipts=structuredClone(w.effects);const {checksum,...record}=w.record!;w.record!.checksum=hash(record);assert.throws(()=>validateProviderDispatchClaims(w));const {resolvedPrerequisites}=await import('../src/work-prerequisites.ts');assert.throws(()=>resolvedPrerequisites(mission,mission.works.find(w=>w.id==='consumer')!));const {validateMissionLineage}=await import('../src/backup-lineage.ts');assert.throws(()=>validateMissionLineage(mission));let reads=0;const store=new Proxy(f.store,{get(target,key){if(key==='readState')return async()=>({...await target.readState('mission'),snapshot:{...result.snapshot,value:mission}});const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}});const {readRecordArtifact}=await import('../src/record-artifact.ts');await assert.rejects(readRecordArtifact(store,{async read(){reads++;return ''; }},'mission','fresh',{recordId:w.record!.id,artifactVersion:w.artifact!.version,artifactSha256:w.artifact!.sha256}));assert.equal(reads,0);
});

test('claimed receipt requires exact original claim identity before any state change',async t=>{
 const f=await boundary(t,false,'after');await f.until(()=>!!f.captured());const input=f.captured()!,claim=f.claimCommand()!.claim,revision=(await f.current()).revision,before=await f.journal();
 for(const providerDispatchId of [undefined,'wrong-claim'])await assert.rejects(f.runtime.app.dispatch({missionId:'mission',commandId:crypto.randomUUID(),actorId:'host-executor',expectedRevision:revision,command:{type:'receipt',workId:'fresh',effectId:'claim-boundary:executor',outcome:'unknown',receipt:'Fixture not a real receipt',usage:null,...(providerDispatchId?{providerDispatchId}:{})}}),/original provider dispatch claim/);
 assert.deepEqual(await f.journal(),before);await new ProductService(f.store).intervene('mission',{commandId:'cancel-after-invalid-receipt',expectedRevision:revision,command:{type:'cancel',workId:'fresh'}});f.release();assert.equal((await f.run).status,'cancelled');assert.equal(f.calls.length,0);
});
