import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {ConnectionWorkbench} from '../src/connection-workbench.ts';
import {TextArtifactStore} from '../src/text-artifacts.ts';
import {InMemoryStore,SurrealStore,createHttpRpcTransport,initializeSurrealSchema} from '../src/storage.ts';
import type {Mission} from '../src/domain.ts';
import {ProductService} from '../src/product.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply,selectionField} from './support/workbench-client.ts';
import type {Handler} from './support/workbench-client.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
const eventually=async(check:()=>boolean)=>{const end=Date.now()+5000;while(!check()){assert.ok(Date.now()<end,'Client state timeout');await new Promise(r=>setTimeout(r,5));}};
test('connection grants preserve the full Mission scope contract and exact matching without effects',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-grant-scope-'));t.after(()=>rm(root,{recursive:true,force:true}));let sends=0;const store=new InMemoryStore<Mission>();
 const manager=new ConnectionWorkbench(store,new TextArtifactStore(join(root,'artifacts')),{allowFixture:true,transport:async()=>{sends++;assert.fail('Grant and preflight must not dispatch');}});
 manager.connect({id:'fixture',label:'Fixture',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});const connection=manager.list().connections[0]!;
 const exec=manager.selectModel(connection.id,{model:'exec',label:'Executor',expectedConfigHash:connection.configHash}),verify=manager.selectModel(connection.id,{model:'verify',label:'Verifier',expectedConfigHash:connection.configHash});const product=new ProductService(store,undefined,manager);
 for(const [index,scope] of ['s'.repeat(513),'s'.repeat(16000),'  multiline\nscope  '].entries()){
  const id='mission'+index,grant='grant'+index;manager.authorize({id:grant,scope,executorProfileId:exec.profileId,verifierProfileId:verify.profileId,maxOutputTokensPerCall:8,expectedConfigHash:manager.list().configHash});assert.equal(manager.list().runtime.authorizations.at(-1)!.scope,scope);
  await product.create({id,purpose:'Scope parity',scope,constraints:[],criteria:{version:1,description:'Text',oracle:'bounded-text-review/v1'}},'create'+index);await product.admit(id,{commandId:'admit'+index,expectedRevision:1,workId:'work',title:'Scope parity',budget:16});
  const choice={executorProfileId:exec.profileId,verifierProfileId:verify.profileId,authorizationId:grant,outputTokenCap:8};const preflight=await product.preflight(id,'work',2,choice);assert.ok(preflight);assert.equal(preflight.diagnostics.length,0);
  const mismatch=await product.preflight(id,'work',2,{...choice,authorizationId:index===0?'missing':'grant0'});assert.ok(mismatch?.diagnostics.some(d=>d.code==='authorization_mismatch'));
 }
 const before=manager.list();for(const scope of ['', '   ', 's'.repeat(16001)])assert.throws(()=>manager.authorize({id:'invalid',scope,executorProfileId:exec.profileId,verifierProfileId:verify.profileId,maxOutputTokensPerCall:8,expectedConfigHash:manager.list().configHash}),/scope/);assert.deepEqual(manager.list(),before);assert.equal(sends,0);
});
test('connection HTTP rejects invalid custom base URLs with actionable client errors and no mutation',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-connection-url-'));t.after(()=>rm(root,{recursive:true,force:true}));let sends=0;
 const manager=new ConnectionWorkbench(new InMemoryStore<Mission>(),new TextArtifactStore(join(root,'artifacts')),{transport:async()=>{sends++;assert.fail('Saving connection metadata must not contact a provider');}});
 const server=createWorkbench(new InMemoryStore<Mission>(),root,{connections:manager});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');
 const save=(baseUrl:unknown)=>fetch('http://127.0.0.1:'+address.port+'/connections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:'custom',label:'Custom',providerType:'compatible',baseUrl,mode:'https'})});
 for(const base of ['https://host/v1','not-a-url/',42,'https://host/v1/?key=private','http://host/v1/']){const response=await save(base);assert.equal(response.status,400,String(base));const body=await response.json();assert.match(body.error,/base URL/);assert.doesNotMatch(body.error,/private/);assert.equal(manager.list().connections.length,0);}
 assert.equal((await save('https://host/v1/')).status,200);assert.equal(manager.list().connections.length,1);assert.equal(sends,0);
});
for(const durable of [false,true])test(`${durable?'actual Surreal':'in-memory'} provider connect/discover/manual model/roles UI reaches accepted native fixture and never replays`,{skip:durable&&!process.env.MASSION_TEST_SURREAL_RPC},async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-provider-setup-'));t.after(()=>rm(root,{recursive:true,force:true}));const sends:{protocol:string;model:string}[]=[];
 const provider=createServer(async(req,res)=>{res.setHeader('content-type','application/json');const native=req.url!.startsWith('/anthropic/'),gemini=req.url!.startsWith('/gemini/');if(req.method==='GET'){const model=native?'native-executor':gemini?'native-reviewer':'chat-model';res.end(JSON.stringify(gemini?{models:[{name:'models/'+model,displayName:model,supportedGenerationMethods:['generateContent'],outputTokenLimit:16}]}:{data:[{id:model,display_name:model}]}));return;}let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);const model=native?body.model:gemini?'native-reviewer':body.model;const text=gemini?body.contents[0].parts[0].text:body.messages[0].content;const instruction=JSON.parse(text);sends.push({protocol:native?'anthropic':gemini?'gemini':'chat',model});const output=instruction.artifact?JSON.stringify({artifactSha256:instruction.binding.artifactSha256,criteriaVersion:instruction.criteria.version,criteriaHash:instruction.binding.criteriaHash,verdict:'passed',checks:[{criterion:instruction.criteria.description,passed:true,quote:'Native fixture result',reason:'Synthetic exact-text evidence'}]}):'Native fixture result';res.end(JSON.stringify(native?{id:'msg-fixture',type:'message',role:'assistant',model,stop_reason:'end_turn',content:[{type:'text',text:output}],usage:{input_tokens:3,output_tokens:2}}:gemini?{responseId:'fixture',modelVersion:model,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:output}]}}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:2,totalTokenCount:5}}:{id:'fixture',object:'chat.completion',created:1,model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:output}}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}}));});provider.listen(0,'127.0.0.1');await once(provider,'listening');t.after(async()=>{provider.closeAllConnections();await new Promise<void>(r=>provider.close(()=>r()));});const addr=provider.address();assert.ok(addr&&typeof addr==='object');
 const providerPort=addr.port;
 const options={endpoint:process.env.MASSION_TEST_SURREAL_RPC??'',namespace:'massion_storage_tests',database:'provider_setup_'+crypto.randomUUID().replaceAll('-','')};const transport=durable?createHttpRpcTransport(options):undefined;if(transport){await transport.query('DEFINE DATABASE '+options.database+';',{});await initializeSurrealSchema(transport);}const store=transport?new SurrealStore<Mission>(transport):new InMemoryStore<Mission>();const artifacts=new TextArtifactStore(join(root,'artifacts'));const manager=new ConnectionWorkbench(store,artifacts,{transport:fetch,allowFixture:true});const server=createWorkbench(store,root,{connections:manager});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const sa=server.address();assert.ok(sa&&typeof sa==='object');const base='http://127.0.0.1:'+sa.port;const handler:Handler=async(path,init)=>{const response=await fetch(base+path,init);return reply(await response.json(),response.status);};const app=harness(handler,{},undefined,{network:true,identity:crypto.randomUUID()});await eventually(()=>app.node('connection-status').textContent.includes('ready'));
 async function add(kind:string,path:string,discover:boolean,model:string){app.node('connection-kind').value=kind;await app.node('connection-kind').fire('change');app.node('connection-label').value=kind;app.node('connection-base').value=`http://127.0.0.1:${providerPort}/${path}/`;app.node('connection-mode').value='local-http-mock';await app.submit('connection-form');const connection=manager.list().connections.at(-1)!;if(discover){const buttons=app.all().filter(n=>n.textContent==='Explore models');assert.equal(buttons.at(-1)!.disabled,false,'Explore must unlock after saving a connection');await buttons.at(-1)!.fire('click');assert.equal(manager.list().connections.at(-1)!.discovery,'models-discovered');}const form=app.all().filter(n=>n.className==='model-connect-form').at(-1)!;selectionField(app,'manual-model-'+connection.id).value=model;selectionField(app,'model-label-'+connection.id).value=kind+' '+model;await form.fire('submit');assert.equal(app.all().filter(n=>n.textContent==='Explore models').every(n=>!n.disabled),true,'Rebuilt buttons must unlock after model selection');return manager.list().runtime.connections.at(-1)!.id;}
 const exec=await add('anthropic','anthropic',true,'native-executor');const verify=await add('gemini','gemini',true,'native-reviewer');await add('compatible','chat',false,'chat-model');assert.equal(sends.length,0);assert.match(app.node('connection-list').textContent,/live execution not verified/);assert.equal(manager.list().providerTypes.length,5);assert.equal(manager.list().agentBackends.every(v=>v.supported===false),true);
 selectionField(app,'grant-executor').value=exec;selectionField(app,'grant-verifier').value=verify;selectionField(app,'grant-scope').value='fixture';selectionField(app,'grant-cap').value='8';const grantForm=app.all().find(n=>n.className==='connection-authorization-form')!;grantForm.children.find(n=>n.textContent==='Permit these models for this scope')!.focus();await grantForm.fire('submit');assert.equal((app.context as any).document.activeElement.id,'grant-executor');assert.equal(manager.list().runtime.authorizations.length,1);assert.equal(app.all().filter(n=>n.textContent==='Explore models').every(n=>!n.disabled),true,'Rebuilt controls must unlock after scoped permission');
 app.node('purpose').value='Produce controlled native output';app.node('scope').value='fixture';app.node('criteria').value='Exact fixture text';app.node('criteria-oracle').value='bounded-text-review/v1';await app.submit('mission-form');app.node('work-title').value='Native providers';app.node('work-budget').value='16';await app.submit('work-form');const snapshot=JSON.parse(app.node('snapshot-json').textContent);const workId=snapshot.value.works[0].id;const grant=manager.list().runtime.authorizations[0]!.id;
 for(const [prefix,value] of [['executor-profile-',exec],['verifier-profile-',verify],['authorization-',grant],['output-cap-','8']]){const field=selectionField(app,prefix+workId);field.value=value!;await field.fire('change');}await app.all().find(n=>n.textContent==='Check selection')!.fire('click');await app.all().find(n=>n.className==='execution-form')!.fire('submit');await eventually(()=>app.node('work-list').textContent.includes('Acceptance: accepted'));assert.deepEqual(sends,[{protocol:'anthropic',model:'native-executor'},{protocol:'gemini',model:'native-reviewer'}]);const accepted=(await store.load(snapshot.value.id))!;assert.equal(accepted.value.works[0]!.record!.evidenceClass,'fixture');assert.equal(accepted.value.works[0]!.runtimeRun!.connectionBindings!.executor.profileId,exec);assert.equal(accepted.value.works[0]!.effects.every(e=>e.status==='succeeded'),true);const operations=transport?(await (store as SurrealStore<Mission>).exportJournal()).operations:(store as InMemoryStore<Mission>).inspect();validateMissionJournalLineage(operations);
 const reloaded=harness(handler,Object.fromEntries(app.storage),undefined,{network:true});await eventually(()=>reloaded.node('work-list').textContent.includes('Acceptance: accepted'));assert.equal(reloaded.calls.filter(c=>c.options.method==='POST').length,0);assert.deepEqual(await store.load(snapshot.value.id),accepted);assert.equal(sends.length,2);assert.equal([...app.storage].some(([k,v])=>/credential|secret|reference/i.test(k+v)),false);
 const activeSnapshot=structuredClone(accepted);activeSnapshot.value.works[0]!.execution='active';const activeReload=harness(async(path,init)=>path==='/missions/'+encodeURIComponent(snapshot.value.id)&&!init.method?reply(activeSnapshot):handler(path,init),Object.fromEntries(app.storage),undefined,{network:true});await eventually(()=>activeReload.node('work-list').textContent.includes('Execution: active'));assert.equal(activeReload.node('connection-fields').disabled,true,'Reloaded active Work locks provider configuration');assert.equal(activeReload.all().filter(n=>['Explore models','Use this model','Permit these models for this scope'].includes(n.textContent)).every(n=>n.disabled),true);const activeCalls=activeReload.calls.length;await activeReload.submit('connection-form');assert.equal(activeReload.calls.length,activeCalls);
 if(transport){const {exportPortableBackup,restorePortableBackup,openRestoredArtifacts}=await import('../src/portable-backup.ts');const bundle=await exportPortableBackup(store as SurrealStore<Mission>,artifacts);const target={...options,database:options.database+'_restored'};const targetTransport=createHttpRpcTransport(target);await targetTransport.query('DEFINE DATABASE '+target.database+';',{});await initializeSurrealSchema(targetTransport);const restored=new SurrealStore<Mission>(targetTransport),destination=join(root,'restored');await restorePortableBackup(bundle,restored,destination);assert.deepEqual(await restored.load(snapshot.value.id),accepted);validateMissionJournalLineage((await restored.exportJournal()).operations);const newSession=new ConnectionWorkbench(restored,openRestoredArtifacts(bundle,destination),{transport:async()=>{assert.fail('Restoration must not invoke a model');}});assert.equal(newSession.list().runtime.connections.length,0);assert.equal(newSession.list().runtime.authorizations.length,0);assert.equal((await newSession.run(snapshot.value.id,workId,'restored-run',accepted.revision)).status,'already-started');assert.equal(sends.length,2);}
 const c=manager.list().connections[0]!;manager.connect({id:c.id,label:'Changed',providerType:'anthropic',baseUrl:c.baseUrl,mode:'local-http-mock'});assert.equal(manager.list().runtime.authorizations.length,0);assert.equal(manager.list().runtime.connections.some(p=>p.id===exec),false);assert.equal(sends.length,2);
});
test('missing credentials, raw keys, stale discovery and hanging dependencies fail closed without effects',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-discovery-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new InMemoryStore<Mission>(),artifacts=new TextArtifactStore(join(root,'artifacts'));let sends=0;const manager=new ConnectionWorkbench(store,artifacts,{transport:async()=>{sends++;throw Error('private-host-error');}});const input={id:'account',label:'Anthropic',providerType:'anthropic',baseUrl:'https://api.anthropic.com/v1/',mode:'https'};assert.throws(()=>manager.connect({...input,apiKey:'private'}),/raw credentials/);manager.connect(input);assert.equal(manager.list().connections[0]!.credentialConfigured,false);assert.equal((await manager.discover('account',manager.list().connections[0]!.configHash)).status,'unavailable');assert.equal(sends,0);const selected=manager.selectModel('account',{model:'exact-model',label:'Manual model',expectedConfigHash:manager.list().connections[0]!.configHash});assert.ok(selected.runtime.connections[0]!.diagnostics.length);assert.throws(()=>manager.authorize({id:'grant',scope:'fixture',executorProfileId:selected.profileId,verifierProfileId:selected.profileId,maxOutputTokensPerCall:8,expectedConfigHash:selected.configHash}),/unavailable/);
 let release!:(r:Response)=>void;const pendingManager=new ConnectionWorkbench(store,artifacts,{transport:async()=>new Promise<Response>(r=>release=r),allowFixture:true});pendingManager.connect({id:'test',label:'test',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});const old=pendingManager.list().connections[0]!;const pending=pendingManager.discover('test',old.configHash);await new Promise(r=>setImmediate(r));pendingManager.connect({id:'test',label:'changed',providerType:'compatible',baseUrl:old.baseUrl,mode:'local-http-mock'});release(new Response(JSON.stringify({data:[{id:'old-model'}]}),{headers:{'content-type':'application/json'}}));assert.equal((await pending).status,'stale');assert.deepEqual(pendingManager.list().connections[0]!.models,[]);
 const hangs=new ConnectionWorkbench(store,artifacts,{transport:async()=>new Promise(()=>{}),allowFixture:true,discoveryTimeoutMs:10});hangs.connect({id:'test',label:'test',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});assert.equal((await hangs.discover('test',hangs.list().connections[0]!.configHash)).status,'unavailable');assert.doesNotMatch(JSON.stringify(manager.list()),/private-host-error|private/);
});
test('active ordinary Work prevents connection changes until pinned executor and verifier complete',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-active-config-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new InMemoryStore<Mission>(),artifacts=new TextArtifactStore(join(root,'artifacts'));let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);let sends=0;const manager=new ConnectionWorkbench(store,artifacts,{allowFixture:true,transport:async(_url,init)=>{const body=JSON.parse(String(init.body)),prompt=JSON.parse(body.messages[0].content);sends++;if(sends===1){entered();await gate;}const content=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Pinned output',reason:'fixture'}]}):'Pinned output';return new Response(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:body.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content}}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}}),{headers:{'content-type':'application/json'}});}});
 const input={id:'connection',label:'Pinned',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'};manager.connect(input);const account=manager.list().connections[0]!;const one=manager.selectModel('connection',{model:'executor',label:'exec',expectedConfigHash:account.configHash}),two=manager.selectModel('connection',{model:'verify',label:'verify',expectedConfigHash:account.configHash});const authorization={id:'grant',scope:'fixture',executorProfileId:one.profileId,verifierProfileId:two.profileId,maxOutputTokensPerCall:8,expectedConfigHash:two.configHash};manager.authorize(authorization);const product=new ProductService(store,undefined,manager);await product.create({id:'mission',purpose:'Pinned execution',scope:'fixture',constraints:[],criteria:{version:1,description:'Text',oracle:'bounded-text-review/v1'}},'create');await product.admit('mission',{commandId:'admit',expectedRevision:1,workId:'work',title:'Pinned',budget:16});const pending=product.run('mission','work','run',2,{executorProfileId:one.profileId,verifierProfileId:two.profileId,authorizationId:'grant',outputTokenCap:8});await ready;const before=manager.list();assert.throws(()=>manager.connect({...input,label:'changed'}),/Active Work/);assert.throws(()=>manager.selectModel('connection',{model:'new',label:'new',expectedConfigHash:account.configHash}),/Active Work/);assert.throws(()=>manager.authorize({...authorization,id:'new',expectedConfigHash:before.configHash}),/Active Work/);assert.deepEqual(manager.list(),before);release();assert.equal((await pending).status,'settled');assert.equal(sends,2);assert.equal((await store.load('mission'))!.value.works[0]!.acceptance,'accepted');manager.connect({...input,label:'changed'});assert.equal(manager.list().runtime.authorizations.length,0);
});
test('official registry discovery uses per-protocol fake credentials and declares unverified live status',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-official-models-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new InMemoryStore<Mission>(),artifacts=new TextArtifactStore(join(root,'artifacts'));const requests:{url:string;method:string;header:string}[]=[];const manager=new ConnectionWorkbench(store,artifacts,{resolveCredential:async req=>{assert.equal(req.secretRef,'test-reference');assert.ok(req.endpoint.endsWith('/models'));return 'fake-fixture-secret';},transport:async(url,init)=>{const h=new Headers(init.headers);requests.push({url,method:String(init.method),header:h.get('authorization')??h.get('x-api-key')??h.get('x-goog-api-key')??''});if(url.includes('anthropic'))assert.equal(h.get('anthropic-version'),'2023-06-01');return new Response(JSON.stringify(url.includes('googleapis')?{models:[{name:'models/exact',displayName:'Exact',supportedGenerationMethods:['generateContent']},{name:'models/embed',displayName:'Embed',supportedGenerationMethods:['embedContent']}]}:{data:[{id:'exact'}]}),{headers:{'content-type':'application/json'}});}});
 for(const [providerType,baseUrl] of [['openai','https://api.openai.com/v1/'],['openrouter','https://openrouter.ai/api/v1/'],['anthropic','https://api.anthropic.com/v1/'],['gemini','https://generativelanguage.googleapis.com/v1beta/']]){manager.connect({id:providerType,label:providerType,providerType,baseUrl,mode:'https',secretRef:'test-reference'});const account=manager.list().connections.at(-1)!;const models=await manager.discover(account.id,account.configHash);assert.equal(models.status,'listed');assert.deepEqual(models.models.map(m=>m.id),['exact']);assert.equal(models.liveVerified,false);assert.equal(manager.list().connections.at(-1)!.connectionStatus,'configured-unverified');const selected=manager.selectModel(account.id,{model:'exact',label:providerType+' exact',expectedConfigHash:account.configHash});assert.equal(selected.runtime.connections.at(-1)!.diagnostics.length,0);}
 assert.equal(requests.length,4);assert.equal(requests.every(r=>r.method==='GET'),true);assert.equal(requests.filter(r=>r.header==='Bearer fake-fixture-secret').length,2);assert.doesNotMatch(JSON.stringify(manager.list()),/test-reference|fake-fixture-secret/);const profiles=manager.list().runtime.connections;assert.throws(()=>manager.authorize({id:'live',scope:'fixture',executorProfileId:profiles[0]!.id,verifierProfileId:profiles[1]!.id,maxOutputTokensPerCall:8,expectedConfigHash:manager.list().configHash}),/separately authorized/);
});
test('native unknown effect remains retained and connection replacement cannot replay it',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-native-unknown-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new InMemoryStore<Mission>(),artifacts=new TextArtifactStore(join(root,'artifacts'));let sends=0;const manager=new ConnectionWorkbench(store,artifacts,{allowFixture:true,transport:async()=>{sends++;throw Error('ambiguous native send');}});const input={id:'native',label:'Native',providerType:'anthropic',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'};manager.connect(input);const account=manager.list().connections[0]!;const exec=manager.selectModel('native',{model:'exec',label:'exec',expectedConfigHash:account.configHash}),verify=manager.selectModel('native',{model:'verify',label:'verify',expectedConfigHash:account.configHash});manager.authorize({id:'grant',scope:'fixture',executorProfileId:exec.profileId,verifierProfileId:verify.profileId,maxOutputTokensPerCall:8,expectedConfigHash:verify.configHash});const product=new ProductService(store,undefined,manager);await product.create({id:'mission',purpose:'Unknown',scope:'fixture',constraints:[],criteria:{version:1,description:'Text',oracle:'bounded-text-review/v1'}},'create');await product.admit('mission',{commandId:'admit',expectedRevision:1,workId:'work',title:'Unknown',budget:16});await product.run('mission','work','run',2,{executorProfileId:exec.profileId,verifierProfileId:verify.profileId,authorizationId:'grant',outputTokenCap:8});const before=(await store.load('mission'))!;assert.equal(before.value.works[0]!.effects[0]!.status,'unknown');assert.equal(before.value.works[0]!.budget.measured,null);assert.equal(before.value.works[0]!.record,undefined);manager.connect({...input,label:'Replacement'});assert.equal((await product.run('mission','work','new-run',before.revision)).status,'already-started');assert.deepEqual(await store.load('mission'),before);assert.equal(sends,1);validateMissionJournalLineage(store.inspect());
});
test('client provider change discards outstanding discovery results and preserves no credential browser state',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-provider-client-stale-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new InMemoryStore<Mission>(),artifacts=new TextArtifactStore(join(root,'artifacts'));const manager=new ConnectionWorkbench(store,artifacts,{transport:async()=>new Promise(()=>{}),allowFixture:true});manager.connect({id:'existing',label:'Existing',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});let release!:(r:ReturnType<typeof reply>)=>void;const handler:Handler=async(path)=>path==='/connections'?reply(manager.list()):path==='/connections/existing/models'?new Promise(r=>release=r):path==='/health'?reply({status:'ready'}):path==='/providers'?reply({providers:[],selection:{status:'unavailable'},runtime:manager.configuration()}):reply({cursor:0,events:[]});const app=harness(handler,{},undefined,{network:true});await eventually(()=>app.node('connection-status').textContent.includes('ready'));const pending=app.all().find(n=>n.textContent==='Explore models')!.fire('click');await eventually(()=>!!release);assert.equal(app.node('connection-fields').disabled,false,'Provider selector must remain available to discard readonly discovery');app.node('connection-kind').value='anthropic';await app.node('connection-kind').fire('change');release(reply({status:'listed',models:[{id:'stale-model',label:'Stale',outputTokenLimit:8}],message:'stale-result'}));await pending;assert.doesNotMatch(app.node('connection-list').textContent,/stale-model|stale-result/);assert.equal(selectionField(app,'discovered-existing').children.length,1);assert.deepEqual([...app.storage.keys()],['massion.workbench.cursor']);assert.equal(app.storage.get('massion.workbench.cursor'),'0');
});

test('Gemini discovery rejects malformed name and generation methods without inventing a model ID',async t=>{const root=await mkdtemp(join(tmpdir(),'massion-invalid-models-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new InMemoryStore<Mission>(),artifacts=new TextArtifactStore(join(root,'artifacts'));for(const metadata of [{supportedGenerationMethods:['generateContent']},{name:'models/exact',supportedGenerationMethods:'generateContent'}]){const manager=new ConnectionWorkbench(store,artifacts,{allowFixture:true,transport:async()=>new Response(JSON.stringify({models:[metadata]}),{headers:{'content-type':'application/json'}})});manager.connect({id:'gemini',label:'Gemini fixture',providerType:'gemini',baseUrl:'http://127.0.0.1:9999/v1beta/',mode:'local-http-mock'});const result=await manager.discover('gemini',manager.list().connections[0]!.configHash);assert.equal(result.status,'unavailable');assert.deepEqual(result.models,[]);}});
test('discovery completion cannot unlock connection mutations during busy or unknown Mission creation',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-connection-lock-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const manager=new ConnectionWorkbench(new InMemoryStore<Mission>(),new TextArtifactStore(join(root,'artifacts')),{transport:fetch,allowFixture:true});manager.connect({id:'existing',label:'Existing',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});
 let discovery!:(r:ReturnType<typeof reply>)=>void,mission!:(r:ReturnType<typeof reply>)=>void;
 const handler:Handler=async(path)=>path==='/connections'?reply(manager.list()):path==='/connections/existing/models'?new Promise(r=>discovery=r):path==='/missions'?new Promise(r=>mission=r):path==='/health'?reply({status:'ready'}):path==='/providers'?reply({providers:[],selection:{status:'unavailable'},runtime:manager.configuration()}):reply({cursor:0,events:[]});
 const app=harness(handler,{},undefined,{network:true});await eventually(()=>app.node('connection-status').textContent.includes('ready'));
 const pending=app.all().find(n=>n.textContent==='Explore models')!.fire('click');await eventually(()=>!!discovery);
 app.node('purpose').value='Lock regression';app.node('scope').value='fixture';app.node('criteria').value='Evidence';const creation=app.submit('mission-form');await eventually(()=>!!mission);
 discovery(reply({status:'listed',models:[],message:'Listed'}));await pending;
 const locked=()=>{assert.equal(app.node('connection-fields').disabled,true);assert.equal(app.all().filter(n=>['Explore models','Use this model','Permit these models for this scope'].includes(n.textContent)).every(n=>n.disabled),true);};locked();
 mission(reply({error:'Unknown result',outcome:'unknown'},503));await creation;locked();
 const count=app.calls.length;await app.submit('connection-form');await app.all().find(n=>n.className==='model-connect-form')!.fire('submit');await app.all().find(n=>n.textContent==='Explore models')!.fire('click');assert.equal(app.calls.length,count,'Unknown Mission outcome must also guard programmatic submission');
});

test('failed reconnect setup read removes stale mutation controls without replay or credential persistence',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-setup-reconnect-'));t.after(()=>rm(root,{recursive:true,force:true}));const manager=new ConnectionWorkbench(new InMemoryStore<Mission>(),new TextArtifactStore(join(root,'artifacts')),{transport:fetch,allowFixture:true});manager.connect({id:'existing',label:'Existing',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});let setupDown=false;const posts:string[]=[];const handler:Handler=(path,init)=>{if(init.method==='POST'){posts.push(path);return reply(manager.list());}return path==='/health'?reply({status:'ready'}):path==='/providers'?reply({providers:[],selection:{status:'unavailable'},runtime:manager.configuration()}):path==='/connections'?setupDown?reply({error:'Unavailable'},503):reply(manager.list()):reply({cursor:0,events:[]});};const app=harness(handler,{},undefined,{network:true});await eventually(()=>app.node('sync-notice').hidden);const detached=app.all().find(n=>n.textContent==='Explore models')!;setupDown=true;await app.windowEvent('online');await eventually(()=>app.node('sync-notice').hidden);assert.equal(app.node('connection-fields').disabled,true);assert.equal(app.node('connection-list').children.length,0);app.node('connection-label').value='No stale save';await app.submit('connection-form');await detached.fire('click');assert.deepEqual(posts,[]);assert.deepEqual([...app.storage.keys()],['massion.workbench.cursor']);
});

test('reconnect fences delayed setup acknowledgement and refreshes the committed state before unlocking',async t=>{
 const root=await mkdtemp(join(tmpdir(),'massion-setup-epoch-'));t.after(()=>rm(root,{recursive:true,force:true}));const manager=new ConnectionWorkbench(new InMemoryStore<Mission>(),new TextArtifactStore(join(root,'artifacts')),{transport:fetch,allowFixture:true});const input={id:'existing',label:'Current host connection',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'};manager.connect(input);let release!:(value:ReturnType<typeof reply>)=>void,releaseSetup!:(value:ReturnType<typeof reply>)=>void,holdSetup=false,posts=0;const handler:Handler=(path,init)=>{if(init.method==='POST'){posts++;return new Promise(resolve=>release=resolve);}return path==='/health'?reply({status:'ready'}):path==='/providers'?reply({providers:[],selection:{status:'unavailable'},runtime:manager.configuration()}):path==='/connections'?holdSetup?new Promise(resolve=>releaseSetup=resolve):reply(manager.list()):reply({cursor:0,events:[]});};const app=harness(handler,{},undefined,{network:true});await eventually(()=>app.node('sync-notice').hidden);app.node('connection-label').value='A pending setup edit';const pending=app.submit('connection-form');await eventually(()=>typeof release==='function');await app.windowEvent('offline');await app.windowEvent('online');await eventually(()=>app.node('sync-notice').hidden);const stale=structuredClone(manager.list());stale.connections[0]!.label='Stale mutation acknowledgement';manager.connect({...input,label:'Committed after the reconnect read'});holdSetup=true;release(reply(stale));await pending;await eventually(()=>typeof releaseSetup==='function');assert.equal(app.node('sync-notice').hidden,false);assert.equal(app.node('connection-fields').disabled,true);assert.equal(posts,1);assert.doesNotMatch(app.node('connection-list').textContent,/Stale mutation acknowledgement/);holdSetup=false;releaseSetup(reply(manager.list()));await eventually(()=>app.node('sync-notice').hidden);assert.match(app.node('connection-list').textContent,/Committed after the reconnect read/);assert.equal(posts,1);assert.deepEqual([...app.storage.keys()],['massion.workbench.cursor']);
});
