import test from 'node:test';
import assert from 'node:assert/strict';
import {chmod,writeFile} from 'node:fs/promises';
import {hash} from '../src/domain.ts';
import type {Mission} from '../src/domain.ts';
import type {Store} from '../src/storage.ts';
import {readRejectedText} from '../src/rejected-text.ts';
import {rejectedFixture,rejectedContent} from './support/rejected-text-fixture.ts';
for(const durable of [false,true]){
 const options={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} exact failed candidate read exposes original rejection without acceptance or writes`,options,async t=>{const f=await rejectedFixture(t,durable),before=await f.journal(),result=await f.product.readRejectedText('mission','fresh',f.input);assert.equal(result!.content,rejectedContent);assert.equal(result!.acceptance,'failed');assert.equal(result!.recordId,null);assert.equal(result!.verdict.status,'failed');assert.equal(result!.evidenceClass,'fixture');assert.equal(JSON.stringify(result).includes(f.work.artifact!.path),false);assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,2);const query=new URLSearchParams({work:'fresh',binding:f.input.binding,version:String(f.input.artifactVersion),sha256:f.input.artifactSha256}),response=await fetch(f.base+'/missions/mission/rejected-artifact?'+query,{headers:{'X-Massion-Feed':f.input.feedId}});assert.equal(response.status,200);assert.equal((await response.json()).content,rejectedContent);assert.deepEqual(await f.journal(),before);});
 test(`${durable?'actual DB':'memory'} stale binding, accepted Record, wrong feed and injected query path fail without fallback`,options,async t=>{const f=await rejectedFixture(t,durable),before=await f.journal();for(const input of [{...f.input,binding:'a'.repeat(64)},{...f.input,feedId:'other-db'},{...f.input,artifactSha256:'b'.repeat(64)}])await assert.rejects(f.product.readRejectedText('mission','fresh',input));const accepted=(await f.current()).value.works[0]!;await assert.rejects(f.product.readRejectedText('mission',accepted.id,{binding:hash(accepted),artifactVersion:accepted.artifact!.version,artifactSha256:accepted.artifact!.sha256}));const query=new URLSearchParams({work:'fresh',binding:f.input.binding,version:String(f.input.artifactVersion),sha256:f.input.artifactSha256});for(const suffix of ['&path=/etc/passwd','&binding='+f.input.binding,'&record=forged'])assert.equal((await fetch(f.base+'/missions/mission/rejected-artifact?'+query+suffix)).status,400);assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,2);});
 test(`${durable?'actual DB':'memory'} tampered artifact bytes cannot be shown as original rejected result`,options,async t=>{const f=await rejectedFixture(t,durable);await chmod(f.work.artifact!.path,0o600);await writeFile(f.work.artifact!.path,'Replaced bytes');await chmod(f.work.artifact!.path,0o400);await assert.rejects(f.product.readRejectedText('mission','fresh',f.input));assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.acceptance,'failed');assert.equal(f.calls.length,2);});
}
test('unknown effects and forged runtime/criteria/verdict bindings reject before artifact read',async t=>{const f=await rejectedFixture(t);for(const mutate of [(w:any)=>w.effects[0].status='unknown',(w:any)=>w.runtimeRun.inputHash='a'.repeat(64),(w:any)=>w.verdict.artifactSha256='b'.repeat(64),(w:any)=>w.criteria.version++]){const state=await f.store.readState('mission'),w=state.snapshot!.value.works.find(w=>w.id==='fresh')!;mutate(w);const proxy=new Proxy(f.store,{get(target,key){if(key==='readState')return async()=>state;const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}) as Store<Mission>;let reads=0;await assert.rejects(readRejectedText(proxy,{read:async()=>{reads++;return rejectedContent;}},'mission','fresh',{...f.input,binding:hash(w)}));assert.equal(reads,0);}});
test('asynchronous read rechecks exact Work and feed; unrelated writes preserve pinned failure',async t=>{const f=await rejectedFixture(t);let release!:(()=>void);const gate=new Promise<void>(r=>release=r),pending=readRejectedText(f.store,{read:async a=>{await gate;return f.artifacts.read(a);}},'mission','fresh',f.input);await f.product.intervene('mission',{commandId:'new-steer',expectedRevision:(await f.current()).revision,command:{type:'steer',workId:'fresh',instruction:'Owner later instruction'}});release();await assert.rejects(pending);assert.equal(f.calls.length,2);});
test('feed replacement during artifact read rejects even with unchanged rejected bytes',async t=>{const f=await rejectedFixture(t);let reads=0;const proxy=new Proxy(f.store,{get(target,key){if(key==='readState')return async(...args:Parameters<Store<Mission>['readState']>)=>{const state=await target.readState(...args);if(++reads>1)state.feedId='replacement-db';return state;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}) as Store<Mission>;await assert.rejects(readRejectedText(proxy,f.artifacts,'mission','fresh',f.input));assert.equal(reads,2);assert.equal(f.calls.length,2);});
test('unrelated owner admission does not substitute pinned rejected evidence',async t=>{const f=await rejectedFixture(t),reader={read:async(a:any)=>{await f.product.admit('mission',{commandId:'unrelated',expectedRevision:(await f.current()).revision,workId:'unrelated',title:'Owner later Work',budget:8});return f.artifacts.read(a);}},result=await readRejectedText(f.store,reader,'mission','fresh',f.input);assert.equal(result!.content,rejectedContent);assert.equal(result!.acceptance,'failed');assert.equal(f.calls.length,2);});

for(const durable of [false,true])test(`${durable?'actual DB':'memory'} normal owner cancellation preserves failed evidence but prevents a new text read`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await rejectedFixture(t,durable);await f.product.intervene('mission',{commandId:'owner-cancel-failed',expectedRevision:(await f.current()).revision,command:{type:'cancel',workId:'fresh'}});const w=(await f.current()).value.works.find(w=>w.id==='fresh')!,journal=await f.journal();assert.equal(w.execution,'cancelled');assert.deepEqual(w.artifact,f.work.artifact);assert.deepEqual(w.verdict,f.work.verdict);await assert.rejects(f.product.readRejectedText('mission','fresh',{...f.input,binding:hash(w)}));assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,2);});
