import test from 'node:test';
import assert from 'node:assert/strict';
import {runInContext} from 'node:vm';
import {selectionField} from './support/workbench-client.ts';
import {rejectedFixture,rejectedContent} from './support/rejected-text-fixture.ts';
for(const durable of [false,true]){
 const options={skip:durable&&!process.env.SURREAL_TEST_RUNTIME};
 test(`${durable?'actual DB':'memory'} owner inspects rejected bytes and failure literally without POST or accepted Record`,options,async t=>{const f=await rejectedFixture(t,durable),app=await f.client(),journal=await f.journal();app.node('work-title').value='Keep future correction draft';const read=selectionField(app,'work-rejected-text-read-fresh');read.focus();await read.fire('click');assert.equal(selectionField(app,'work-rejected-text-content-fresh').textContent,rejectedContent);assert.match(selectionField(app,'work-rejected-text-verdict-fresh').textContent,/failed|Controlled known incorrect/);assert.match(selectionField(app,'work-rejected-text-status-fresh').textContent,/Failed Assurance remains failed/);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);assert.equal(app.node('work-title').value,'Keep future correction draft');assert.equal(app.calls.filter(c=>c.options.method==='POST').length,0);assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.record,undefined);assert.equal(f.calls.length,2);assert.deepEqual(await f.journal(),journal);const fresh=await f.client();assert.equal(fresh.calls.some(c=>c.path.includes('/rejected-artifact?')),false);assert.equal(selectionField(fresh,'work-rejected-text-content-fresh').textContent,'');});
 test(`${durable?'actual DB':'memory'} cancel ignores late rejected text and preserves moved focus`,options,async t=>{const f=await rejectedFixture(t,durable,'held'),app=await f.client(),read=selectionField(app,'work-rejected-text-read-fresh'),pending=read.fire('click');await f.until(()=>app.calls.some(c=>c.path.includes('/rejected-artifact?')));await selectionField(app,'work-rejected-text-cancel-fresh').fire('click');app.node('sequence-summary').focus();f.release();await pending;assert.equal(selectionField(app,'work-rejected-text-content-fresh').textContent,'');assert.match(selectionField(app,'work-rejected-text-status-fresh').textContent,/cancelled/);assert.equal(runInContext('document.activeElement.id',app.context),'sequence-summary');assert.equal(f.calls.length,2);});
 test(`${durable?'actual DB':'memory'} late result cannot restore text from a previous Mission`,options,async t=>{const f=await rejectedFixture(t,durable,'held'),app=await f.client(),old=selectionField(app,'work-rejected-text-content-fresh'),pending=selectionField(app,'work-rejected-text-read-fresh').fire('click');await f.until(()=>app.calls.some(c=>c.path.includes('/rejected-artifact?')));await app.navigateFragment('#mission=other');await f.until(()=>app.node('loaded-id').textContent==='other');f.release();await pending;assert.equal(old.textContent,'');assert.equal(app.node('loaded-id').textContent,'other');assert.equal(runInContext('rejectedTextReads.size',app.context),0);assert.equal(f.calls.length,2);});
}
for(const mode of ['wrong-feed','bad-bytes','wrong-class'] as const)test(`${mode} reply cannot expose or upgrade rejected candidate`,async t=>{const f=await rejectedFixture(t,false,mode),app=await f.client();await selectionField(app,'work-rejected-text-read-fresh').fire('click');assert.equal(selectionField(app,'work-rejected-text-content-fresh').textContent,'');assert.equal(selectionField(app,'work-rejected-text-verdict-fresh').textContent,'');assert.match(selectionField(app,'work-rejected-text-status-fresh').textContent,/not verified/);assert.equal(f.calls.length,2);assert.equal(app.calls.filter(c=>c.options.method==='POST').length,0);});

test('keyboard cancel returns focus to deliberate Read while discarded late reply stays empty',async t=>{const f=await rejectedFixture(t,false,'held'),app=await f.client(),pending=selectionField(app,'work-rejected-text-read-fresh').fire('click');await f.until(()=>app.calls.some(c=>c.path.includes('/rejected-artifact?')));const cancel=selectionField(app,'work-rejected-text-cancel-fresh');cancel.focus();await cancel.fire('click');assert.equal(runInContext('document.activeElement.id',app.context),'work-rejected-text-read-fresh');f.release();await pending;assert.equal(selectionField(app,'work-rejected-text-content-fresh').textContent,'');});
