import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,lstat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {Application} from '../src/application.ts';
import type {Mission} from '../src/domain.ts';
import {InMemoryStore,SurrealStore,createHttpRpcTransport,journalRestoreRpcRequestBytes,journalChecksum} from '../src/storage.ts';
import {TextArtifactStore} from '../src/text-artifacts.ts';
import {exportPortableBackup,parsePortableBackup} from '../src/portable-backup.ts';
import {growthStore} from './support/growth-fixture.ts';
async function fixture(t:import('node:test').TestContext,rich=false){
 const root=await mkdtemp(join(tmpdir(),'massion-capacity-'));t.after(()=>rm(root,{recursive:true,force:true}));const memory=new InMemoryStore<Mission>(),app=new Application(memory,[{id:'owner',roles:['owner']}]);await app.create({id:'capacity',purpose:rich?'Known fixture " \\ 한글 🌙 '.repeat(300):'Local fixture " \\ 한글 🌙',scope:'local',constraints:[],criteria:{version:1,description:'Retain literal original history',oracle:'fixture-capacity/v1'}},'owner','create');
 for(let i=0;i<(rich?32:1);i++)await app.dispatch({missionId:'capacity',commandId:'admit-'+i,expectedRevision:i+1,actorId:'owner',command:{type:'admit-work',workId:'work-'+i,title:'Original Work '+i,budget:0}});const operations=[...memory.inspect()],journal={schemaVersion:2 as const,head:operations.length,operations},serialized=await exportPortableBackup({exportJournal:async()=>journal},new TextArtifactStore(join(root,'source'))),bundle=join(root,'bundle.json'),target=join(root,'target');await writeFile(bundle,serialized,{mode:0o600});return {root,memory,journal,serialized,bundle,target,bytes:journalRestoreRpcRequestBytes(journal)};
}
const cli=(s:Awaited<ReturnType<typeof fixture>>,mode:string,extra:string[]=[],endpoint='http://127.0.0.1:1/rpc',namespace='unused',database='unused')=>[ 'scripts/backup.ts',mode,endpoint,namespace,database,s.target,s.bundle,...extra];
async function absent(path:string){await assert.rejects(lstat(path),(error:any)=>error.code==='ENOENT');}
test('restore wire measurement equals the real UTF-8 transport body including escaped values and generated event/outbox rows',async()=>{
 const source=new InMemoryStore<{text:string}>();await source.commit({id:'source',commandId:'unicode',fingerprint:'fixture',expectedRevision:0,value:{text:'" \\ 한글 🌙'.repeat(100)},events:[{type:'fixture',text:'" \\ 한글 🌙'}],outbox:[{id:'out',text:'" \\ 한글 🌙'}]});const journal={schemaVersion:2 as const,head:1,operations:[...source.inspect()]};let captured=0,calls=0;const transport=createHttpRpcTransport({endpoint:'http://127.0.0.1:1/rpc',namespace:'fixture',database:'fixture',fetch:async(_url,options)=>{calls++;const body=String(options!.body);captured=Buffer.byteLength(body);const envelope=JSON.parse(body),values=Object.values(envelope.params[1]).map(v=>JSON.parse(v as string));assert.match(body,/eventRows/);assert.match(body,/outboxRows/);return new Response(JSON.stringify({id:envelope.id,result:[...values.map(()=>({status:'OK',result:null})),{status:'OK',result:{status:'restored',head:values[1],checksum:values[2],restoreId:values[3]}}]}),{headers:{'content-type':'application/json'}});}});await new SurrealStore(transport).restoreJournal(journal);assert.equal(calls,1);assert.equal(journalRestoreRpcRequestBytes(journal),captured);assert.equal(journalChecksum(journal),journalChecksum({schemaVersion:2,head:1,operations:[...source.inspect()]}));
});
test('offline restore-check validates the bundle and exact budget boundary without creating a root or accessing unreachable DB',async t=>{
 const s=await fixture(t);for(const budget of [s.bytes-1,s.bytes]){const child=spawnSync(process.execPath,cli(s,'restore-check',['--rpc-body-budget',String(budget)]),{encoding:'utf8'});assert.equal(child.status,budget<s.bytes?1:0,child.stderr);const result=JSON.parse(child.stdout);assert.equal(result.rpcRequestBytes,s.bytes);assert.equal(result.serverCapacity,'not-discovered');assert.equal(result.changes,'none');assert.equal(result.status,budget<s.bytes?'blocked':'within-client-budget');await absent(s.target);}const original=await s.memory.load('capacity');const invalid=JSON.parse(s.serialized);invalid.journal.operations[0].value.purpose='tampered';await writeFile(s.bundle,JSON.stringify(invalid));const child=spawnSync(process.execPath,cli(s,'restore-check'),{encoding:'utf8'});assert.notEqual(child.status,0);assert.match(child.stderr,/checksum/);assert.deepEqual(await s.memory.load('capacity'),original);await absent(s.target);
});
test('actual normal restore CLI blocks over-budget request before all schema/network/root/artifact mutations',async t=>{
 const s=await fixture(t);let requests=0;const server=createServer((_request,response)=>{requests++;response.writeHead(500);response.end('Trap: no request permitted');});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const child=spawn(process.execPath,cli(s,'restore',['--rpc-body-budget','1'],'http://127.0.0.1:'+address.port+'/rpc'),{stdio:['ignore','pipe','pipe']});let error='';child.stderr.on('data',d=>error+=d);assert.deepEqual(await once(child,'exit'),[1,null]);assert.match(error,/blocked before any database request or artifact mutation/);assert.equal(requests,0);await absent(s.target);
});
test('rich valid backup exceeding default 4MiB wire budget blocks offline; explicit bounded budget remains capacity-unknown',async t=>{
 const s=await fixture(t,true);assert.ok(s.bytes>4*1024*1024);const blocked=spawnSync(process.execPath,cli(s,'restore-check'),{encoding:'utf8'});assert.equal(blocked.status,1,blocked.stderr);assert.equal(JSON.parse(blocked.stdout).rpcRequestBytes,s.bytes);const explicit=spawnSync(process.execPath,cli(s,'restore-check',['--rpc-body-budget',String(s.bytes)]),{encoding:'utf8'});assert.equal(explicit.status,0,explicit.stderr);assert.equal(JSON.parse(explicit.stdout).serverCapacity,'not-discovered');assert.match(JSON.parse(explicit.stdout).guidance,/not a server-capacity or success guarantee/);await absent(s.target);
});
test('invalid, unbounded or export-only budget options fail closed',async t=>{
 const s=await fixture(t);for(const value of ['0','-1','01','1.5','1e6','Infinity','67108865','999999999999999999999']){const r=spawnSync(process.execPath,cli(s,'restore',['--rpc-body-budget',value]),{encoding:'utf8'});assert.notEqual(r.status,0);await absent(s.target);}const r=spawnSync(process.execPath,cli(s,'export',['--rpc-body-budget','100']),{encoding:'utf8'});assert.notEqual(r.status,0);
});
test('actual DB explicit exact-budget CLI restores a fresh small destination preserving source and effects-held behavior',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const s=await fixture(t),{store,transport}=await growthStore(true),database=(await transport!.query('RETURN $session.db;',{}))[0] as string,original=await s.memory.load('capacity');assert.ok(store instanceof SurrealStore);const before=await store.exportJournal();const over=spawnSync(process.execPath,cli(s,'restore',['--rpc-body-budget','1'],process.env.MASSION_TEST_SURREAL_RPC!,process.env.MASSION_TEST_SURREAL_NAMESPACE!,database),{encoding:'utf8'});assert.equal(over.status,1);assert.deepEqual(await store.exportJournal(),before);await absent(s.target);const restore=spawnSync(process.execPath,cli(s,'restore',['--rpc-body-budget',String(s.bytes)],process.env.MASSION_TEST_SURREAL_RPC!,process.env.MASSION_TEST_SURREAL_NAMESPACE!,database),{encoding:'utf8',timeout:30000});assert.equal(restore.status,0,restore.stderr);const result=JSON.parse(restore.stdout);assert.equal(result.rpcRequestBytes,s.bytes);assert.equal(result.effectsReplayed,0);assert.equal(result.serverCapacity,'not-discovered');assert.deepEqual(await store.load('capacity'),original);assert.deepEqual(await store.exportJournal(),s.journal);assert.deepEqual(await s.memory.load('capacity'),original);assert.equal(parsePortableBackup(s.serialized).journal.head,result.head);
});
