/** Real backup CLI -> clean DB/root -> normal host exact accepted-text route. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import type {ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {createServer} from 'node:http';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {rename,readFile} from 'node:fs/promises';
import {textFixture} from './support/record-artifact-fixture.ts';
import {growthStore} from './support/growth-fixture.ts';
import {SurrealStore,createHttpRpcTransport,initializeSurrealSchema} from '../src/storage.ts';
import type {Mission} from '../src/domain.ts';
import {verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';
const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),backup=fileURLToPath(new URL('../scripts/backup.ts',import.meta.url));
async function proof(t:import('node:test').TestContext,browserEnabled=false){
 const {store,transport}=await growthStore(true),f=await textFixture(t,store);assert.ok(transport&&store instanceof SurrealStore);const sourceDB=(await transport.query('RETURN $session.db;',{}))[0] as string,namespace=process.env.MASSION_TEST_SURREAL_NAMESPACE!,endpoint=process.env.MASSION_TEST_SURREAL_RPC!,destDB='restored_ui_'+crypto.randomUUID().replaceAll('-',''),bundle=join(f.root,'backup.json'),artifactRoot=join(f.root,'restored-artifacts');const run=(args:string[])=>{const r=spawnSync(process.execPath,[backup,...args],{encoding:'utf8',timeout:30000});assert.equal(r.status,0,r.stderr);return r.stdout;};run(['export',endpoint,namespace,sourceDB,f.artifacts.root,bundle]);await transport.query('DEFINE DATABASE '+destDB+';',{});assert.equal(JSON.parse(run(['restore',endpoint,namespace,destDB,artifactRoot,bundle])).effectsReplayed,0);await rename(f.artifacts.root,join(f.root,'preserved-original'));const targetTransport=createHttpRpcTransport({endpoint,namespace,database:destDB});await initializeSurrealSchema(targetTransport);const dest=new SurrealStore<Mission>(targetTransport),before=await dest.load('mission'),journal=await dest.exportJournal(),outbox=(await targetTransport.query('SELECT * FROM massion_outbox;',{}))[0];assert.deepEqual(before!.value,(await store.load('mission'))!.value);const record=before!.value.works[0]!.record!,argv=[process.execPath,entry,'--restored-bundle',bundle,'--restored-artifact-root',artifactRoot];let child:ChildProcess|undefined,browser:any,base='',activeArgv=argv;
 async function start(useRestore=true){const server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const a=server.address();assert.ok(a&&typeof a==='object');await new Promise<void>(r=>server.close(()=>r()));let logs='';activeArgv=useRestore?argv:argv.slice(0,2);child=spawn(process.execPath,activeArgv.slice(1),{cwd:f.root,env:{MASSION_SURREAL_RPC:endpoint,MASSION_SURREAL_NAMESPACE:namespace,MASSION_SURREAL_DATABASE:destDB,MASSION_PORT:String(a.port)},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',d=>logs+=d);child.stderr!.on('data',d=>logs+=d);const end=Date.now()+10000;while(!logs.includes('Massion development workbench:')){assert.equal(child.exitCode,null,logs);assert.ok(Date.now()<end,'CLI start deadline: '+logs);await new Promise(r=>setTimeout(r,10));}base='http://127.0.0.1:'+a.port;}
 const exact='/missions/mission/record-artifact?work=work&record='+record.id+'&version='+record.artifact.version+'&sha256='+record.artifact.sha256;
 try{await start(false);const defaultRead=await fetch(base+exact);assert.equal(defaultRead.status,503);t.diagnostic('Default normal host refuses unavailable original path; explicit relocation binding required.');await stopOwnedChild(child!,{cwd:f.root,argv:argv.slice(0,2)});await start();const connections=await(await fetch(base+'/connections')).json();assert.equal(connections.liveExecutionEnabled,false);assert.equal(connections.runtime.authorizations.length,0);const response=await fetch(base+exact);assert.equal(response.status,200,await response.clone().text());const content=await response.json();assert.match(content.content,/Exact accepted fixture/);assert.equal(content.recordChecksum,record.checksum);assert.equal(content.evidenceClass,'fixture');assert.deepEqual(await dest.load('mission'),before);assert.deepEqual(await dest.exportJournal(),journal);assert.deepEqual((await targetTransport.query('SELECT * FROM massion_outbox;',{}))[0],outbox);
 if(browserEnabled){const {chromium}=await import(process.env.MASSION_PLAYWRIGHT_PATH!);browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1280,height:844}});await page.goto(base+'/#mission=mission');await page.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission'&&document.getElementById('sync-notice')?.hidden);await page.locator('#work-evidence-summary-work').click();await page.locator('#work-record-text-summary-work').click();await page.locator('#work-record-text-read-work').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('work-record-text-status-work')?.textContent?.includes('verified'));assert.equal(await page.locator('#work-record-text-content-work').textContent(),content.content);assert.equal(await page.locator('#work-record-text-content-work img').count(),0);for(const width of [390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}await page.locator('#work-record-text-content-work').scrollIntoViewIfNeeded();await page.screenshot({path:process.env.MASSION_RESTORED_SCREENSHOT||'/tmp/massion-restored.png'});await page.reload();await page.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission');}
 t.diagnostic(JSON.stringify(await verifyOwnedChild(child!,{cwd:f.root,argv})));await stopOwnedChild(child!,{cwd:f.root,argv});await start();assert.equal((await(await fetch(base+exact)).json()).content,content.content);assert.equal((await(await fetch(base+'/connections')).json()).runtime.authorizations.length,0);assert.deepEqual(await dest.load('mission'),before);assert.deepEqual(await dest.exportJournal(),journal);assert.deepEqual((await targetTransport.query('SELECT * FROM massion_outbox;',{}))[0],outbox);assert.equal((await readFile(bundle,'utf8')).includes(record.checksum),true);t.diagnostic(JSON.stringify({actualBackupCLI:true,normalHost:true,cleanDB:true,relocatedRoot:true,originalPathUnavailable:true,recordChecksumUnchanged:true,headlessChrome:browserEnabled,restartGrants:0,effectsReplayed:0,modelCalls:0}));}finally{if(browser)await browser.close();if(child)await stopOwnedChild(child,{cwd:f.root,argv:activeArgv});}
}
test('actual DB backup CLI restored accepted Record readable in normal CLI after relocation/restart',{skip:!process.env.SURREAL_TEST_RUNTIME,timeout:60000},async t=>proof(t));
test('actual DB restored accepted result readable through normal CLI/Chrome keyboard',{skip:!process.env.SURREAL_TEST_RUNTIME||!process.env.MASSION_PLAYWRIGHT_PATH,timeout:60000},async t=>proof(t,true));
