import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFile,rename,symlink,link,mkdir,chmod} from 'node:fs/promises';
import {join} from 'node:path';
import {textFixture} from './support/record-artifact-fixture.ts';
import {InMemoryStore} from '../src/storage.ts';
import type {Mission} from '../src/domain.ts';
import {exportPortableBackup,restorePortableBackup} from '../src/portable-backup.ts';
import {loadRestoredArtifactReader} from '../src/restored-artifact-reader.ts';
import {loadHostStartup} from '../src/host-connections.ts';
import {TextArtifactStore} from '../src/text-artifacts.ts';
function journal(store:InMemoryStore<Mission>){const operations=[...structuredClone(store.inspect())];return {schemaVersion:2 as const,head:operations.length,operations};}
async function fixture(t:import('node:test').TestContext){const f=await textFixture(t),serialized=await exportPortableBackup({exportJournal:async()=>journal(f.store as InMemoryStore<Mission>)},f.artifacts),bundlePath=join(f.root,'bundle.json'),artifactRoot=join(f.root,'relocated'),dest=new InMemoryStore<Mission>();await writeFile(bundlePath,serialized,{mode:0o600});await restorePortableBackup(serialized,{exportJournal:async()=>({schemaVersion:2,head:0,operations:[]}),restoreJournal:async()=>({status:'restored' as const,head:0,checksum:''})},artifactRoot);const current=new TextArtifactStore(join(f.root,'new'));return {...f,bundlePath,artifactRoot,current,dest,selection:{bundlePath,artifactRoot}};}
test('explicit relocation reads originals without fallback, while new artifacts keep their normal store',async t=>{const f=await fixture(t),reader=await loadRestoredArtifactReader(f.selection,f.current),text=await f.artifacts.read(f.artifact);await rename(f.artifacts.root,join(f.root,'preserved-original'));assert.equal(await reader.read(f.artifact),text);const fresh=await f.current.write('fresh',1,'New normal artifact');assert.equal(await reader.read(fresh),'New normal artifact');await assert.rejects(reader.read({...f.artifact,path:f.artifact.path+'.other'}));const relocated=join(f.artifactRoot,'work',f.artifact.sha256+'.txt');await chmod(relocated,0o600);await writeFile(relocated,'tampered');await assert.rejects(reader.read(f.artifact),/Text artifact boundary/);});
test('startup requires explicit paired canonical paths and creates no live option',async()=>{const s=await loadHostStartup(['--restored-bundle','/tmp/bundle.json','--restored-artifact-root','/tmp/artifacts']);assert.equal(s.allowLiveExecution,false);assert.deepEqual(s.restoredArtifacts,{bundlePath:'/tmp/bundle.json',artifactRoot:'/tmp/artifacts'});for(const args of [['--restored-bundle','/tmp/x'],['--restored-artifact-root','/tmp/x'],['--restored-bundle'],['--restored-bundle','/tmp/x','--restored-bundle','/tmp/y','--restored-artifact-root','/tmp/z'],['--restored-bundle','relative','--restored-artifact-root','/tmp/z'],['--restored-bundle','/tmp/a/../b','--restored-artifact-root','/tmp/z'],['--restored-bundle','/tmp/x','--restored-artifact-root','/tmp/z','--allow-live-model-calls']])await assert.rejects(loadHostStartup(args));});
for(const mode of ['invalid-json','invalid-utf8','checksum','symlink','hardlink','parent-symlink','missing-root','wrong-root','root-symlink','missing-bytes','changed-bytes'] as const)test(`restored binding rejects ${mode} before opening service`,async t=>{const f=await fixture(t);let selection=f.selection;switch(mode){case 'invalid-json':await writeFile(f.bundlePath,'{');break;case 'invalid-utf8':await writeFile(f.bundlePath,Buffer.from([0xff]));break;case 'checksum':await writeFile(f.bundlePath,JSON.stringify({...JSON.parse(await exportPortableBackup({exportJournal:async()=>journal(f.store as InMemoryStore<Mission>)},f.artifacts)),checksum:'0'.repeat(64)}));break;case 'symlink':await rename(f.bundlePath,f.bundlePath+'.preserved');await symlink(f.bundlePath+'.preserved',f.bundlePath);break;case 'hardlink':await link(f.bundlePath,f.bundlePath+'.linked');break;case 'parent-symlink':await symlink(f.root,f.root+'-linked');t.after(async()=>{await import('node:fs/promises').then(fs=>fs.unlink(f.root+'-linked'));});selection={...selection,bundlePath:join(f.root+'-linked','bundle.json')};break;case 'missing-root':selection={...selection,artifactRoot:join(f.root,'missing')};break;case 'wrong-root':await mkdir(join(f.root,'wrong'));selection={...selection,artifactRoot:join(f.root,'wrong')};break;case 'root-symlink':await symlink(f.artifactRoot,f.artifactRoot+'-linked');selection={...selection,artifactRoot:f.artifactRoot+'-linked'};break;case 'missing-bytes':await rename(join(f.artifactRoot,'work',f.artifact.sha256+'.txt'),join(f.root,'preserved-bytes'));break;case 'changed-bytes':await chmod(join(f.artifactRoot,'work',f.artifact.sha256+'.txt'),0o600);await writeFile(join(f.artifactRoot,'work',f.artifact.sha256+'.txt'),'bad');break;}await assert.rejects(loadRestoredArtifactReader(selection,f.current));});
