import test from 'node:test';
import assert from 'node:assert/strict';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {hash,workInputHash,DomainError} from '../src/domain.ts';
import {ConfiguredTextRuntime} from '../src/configured-runtime.ts';
import {ProductService} from '../src/product.ts';
import {sequenceRunId} from '../src/run-sequence.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'memory'} explicit two Work causal sequence completes through independent Records`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable);await f.product.admit('mission',{commandId:'second-admit',expectedRevision:(await f.current()).revision,workId:'second',title:'Explicit causal successor',budget:8});let s=await f.current();const first=s.value.works.find(w=>w.id==='fresh')!;await f.product.attachWorkPrerequisite('mission',{commandId:'second-pin',expectedRevision:s.revision,workId:'second',prerequisiteId:'fresh',criteriaHash:hash(first.criteria),inputHash:workInputHash(first),reason:'Original causal dependency'});s=await f.current();const works=['fresh','second'].map(workId=>{const w=s.value.works.find(w=>w.id===workId)!;return {workId,criteriaHash:hash(w.criteria),inputHash:workInputHash(w)};});const result=await f.product.runSequence('mission',{commandId:'owner-sequence',expectedRevision:s.revision,works});assert.equal(result.status,'completed');assert.deepEqual(result.completedWorkIds,['fresh','second']);assert.equal(f.calls.length,4);assert.equal((await f.current()).value.works.find(w=>w.id==='second')!.acceptance,'accepted');const finished=await f.current(),firstRecord=finished.value.works.find(w=>w.id==='fresh')!.record!;assert.equal(f.calls[2]!.input.work.prerequisiteRecords[0].checksum,firstRecord.checksum);assert.equal(f.calls[3]!.input.requirements.prerequisiteRecords[0].checksum,firstRecord.checksum);assert.deepEqual(finished.value.works.find(w=>w.id==='work'),f.original.value.works.find(w=>w.id==='work'));validateMissionJournalLineage(await f.journal());if(durable){const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{SurrealStore}=await import('../src/storage.ts'),{store:target}=await growthStore(true);assert.ok(f.store instanceof SurrealStore&&target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/sequence-restored');assert.deepEqual((await target.load('mission'))!.value,finished.value);}
});

async function plan(f:Awaited<ReturnType<typeof fixture>>,causal=false){await f.product.admit('mission',{commandId:'second-admit',expectedRevision:(await f.current()).revision,workId:'second',title:'Explicit successor',budget:8});if(causal){const s=await f.current(),w=s.value.works.find(w=>w.id==='fresh')!;await f.product.attachWorkPrerequisite('mission',{commandId:'second-pin',expectedRevision:s.revision,workId:'second',prerequisiteId:'fresh',criteriaHash:hash(w.criteria),inputHash:workInputHash(w),reason:'Original dependency'});}const s=await f.current();return {commandId:'owner-plan',expectedRevision:s.revision,works:['fresh','second'].map(workId=>{const w=s.value.works.find(w=>w.id===workId)!;return {workId,criteriaHash:hash(w.criteria),inputHash:workInputHash(w)};})};}
for(const durable of [false,true])for(const kind of ['empty','too-many','duplicate','hash','stale','reversed','extra','external-pending'] as const)test(`${durable?'actual SurrealDB':'memory'} explicit sequence ${kind} rejects before any call/journal change`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),input=await plan(f,kind==='reversed'),before=await f.journal();if(kind==='empty')input.works=[];if(kind==='too-many')input.works=[...input.works,...input.works];if(kind==='duplicate')input.works=[input.works[0]!,input.works[0]!];if(kind==='hash')input.works[1]!.inputHash='0'.repeat(64);if(kind==='stale')input.expectedRevision--;if(kind==='reversed')input.works.reverse();if(kind==='extra')(input as any).queue=true;if(kind==='external-pending'){const s=await f.current(),w=s.value.works.find(w=>w.id==='fresh')!;await f.product.attachWorkPrerequisite('mission',{commandId:'late-pin',expectedRevision:s.revision,workId:'second',prerequisiteId:'fresh',criteriaHash:hash(w.criteria),inputHash:workInputHash(w),reason:'External unaccepted Work'});const now=await f.current(),second=now.value.works.find(w=>w.id==='second')!;input.expectedRevision=now.revision;input.works=[{workId:'second',criteriaHash:hash(second.criteria),inputHash:workInputHash(second)}];}
 const journal=kind==='external-pending'?await f.journal():before;try{const result=await f.product.runSequence('mission',input);assert.equal(result.status,'stopped');assert.equal(result.results.at(-1)!.status,'conflict');}catch(e){assert.ok(e instanceof DomainError);}assert.equal(f.calls.length,0);assert.deepEqual(await f.journal(),journal);
});
for(const durable of [false,true])for(const boundary of ['cancel','deadline','activation-ack','claim-ack'] as const)test(`${durable?'actual SurrealDB':'memory'} sequence ${boundary} stops without invoking fresh remainder or replaying original`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:'executor',runTimeoutMs:boundary==='deadline'?1500:undefined}),input=await plan(f),id=sequenceRunId(input.commandId,0);let lost=false;const store=new Proxy(f.store,{get(target,key){if(key==='commit')return async(value:any)=>{const result=await target.commit(value);if(!lost&&(boundary==='activation-ack'?value.commandId===id:boundary==='claim-ack'&&value.events?.some((o:any)=>o.type==='claim-provider-dispatch'))){lost=true;throw Error('Controlled committed ACK loss');}return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),product=['activation-ack','claim-ack'].includes(boundary)?new ProductService(store,undefined,new ConfiguredTextRuntime(store,f.config)):f.product;
 const run=product.runSequence('mission',input);void run.catch(()=>{});if(boundary==='cancel'){await f.until(()=>f.calls.length===1);await f.product.intervene('mission',{commandId:'owner-cancel',expectedRevision:(await f.current()).revision,command:{type:'cancel',workId:'fresh'}});}if(['activation-ack','claim-ack'].includes(boundary))await assert.rejects(run,/committed|admission/i);else{assert.equal((await run).status,'stopped');}
 const after=await f.current(),first=structuredClone(after.value.works.find(w=>w.id==='fresh')!);assert.equal(after.value.works.find(w=>w.id==='second')!.runtimeRun,undefined);assert.equal(f.calls.length,['activation-ack','claim-ack'].includes(boundary)?0:1);if(boundary==='deadline'||boundary==='cancel'){assert.equal(first.effects[0]!.status,'unknown');assert.equal(first.budget.reserved,4);}const journal=await f.journal();f.release();await new Promise(r=>setImmediate(r));assert.deepEqual(await f.journal(),journal);const repeated=await product.runSequence('mission',{...input,expectedRevision:after.revision});assert.equal(repeated.status,'stopped');assert.equal(repeated.results[0]!.status,'already-started');assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.current()).value.works.find(w=>w.id==='fresh'),first);validateMissionJournalLineage(await f.journal());
});
for(const durable of [false,true])for(const boundary of ['caller-edit','revision','configuration','busy-read','drain-read'] as const)test(`${durable?'actual SurrealDB':'memory'} sequence ${boundary} captures original request and stops safely across held reads`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:boundary==='busy-read'?'executor':undefined}),input=await plan(f);let held=false,release!:()=>void;const gate=new Promise<void>(r=>release=r);t.after(()=>release());const store=new Proxy(f.store,{get(target,key){if(key==='load')return async(id:string)=>{const s=await target.load(id);if(!held&&id==='mission'&&(boundary==='caller-edit'||boundary==='busy-read'||boundary==='drain-read'||s?.value.works.find(w=>w.id==='fresh')?.acceptance==='accepted')){held=true;await gate;if(boundary==='revision')return target.load(id);}return s;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),runtime=f.runtime;let config=1;const routed=new Proxy(runtime,{get(target,key){if(key==='configuration')return ()=>({config});const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),product=new ProductService(store,undefined,routed);let original:Promise<any>|undefined;if(boundary==='busy-read'){original=f.runtime.run('mission','fresh','other-explicit',(await f.current()).revision);await f.until(()=>f.calls.length===1);input.expectedRevision=(await f.current()).revision;input.works=[input.works[1]!];}
 const run=product.runSequence('mission',input);void run.catch(()=>{});await f.until(()=>held);if(boundary==='caller-edit'){input.works.reverse();input.commandId='mutated';}if(boundary==='configuration')config++;if(boundary==='revision')await f.product.appendWorkMessage('mission',{commandId:'between-steps',expectedRevision:(await f.current()).revision,workId:'second',messageId:'between-steps',replyTo:null,text:'Another owner write'});if(boundary==='busy-read'){f.release();await original;}if(boundary==='drain-read')runtime.beginDrain();const before=await f.journal();release();const result=await run;if(boundary==='caller-edit'){assert.equal(result.status,'completed');assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.runtimeRun!.id,sequenceRunId('owner-plan',0));assert.equal(f.calls.length,4);}else{assert.equal(result.status,'stopped');assert.equal((await f.current()).value.works.find(w=>w.id==='second')!.runtimeRun,undefined);assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,boundary==='drain-read'?0:2);}validateMissionJournalLineage(await f.journal());
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'memory'} same sequence identity cannot dispatch a reordered fresh Work after partial acceptance`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),input=await plan(f);const first=await f.product.runSequence('mission',{...input,works:[input.works[0]!]});assert.equal(first.status,'completed');const journal=await f.journal(),original=structuredClone((await f.current()).value.works.find(w=>w.id==='fresh')!);const next=await f.product.runSequence('mission',{...input,expectedRevision:first.snapshot.revision,works:[input.works[1]!]});assert.equal(next.status,'stopped');assert.equal(next.results[0]!.status,'conflict');assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,2);const deliberate=await f.product.runSequence('mission',{...input,commandId:'new-explicit-plan',expectedRevision:first.snapshot.revision,works:[input.works[1]!]});assert.equal(deliberate.status,'completed');assert.deepEqual((await f.current()).value.works.find(w=>w.id==='fresh'),original);assert.equal(f.calls.length,4);validateMissionJournalLineage(await f.journal());
});

for(const durable of [false,true])for(const kind of ['failed-assurance','remaining-budget','remaining-cancel'] as const)test(`${durable?'actual SurrealDB':'memory'} sequence ${kind} preserves partial originals and stops before remaining admission`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:kind==='failed-assurance'?undefined:'executor'}),input=await plan(f);if(kind==='failed-assurance'){const invoke=f.config.verifier.adapter.invoke.bind(f.config.verifier.adapter);f.config.verifier.adapter.invoke=async req=>{const result=await invoke(req),report=JSON.parse(result.output!);report.verdict='failed';for(const check of report.checks)check.passed=false;return {...result,output:JSON.stringify(report)};};}
 const run=f.product.runSequence('mission',input);if(kind!=='failed-assurance'){await f.until(()=>f.calls.length===1);if(kind==='remaining-budget')await f.product.reviseBudget('mission',{commandId:'changed-later-budget',expectedRevision:(await f.current()).revision,workId:'second',limit:12,reason:'Separate owner change during prior run'});else await f.product.intervene('mission',{commandId:'cancel-remainder',expectedRevision:(await f.current()).revision,command:{type:'cancel',workId:'second'}});f.release();}const result=await run;assert.equal(result.status,'stopped');assert.equal((await f.current()).value.works.find(w=>w.id==='second')!.runtimeRun,undefined);assert.equal(f.calls.length,2);if(kind!=='failed-assurance'){assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.acceptance,'accepted');assert.deepEqual(result.completedWorkIds,['fresh']);}else assert.deepEqual(result.completedWorkIds,[]);assert.deepEqual((await f.current()).value.works.find(w=>w.id==='work'),f.original.value.works.find(w=>w.id==='work'));validateMissionJournalLineage(await f.journal());
});
