import test from 'node:test';
import assert from 'node:assert/strict';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {apply,hash,workInputHash} from '../src/domain.ts';
import {workAdmissionPreflight} from '../src/configured-runtime.ts';
import {validateMissionJournalLineage,validateMissionLineage} from '../src/backup-lineage.ts';
import {ProductService} from '../src/product.ts';
import {SurrealStore} from '../src/storage.ts';
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} owner questions block first Run; immutable explicit answers pin prompts and Record without changing original Work`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,durable),original=(await f.current()).value.works.find(w=>w.id==='work'),before=await f.current(),input={commandId:'ask',expectedRevision:before.revision,workId:'fresh',questionId:'q',text:'  Literal <img src=x> 원문 😀\r\nWhich exact output?  '};assert.equal((await f.product.clarifyWork('mission',input,false)).status,'committed');let now=await f.current(),w=now.value.works.find(w=>w.id==='fresh')!;assert.equal(w.questions![0]!.text,input.text);assert.equal(w.questions![0]!.actorId,'local-owner');assert.notEqual(workInputHash(w),workInputHash(before.value.works.find(w=>w.id==='fresh')!));assert.ok(workAdmissionPreflight(now,'fresh',now.revision).diagnostics.some(d=>d.code==='clarification_pending'));assert.equal((await f.product.run('mission','fresh','blocked-question',now.revision)).status,'blocked');assert.deepEqual(await f.current(),now);assert.equal(f.calls.length,0);
 assert.throws(()=>apply(now.value,{type:'activate-runtime',workId:'fresh',run:{id:'forged',authorizationId:'x',criteriaHash:hash(w.criteria),inputHash:workInputHash(w),mode:'mock-http',outputTokenCap:4}},{id:'local-owner',roles:['owner']}),/Open owner clarification/);
 assert.equal((await new ProductService(f.store,f.product.providers,f.runtime).clarifyWork('mission',input,false)).status,'replayed');assert.equal((await f.product.clarifyWork('mission',{...input,text:'different'},false)).status,'conflict');assert.equal((await f.product.clarifyWork('mission',{...input,commandId:'stale',questionId:'other'},false)).status,'conflict');
 const answer={commandId:'answer',expectedRevision:now.revision,workId:'fresh',questionId:'q',text:'Original bounded lifetime fixture'};await f.product.clarifyWork('mission',answer,true);now=await f.current();w=now.value.works.find(w=>w.id==='fresh')!;assert.equal(f.calls.length,0);assert.equal(w.runtimeRun,undefined);assert.equal(workAdmissionPreflight(now,'fresh',now.revision).ready,true);await assert.rejects(f.product.clarifyWork('mission',{...answer,commandId:'twice',expectedRevision:now.revision},true),/open question/);assert.equal((await f.product.run('mission','fresh','explicit-answered',now.revision)).status,'settled');now=await f.current();w=now.value.works.find(w=>w.id==='fresh')!;assert.equal(f.calls.length,2);assert.deepEqual(f.calls[0]!.input.work.questions,w.questions);assert.deepEqual(f.calls[1]!.input.requirements.questions,w.questions);assert.deepEqual(w.record!.questions,w.questions);assert.equal(w.runtimeRun!.inputHash,workInputHash(w));assert.ok(w.assignments.every(a=>a.extensionVersion==='massion.builtin.bounded-text@8'));assert.deepEqual(now.value.works.find(w=>w.id==='work'),original);validateMissionJournalLineage(await f.journal());await assert.rejects(f.product.clarifyWork('mission',{...answer,commandId:'started',expectedRevision:now.revision},false),/fresh unstarted/);
 const read={recordId:w.record!.id,artifactVersion:w.artifact!.version,artifactSha256:w.artifact!.sha256};const {readRecordArtifact}=await import('../src/record-artifact.ts');assert.equal((await readRecordArtifact(f.store,f.artifacts,'mission','fresh',read))!.content,'Original bounded lifetime fixture');const forged=structuredClone(now.value);forged.works.find(w=>w.id==='fresh')!.record!.questions![0]!.answer!.text='Substituted answer';const {checksum,...bundle}=forged.works.find(w=>w.id==='fresh')!.record!;forged.works.find(w=>w.id==='fresh')!.record!.checksum=hash(bundle);assert.throws(()=>validateMissionLineage(forged));
 if(durable){assert.ok(f.store instanceof SurrealStore);const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{store}=await growthStore(true);assert.ok(store instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),store,f.root+'/question-restored');assert.deepEqual((await store.load('mission'))!.value,now.value);}
});
test('exact bounded owner decisions reject forged actor, extra keys, malformed text, fourth question, cancelled and uncertain Work',async t=>{
 const f=await lifetimeFixture(t),before=await f.current(),base={type:'ask-work-question' as const,workId:'fresh',questionId:'q',text:'Question'};assert.throws(()=>apply(before.value,base,{id:'verifier',roles:['verifier']}));for(const text of ['', ' ', '\ud800','x'.repeat(4097)])assert.throws(()=>apply(before.value,{...base,text},{id:'owner',roles:['owner']}));await assert.rejects(f.product.clarifyWork('mission',{commandId:'extra',expectedRevision:before.revision,workId:'fresh',questionId:'q',text:'Question',actorId:'forged'} as any,false));for(let i=0;i<3;i++)await f.product.clarifyWork('mission',{commandId:'q'+i,expectedRevision:(await f.current()).revision,workId:'fresh',questionId:'q'+i,text:'Question '+i},false);const now=await f.current();await assert.rejects(f.product.clarifyWork('mission',{commandId:'four',expectedRevision:now.revision,workId:'fresh',questionId:'q4',text:'Fourth'},false));assert.deepEqual(await f.current(),now);const cancelled=apply(now.value,{type:'cancel',workId:'fresh'},{id:'owner',roles:['owner']});assert.throws(()=>apply(cancelled.value,{...base,type:'answer-work-question',questionId:'q0'},{id:'owner',roles:['owner']}));assert.equal(f.calls.length,0);
});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} clarification preserves unknown original receipts and rejects all later questions without recalling adapters`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await lifetimeFixture(t,durable,{hold:'executor',runTimeoutMs:durable?5000:80});await f.product.clarifyWork('mission',{commandId:'ask-unknown',expectedRevision:(await f.current()).revision,workId:'fresh',questionId:'q',text:'Clarify output'},false);await f.product.clarifyWork('mission',{commandId:'answer-unknown',expectedRevision:(await f.current()).revision,workId:'fresh',questionId:'q',text:'Original bounded lifetime fixture'},true);assert.equal((await f.product.run('mission','fresh','unknown-answered',(await f.current()).revision)).status,'blocked');const before=await f.current(),journal=await f.journal();assert.ok(before.value.works.find(w=>w.id==='fresh')!.effects.some(e=>e.status==='unknown'));await assert.rejects(f.product.clarifyWork('mission',{commandId:'later',expectedRevision:before.revision,workId:'fresh',questionId:'later',text:'Do not recall'},false));assert.deepEqual(await f.current(),before);assert.equal(f.calls.length,1);f.release();await new Promise(r=>setTimeout(r,25));assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,1);});
