import test from 'node:test';
import {once} from 'node:events';
import assert from 'node:assert/strict';
import {SurrealWorkInbox,WorkInboxChangedError,inboxInput,unresolvedInboxItem} from '../src/work-inbox.ts';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {StorageProtocolError,SurrealStore} from '../src/storage.ts';
const row=(workId:string,patch={})=>({aggregateId:'mission',missionId:'mission',missionPurpose:'Original',revision:2,workId,title:'Original <img src=x> 원문 😀',execution:'blocked',acceptance:'pending',openQuestions:0,unknownEffects:0,pendingEffects:0,interrupted:false,blocker:{code:'runtime_unavailable',detail:'Stored original blocker'},...patch});
test('inbox predicate retains unknown cancelled/closed pending and owner questions, excludes healthy pending/accepted outcomes',()=>{const plain={openQuestions:0,unknownEffects:0,pendingEffects:0,interrupted:false,execution:'settled',acceptance:'accepted',blocker:null};assert.equal(unresolvedInboxItem(plain),false);assert.equal(unresolvedInboxItem({...plain,execution:'active',acceptance:'pending',pendingEffects:1}),false);for(const patch of [{unknownEffects:1,execution:'cancelled'},{pendingEffects:1,execution:'cancelled'},{pendingEffects:1,interrupted:true},{openQuestions:1},{acceptance:'failed'},{acceptance:'stale'},{blocker:{code:'runtime_unavailable',detail:'Stored'}}])assert.equal(unresolvedInboxItem({...plain,...patch}),true);});
test('strict native inbox paging rejects malformed identity/facts',async()=>{for(const input of [{afterMission:'mission'},{afterMission:'mission',afterWork:'w',cursor:1},{cursor:1},{limit:21},{unknown:'x'}])assert.throws(()=>inboxInput(input as any));for(const rows of [[row('a'),row('a')],[row('a',{aggregateId:'other'})],[row('a',{openQuestions:4})],[row('a',{blocker:null})],[row('a',{title:'\ud800'})],[row('a',{content:'Forbidden body'})]])await assert.rejects(new SurrealWorkInbox({async query(){return [{feedId:'feed',cursor:2,rows}];}}).readInbox({limit:2}),StorageProtocolError);for(const changed of ['feed','cursor'] as const)await assert.rejects(new SurrealWorkInbox({async query(){return [{changed}];}}).readInbox({}),WorkInboxChangedError);const page=await new SurrealWorkInbox({async query(){return [null,{feedId:'feed',cursor:2,rows:[row('a'),row('b'),row('c')]},null];}}).readInbox({limit:2});assert.deepEqual(page.nextAfter,{missionId:'mission',workId:'b'});assert.equal(Object.hasOwn(page.items[0]!,'aggregateId'),false);});
test('actual DB inbox finds an original question and blocked Work across Missions without mutating Work/Record/journal',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await lifetimeFixture(t,true);await f.product.clarifyWork('mission',{commandId:'inbox-question',expectedRevision:(await f.current()).revision,workId:'fresh',questionId:'q',text:'Original unresolved question'},false);await f.product.create({id:'other',purpose:'Other mission',scope:'local',constraints:[],criteria:{version:1,description:'Original',oracle:'manual-review/v1'}},'inbox-other');await f.product.admit('other',{commandId:'inbox-other-work',expectedRevision:1,workId:'blocked',title:'Stored blocker',budget:0});const before=await f.journal(),reader=new SurrealWorkInbox(f.transport!),page=await reader.readInbox({});assert.deepEqual(page.items.map(x=>[x.missionId,x.workId]),[['mission','fresh'],['other','blocked']]);assert.equal(page.items[0]!.openQuestions,1);assert.equal(page.items[1]!.blocker!.code,'provider_unavailable');assert.deepEqual(await f.journal(),before);assert.equal(f.calls.length,0);await f.product.clarifyWork('mission',{commandId:'inbox-answer',expectedRevision:(await f.current()).revision,workId:'fresh',questionId:'q',text:'Original answer'},true);assert.deepEqual((await reader.readInbox({})).items.map(x=>[x.missionId,x.workId]),[['other','blocked']]);});
test('actual DB inbox uses exact tuple/feed/cursor across pages, replacement/restore and preserves cancelled unknown late receipts',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await lifetimeFixture(t,true,{hold:'executor',runTimeoutMs:5000}),reader=new SurrealWorkInbox(f.transport!);const run=f.product.run('mission','fresh','inbox-unknown',(await f.current()).revision);await f.until(()=>f.calls.length===1);await f.product.intervene('mission',{commandId:'inbox-cancel',expectedRevision:(await f.current()).revision,command:{type:'cancel',workId:'fresh'}});assert.equal((await run).status,'cancelled');
 for(let i=0;i<22;i++){await f.product.admit('mission',{commandId:'inbox-page:'+i,expectedRevision:(await f.current()).revision,workId:'blocked:'+String(i).padStart(2,'0'),title:'Original Work '+i,budget:0});await f.product.clarifyWork('mission',{commandId:'inbox-page-question:'+i,expectedRevision:(await f.current()).revision,workId:'blocked:'+String(i).padStart(2,'0'),questionId:'q',text:'Original open question '+i},false);}const original=await f.current(),journal=await f.journal(),first=await reader.readInbox({});assert.equal(first.items.length,20);assert.deepEqual(first.nextAfter,{missionId:'mission',workId:'blocked:19'});const second=await reader.readInbox({afterMission:first.nextAfter!.missionId,afterWork:first.nextAfter!.workId,cursor:first.cursor,feedId:first.feedId});assert.deepEqual(second.items.map(x=>x.workId),['blocked:20','blocked:21','fresh']);const unknown=second.items.at(-1)!;assert.equal(unknown.execution,'cancelled');assert.equal(unknown.unknownEffects,1);assert.equal(second.nextAfter,null);assert.deepEqual(await f.current(),original);assert.deepEqual(await f.journal(),journal);f.release();await new Promise(r=>setTimeout(r,25));assert.deepEqual(await f.current(),original);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,1);
 const {growthStore}=await import('./support/growth-fixture.ts'),{exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{store,transport}=await growthStore(true),replacement=new SurrealWorkInbox(transport!);assert.ok(store instanceof SurrealStore);assert.ok(f.store instanceof SurrealStore);assert.deepEqual((await replacement.readInbox({})).items,[]);await assert.rejects(replacement.readInbox({feedId:first.feedId}),e=>e instanceof WorkInboxChangedError&&e.reason==='feed');await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),store,f.root+'/inbox-restored');const restored=await replacement.readInbox({});assert.deepEqual(restored.items,first.items);assert.notEqual(restored.feedId,first.feedId);assert.deepEqual((await store.load('mission'))!.value,original.value);
 await f.product.admit('mission',{commandId:'inbox-after-page',expectedRevision:original.revision,workId:'late',title:'Later original blocker',budget:0});await assert.rejects(reader.readInbox({afterMission:first.nextAfter!.missionId,afterWork:first.nextAfter!.workId,cursor:first.cursor,feedId:first.feedId}),e=>e instanceof WorkInboxChangedError&&e.reason==='cursor');
});
test('reader freezes owner read boundary before await and read-only route rejects hidden fallback/extra query fields',async t=>{
 let release!:()=>void,seen:any;const gate=new Promise<void>(r=>release=r),reader=new SurrealWorkInbox({async query(_query,vars){seen=structuredClone(vars);await gate;return [{feedId:'feed',cursor:2,rows:[row('a')]}];}}),input={feedId:'feed',limit:1},pending=reader.readInbox(input);input.feedId='other';input.limit=20;release();assert.equal((await pending).limit,1);assert.equal(seen.feedId,'feed');assert.equal(seen.fetchLimit,2);
 const {createWorkbench}=await import('../src/server.ts'),{InMemoryStore}=await import('../src/storage.ts'),store=new InMemoryStore<any>();let reads=0;const server=createWorkbench(store,'.',{inbox:{async readInbox(){reads++;return {feedId:'feed',cursor:0,limit:20,items:[],nextAfter:null};}}});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port;
 for(const query of ['?afterMission=a','?cursor=1','?afterMission=a&afterWork=b&cursor=-1','?afterMission=a&afterWork=b&cursor=1&afterWork=c','?priority=high'])assert.equal((await fetch(base+'/work-inbox'+query)).status,400);assert.equal(reads,0);assert.equal((await fetch(base+'/work-inbox',{method:'POST'})).status,404);assert.equal((await fetch(base+'/work-inbox')).status,200);assert.equal(reads,1);assert.deepEqual(store.inspect(),[]);
});
