import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {ProductService} from '../src/product.ts';
import {Application} from '../src/application.ts';
import {hash,workInputHash} from '../src/domain.ts';
import type {Mission} from '../src/domain.ts';
import {validateConversations,workConversationId} from '../src/work-conversation.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {SurrealStore} from '../src/storage.ts';
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} owner conversation is separate from exact accepted Work/Record, input/grants/budgets and unknown provider claims`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable,{hold:'executor',runTimeoutMs:durable?1500:150}),run=await f.product.run('mission','fresh','unknown-conversation',(await f.current()).revision),before=await f.current(),works=structuredClone(before.value.works);assert.equal(run.status,'blocked');const root={commandId:'message-root',expectedRevision:before.revision,workId:'fresh',messageId:'message-root',replyTo:null,text:'  Discuss unknown, do not replay <img src=x>\n원문 😀  '};const result=await f.product.appendWorkMessage('mission',root);assert.notEqual(result.status,'conflict');const reply={commandId:'message-reply',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'message-reply',replyTo:'message-root',text:'Owner reply: inspect original evidence; no authority granted'};await f.product.appendWorkMessage('mission',reply);await f.product.appendWorkMessage('mission',{commandId:'accepted-note',expectedRevision:(await f.current()).revision,workId:'work',messageId:'accepted-note',replyTo:null,text:'Original accepted Record remains immutable'});const current=await f.current();assert.deepEqual(current.value.works,works);assert.equal(f.calls.length,1);assert.equal(workInputHash(current.value.works[1]!),workInputHash(works[1]!));assert.equal(hash(current.value.works[0]!.record),hash(f.original.value.works[0]!.record));const thread=current.value.conversations!.find(c=>c.workId==='fresh')!;assert.equal(thread.id,workConversationId('mission','fresh'));assert.equal(thread.messages[0]!.text,root.text);assert.deepEqual(thread.messages.map(m=>[m.ordinal,m.actorId,m.role,m.replyTo]),[[1,'local-owner','owner',null],[2,'local-owner','owner','message-root']]);const state=await f.store.readState('mission'),query=await new ProductService(f.store).readWorkConversation('mission','fresh',state.feedId);assert.deepEqual(query!.conversation,thread);assert.equal(query!.revision,current.revision);assert.equal(query!.cursor,state.cursor);assert.equal(query!.conversation!.messages.some(m=>m.id==='accepted-note'),false);validateConversations(current.value);validateMissionJournalLineage(await f.journal());const journal=await f.journal();f.release();await new Promise(r=>setTimeout(r,20));assert.deepEqual(await f.journal(),journal);
 if(durable){assert.ok(f.store instanceof SurrealStore);const {exportPortableBackup,restorePortableBackup}=await import('../src/portable-backup.ts'),{growthStore}=await import('./support/growth-fixture.ts'),{store:target}=await growthStore(true);assert.ok(target instanceof SurrealStore);await restorePortableBackup(await exportPortableBackup(f.store,f.artifacts),target,f.root+'/conversation-restored');assert.deepEqual((await target.load('mission'))!.value,current.value);assert.deepEqual((await new ProductService(target).readWorkConversation('mission','fresh'))!.conversation,thread);}
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} CAS, exact replay/changed payload, duplicate message ID and committed lost ACK append once`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable),revision=(await f.current()).revision,input={commandId:'one',expectedRevision:revision,workId:'fresh',messageId:'one',replyTo:null,text:'Original owner message'},other={...input,commandId:'two',messageId:'two',text:'Concurrent owner message'},results=await Promise.all([f.product.appendWorkMessage('mission',input),new ProductService(f.store).appendWorkMessage('mission',other)]);assert.equal(results.filter(r=>r.status==='committed').length,1);assert.equal(results.filter(r=>r.status==='conflict').length,1);const winner=results[0]!.status==='committed'?input:other,journal=await f.journal();assert.equal((await f.product.appendWorkMessage('mission',winner)).status,'replayed');assert.equal((await f.product.appendWorkMessage('mission',{...winner,text:'Changed old payload'})).status,'conflict');await assert.rejects(f.product.appendWorkMessage('mission',{...winner,commandId:'new-identity-old-message',expectedRevision:(await f.current()).revision}));assert.deepEqual(await f.journal(),journal);
 let lost=false;const store=new Proxy(f.store,{get(target,key){if(key==='commit')return async(input:any)=>{const result=await target.commit(input);if(!lost){lost=true;throw Error('Owned fixture lost committed response');}return result;};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),submitted={commandId:'lost-message',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'lost-message',replyTo:winner.messageId,text:'Original after lost ACK'};await assert.rejects(new ProductService(store).appendWorkMessage('mission',submitted));assert.equal(lost,true);assert.equal((await new ProductService(f.store).appendWorkMessage('mission',submitted)).status,'replayed');assert.equal((await f.product.readWorkConversation('mission','fresh'))!.conversation!.messages.length,2);validateMissionJournalLineage(await f.journal());assert.equal(f.calls.length,0);
});
test('message command freezes caller inputs across asynchronous lookup and never redirects Work, role or text',async t=>{
 const f=await fixture(t);let hold!:()=>void,release!:()=>void;const reached=new Promise<void>(r=>hold=r),gate=new Promise<void>(r=>release=r);let held=false;const store=new Proxy(f.store,{get(target,key){if(key==='lookupOperation')return async(input:any)=>{if(!held){held=true;hold();await gate;}return target.lookupOperation(input);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}}),service=new ProductService(store),input={commandId:'frozen',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'frozen',replyTo:null,text:'Original frozen text'},running=service.appendWorkMessage('mission',input);await reached;input.workId='work';input.text='Mutated provider instructions';input.messageId='mutated';release();assert.equal((await running).status,'committed');const thread=(await f.current()).value.conversations![0]!;assert.equal(thread.workId,'fresh');assert.equal(thread.messages[0]!.text,'Original frozen text');assert.equal(thread.messages[0]!.id,'frozen');assert.equal(f.calls.length,0);
});
test('only registered owner may append exact bounded text and earlier same-thread replies, with no spoof or mutation',async t=>{
 const f=await fixture(t),post=(workId:string,messageId:string,replyTo:string|null,text:string)=>f.product.appendWorkMessage('mission',{commandId:crypto.randomUUID(),expectedRevision:0,workId,messageId,replyTo,text});await f.product.appendWorkMessage('mission',{commandId:'root',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'root',replyTo:null,text:'Original'});await f.product.appendWorkMessage('mission',{commandId:'other',expectedRevision:(await f.current()).revision,workId:'work',messageId:'other',replyTo:null,text:'Other thread'});const revision=(await f.current()).revision,journal=await f.journal(),base={commandId:crypto.randomUUID(),expectedRevision:revision,workId:'fresh',messageId:'bad',replyTo:null,text:'Original'};
 for(const patch of [{workId:'absent'},{messageId:'root'},{replyTo:'other'},{replyTo:'bad'},{replyTo:'absent'},{text:''},{text:' \n '},{text:'\ud800'},{text:'😀'.repeat(1025)},{text:'x'.repeat(4097)},{actorId:'host-executor'},{role:'representative'}])await assert.rejects(f.product.appendWorkMessage('mission',{...base,...patch} as any));const app=new Application(f.store,[{id:'provider',roles:['executor']},{id:'representative',roles:['representative']}]);for(const actorId of ['provider','representative'])await assert.rejects(app.dispatch({missionId:'mission',commandId:crypto.randomUUID(),expectedRevision:revision,actorId,command:{type:'append-work-message',workId:'fresh',messageId:'not-owner',replyTo:null,text:'Spoof'}}));assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);
 const valid={...base,commandId:'utf8-bound',messageId:'utf8-bound',text:'😀'.repeat(1024)};assert.equal((await f.product.appendWorkMessage('mission',valid)).status,'committed');
});
test('stored conversation bounds and original message order/identity/reply integrity fail closed',async t=>{
 const f=await fixture(t);await f.product.appendWorkMessage('mission',{commandId:'original',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'original',replyTo:null,text:'Original literal'});await f.product.appendWorkMessage('mission',{commandId:'reply',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'reply',replyTo:'original',text:'Original reply'});const original=(await f.current()).value;
 for(const change of [(m:Mission)=>m.conversations![0]!.id='wrong',(m:Mission)=>m.conversations![0]!.workId='absent',(m:Mission)=>m.conversations![0]!.messages.reverse(),(m:Mission)=>m.conversations![0]!.messages[0]!.role='representative' as any,(m:Mission)=>m.conversations![0]!.messages[0]!.replyTo='reply',(m:Mission)=>m.conversations![0]!.messages[1]!.id='original',(m:Mission)=>(m.conversations![0]!.messages[0] as any).extra=true]){const mission=structuredClone(original);change(mission);assert.throws(()=>validateConversations(mission));const store=new Proxy(f.store,{get(target,key){if(key==='readState')return async()=>({...await target.readState('mission'),snapshot:{...(await f.current()),value:mission}});const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}});await assert.rejects(new ProductService(store).readWorkConversation('mission','fresh'));}
 const max=structuredClone(original);max.conversations![0]!.messages=Array.from({length:100},(_,index)=>({id:'message-'+index,ordinal:index+1,actorId:'local-owner',role:'owner',replyTo:null,text:'x'}));validateConversations(max);max.conversations![0]!.messages.push({id:'overflow',ordinal:101,actorId:'local-owner',role:'owner',replyTo:null,text:'x'});assert.throws(()=>validateConversations(max));const full=structuredClone(original);full.conversations![0]!.messages=Array.from({length:70},(_,index)=>({id:'message-'+index,ordinal:index+1,actorId:'local-owner',role:'owner',replyTo:null,text:'x'.repeat(4096)}));assert.throws(()=>validateConversations(full));
});
test('normal HTTP conversation routes require exact Work/feed and original owner fields; reads never write or invoke',async t=>{
 const f=await fixture(t),{createWorkbench}=await import('../src/server.ts'),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const base=`http://127.0.0.1:${address.port}/missions/mission`,before=await f.journal();for(const query of ['', '?work=fresh&work=fresh','?work=fresh&extra=x','?work='])assert.equal((await fetch(base+'/work-conversation'+query)).status,400);assert.equal((await fetch(base+'/work-conversation?work=absent')).status,404);assert.equal((await fetch(base+'/work-conversation?work=fresh',{headers:{'x-massion-feed':'other-feed'}})).status,409);assert.equal((await (await fetch(base+'/work-conversation?work=fresh')).json()).conversation,null);assert.deepEqual(await f.journal(),before);
 const body={commandId:'http-note',expectedRevision:(await f.current()).revision,workId:'fresh',messageId:'http-note',replyTo:null,text:'Original normal HTTP conversation'},post=async(value:any,feed?:string)=>fetch(base+'/work-message',{method:'POST',headers:{'content-type':'application/json',...(feed?{'x-massion-feed':feed}:{})},body:JSON.stringify(value)});assert.equal((await post({...body,actorId:'provider'})).status,400);assert.equal((await post(body,'other-feed')).status,409);assert.equal((await post(body)).status,200);assert.equal((await (await post(body)).json()).status,'replayed');assert.equal((await (await fetch(base+'/work-conversation?work=fresh')).json()).conversation.messages[0].text,body.text);assert.equal(f.calls.length,0);
});
