import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {verifyOwnedChild,stopOwnedChild} from './support/owned-process.ts';
test('actual DB normal CLI Chrome keyboard reviews original-message Work questions and answers without automatic Run',{skip:!process.env.SURREAL_TEST_RUNTIME||!process.env.MASSION_PLAYWRIGHT_PATH,timeout:45000},async t=>{
 const f=await lifetimeFixture(t,true);await f.product.appendWorkMessage('mission',{commandId:'browser-original',expectedRevision:(await f.current()).revision,workId:'work',messageId:'browser-original',replyTo:null,text:'Original selected <img src=x> 원문 😀'});const database=(await f.transport!.query('RETURN $session.db;',{}))[0] as string,{chromium}=await import(process.env.MASSION_PLAYWRIGHT_PATH!),probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const address=probe.address();assert.ok(address&&typeof address==='object');await new Promise<void>(r=>probe.close(()=>r()));const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry],child=spawn(process.execPath,argv.slice(1),{cwd:f.root,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database,MASSION_PORT:String(address.port)},stdio:['ignore','pipe','pipe']});let logs='';child.stdout!.on('data',d=>logs+=d);child.stderr!.on('data',d=>logs+=d);let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;try{browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});await f.until(()=>{assert.equal(child.exitCode,null,logs);return logs.includes('Massion development workbench:');});const page=await browser.newPage({viewport:{width:390,height:844}}),base='http://127.0.0.1:'+address.port,works=structuredClone((await f.current()).value.works);await page.goto(base+'/#mission=mission');await page.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission'&&document.getElementById('sync-notice')?.hidden);await page.locator('#conversation-work-panel > summary').focus();await page.keyboard.press('Enter');await page.locator('#conversation-work-source').selectOption(JSON.stringify(['work','browser-original']));await page.locator('#conversation-work-title').fill('Original bounded lifetime fixture');await page.locator('#conversation-work-budget').fill('8');await page.locator('#conversation-work-review').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!(document.getElementById('conversation-work-save') as HTMLButtonElement).disabled);await page.locator('#conversation-work-save').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('conversation-work-status')?.textContent?.includes('confirmed'));const derived=(await f.current()).value.works.at(-1)!;assert.equal(derived.conversationSource!.message.id,'browser-original');assert.equal(f.calls.length,0);
 await page.locator('#clarification-panel > summary').focus();await page.keyboard.press('Enter');await page.locator('#clarification-work').selectOption(derived.id);await page.locator('#clarification-text').fill('Which exact output? <img src=x> 원문 😀');await page.locator('#clarification-review').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!(document.getElementById('clarification-save') as HTMLButtonElement).disabled);const before=await f.journal();await page.locator('#clarification-cancel').focus();await page.keyboard.press('Enter');assert.deepEqual(await f.journal(),before);await page.locator('#clarification-work').selectOption(derived.id);await page.locator('#clarification-text').fill('Which exact output? <img src=x> 원문 😀');await page.locator('#clarification-review').focus();await page.keyboard.press('Enter');await page.locator('#clarification-save').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.getElementById('clarification-status')?.textContent?.includes('confirmed'));let w=(await f.current()).value.works.find(w=>w.id===derived.id)!;assert.equal(w.questions![0]!.answer,null);assert.equal(f.calls.length,0);const response=await fetch(base+'/missions/mission/preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({commandId:'browser-check',expectedRevision:(await f.current()).revision,workId:derived.id})}),checked=await response.json();assert.ok(checked.diagnostics.some((d:any)=>d.code==='clarification_pending'));
 await page.locator('#clarification-work').selectOption(derived.id);await page.locator('#clarification-question').selectOption(w.questions![0]!.id);await page.locator('#clarification-text').fill('Original bounded lifetime fixture');await page.locator('#clarification-review').focus();await page.keyboard.press('Enter');assert.match(await page.locator('#clarification-original').textContent()||'',/Which exact output/);await page.locator('#clarification-save').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>(document.getElementById('clarification-text') as HTMLTextAreaElement)?.value===''&&document.getElementById('clarification-status')?.textContent?.includes('confirmed'));w=(await f.current()).value.works.find(w=>w.id===derived.id)!;assert.equal(w.questions![0]!.answer!.text,'Original bounded lifetime fixture');assert.equal(w.runtimeRun,undefined);assert.deepEqual((await f.current()).value.works.slice(0,-1),works);assert.equal(f.calls.length,0);assert.equal(await page.locator('#clarification-original img').count(),0);const journal=await f.journal();await page.reload();await page.waitForFunction(()=>document.getElementById('loaded-id')?.textContent==='mission'&&document.getElementById('sync-notice')?.hidden);assert.deepEqual(await f.journal(),journal);for(const width of [390,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 t.diagnostic(JSON.stringify({...await verifyOwnedChild(child,{cwd:f.root,argv}),normalCLI:true,keyboardQuestions:true,cancelWrites:0,questionGate:true,explicitAnswerSaved:true,selectionReset:true,originalWorksExact:true,providerCalls:0,liveCalls:0}));}finally{if(browser)await browser.close();await stopOwnedChild(child,{cwd:f.root,argv});}
});
