import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {SurrealWorkInbox} from '../src/work-inbox.ts';
import {InMemoryStore} from '../src/storage.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function fixture(t:any,durable=false,mode='normal'){
 const f=await lifetimeFixture(t,durable);await f.product.clarifyWork('mission',{commandId:'inbox-question',expectedRevision:(await f.current()).revision,workId:'fresh',questionId:'q',text:'Original unresolved question'},false);await f.product.create({id:'other',purpose:'Other stored Mission <img src=x> 원문 😀',scope:'local',constraints:[],criteria:{version:1,description:'Original',oracle:'manual-review/v1'}},'inbox-other');await f.product.admit('other',{commandId:'inbox-blocked',expectedRevision:1,workId:'blocked',title:'Other blocked Work <img src=x> 원문 😀',budget:0});const inbox=new SurrealWorkInbox(f.transport??{async query(_query,vars){assert.ok(f.store instanceof InMemoryStore);const state=await f.store.readState();if(vars.feedId&&state.feedId!==vars.feedId)return [{changed:'feed'}];if(Number(vars.cursor)>=0&&state.cursor!==vars.cursor)return [{changed:'cursor'}];const latest=new Map();for(const op of f.store.inspect())latest.set(op.aggregateId,op);const rows=[...latest.values()].flatMap(op=>op.value.works.map((w:any)=>({aggregateId:op.aggregateId,missionId:op.value.id,missionPurpose:op.value.purpose,revision:op.revision,workId:w.id,title:w.title,execution:w.execution,acceptance:w.acceptance,openQuestions:(w.questions??[]).filter((q:any)=>q.answer===null).length,unknownEffects:w.effects.filter((e:any)=>e.status==='unknown').length,pendingEffects:w.effects.filter((e:any)=>e.status==='pending').length,interrupted:!!(w.runtimeInterruption||w.runtimeRecovery),blocker:w.blocker??null}))).filter(w=>(w.missionId>String(vars.afterMission)||w.missionId===vars.afterMission&&w.workId>String(vars.afterWork))&&(w.openQuestions||w.unknownEffects||w.pendingEffects&&(w.execution==='cancelled'||w.interrupted)||['failed','stale'].includes(w.acceptance)||w.blocker!==null)).sort((a,b)=>a.missionId<b.missionId?-1:a.missionId>b.missionId?1:a.workId<b.workId?-1:1).slice(0,Number(vars.fetchLimit));return [{feedId:state.feedId,cursor:state.cursor,rows}];}});const server=createWorkbench(f.store,f.root,{inbox,providers:f.product.providers,runtime:f.runtime,artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const base='http://127.0.0.1:'+(server.address() as any).port;let release!:()=>void,writes=0,inboxReads=0;const gate=new Promise<void>(r=>release=r);
 const handler=async(path:string,options:any)=>{if(options.method==='POST')writes++;if(path.startsWith('/work-inbox'))inboxReads++;const response=await fetch(base+path,options),body=await response.json();if(mode==='held-load'&&path==='/read-state?mission=mission')await gate;if(path.startsWith('/work-inbox')){if(mode==='held')await gate;if(mode==='wrong-feed')body.feedId='different-feed';if(mode==='wrong-identity')body.items[0].workId='bad id';}return reply(body,response.status);};async function client(){const app=harness(handler,{},undefined,{network:true});await f.until(()=>app.node('sync-notice').hidden&&!app.node('work-inbox-refresh').disabled);return app;}return {...f,base,client,release:()=>release(),writes:()=>writes,inboxReads:()=>inboxReads};
}
function selection(app:any,id:string){return app.all().find((n:any)=>n.attributes.get('data-inbox-work')===id);}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} fresh client finds unresolved Work without ID and explicitly inspects original evidence without a command`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await fixture(t,durable),app=await f.client(),journal=await f.journal();assert.equal(app.node('mission-id').value,'');assert.equal(f.inboxReads(),0);await app.node('work-inbox-refresh').fire('click');assert.match(app.node('work-inbox-results').textContent,/Other blocked Work/);assert.equal(f.inboxReads(),1);assert.equal(f.writes(),0);assert.equal(app.all().some(n=>n.tagName==='IMG'),false);await selection(app,'fresh').fire('click');assert.equal(app.node('loaded-id').textContent,'mission');assert.deepEqual(runInContext('JSON.parse(JSON.stringify(snapshot.value))',app.context),(await f.current()).value);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);await app.node('work-inbox-close').fire('click');assert.equal(app.node('work-inbox-results').hidden,true);assert.equal(f.writes(),0);});
test('late closed or disconnected inbox read cannot restore a list or overwrite the Mission',async t=>{const f=await fixture(t,false,'held'),app=await f.client();const pending=app.node('work-inbox-refresh').fire('click');await f.until(()=>f.inboxReads()===1);await runInContext("loadMission('mission',false)",app.context);await app.node('work-inbox-close').fire('click');f.release();await pending;assert.equal(app.node('work-inbox-results').hidden,true);assert.equal(app.node('loaded-id').textContent,'mission');assert.equal(f.writes(),0);});
for(const mode of ['wrong-feed','wrong-identity'])test(`${mode} inbox is not selectable or reused`,async t=>{const f=await fixture(t,false,mode),app=await f.client();await app.node('work-inbox-refresh').fire('click');assert.equal(app.node('work-inbox-results').hidden,true);assert.equal(selection(app,'fresh'),undefined);assert.equal(app.node('loaded-id').textContent,'');assert.equal(f.writes(),0);assert.equal(f.inboxReads(),1);});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} same-ID replaced database invalidates an old inbox button without a load or write`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const one=await fixture(t,durable),two=await fixture(t,durable);let base=one.base,missionReads=0,writes=0;const app=harness(async(path:string,options:any)=>{if(path.startsWith('/read-state?mission=')||path.startsWith('/missions/'))missionReads++;if(options.method==='POST')writes++;const response=await fetch(base+path,options);return reply(await response.json(),response.status);},{},undefined,{network:true});await one.until(()=>app.node('sync-notice').hidden&&!app.node('work-inbox-refresh').disabled);await app.node('work-inbox-refresh').fire('click');const old=selection(app,'fresh'),beforeOne=await one.journal(),beforeTwo=await two.journal();base=two.base;await app.windowEvent('online');await app.tick();const deadline=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('work-inbox-refresh').disabled){assert.ok(Date.now()<deadline);await app.tick();await new Promise(r=>setTimeout(r,10));}const reads=missionReads;await old.fire('click');assert.equal(missionReads,reads);assert.equal(app.node('work-inbox-results').hidden,true);assert.equal(writes,0);assert.deepEqual(await one.journal(),beforeOne);assert.deepEqual(await two.journal(),beforeTwo);});
test('inbox read/selection retains an original unknown operation and its write barrier',async t=>{const f=await fixture(t),app=await f.client();await runInContext("unknownOperation={commandId:'original-unknown',missionId:'mission',reconcileCursor:0};controls()",app.context);await app.node('work-inbox-refresh').fire('click');await selection(app,'blocked').fire('click');assert.equal(app.node('loaded-id').textContent,'other');assert.equal(runInContext('unknownOperation.commandId',app.context),'original-unknown');assert.equal(app.node('mission-fields').disabled,true);assert.equal(f.writes(),0);assert.equal(f.calls.length,0);});
test('inbox selection reads newer authoritative Work rather than the displayed revision',async t=>{const f=await fixture(t),app=await f.client();await app.node('work-inbox-refresh').fire('click');const row=selection(app,'fresh');await f.product.admit('mission',{commandId:'after-inbox',expectedRevision:(await f.current()).revision,workId:'later',title:'New responsibility after inbox read',budget:8});await row.fire('click');assert.equal(runInContext('snapshot.revision',app.context),(await f.current()).revision);assert.ok(runInContext('snapshot.value.works.some(w=>w.id==="later")',app.context));assert.equal(f.writes(),0);assert.equal(f.calls.length,0);});
test('disconnect aborts a pending first-page read and prevents its late rendering',async t=>{const f=await fixture(t,false,'held'),app=await f.client();const pending=app.node('work-inbox-refresh').fire('click');await f.until(()=>f.inboxReads()===1);await app.windowEvent('offline');f.release();await pending;assert.equal(app.node('work-inbox-results').hidden,true);assert.equal(app.node('work-inbox-refresh').disabled,true);assert.equal(f.writes(),0);});

test('late selected Work read cannot replace a newer owner Mission selection or focus stale evidence',async t=>{const f=await fixture(t,false,'held-load'),app=await f.client();await app.node('work-inbox-refresh').fire('click');const pending=selection(app,'fresh').fire('click');await f.until(()=>runInContext('loading',app.context));await runInContext("loadMission('other',false)",app.context);f.release();await pending;assert.equal(app.node('loaded-id').textContent,'other');assert.equal(f.writes(),0);assert.equal(f.calls.length,0);});
