import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {join} from 'node:path';
import {prerequisiteFixture as fixture} from './support/work-prerequisites-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {hash,workInputHash,apply} from '../src/domain.ts';
import {resolvedPrerequisites} from '../src/work-prerequisites.ts';
import {workAdmissionPreflight} from '../src/configured-runtime.ts';
import {validateMissionJournalLineage} from '../src/backup-lineage.ts';
import {SurrealStore} from '../src/storage.ts';
import {exportPortableBackup,restorePortableBackup} from '../src/portable-backup.ts';
import {growthStore} from './support/growth-fixture.ts';
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} causal prerequisite blocks normal runtime without calls then retains exact accepted independent Record in successor`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable);await f.admit('first');await f.admit('next');const pin=await f.pin('next','first'),server=createWorkbench(f.store,f.root,{runtime:f.runtime,artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const base='http://127.0.0.1:'+address.port,feed=(await f.store.readState()).feedId;
 const post=async(path:string,body:unknown)=>{const r=await fetch(base+'/missions/mission/'+path,{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':feed},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};assert.equal((await post('work-prerequisite',pin)).body.status,'committed');const before=await f.current(),journal=await f.journal();assert.ok(workAdmissionPreflight(before,'next',before.revision).diagnostics.some(d=>d.code==='prerequisite_unavailable'));assert.equal((await post('run',{commandId:'blocked-next',expectedRevision:before.revision,workId:'next'})).body.status,'blocked');assert.equal(f.calls.length,0);assert.deepEqual(await f.journal(),journal);
 assert.equal((await f.product.run('mission','first','run-first',before.revision)).status,'settled');const first=(await f.current()).value.works.find(w=>w.id==='first')!,record=structuredClone(first.record!),ready=await f.current();assert.equal(f.calls.length,2);assert.equal((await post('preflight',{commandId:'check',expectedRevision:ready.revision,workId:'next'})).body.ready,true);assert.equal((await post('run',{commandId:'run-next',expectedRevision:ready.revision,workId:'next'})).body.status,'settled');const state=await f.current(),next=state.value.works.find(w=>w.id==='next')!;assert.equal(next.acceptance,'accepted');assert.equal(f.calls.length,4);const evidence=resolvedPrerequisites(state.value,next)!;assert.equal(evidence[0]!.recordId,record.id);assert.equal(evidence[0]!.checksum,record.checksum);assert.equal(evidence[0]!.artifact.sha256,record.artifact.sha256);assert.deepEqual(next.record!.prerequisites,next.prerequisites);assert.deepEqual(next.record!.prerequisiteRecords,evidence);assert.deepEqual(f.calls[2]!.input.work.prerequisiteRecords,evidence);assert.deepEqual(f.calls[3]!.input.requirements.prerequisiteRecords,evidence);assert.ok(next.assignments.every(a=>a.extensionVersion==='massion.builtin.bounded-text@5'));assert.deepEqual(state.value.works[0],f.original.value.works[0]);assert.deepEqual(state.value.works.find(w=>w.id==='first')!.record,record);validateMissionJournalLineage(await f.journal());
 const artifact=await (await fetch(base+'/missions/mission/record-artifact?work=next&record='+next.record!.id+'&version=1&sha256='+next.artifact!.sha256)).json();assert.equal(artifact.content,'Independent bounded prerequisite output');
 if(durable){assert.ok(f.store instanceof SurrealStore);const backup=await exportPortableBackup(f.store,f.artifacts),{store:restored}=await growthStore(true);assert.ok(restored instanceof SurrealStore);await restorePortableBackup(backup,restored,join(f.root,'restored'));assert.deepEqual(await restored.exportJournal(),await f.store.exportJournal());assert.deepEqual(resolvedPrerequisites((await restored.load('mission'))!.value,(await restored.load('mission'))!.value.works.find(w=>w.id==='next')!),evidence);}
});
test('owner prerequisite admission rejects self, cycle, duplicate, missing/cross-Mission, forged fields and progress; legacy inputs and advisory relations remain unchanged',async t=>{
 const f=await fixture(t);for(const id of ['a','b','c','d','e'])await f.admit(id);const owner={id:'owner',roles:['owner' as const]},i=await f.pin('a','b'),command={type:'attach-work-prerequisite' as const,...((({commandId,expectedRevision,...c})=>c)(i))},original=(await f.current()).value;
 assert.throws(()=>apply(original,command,{id:'executor',roles:['executor']}),/role/);for(const change of [{prerequisiteId:'a'},{prerequisiteId:'missing'},{criteriaHash:'0'.repeat(64)},{inputHash:'bad'},{reason:''},{reason:'\ud800'},{actorId:'forged'}])assert.throws(()=>apply(original,{...command,...change} as any,owner));
 for(const mutate of [(w:any)=>w.runtimeRun={},(w:any)=>w.effects.push({}),(w:any)=>w.assignments.push({}),(w:any)=>w.tasks[0].result='progress',(w:any)=>w.execution='cancelled',(w:any)=>w.acceptance='accepted']){const copy=structuredClone(original);mutate(copy.works.find(w=>w.id==='a'));assert.throws(()=>apply(copy,command,owner));}
 const pinned=apply(original,command,owner).value;assert.throws(()=>apply(pinned,command,owner),/duplicate/);const target=pinned.works.find(w=>w.id==='a')!;assert.throws(()=>apply(pinned,{...command,workId:'b',prerequisiteId:'a',inputHash:workInputHash(target),criteriaHash:hash(target.criteria)},owner),/Cyclic/);
 let bounded=pinned;for(const id of ['c','d']){const target=bounded.works.find(w=>w.id===id)!;bounded=apply(bounded,{...command,prerequisiteId:id,inputHash:workInputHash(target),criteriaHash:hash(target.criteria)},owner).value;}const e=bounded.works.find(w=>w.id==='e')!;assert.throws(()=>apply(bounded,{...command,prerequisiteId:'e',inputHash:workInputHash(e),criteriaHash:hash(e.criteria)},owner),/bound/);
 const a=original.works.find(w=>w.id==='a')!;assert.equal(workInputHash(a),hash({mission:a.missionSnapshot,title:a.title,instructions:[],memoryVersions:a.appliedMemoryVersions}));await f.product.recordRelation('mission',{commandId:'advisory',expectedRevision:(await f.current()).revision,relation:{from:'a',to:'b',type:'depends-on',fromVersion:1,toVersion:1,provenance:'Owner declaration, not execution control'}});const state=await f.current();assert.equal(workAdmissionPreflight(state,'a',state.revision).ready,true);assert.equal((await f.product.run('mission','a','advisory-not-gate',state.revision)).status,'settled');assert.deepEqual((await f.current()).value.works[0],f.original.value.works[0]);
});
test('atomic activation and effect admission reject pending or changed prerequisite even when preflight is bypassed',async t=>{
 const f=await fixture(t);await f.admit('first');await f.admit('next');await f.product.attachWorkPrerequisite('mission',await f.pin('next','first'));const before=await f.current(),owner={id:'owner',roles:['owner' as const]},next=before.value.works.find(w=>w.id==='next')!,activation={type:'activate-runtime' as const,workId:'next',run:{id:'run',authorizationId:'fixture',mode:'mock-http' as const,outputTokenCap:4,criteriaHash:hash(next.criteria),inputHash:workInputHash(next)}};assert.throws(()=>apply(before.value,activation,owner),/no accepted Record/);
 const copy=structuredClone(before.value),w=copy.works.find(w=>w.id==='next')!;w.assignments.push({id:'exec',actorId:'executor',role:'executor',taskId:'next:root',model:f.original.value.works[0]!.assignments[0]!.model,extensionVersion:'fixture'});assert.throws(()=>apply(copy,{type:'admit-effect',workId:'next',effect:{id:'effect',taskId:'next:root',status:'pending',target:'fixture',authority:'fixture'},reserve:1},{id:'executor',roles:['executor']}),/no accepted Record/);
 await f.product.intervene('mission',{commandId:'changed-input',expectedRevision:before.revision,command:{type:'steer',workId:'first',instruction:'A different prerequisite input'}});let state=await f.current();assert.ok(workAdmissionPreflight(state,'next',state.revision).diagnostics.some(d=>d.message.includes('changed')));assert.equal((await f.product.run('mission','next','blocked-change',state.revision)).status,'blocked');assert.equal(f.calls.length,0);assert.deepEqual(state.value.works.find(w=>w.id==='next')!.prerequisites,next.prerequisites);validateMissionJournalLineage(await f.journal());
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} prerequisite concurrent exact admission, frozen caller and committed-unknown receipt retain one original decision`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable);await f.admit('a');await f.admit('b');const i=await f.pin('b','a'),before=await f.journal();const results=await Promise.all([f.product.attachWorkPrerequisite('mission',i),f.product.attachWorkPrerequisite('mission',i)]);assert.deepEqual(results.map(r=>r.status).sort(),['committed','replayed']);assert.equal((await f.journal()).length,before.length+1);assert.equal((await f.product.attachWorkPrerequisite('mission',{...i,reason:'Changed payload'})).status,'conflict');
 await f.admit('c');await f.admit('d');const current=await f.current(),ci=await f.pin('c','a'),di=await f.pin('c','d');const race=await Promise.all([f.product.attachWorkPrerequisite('mission',ci),f.product.attachWorkPrerequisite('mission',di)]);assert.deepEqual(race.map(r=>r.status).sort(),['committed','conflict']);assert.equal((await f.current()).value.works.find(w=>w.id==='c')!.prerequisites!.length,1);
 const {ProductService}=await import('../src/product.ts');let ready!:()=>void,release!:()=>void;const started=new Promise<void>(r=>ready=r),held=new Promise<void>(r=>release=r);let paused=true;const proxy=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='lookupOperation')return async(...args:unknown[])=>{if(paused){paused=false;ready();await held;}return fn.apply(target,args);};return typeof fn==='function'?fn.bind(target):fn;}});const frozen=await f.pin('d','a'),input=structuredClone(frozen),pending=new ProductService(proxy).attachWorkPrerequisite('mission',input);await started;input.reason='Later edit';input.prerequisiteId='b';release();assert.equal((await pending).status,'committed');assert.equal((await f.current()).value.works.find(w=>w.id==='d')!.prerequisites![0]!.reason,frozen.reason);
 await f.admit('e');const lost=await f.pin('e','a');let fail=true;const lossy=new Proxy(f.store,{get(target,key){const fn=Reflect.get(target,key);if(key==='commit')return async(...args:unknown[])=>{const result=await fn.apply(target,args);if(fail){fail=false;throw Error('Controlled acknowledgement loss');}return result;};return typeof fn==='function'?fn.bind(target):fn;}});await assert.rejects(new ProductService(lossy).attachWorkPrerequisite('mission',lost),/acknowledgement/);const journal=await f.journal();const {commandId,expectedRevision,...pin}=lost;const receipt=await f.store.lookupOperation({id:'mission',commandId,fingerprint:hash({actorId:'local-owner',expectedRevision,command:{type:'attach-work-prerequisite',...pin}})});assert.notEqual(receipt.status,'unknown');assert.deepEqual(await f.journal(),journal);assert.deepEqual((await f.current()).value.works[0],f.original.value.works[0]);validateMissionJournalLineage(journal);
});
test('prerequisite Record and exact Work bindings including recomputed organization assignment corruption fail closed',async t=>{
 const f=await fixture(t);await f.product.reviseOrganization('mission',{commandId:'org',expectedRevision:(await f.current()).revision,version:1,reason:'Original owner organization',responsibilities:[{role:'executor',responsibility:'Write bounded text',capability:'text-output'},{role:'verifier',responsibility:'Review independently',capability:'independent-text-review'}]});await f.admit('first');await f.admit('next');await f.product.attachWorkPrerequisite('mission',await f.pin('next','first'));assert.equal((await f.product.run('mission','first','first-run',(await f.current()).revision)).status,'settled');const state=await f.current(),next=state.value.works.find(w=>w.id==='next')!;
 for(const mutate of [(w:any)=>w.record.checksum='0'.repeat(64),(w:any)=>w.record.artifact.sha256='0'.repeat(64),(w:any)=>w.title='Substituted input',(w:any)=>w.criteria.description='Substituted criteria',(w:any)=>{for(const a of [...w.assignments,...w.record.assignments])a.organizationVersion=2;const {checksum,...bundle}=w.record;w.record.checksum=hash(bundle);},(w:any)=>w.record.prerequisites=[]]){const copy=structuredClone(state);mutate(copy.value.works.find(w=>w.id==='first'));assert.throws(()=>resolvedPrerequisites(copy.value,copy.value.works.find(w=>w.id==='next')!));assert.ok(workAdmissionPreflight(copy,'next',copy.revision).diagnostics.some(d=>d.code==='prerequisite_unavailable'));assert.throws(()=>apply(copy.value,{type:'activate-runtime',workId:'next',run:{id:'bad',authorizationId:'fixture',mode:'mock-http',outputTokenCap:4,criteriaHash:hash(next.criteria),inputHash:workInputHash(next)}},{id:'owner',roles:['owner']}));}
 assert.equal(f.calls.length,2);assert.deepEqual((await f.current()).value,state.value);await f.admit('legacy-next');await f.product.attachWorkPrerequisite('mission',await f.pin('legacy-next','work'));const legacy=await f.current(),target=legacy.value.works[0]!;for(const a of [...target.assignments,...target.record!.assignments])a.organizationVersion=1;const {checksum,...bundle}=target.record!;target.record!.checksum=hash(bundle);assert.throws(()=>resolvedPrerequisites(legacy.value,legacy.value.works.find(w=>w.id==='legacy-next')!),/organization version/);
});
test('transitive prerequisites retain original Record chain; changed Mission revisions do not replace Work input; declaration depth is bounded',async t=>{
 const f=await fixture(t);for(const id of ['a','b','c'])await f.admit(id);await f.product.attachWorkPrerequisite('mission',await f.pin('b','a'));await f.product.attachWorkPrerequisite('mission',await f.pin('c','b'));const pending=await f.current(),pins=structuredClone(pending.value.works.find(w=>w.id==='c')!.prerequisites);assert.equal((await f.product.run('mission','c','blocked-chain',pending.revision)).status,'blocked');assert.equal(f.calls.length,0);
 for(const id of ['a','b','c'])assert.equal((await f.product.run('mission',id,'run-'+id,(await f.current()).revision)).status,'settled');const accepted=await f.current(),c=accepted.value.works.find(w=>w.id==='c')!,records=structuredClone(c.prerequisiteRecords);await f.product.reviseMission('mission',{commandId:'future-mission',expectedRevision:accepted.revision,purpose:'Future purpose',criteria:{version:3,description:'Future criteria',oracle:'bounded-text-review/v1'}});const after=await f.current();assert.deepEqual(after.value.works.find(w=>w.id==='c'),c);assert.deepEqual(resolvedPrerequisites(after.value,c),records);assert.deepEqual(c.record!.prerequisites,pins);assert.equal(f.calls.length,6);validateMissionJournalLineage(await f.journal());
 let m=structuredClone(after.value);const owner={id:'owner',roles:['owner' as const]};for(let n=0;n<33;n++){const id='depth-'+n;m=apply(m,{type:'admit-work',workId:id,title:'Declared bounded chain',budget:8},owner).value;if(n){const target=m.works.find(w=>w.id==='depth-'+(n-1))!,cmd={type:'attach-work-prerequisite' as const,workId:id,prerequisiteId:target.id,criteriaHash:hash(target.criteria),inputHash:workInputHash(target),reason:'Exact ancestor'};if(n===32)assert.throws(()=>apply(m,cmd,owner),/32 Work depth/);else m=apply(m,cmd,owner).value;}}
});
test('normal prerequisite HTTP rejects wrong feed, unknown other-Mission target and forged actor/Record evidence without writes',async t=>{
 const f=await fixture(t);await f.admit('next');await f.product.create({id:'other',purpose:'Separate scope',scope:'other',constraints:[],criteria:{version:1,description:'Other',oracle:'manual/v1'}},'other-create');await f.product.admit('other',{commandId:'other-admit',expectedRevision:1,workId:'other-work',title:'Other scope',budget:8});const server=createWorkbench(f.store,f.root,{runtime:f.runtime});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port,feed=(await f.store.readState()).feedId,i=await f.pin('next','work'),journal=await f.journal();
 for(const [change,identity,status] of [[{},'wrong',409],[{actorId:'executor'},feed,400],[{recordId:'forged'},feed,400],[{prerequisiteId:'other-work'},feed,400]] as const){const r=await fetch(base+'/missions/mission/work-prerequisite',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':identity},body:JSON.stringify({...i,...change})});assert.equal(r.status,status);}assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);
});
test('actual SurrealDB normal CLI retains prerequisite decisions and exact accepted Record metadata through restart without dispatch',{skip:!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const {spawn}=await import('node:child_process'),{createServer}=await import('node:net'),{fileURLToPath}=await import('node:url'),{stopOwnedChild}=await import('./support/owned-process.ts');let child:ReturnType<typeof spawn>|undefined,log='',cwd='';const entry=fileURLToPath(new URL('../src/server.ts',import.meta.url)),argv=[process.execPath,entry];async function stop(){if(child)await stopOwnedChild(child,{cwd,argv});}t.after(stop);const f=await fixture(t,true,true);cwd=f.root;assert.ok(f.store instanceof SurrealStore);const transport=f.transport!;const database=(await transport.query('RETURN $session.db;',{}))[0] as string,probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const a=probe.address();assert.ok(a&&typeof a==='object');const port=a.port;await new Promise<void>(r=>probe.close(()=>r()));const base='http://127.0.0.1:'+port;
 async function start(){child=spawn(process.execPath,[entry],{cwd,env:{MASSION_SURREAL_RPC:process.env.MASSION_TEST_SURREAL_RPC!,MASSION_SURREAL_NAMESPACE:process.env.MASSION_TEST_SURREAL_NAMESPACE!,MASSION_SURREAL_DATABASE:database,MASSION_PORT:String(port)},stdio:['ignore','pipe','pipe']});child.stdout!.on('data',b=>log+=b);child.stderr!.on('data',b=>log+=b);const deadline=Date.now()+10000;while(true){try{if((await fetch(base+'/health')).ok)return;}catch{}assert.ok(child.exitCode===null&&Date.now()<deadline,log);await new Promise(r=>setTimeout(r,10));}}
 await f.admit('next');const pin=await f.pin('next','work');await start();const first=child!.pid;const post=async(body:unknown)=>{const r=await fetch(base+'/missions/mission/work-prerequisite',{method:'POST',headers:{'content-type':'application/json','X-Massion-Feed':(await f.store.readState()).feedId},body:JSON.stringify(body)});assert.equal(r.ok,true);return r.json();};assert.equal((await post(pin)).status,'committed');const state=await f.store.readState('mission'),journal=await f.journal(),next=state.snapshot!.value.works.find((w:import('../src/domain.ts').Work)=>w.id==='next')!,evidence=resolvedPrerequisites(state.snapshot!.value,next);await stop();await start();assert.notEqual(child!.pid,first);assert.deepEqual(await (await fetch(base+'/read-state?mission=mission')).json(),state);assert.equal((await post(pin)).status,'replayed');assert.deepEqual(await f.journal(),journal);assert.deepEqual(resolvedPrerequisites((await f.current()).value,(await f.current()).value.works.find(w=>w.id==='next')!),evidence);assert.deepEqual((await f.current()).value.works[0],f.original.value.works[0]);assert.equal(f.calls.length,0);validateMissionJournalLineage(journal);t.diagnostic(JSON.stringify({distinctNormalCliPids:true,actualStore:true,originalRecordUnchanged:true,exactPrerequisiteDecisionAndRecordMetadataRetained:true,liveCalls:0}));
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} existing Work evidence and preflight surface expose literal prerequisite decision without a write`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await fixture(t,durable);await f.admit('first');await f.admit('next');await f.product.attachWorkPrerequisite('mission',await f.pin('next','first'));const server=createWorkbench(f.store,f.root,{runtime:f.runtime});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const {harness,reply}=await import('./support/workbench-client.ts'),journal=await f.journal(),app=harness(async(path:string,options:any)=>{const r=await fetch('http://127.0.0.1:'+a.port+path,options);return reply(await r.json(),r.status);},{},undefined,{network:true,fragment:'#mission=mission'});const until=async(check:()=>boolean)=>{const deadline=Date.now()+10000;while(!check()){assert.ok(Date.now()<deadline);await new Promise(r=>setTimeout(r,10));}};await until(()=>app.node('snapshot-json').textContent.includes('prerequisites')&&app.node('sync-notice').hidden);assert.ok(app.all().some(n=>n.id==='work-prerequisites-next'&&n.textContent.includes('Owner causal decision <img src=x>')));assert.equal(app.all().some(n=>n.tagName==='IMG'),false);assert.deepEqual(await f.journal(),journal);assert.equal(f.calls.length,0);
});

test('missing or substituted retained consumer prerequisite binding is never reconstructed from current target acceptance',async t=>{
 const f=await fixture(t);await f.admit('next');await f.product.attachWorkPrerequisite('mission',await f.pin('next','work'));assert.equal((await f.product.run('mission','next','consumer',(await f.current()).revision)).status,'settled');const state=await f.store.readState('mission'),{readRecordArtifact}=await import('../src/record-artifact.ts'),{validateMissionLineage}=await import('../src/backup-lineage.ts');
 for(const missing of [true,false]){const copy=structuredClone(state),w=copy.snapshot!.value.works.find(w=>w.id==='next')!;if(missing){delete w.prerequisiteRecords;delete w.record!.prerequisiteRecords;}else{w.prerequisiteRecords![0]!.checksum='0'.repeat(64);w.record!.prerequisiteRecords=structuredClone(w.prerequisiteRecords);}const {checksum,...bundle}=w.record!;w.record!.checksum=hash(bundle);assert.throws(()=>resolvedPrerequisites(copy.snapshot!.value,w),/retained|Retained/);assert.throws(()=>validateMissionLineage(copy.snapshot!.value));let reads=0;await assert.rejects(readRecordArtifact({readState:async()=>copy} as any,{read:async()=>{reads++;return 'fallback';}},'mission','next',{recordId:w.record!.id,artifactVersion:w.artifact!.version,artifactSha256:w.artifact!.sha256}),/prerequisite evidence/);assert.equal(reads,0);}
 assert.equal(f.calls.length,2);assert.deepEqual(await f.store.readState('mission'),state);
});
