import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {lifetimeFixture} from './support/runtime-lifetime-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
import {workInputHash} from '../src/domain.ts';
async function fixture(t:any,durable=false,mode='normal'){
 const f=await lifetimeFixture(t,durable);await f.product.create({id:'other',purpose:'Other',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'other');const server=createWorkbench(f.store,f.root,{providers:f.product.providers,runtime:f.runtime,artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address() as any,base='http://127.0.0.1:'+address.port;let writes=0,release!:()=>void;const gate=new Promise<void>(r=>release=r);
 const handler=async(path:string,options:any)=>{const writing=/\/work-(question|answer)$/.test(path)&&options.method==='POST';if(writing)writes++;const response=await fetch(base+path,options),body=await response.json();if(writing){if(mode.startsWith('held'))await gate;if(mode.includes('unknown'))throw Error('Controlled lost committed answer receipt');if(mode==='wrong-feed')body.feedId='different-db';}return reply(body,response.status);};async function client(){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);return app;}return {...f,base,client,release:()=>release(),writes:()=>writes};
}
async function choose(app:any,text='Literal owner question <img src=x> 원문 😀',answer=false){app.node('clarification-work').value='fresh';await app.node('clarification-work').fire('change');if(answer){const qs=runInContext('snapshot.value.works.find(w=>w.id==="fresh").questions',app.context);app.node('clarification-question').value=qs[0].id;await app.node('clarification-question').fire('change');}app.node('clarification-text').value=text;await app.node('clarification-text').fire('input');await app.node('clarification-review').fire('click');}
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} private question cancel, exact save, literal answer and separate Run preserve original evidence`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const f=await fixture(t,durable),app=await f.client(),before=await f.current();await choose(app);assert.equal(app.node('clarification-save').disabled,false);await app.node('clarification-cancel').fire('click');assert.equal(f.writes(),0);assert.deepEqual(await f.current(),before);await choose(app);await app.submit('clarification-form');assert.match(app.node('clarification-status').textContent,/confirmed/);let now=await f.current(),w=now.value.works.find(w=>w.id==='fresh')!;assert.equal(w.questions![0]!.answer,null);assert.equal(f.calls.length,0);assert.equal(await runInContext('sequenceHash(sequenceInput(snapshot.value.works.find(w=>w.id==="fresh")))',app.context),workInputHash(w));await choose(app,'Original bounded lifetime fixture',true);assert.match(app.node('clarification-original').textContent,/Literal owner question/);await app.submit('clarification-form');now=await f.current();w=now.value.works.find(w=>w.id==='fresh')!;assert.equal(w.questions![0]!.answer!.text,'Original bounded lifetime fixture');assert.equal(f.calls.length,0);assert.equal(w.runtimeRun,undefined);assert.deepEqual(now.value.works.find(w=>w.id==='work'),before.value.works.find(w=>w.id==='work'));assert.equal(app.all().some(n=>n.tagName==='IMG'),false);});
for(const mode of ['unknown','wrong-feed'])test(`${mode} question receipt settles once, reload does not repeat`,async t=>{const f=await fixture(t,false,mode),app=await f.client();await choose(app);await app.submit('clarification-form');await app.tick();await f.until(()=>runInContext('unknownOperation',app.context)===null);assert.equal(f.writes(),1);assert.equal((await f.current()).value.works.find(w=>w.id==='fresh')!.questions!.length,1);const fresh=await f.client();await fresh.submit('clarification-form');assert.equal(f.writes(),1);});
test('late question save preserves later draft but requires a new immutable question identity',async t=>{const f=await fixture(t,false,'held'),app=await f.client();await choose(app);const pending=app.submit('clarification-form');await f.until(()=>f.writes()===1);app.node('clarification-text').value='Later distinct question';await app.node('clarification-text').fire('input');f.release();await pending;assert.equal(app.node('clarification-text').value,'Later distinct question');assert.equal(app.node('clarification-save').disabled,true);await app.node('clarification-review').fire('click');await app.submit('clarification-form');const qs=(await f.current()).value.works.find(w=>w.id==='fresh')!.questions!;assert.equal(qs.length,2);assert.notEqual(qs[0]!.id,qs[1]!.id);});
test('stale review and late Mission navigation do not rebase or restore the prior Mission',async t=>{const f=await fixture(t,false,'held'),app=await f.client();await choose(app);await f.product.admit('mission',{commandId:'peer',expectedRevision:(await f.current()).revision,workId:'peer',title:'Other',budget:8});await app.tick();const rev=(await f.current()).revision;await f.until(()=>runInContext('snapshot.revision',app.context)===rev&&!runInContext('loading',app.context));await app.submit('clarification-form');assert.equal(f.writes(),0);await app.node('clarification-review').fire('click');const pending=app.submit('clarification-form');await f.until(()=>f.writes()===1);await runInContext("loadMission('other',false)",app.context);await f.until(()=>app.node('loaded-id').textContent==='other');f.release();await pending;assert.equal(app.node('loaded-id').textContent,'other');assert.equal(f.writes(),1);});
for(const durable of [false,true])test(`${durable?'actual DB':'memory'} identical Mission in a replaced database invalidates reviewed question without writing`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{const first=await fixture(t,durable),second=await fixture(t,durable);let base=first.base,writes=0;const app=harness(async(path:string,options:any)=>{if(/\/work-(question|answer)$/.test(path)&&options.method==='POST')writes++;const response=await fetch(base+path,options);return reply(await response.json(),response.status);},{},undefined,{network:true,fragment:'#mission=mission'});await first.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);await choose(app);const one=await first.journal(),two=await second.journal();base=second.base;await app.windowEvent('online');await app.tick();const deadline=Date.now()+12000;while(!app.node('sync-notice').hidden||app.node('clarification-fields').disabled){assert.ok(Date.now()<deadline);await app.tick();await new Promise(r=>setTimeout(r,10));}assert.equal(app.node('clarification-save').disabled,true);assert.equal(app.node('clarification-text').value,'Literal owner question <img src=x> 원문 😀');await app.submit('clarification-form');assert.equal(writes,0);assert.deepEqual(await first.journal(),one);assert.deepEqual(await second.journal(),two);});
