import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {lifetimeFixture as fixture} from './support/runtime-lifetime-fixture.ts';
import {createWorkbench} from '../src/server.ts';
import {harness,reply} from './support/workbench-client.ts';
async function setup(t:import('node:test').TestContext,durable=false){
 const f=await fixture(t,durable),server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();assert.ok(address&&typeof address==='object');const base=`http://127.0.0.1:${address.port}`;let currentBase=base;let mode='',blocked=false,held=false,release!:(()=>void);t.after(()=>release?.());
 async function handler(path:string,options:any){if(blocked&&(path.startsWith('/events')||path.startsWith('/read-state')))throw Error('Owned fixture holds committed readback');if(path.endsWith('/work-message')){if(mode==='unknown'){blocked=true;return reply({status:'unknown'},503);}if(mode==='reject')return reply({error:'Definite fixture rejection'},400);if(mode==='hold-before'){held=true;await new Promise<void>(r=>release=r);}}
 const response=await fetch(currentBase+path,options),body=await response.json();if(path.endsWith('/work-message')){if(mode==='late'){blocked=true;throw Error('Owned fixture lost committed message ACK');}if(mode==='hold-after'){held=true;await new Promise<void>(r=>release=r);}}return reply(body,response.status);}
 async function until(check:()=>boolean){const end=Date.now()+10000;while(!check()){assert.ok(Date.now()<end,'conversation panel deadline');await new Promise(r=>setTimeout(r,5));}}
 async function client(identity='conversation-client'){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission',identity});await until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);const form=app.node('conversation-form'),fields=app.node('conversation-fields');form.append(fields);for(const id of ['conversation-target','conversation-text','conversation-reply','conversation-messages','conversation-send','conversation-review','conversation-cancel']){const node=app.node(id);fields.append(node);node.onFocus=()=>{if(!fields.disabled)(app.context as any).document.activeElement=node;};}return app;}
 async function choose(app:Awaited<ReturnType<typeof client>>,workId='fresh',text='Owner original <img src=x>\n원문 😀',replyTo=''){app.node('conversation-target').value=workId;await app.node('conversation-target').fire('change');app.node('conversation-text').value=text;await app.node('conversation-text').fire('input');app.node('conversation-reply').value=replyTo;await app.node('conversation-reply').fire('change');}
 return {...f,base,replaceBase(value:string){currentBase=value;},client,choose,until,setMode(value:string){mode=value;},held:()=>held,release(){release?.();},resume(){mode='';blocked=false;held=false;}};
}
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} two clients share literal owner message/reply without altering Work inputs or accepted Record`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),first=await f.client('first'),second=await f.client('second'),works=structuredClone((await f.current()).value.works);await f.choose(first);first.node('conversation-send').focus();await first.submit('conversation-form');await f.until(()=>first.node('conversation-text').value===''&&!first.node('conversation-fields').disabled);assert.equal((first.context as any).document.activeElement.id,'conversation-text');assert.match(first.node('conversation-messages').textContent,/<img src=x>/);await second.submit('load-form');await f.until(()=>second.node('snapshot-json').textContent.includes('conversation:'));await f.choose(second,'fresh','Owner shared reply');const root=(await f.current()).value.conversations![0]!.messages[0]!.id;second.node('conversation-reply').value=root;await second.node('conversation-reply').fire('change');await second.submit('conversation-form');await f.until(()=>(first.calls.length>0&&(second.node('conversation-messages').textContent.includes('Owner shared reply'))));assert.deepEqual((await f.current()).value.works,works);assert.equal(f.calls.length,0);await first.tick();await f.until(()=>first.node('conversation-messages').textContent.includes('Owner shared reply'));assert.equal(first.all().some(n=>n.tagName==='IMG'),false);assert.equal(first.calls.filter(c=>c.path.endsWith('/work-message')).length,1);assert.equal(second.calls.filter(c=>c.path.endsWith('/work-message')).length,1);
});
for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} lost committed message receipt locks repeats, preserves later private edits and clears only exact submission`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const f=await setup(t,durable),app=await f.client();await f.choose(app);f.setMode('late');await app.submit('conversation-form');assert.ok(app.storage.has('massion.workbench.pending'));assert.equal(app.node('conversation-fields').disabled,true);assert.equal((await f.current()).value.conversations![0]!.messages.length,1);await app.submit('conversation-form');app.node('conversation-text').value='Later private text';await app.node('conversation-text').fire('input');f.resume();await app.tick();await f.until(()=>!app.storage.has('massion.workbench.pending')&&!app.node('conversation-fields').disabled);assert.equal(app.node('conversation-text').value,'Later private text');assert.equal(app.calls.filter(c=>c.path.endsWith('/work-message')).length,1);assert.equal((await f.current()).value.conversations![0]!.messages.length,1);
});
test('conversation conflict and state refresh retain original reply/text/revision until deliberate review; no automatic write',async t=>{
 const f=await setup(t),app=await f.client();await f.choose(app,'fresh','Private reviewed draft');const revision=(await f.current()).revision;await f.product.appendWorkMessage('mission',{commandId:'other-client',expectedRevision:revision,workId:'fresh',messageId:'other-client',replyTo:null,text:'Other client changes state'});await app.submit('conversation-form');await f.until(()=>!app.node('conversation-fields').disabled);assert.equal(app.node('conversation-text').value,'Private reviewed draft');assert.match(app.node('conversation-base').textContent,/State or database changed/);const journal=await f.journal();await app.submit('conversation-form');assert.equal(app.calls.filter(c=>c.path.endsWith('/work-message')).length,1);assert.deepEqual(await f.journal(),journal);await app.node('conversation-review').fire('click');await app.submit('conversation-form');assert.equal((await f.current()).value.conversations![0]!.messages.length,2);
});
test('private conversation draft stays Mission/Work-scoped; clearing it does not edit stored messages',async t=>{
 const f=await setup(t),app=await f.client();await f.choose(app,'fresh','Private Fresh');await f.choose(app,'work','Private Accepted');app.node('conversation-target').value='fresh';await app.node('conversation-target').fire('change');assert.equal(app.node('conversation-text').value,'Private Fresh');await f.product.create({id:'other-mission',purpose:'Other',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'other-create');await f.product.admit('other-mission',{commandId:'other-work',expectedRevision:1,workId:'fresh',title:'Same ID different Mission',budget:0});await app.navigateFragment('#mission=other-mission');await f.until(()=>app.node('loaded-id').textContent==='other-mission');await f.choose(app,'fresh','Private Other Mission');await app.navigateFragment('#mission=mission');await f.until(()=>app.node('loaded-id').textContent==='mission');assert.equal(app.node('conversation-target').value,'fresh');assert.equal(app.node('conversation-text').value,'Private Fresh');const journal=await f.journal();await app.node('conversation-cancel').fire('click');assert.equal(app.node('conversation-text').value,'');assert.deepEqual(await f.journal(),journal);
});
test('conversation validation/rejection/unresolved write keeps draft, blocks duplicate submit and does not steal moved focus',async t=>{
 const f=await setup(t),app=await f.client();for(const text of ['',' ','😀'.repeat(1025)]){await f.choose(app,'fresh',text);await app.submit('conversation-form');}assert.equal(app.calls.filter(c=>c.path.endsWith('/work-message')).length,0);await f.choose(app);f.setMode('reject');await app.submit('conversation-form');assert.match(app.node('conversation-text').value,/<img src=x>/);assert.equal(app.storage.has('massion.workbench.pending'),false);f.setMode('hold-after');app.node('conversation-send').focus();const pending=app.submit('conversation-form');await f.until(f.held);app.node('snapshot-json').focus();await app.submit('conversation-form');f.release();await pending;assert.equal((app.context as any).document.activeElement.id,'snapshot-json');assert.equal((await f.current()).value.conversations![0]!.messages.length,1);assert.equal(app.calls.filter(c=>c.path.endsWith('/work-message')).length,2);
 const g=await setup(t),unknown=await g.client();await g.choose(unknown);g.setMode('unknown');await unknown.submit('conversation-form');assert.equal(unknown.node('conversation-fields').disabled,true);await unknown.submit('conversation-form');await unknown.node('conversation-cancel').fire('click');assert.match(unknown.node('conversation-text').value,/<img src=x>/);assert.equal(unknown.calls.filter(c=>c.path.endsWith('/work-message')).length,1);assert.equal((await g.current()).value.conversations,undefined);
});

for(const durable of [false,true])test(`${durable?'actual SurrealDB':'in-memory fixture'} replaced feed clears old conversation confirmation while retaining original private draft binding`,{skip:durable&&!process.env.SURREAL_TEST_RUNTIME},async t=>{
 const first=await setup(t,durable),second=await setup(t,durable),app=await first.client();await first.choose(app);await app.submit('conversation-form');assert.match(app.node('conversation-status').textContent,/Exact owner message confirmed/);await first.choose(app,'fresh','Private draft from original database');const originalJournal=await first.journal(),newJournal=await second.journal();first.replaceBase(second.base);await app.windowEvent('online');const end=Date.now()+10000;while(!app.node('sync-notice').hidden||app.node('conversation-fields').disabled){assert.ok(Date.now()<end,'replacement feed did not recover');await app.tick();await new Promise(r=>setTimeout(r,10));}assert.doesNotMatch(app.node('conversation-status').textContent,/confirmed/);assert.match(app.node('conversation-messages').textContent,/No saved conversation/);assert.equal(app.node('conversation-text').value,'Private draft from original database');assert.match(app.node('conversation-base').textContent,/State or database changed/);assert.equal(app.node('conversation-send').disabled,true);await app.submit('conversation-form');assert.deepEqual(await first.journal(),originalJournal);assert.deepEqual(await second.journal(),newJournal);assert.equal(app.calls.filter(c=>c.path.endsWith('/work-message')).length,1);
});
