import test from 'node:test';
import {once} from 'node:events';
import assert from 'node:assert/strict';
import {growthStore} from './support/growth-fixture.ts';
import {verifyDisposableDatabase} from './support/owned-process.ts';
import {ProductService} from '../src/product.ts';
/** Deliberately sorts after storage.test.ts: fresh clients must still prove the live wrapper identity. */
test('actual SurrealDB fresh owned client after storage crash suite uses live launcher DB and unchanged identity',{skip:!process.env.SURREAL_TEST_RUNTIME},async()=>{
 await verifyDisposableDatabase();const {store}=await growthStore(true);const p=new ProductService(store);assert.equal((await p.create({id:'after-crash',purpose:'Fresh client after destructive storage test',scope:'lifetime',constraints:[],criteria:{version:1,description:'Still usable owned DB',oracle:'manual-review/v1'}},'create-after-crash')).status,'committed');assert.equal((await store.load('after-crash'))!.value.purpose,'Fresh client after destructive storage test');await verifyDisposableDatabase();
});
test('actual SurrealDB nested wrapper deadline terminates owned descendants and DB and releases root without touching suite',{skip:!process.env.SURREAL_TEST_RUNTIME},async()=>{
 const {promisify}=await import('node:util'),{execFile}=await import('node:child_process'),{createServer}=await import('node:net'),{fileURLToPath}=await import('node:url'),{readFile,access}=await import('node:fs/promises');await verifyDisposableDatabase();const original=Number(process.env.SURREAL_TEST_PID),probe=createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const address=probe.address();assert.ok(address&&typeof address==='object');const port=address.port;await new Promise<void>(r=>probe.close(()=>r()));let output='';try{await promisify(execFile)('python3',[fileURLToPath(new URL('../scripts/with-surreal.py',import.meta.url)),'--port',String(port),'--timeout','1','--',process.execPath,fileURLToPath(new URL('./support/lifetime-timeout-child.ts',import.meta.url))],{env:{...process.env,MASSION_SURREAL_BINARY:process.env.MASSION_TEST_SURREAL_BINARY!},maxBuffer:1024*1024});assert.fail('Owned deadline must expire');}catch(error){const e=error as Error&{code:number;stdout:string};assert.equal(e.code,124);output=e.stdout;}
 const server=JSON.parse(output.split('\n').find(l=>l.startsWith('Disposable SurrealDB ready: '))!.slice('Disposable SurrealDB ready: '.length)),child=JSON.parse(output.split('\n').find(l=>l.startsWith('Owned timeout child: '))!.slice('Owned timeout child: '.length));assert.notEqual(server.pid_in_this_exec_namespace,original);await assert.rejects(access(server.runtime),{code:'ENOENT'});for(const pid of [server.pid_in_this_exec_namespace,child.pid,child.descendant]){try{const stat=await readFile('/proc/'+pid+'/stat','utf8');assert.ok(['Z','X'].includes(stat.slice(stat.lastIndexOf(')')+2).split(' ')[0]!),'Owned timeout process must not remain live');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}await verifyDisposableDatabase();assert.equal(Number(process.env.SURREAL_TEST_PID),original);
});
