import { defineMigration } from "@massion/storage";

export const EVIDENCE_INDEX_MIGRATION = defineMigration(
  "0025-evidence-index",
  `
DEFINE TABLE evidence_repository SCHEMAFULL;
DEFINE FIELD repository_id ON evidence_repository TYPE string;
DEFINE FIELD organization_id ON evidence_repository TYPE string;
DEFINE FIELD project_id ON evidence_repository TYPE option<string>;
DEFINE FIELD name ON evidence_repository TYPE string;
DEFINE FIELD provider_kind ON evidence_repository TYPE string ASSERT $value IN ['git', 'filesystem', 'external'];
DEFINE FIELD root_ref ON evidence_repository TYPE string;
DEFINE FIELD root_real_path_hash ON evidence_repository TYPE string;
DEFINE FIELD default_branch ON evidence_repository TYPE option<string>;
DEFINE FIELD status ON evidence_repository TYPE string ASSERT $value IN ['active', 'inactive'];
DEFINE FIELD current_index_version_id ON evidence_repository TYPE option<string>;
DEFINE FIELD created_by_user_id ON evidence_repository TYPE string;
DEFINE FIELD created_at ON evidence_repository TYPE datetime;
DEFINE FIELD updated_at ON evidence_repository TYPE datetime;
DEFINE INDEX evidence_repository_id ON evidence_repository FIELDS repository_id UNIQUE;
DEFINE INDEX evidence_repository_name ON evidence_repository FIELDS organization_id, name UNIQUE;
DEFINE INDEX evidence_repository_tenant ON evidence_repository FIELDS organization_id;

DEFINE TABLE repository_revision SCHEMAFULL;
DEFINE FIELD repository_revision_id ON repository_revision TYPE string;
DEFINE FIELD organization_id ON repository_revision TYPE string;
DEFINE FIELD repository_id ON repository_revision TYPE string;
DEFINE FIELD version ON repository_revision TYPE int;
DEFINE FIELD provider_revision ON repository_revision TYPE string;
DEFINE FIELD revision ON repository_revision TYPE string;
DEFINE FIELD dirty ON repository_revision TYPE bool;
DEFINE FIELD dirty_fingerprint ON repository_revision TYPE option<string>;
DEFINE FIELD manifest_checksum ON repository_revision TYPE string;
DEFINE FIELD root_real_path_hash ON repository_revision TYPE string;
DEFINE FIELD collector_version ON repository_revision TYPE string;
DEFINE FIELD captured_by_user_id ON repository_revision TYPE string;
DEFINE FIELD captured_at ON repository_revision TYPE datetime;
DEFINE INDEX repository_revision_id ON repository_revision FIELDS repository_revision_id UNIQUE;
DEFINE INDEX repository_revision_version ON repository_revision FIELDS organization_id, repository_id, version UNIQUE;
DEFINE INDEX repository_revision_snapshot ON repository_revision FIELDS organization_id, repository_id, revision, manifest_checksum UNIQUE;

DEFINE TABLE index_configuration SCHEMAFULL;
DEFINE FIELD configuration_id ON index_configuration TYPE string;
DEFINE FIELD organization_id ON index_configuration TYPE string;
DEFINE FIELD repository_id ON index_configuration TYPE string;
DEFINE FIELD version ON index_configuration TYPE int;
DEFINE FIELD checksum ON index_configuration TYPE string;
DEFINE FIELD parser_bundle_version ON index_configuration TYPE string;
DEFINE FIELD schema_version ON index_configuration TYPE string;
DEFINE FIELD embedding_version ON index_configuration TYPE option<string>;
DEFINE FIELD embedding_status ON index_configuration TYPE string ASSERT $value IN ['unavailable', 'pending', 'complete', 'failed'];
DEFINE FIELD settings_json ON index_configuration TYPE string;
DEFINE FIELD created_by_user_id ON index_configuration TYPE string;
DEFINE FIELD created_at ON index_configuration TYPE datetime;
DEFINE INDEX index_configuration_id ON index_configuration FIELDS configuration_id UNIQUE;
DEFINE INDEX index_configuration_version ON index_configuration FIELDS organization_id, repository_id, version UNIQUE;
DEFINE INDEX index_configuration_checksum ON index_configuration FIELDS organization_id, repository_id, checksum UNIQUE;

DEFINE TABLE index_version SCHEMAFULL;
DEFINE FIELD index_version_id ON index_version TYPE string;
DEFINE FIELD organization_id ON index_version TYPE string;
DEFINE FIELD repository_id ON index_version TYPE string;
DEFINE FIELD repository_revision_id ON index_version TYPE string;
DEFINE FIELD configuration_id ON index_version TYPE string;
DEFINE FIELD version ON index_version TYPE int;
DEFINE FIELD mode ON index_version TYPE string ASSERT $value IN ['full', 'incremental', 'reconcile'];
DEFINE FIELD parent_index_version_id ON index_version TYPE option<string>;
DEFINE FIELD status ON index_version TYPE string ASSERT $value IN ['building', 'complete', 'partial', 'failed', 'superseded'];
DEFINE FIELD current ON index_version TYPE bool;
DEFINE FIELD parser_bundle_version ON index_version TYPE string;
DEFINE FIELD schema_version ON index_version TYPE string;
DEFINE FIELD embedding_version ON index_version TYPE option<string>;
DEFINE FIELD embedding_status ON index_version TYPE string ASSERT $value IN ['unavailable', 'pending', 'complete', 'failed'];
DEFINE FIELD configuration_checksum ON index_version TYPE string;
DEFINE FIELD snapshot_checksum ON index_version TYPE option<string>;
DEFINE FIELD file_count ON index_version TYPE int;
DEFINE FIELD symbol_count ON index_version TYPE int;
DEFINE FIELD relation_count ON index_version TYPE int;
DEFINE FIELD chunk_count ON index_version TYPE int;
DEFINE FIELD error_json ON index_version TYPE option<string>;
DEFINE FIELD created_by_user_id ON index_version TYPE string;
DEFINE FIELD created_at ON index_version TYPE datetime;
DEFINE FIELD completed_at ON index_version TYPE option<datetime>;
DEFINE FIELD updated_at ON index_version TYPE datetime;
DEFINE INDEX index_version_id ON index_version FIELDS index_version_id UNIQUE;
DEFINE INDEX index_version_number ON index_version FIELDS organization_id, repository_id, version UNIQUE;
DEFINE INDEX index_version_current ON index_version FIELDS organization_id, repository_id, current;

DEFINE TABLE evidence_index_event SCHEMAFULL;
DEFINE FIELD event_id ON evidence_index_event TYPE string;
DEFINE FIELD organization_id ON evidence_index_event TYPE string;
DEFINE FIELD repository_id ON evidence_index_event TYPE string;
DEFINE FIELD repository_revision_id ON evidence_index_event TYPE option<string>;
DEFINE FIELD index_version_id ON evidence_index_event TYPE option<string>;
DEFINE FIELD command_id ON evidence_index_event TYPE string;
DEFINE FIELD event_type ON evidence_index_event TYPE string;
DEFINE FIELD request_hash ON evidence_index_event TYPE string;
DEFINE FIELD payload_json ON evidence_index_event TYPE string;
DEFINE FIELD result_json ON evidence_index_event TYPE string;
DEFINE FIELD actor_user_id ON evidence_index_event TYPE string;
DEFINE FIELD created_at ON evidence_index_event TYPE datetime;
DEFINE INDEX evidence_index_event_id ON evidence_index_event FIELDS event_id UNIQUE;
DEFINE INDEX evidence_index_event_command ON evidence_index_event FIELDS organization_id, command_id UNIQUE;
DEFINE INDEX evidence_index_event_repository ON evidence_index_event FIELDS organization_id, repository_id;
`,
);
