import {Application} from '../../src/application.ts';
import {ProductService} from '../../src/product.ts';
import type {Command} from '../../src/domain.ts';
import {growthStore,growthJournal} from './growth-fixture.ts';
import {textFixture} from './record-artifact-fixture.ts';
/** Data-only accepted evidence and actual source pins; no provider invocation or new quality claim. */
export const usageDocument=(version=1)=>({id:'document:source',version,title:'Original source v'+version,content:version===1?'Original local source <img src=x>':'Changed source v2',source:'Approved fixture source v'+version});
export async function documentUsageFixture(t:import('node:test').TestContext,durable=false,cli=false){
 const {store,transport}=await growthStore(durable),f=await textFixture(t,store,cli),product=new ProductService(store),original=(await store.load('mission'))!,app=new Application(store,[{id:'local-owner',roles:['owner']},{id:'executor',roles:['executor']},{id:'verifier',roles:['verifier']}]);let sequence=0;
 const send=async(command:Command,actorId='local-owner')=>app.dispatch({missionId:'mission',commandId:'usage-fixture-'+(++sequence),expectedRevision:(await store.load('mission'))!.revision,actorId,command});
 async function work(id:string,version=1,accept=false){if(accept)await send({type:'admit-work',workId:id,title:'Data-only accepted source fixture '+id,budget:2});else await product.admit('mission',{commandId:'admit-'+id,expectedRevision:(await store.load('mission'))!.revision,workId:id,title:'Original source responsibility '+id,budget:2});const d=(await store.load('mission'))!.value.documents!.find(d=>d.version===version)!;await product.attachWorkSource('mission',{commandId:'source-'+id,expectedRevision:(await store.load('mission'))!.revision,workId:id,documentId:d.id,version,contentSha256:d.contentSha256,reason:'Owner original decision '+id+' <img src=x>'});if(accept){for(const role of ['executor','verifier'] as const)await send({type:'assign',workId:id,assignment:{id:id+'-'+role,actorId:role,role,taskId:id+':root',model:original.value.works[0]!.assignments.find(a=>a.role===role)!.model,extensionVersion:'controlled-source-evidence/v1'}});await send({type:'admit-effect',workId:id,effect:{id:'effect-'+id,taskId:id+':root',status:'pending',target:'Fixture accepted bytes',authority:'Data-only source use fixture'},reserve:1},'executor');await send({type:'receipt',workId:id,effectId:'effect-'+id,outcome:'succeeded',receipt:'Controlled fixture, no model',usage:1},'executor');await send({type:'publish-artifact',workId:id,artifact:f.artifact},'executor');await send({type:'verify',workId:id,verdict:{id:'verdict-'+id,verifierAssignmentId:id+'-verifier',artifactSha256:f.artifact.sha256,artifactVersion:1,criteriaVersion:1,status:'passed',evidence:[{kind:'fixture',detail:'Data-only independent role evidence',source:'test'}]}},'verifier');await send({type:'settle-task',workId:id,taskId:id+':root',result:'Original accepted fixture'},'executor');await send({type:'accept',workId:id,recordId:'record-'+id,artifactSnapshot:await f.artifacts.snapshot(f.artifact)});} }
 await product.captureDocument('mission',{commandId:'doc-1',expectedRevision:original.revision,document:usageDocument()});await work('source-accepted',1,true);await product.captureDocument('mission',{commandId:'doc-2',expectedRevision:(await store.load('mission'))!.revision,document:usageDocument(2)});await work('source-later',2);const current=(await store.load('mission'))!,query=(version=1)=>{const d=current.value.documents!.find(d=>d.version===version)!;return {id:d.id,version:d.version,contentSha256:d.contentSha256};};return {...f,transport,product,original,query,work,journal:()=>growthJournal(store)};
}
