import type {TestContext} from 'node:test';
import {once} from 'node:events';
import {lifetimeFixture} from './runtime-lifetime-fixture.ts';
import {ConfiguredTextRuntime} from '../../src/configured-runtime.ts';
import {Application} from '../../src/application.ts';
import {createWorkbench} from '../../src/server.ts';
import {harness,reply} from './workbench-client.ts';
export async function expiredFixture(t:TestContext,durable=false,stage:'activation'|'pending'|'unknown'='activation',mode=''){
 const f=await lifetimeFixture(t,durable,{runTimeoutMs:durable?1500:150});const store=new Proxy(f.store,{get(target,key){if(key==='commit')return async(input:any)=>{const r=await target.commit(input);if(stage==='activation'&&input.commandId==='stranded-ui')throw Error('Controlled activation ACK loss');return r;};const v=Reflect.get(target,key);return typeof v==='function'?v.bind(target):v;}}),runtime=new ConfiguredTextRuntime(store,f.config),internal=runtime as any;if(stage!=='activation'){const send=internal.dispatch.bind(runtime);internal.dispatch=async(id:string,c:any,...args:any[])=>{const r=await send(id,c,...args);if(c.type==='claim-provider-dispatch')throw Error('Controlled claim ACK loss');return r;};}await import('node:assert/strict').then(async({default:a})=>a.rejects(runtime.run('mission','fresh','stranded-ui',(await f.current()).revision)));
 if(stage==='unknown'){const w=(await f.current()).value.works.find(w=>w.id==='fresh')!,e=w.effects[0]!;await new Application(f.store,[{id:'host-executor',roles:['executor']}]).dispatch({missionId:'mission',commandId:'known-unknown',expectedRevision:(await f.current()).revision,actorId:'host-executor',command:{type:'receipt',workId:'fresh',effectId:e.id,providerDispatchId:e.providerDispatch!.id,outcome:'unknown',receipt:'Original unknown receipt',usage:null}});}
 await f.product.create({id:'other',purpose:'Other context',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'other');const original=await f.current(),deadline=original.value.works.find(w=>w.id==='fresh')!.runtimeRun!.ownership!.deadlineAt;await new Promise(r=>setTimeout(r,Math.max(0,deadline-Date.now())+5));const server=createWorkbench(f.store,f.root);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();if(!a||typeof a==='string')throw Error('No address');const base='http://127.0.0.1:'+a.port;let writes=0,reads=0,release!:()=>void;const gate=new Promise<void>(r=>release=r);let submitted:any;
 const handler=async(path:string,options:any)=>{const post=path.endsWith('/commands')&&options.method==='POST',read=path.includes('/run-ownership?');if(post){writes++;submitted=JSON.parse(options.body);if(mode==='unknown-no-commit')return reply({status:'unknown',error:'Controlled unconfirmed transaction'},503);if(mode==='held-rejected'){await gate;return reply({status:'conflict',reason:'revision'},409);}}if(read)reads++;const res=await fetch(base+path,options),body=await res.json();if((post&&mode.startsWith('held'))||(read&&mode==='held-read'))await gate;if(post&&['unknown','held-unknown'].includes(mode))throw Error('Controlled lost closure reply');if(read&&mode==='wrong-feed')body.feedId='other-db';if(read&&mode==='before-deadline'){body.observedAt=deadline-1;body.deadlineHasPassed=false;}if(read&&mode==='wrong-run')body.runId='other-run';return reply(body,res.status);};async function client(){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);return app;}return {...f,client,base,original,release:()=>release(),writes:()=>writes,reads:()=>reads,submitted:()=>submitted};
}
export async function chooseExpired(app:any,reason='Owner inspected expired original <img src=x>'){app.node('expired-work').value='fresh';await app.node('expired-work').fire('change');app.node('expired-reason').value=reason;await app.node('expired-reason').fire('input');app.node('expired-ack').checked=true;await app.node('expired-ack').fire('change');}
