import type {TestContext} from 'node:test';
import {memoryConflictFixture} from './memory-conflict-fixture.ts';
import {Application} from '../../src/application.ts';
import type {Command} from '../../src/domain.ts';
import {memoryVersionHash} from '../../src/domain.ts';
export const LITERAL_MEMORY_ID='  mémoire\r\n원문😀<&?+#%/@1  ';
export const NEAR_MEMORY_ID='  mémoire\n원문😀<&?+#%/@1  ';
/** Data-only original Record/unknown effect plus literal memory pins. No adapter/runtime calls. */
export async function literalMemoryFixture(t:TestContext,durable=false,cli=false){
 const f=await memoryConflictFixture(t,durable,cli),id=LITERAL_MEMORY_ID;
 const save=async(memoryId:string,version:number,content:string)=>f.product.saveMemory('mission',{commandId:'literal-save-'+memoryId+'-'+version,expectedRevision:(await f.current()).revision,memory:{id:memoryId,version,content,source:'Literal owner provenance\r\n원문 😀'}});
 await save(id,1,'Original literal v1 <img src=x>\r\n원문 😀');await save(NEAR_MEMORY_ID,1,'Distinct LF identity');await save('é',1,'Composed identity');await save('e\u0301',1,'Decomposed identity');await save('long literal '+ 'x'.repeat(150),1,'Stored identity beyond 128 units');
 const app=new Application(f.store,[{id:'local-owner',roles:['owner']},{id:'literal-executor',roles:['executor']},{id:'literal-verifier',roles:['verifier']}]);let sequence=0;const send=async(command:Command,actorId='local-owner')=>app.dispatch({missionId:'mission',commandId:'literal-data-'+(++sequence),expectedRevision:(await f.current()).revision,actorId,command});
 await send({type:'admit-work',workId:'literal-accepted',title:'Data-only original literal memory Record',budget:2});const model={provider:'fixture',model:'data-only',configVersion:'literal-v1',reason:'Data-only Record, no model/provider invocation',evidenceClass:'fixture' as const};for(const role of ['executor','verifier'] as const)await send({type:'assign',workId:'literal-accepted',assignment:{id:'literal-'+role,actorId:'literal-'+role,role,taskId:'literal-accepted:root',model,extensionVersion:'v1'}});
 await send({type:'admit-effect',workId:'literal-accepted',effect:{id:'literal-effect',taskId:'literal-accepted:root',status:'pending',target:'Data-only prepared literal artifact',authority:'Data-only owner fixture'},reserve:1},'literal-executor');await send({type:'receipt',workId:'literal-accepted',effectId:'literal-effect',outcome:'succeeded',receipt:'Prepared fixture bytes, no external action',usage:1},'literal-executor');const artifact=await f.artifacts.write('literal-accepted',1,'Literal memory accepted fixture\n원문 😀');await send({type:'publish-artifact',workId:'literal-accepted',artifact},'literal-executor');await send({type:'verify',workId:'literal-accepted',verdict:{id:'literal-verdict',verifierAssignmentId:'literal-verifier',artifactSha256:artifact.sha256,artifactVersion:1,criteriaVersion:1,status:'passed',evidence:[{kind:'fixture',detail:'Data-only independent role',source:'test'}]}},'literal-verifier');await send({type:'settle-task',workId:'literal-accepted',taskId:'literal-accepted:root',result:'Data-only fixture settled'},'literal-executor');await send({type:'accept',workId:'literal-accepted',recordId:'literal-record',artifactSnapshot:await f.artifacts.snapshot(artifact)});
 await save(id,2,'Later literal v2');await send({type:'admit-work',workId:'literal-fresh',title:'Fresh v2 pinned responsibility',budget:0});await f.product.retireMemory('mission',{commandId:'literal-retire',expectedRevision:(await f.current()).revision,memoryId:id,version:2,reason:'Preserve original pins while stopping future application'});
 const query=async(memoryId=id,version=1)=>{const m=(await f.current()).value.memories.find(m=>m.id===memoryId&&m.version===version)!;return {id:memoryId,version,versionHash:memoryVersionHash(m)};};return {...f,id,query};
}
