import type {TestContext} from 'node:test';
import {growthStore,growthJournal} from './growth-fixture.ts';
import {textFixture} from './record-artifact-fixture.ts';
import {LITERAL_MEMORY_ID,NEAR_MEMORY_ID} from './memory-usage-literal-fixture.ts';
import {ProductService} from '../../src/product.ts';
import {Application} from '../../src/application.ts';
import type {Command} from '../../src/domain.ts';
import {memoryVersionHash} from '../../src/domain.ts';
/** Data-only paged original Work/Record fixture; no runtime/provider/model call. */
export async function memoryUsagePagesFixture(t:TestContext,durable=false,cli=false,count=22){
 const {store,transport}=await growthStore(durable),f=await textFixture(t,store,cli),product=new ProductService(store),current=async()=>(await store.load('mission'))!,app=new Application(store,[{id:'local-owner',roles:['owner']},{id:'page-executor',roles:['executor']},{id:'page-verifier',roles:['verifier']}]);let seq=0;const send=async(command:Command,actorId='local-owner')=>app.dispatch({missionId:'mission',commandId:'page-data-'+(++seq),expectedRevision:(await current()).revision,actorId,command});
 for(const [id,content] of [[LITERAL_MEMORY_ID,'Original page memory <img src=x>\r\n원문 😀'],[NEAR_MEMORY_ID,'Different literal LF identity']])await product.saveMemory('mission',{commandId:'page-save-'+id,expectedRevision:(await current()).revision,memory:{id:id!,version:1,content:content!,source:'Owner data-only source'}});
 for(let i=0;i<count;i++)await send({type:'admit-work',workId:'use-'+String(i).padStart(2,'0'),title:'Original pinned responsibility '+i,budget:2});
 if(count){const workId='use-00',model={provider:'fixture',model:'data-only',configVersion:'pages-v1',reason:'Prepared data-only Record, no invocation',evidenceClass:'fixture' as const};for(const role of ['executor','verifier'] as const)await send({type:'assign',workId,assignment:{id:'page-'+role,actorId:'page-'+role,role,taskId:workId+':root',model,extensionVersion:'v1'}});await send({type:'admit-effect',workId,effect:{id:'page-effect',taskId:workId+':root',status:'pending',target:'Prepared data-only bytes',authority:'Owner data-only fixture'},reserve:1},'page-executor');await send({type:'receipt',workId,effectId:'page-effect',outcome:'succeeded',receipt:'Prepared bytes, no external call',usage:1},'page-executor');const artifact=await f.artifacts.write(workId,1,'Accepted exact memory usage page fixture\n원문');await send({type:'publish-artifact',workId,artifact},'page-executor');await send({type:'verify',workId,verdict:{id:'page-verdict',verifierAssignmentId:'page-verifier',artifactSha256:artifact.sha256,artifactVersion:1,criteriaVersion:1,status:'passed',evidence:[{kind:'fixture',detail:'Data-only roles',source:'test'}]}},'page-verifier');await send({type:'settle-task',workId,taskId:workId+':root',result:'Prepared fixture settled'},'page-executor');await send({type:'accept',workId,recordId:'page-record',artifactSnapshot:await f.artifacts.snapshot(artifact)});}
 if(count>1){const workId='use-01',model={provider:'fixture',model:'data-only',configVersion:'pages-v1',reason:'Prepared unknown data, no invocation',evidenceClass:'fixture' as const};await send({type:'assign',workId,assignment:{id:'unknown-page-executor',actorId:'page-executor',role:'executor',taskId:workId+':root',model,extensionVersion:'v1'}});await send({type:'admit-effect',workId,effect:{id:'page-unknown',taskId:workId+':root',status:'pending',target:'Prepared unknown target',authority:'Data-only fixture'},reserve:1},'page-executor');await send({type:'receipt',workId,effectId:'page-unknown',outcome:'unknown',receipt:'Original unknown fixture receipt; no external call',usage:null},'page-executor');}
 await product.retireMemory('mission',{commandId:'page-retire',expectedRevision:(await current()).revision,memoryId:LITERAL_MEMORY_ID,version:1,reason:'Retain exact historical page pins'});await product.create({id:'other',purpose:'Other Mission',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'manual-review/v1'}},'page-other');
 const query=async()=>{const state=await store.readState('mission'),m=state.snapshot!.value.memories.find(m=>m.id===LITERAL_MEMORY_ID)!;return {id:m.id,version:m.version,versionHash:memoryVersionHash(m),feedId:state.feedId,revision:state.snapshot!.revision};};async function until(check:()=>boolean){const end=Date.now()+12000;while(!check()){if(Date.now()>end)throw Error('Page fixture deadline');await new Promise(r=>setTimeout(r,5));}}return {...f,id:LITERAL_MEMORY_ID,transport,product,current,send,query,until,journal:()=>growthJournal(store)};
}
