import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {runInContext} from 'node:vm';
import {lifetimeFixture as fixture} from './runtime-lifetime-fixture.ts';
import {ConnectionWorkbench} from '../../src/connection-workbench.ts';
import {createWorkbench} from '../../src/server.ts';
import {hash,workInputHash} from '../../src/domain.ts';
import {harness,reply} from './workbench-client.ts';
export async function setup(t:import('node:test').TestContext,durable=false,mode?:'unknown'|'held-review'|'wrong-feed'|'malformed'|'attach-unknown'|'attach-held'|'attach-wrong-feed'|'attach-held-unknown'|'attach-held-rejected'){
 const f=await fixture(t,durable),calls:any[]=[];await f.product.admit('mission',{commandId:'second',expectedRevision:(await f.current()).revision,workId:'second',title:'Causal successor <img src=x>',budget:8});let s=await f.current(),first=s.value.works.find(w=>w.id==='fresh')!;await f.product.attachWorkPrerequisite('mission',{commandId:'pin',expectedRevision:s.revision,workId:'second',prerequisiteId:'fresh',criteriaHash:hash(first.criteria),inputHash:workInputHash(first),reason:'Original dependency <img src=x>'});await f.product.admit('mission',{commandId:'third',expectedRevision:(await f.current()).revision,workId:'third',title:'Unrequested fresh Work',budget:8});await f.product.create({id:'other',purpose:'Other private draft',scope:'local',constraints:[],criteria:{version:1,description:'Other',oracle:'bounded-text-review/v1'}},'other');
 const manager=new ConnectionWorkbench(f.store,f.artifacts,{allowFixture:true,transport:async(_url,init)=>{const body=JSON.parse(String(init.body)),prompt=JSON.parse(body.messages[0].content);calls.push({model:body.model,prompt});const content=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Original bounded',reason:'Owned fixture verifier'}]}):'Original bounded lifetime fixture';return new Response(JSON.stringify({id:'fixture',object:'chat.completion',created:1,model:body.model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}),{headers:{'content-type':'application/json'}});}});manager.connect({id:'owned',label:'Owned fixture',providerType:'compatible',baseUrl:'http://127.0.0.1:9999/v1/',mode:'local-http-mock'});const connection=manager.list().connections[0]!,executor=manager.selectModel(connection.id,{model:'executor',label:'Executor',expectedConfigHash:connection.configHash}),verifier=manager.selectModel(connection.id,{model:'verifier',label:'Verifier',expectedConfigHash:connection.configHash});manager.authorize({id:'owned-grant',scope:'local',executorProfileId:executor.profileId,verifierProfileId:verifier.profileId,maxOutputTokensPerCall:4,expectedConfigHash:manager.list().configHash});const choice={executorProfileId:executor.profileId,verifierProfileId:verifier.profileId,authorizationId:'owned-grant',outputTokenCap:4},server=createWorkbench(f.store,f.root,{connections:manager,artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const a=server.address();assert.ok(a&&typeof a==='object');const base='http://127.0.0.1:'+a.port;
 async function until(check:()=>boolean){const end=Date.now()+10000;while(!check()){assert.ok(Date.now()<end,'sequence panel deadline');await new Promise(r=>setTimeout(r,10));}}let releaseReview!:(()=>void);const reviewGate=new Promise<void>(r=>releaseReview=r);const handler=async(path:string,options:any)=>{if(mode==='attach-held-rejected'&&path.endsWith('/work-prerequisite')){await reviewGate;return reply({status:'conflict',reason:'revision'},409);}const res=await fetch(base+path,options),body=await res.json();if(mode==='held-review'&&path.endsWith('/preflight')||['attach-held','attach-held-unknown'].includes(mode||'')&&path.endsWith('/work-prerequisite'))await reviewGate;if(['attach-unknown','attach-held-unknown'].includes(mode||'')&&path.endsWith('/work-prerequisite'))throw Error('Controlled lost prerequisite reply');if(mode==='attach-wrong-feed'&&path.endsWith('/work-prerequisite'))body.feedId='other-db';if(mode==='unknown'&&path.endsWith('/run-sequence'))throw Error('Controlled lost final reply');if(mode==='wrong-feed'&&path.endsWith('/run-sequence'))body.feedId='other-database';if(mode==='malformed'&&path.endsWith('/run-sequence'))body.completedWorkIds=['third'];return reply(body,res.status);};async function client(){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission'});await until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);return app;}return {...f,manager,choice,calls,client,until,releaseReview,base};
}