import {once} from 'node:events';
import type {TestContext} from 'node:test';
import {lifetimeFixture} from './runtime-lifetime-fixture.ts';
import {ConfiguredTextRuntime} from '../../src/configured-runtime.ts';
import {ProductService} from '../../src/product.ts';
import {ProviderRegistry} from '../../src/providers.ts';
import type {ProviderAdapter} from '../../src/providers.ts';
import {createWorkbench} from '../../src/server.ts';
import {hash} from '../../src/domain.ts';
import {harness,reply} from './workbench-client.ts';
export const rejectedContent='Wrong answer <img src=x onerror=alert(1)>\n거절된 후보 🌙';
export async function rejectedFixture(t:TestContext,durable=false,mode?:'held'|'wrong-feed'|'bad-bytes'|'wrong-class'){
 const f=await lifetimeFixture(t,durable),calls:string[]=[];const adapter=(role:'executor'|'verifier'):ProviderAdapter=>({...f.config[role].adapter,async invoke(request){calls.push(role);const input=JSON.parse(request.instruction);return {status:'completed',output:role==='executor'?rejectedContent:JSON.stringify({artifactSha256:input.binding.artifactSha256,criteriaVersion:input.criteria.version,criteriaHash:input.binding.criteriaHash,verdict:'failed',checks:[{criterion:input.criteria.description,passed:false,quote:'Wrong answer',reason:'Controlled known incorrect candidate'}]}),usage:{inputTokens:1,outputTokens:1},reason:'Controlled fixture only'};}});const executor=adapter('executor'),verifier=adapter('verifier'),runtime=new ConfiguredTextRuntime(f.store,{...f.config,executor:{...f.config.executor,adapter:executor},verifier:{...f.config.verifier,adapter:verifier}}),providers=new ProviderRegistry([executor,verifier]),product=new ProductService(f.store,providers,runtime,f.artifacts);await product.run('mission','fresh','failed-fixture',(await f.current()).revision);await product.create({id:'other',purpose:'Separate context',scope:'local',constraints:[],criteria:{version:1,description:'Separate',oracle:'manual-review/v1'}},'other');const server=createWorkbench(f.store,f.root,{providers,runtime,artifacts:f.artifacts});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});const address=server.address();if(!address||typeof address==='string')throw Error('No owned server address');const base='http://127.0.0.1:'+address.port;let release!:(()=>void);const gate=new Promise<void>(r=>release=r);const handler=async(path:string,options:any)=>{const response=await fetch(base+path,options),body=await response.json();if(path.includes('/rejected-artifact?')){if(mode==='held')await gate;if(mode==='wrong-feed')body.feedId='another-db';if(mode==='bad-bytes')body.content+='tampered';if(mode==='wrong-class')body.evidenceClass='real-provider';}return reply(body,response.status);};async function client(){const app=harness(handler,{},undefined,{network:true,fragment:'#mission=mission'});await f.until(()=>app.node('loaded-id').textContent==='mission'&&app.node('sync-notice').hidden);return app;}const state=await f.current(),work=state.value.works.find(w=>w.id==='fresh')!;return {...f,product,runtime,providers,calls,base,client,release:()=>release(),work,input:{binding:hash(work),artifactVersion:work.artifact!.version,artifactSha256:work.artifact!.sha256,feedId:(await f.store.readState()).feedId}};
}
