import {textFixture} from './record-artifact-fixture.ts';
import {growthStore,growthJournal} from './growth-fixture.ts';
import {ConfiguredTextRuntime} from '../../src/configured-runtime.ts';
import {ProductService} from '../../src/product.ts';
import {ProviderRegistry} from '../../src/providers.ts';
import type {ProviderAdapter,ProviderRequest} from '../../src/providers.ts';
/** Controlled adapters can deliberately ignore AbortSignal. No real provider or account. */
export async function lifetimeFixture(t:import('node:test').TestContext,durable=false,options:{hold?:'executor'|'verifier';runTimeoutMs?:number;cli?:boolean;originalArtifactText?:string}={}){
 const {store,transport}=await growthStore(durable),f=await textFixture(t,store,options.cli,options.originalArtifactText),original=(await store.load('mission'))!,calls:{role:string;input:any;signal:AbortSignal}[]=[];let release!:(()=>void);const held=new Promise<void>(r=>release=r);
 const adapter=(role:string):ProviderAdapter=>({descriptor:{provider:'controlled-lifetime-fixture',model:role,configVersion:'fixture-v1',enabled:true,capabilities:['text-output'],evidenceClass:'fixture'},async invoke(req:ProviderRequest){const input=JSON.parse(req.instruction);calls.push({role,input,signal:req.signal});if(options.hold===role)await held;return {status:'completed',output:role==='executor'?'Original bounded lifetime fixture':JSON.stringify({artifactSha256:input.binding.artifactSha256,criteriaVersion:input.criteria.version,criteriaHash:input.binding.criteriaHash,verdict:'passed',checks:[{criterion:input.criteria.description,passed:true,quote:'Original bounded',reason:'Independent controlled verifier fixture'}]}),usage:{inputTokens:1,outputTokens:1},reason:'Credential-free fixture'};}}),executor=adapter('executor'),verifier=adapter('verifier'),config={enabled:true,runTimeoutMs:options.runTimeoutMs,outputTokenCap:4,authorization:{id:'controlled-lifetime-only',scope:'local',mode:'mock-http' as const,executor:executor.descriptor,verifier:verifier.descriptor,maxOutputTokensPerCall:4},executor:{identity:'host-executor',adapter:executor},verifier:{identity:'host-verifier',adapter:verifier},artifacts:f.artifacts},runtime=new ConfiguredTextRuntime(store,config),product=new ProductService(store,new ProviderRegistry([executor,verifier]),runtime),current=async()=>(await store.load('mission'))!;t.after(()=>release());
 await product.reviseMission('mission',{commandId:'lifetime-criteria',expectedRevision:original.revision,purpose:original.value.purpose,criteria:{version:2,description:'Original bounded lifetime fixture',oracle:'bounded-text-review/v1'}});await product.admit('mission',{commandId:'lifetime-admit',expectedRevision:(await current()).revision,workId:'fresh',title:'Owned bounded execution',budget:8});
 async function until(check:()=>boolean){const deadline=Date.now()+10000;while(!check()){if(Date.now()>deadline)throw Error('Lifetime fixture deadline');await new Promise(r=>setTimeout(r,5));}}
 return {...f,transport,original,calls,config,runtime,product,current,until,release:()=>release(),journal:()=>growthJournal(store)};
}
