/** Explicit disposable loopback browser QA. In-memory Mission; synthetic model outputs only. */
import {createServer} from 'node:http';
import {once} from 'node:events';
import {mkdir,appendFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {InMemoryStore} from '../src/storage.ts';
import type {Mission} from '../src/domain.ts';
import {TextArtifactStore} from '../src/text-artifacts.ts';
import {ConnectionWorkbench} from '../src/connection-workbench.ts';
import {createWorkbench} from '../src/server.ts';
const root=resolve(process.env.MASSION_BROWSER_QA_ROOT??'.runtime/browser-qa');await mkdir(root,{recursive:true});
const log=(value:unknown)=>appendFile(resolve(root,'fixture-events.jsonl'),JSON.stringify({at:new Date().toISOString(),value})+'\n');
const provider=createServer(async(req,res)=>{res.setHeader('content-type','application/json');const path=req.url??'';const anthropic=path.includes('/anthropic/'),gemini=path.includes('/gemini/');if(req.method==='GET'){await log({kind:'model-discovery',path});if(path.includes('/slow/'))await new Promise(r=>setTimeout(r,8000));if(path.includes('/unavailable/')){res.statusCode=503;res.end(JSON.stringify({error:'Synthetic discovery unavailable'}));return;}const models=anthropic?['native-executor','slow-executor']:gemini?['native-reviewer']:['chat-executor','chat-reviewer'];res.end(JSON.stringify(gemini?{models:models.map(id=>({name:'models/'+id,displayName:id,supportedGenerationMethods:['generateContent'],outputTokenLimit:1024}))}:{data:models.map(id=>({id,display_name:id}))}));return;}
 let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);const model=gemini?/\/models\/([^/:]+):generateContent/.exec(path)?.[1]:body.model;const text=gemini?body.contents[0].parts[0].text:body.messages[0].content;const prompt=JSON.parse(text);await log({kind:'fixture-model-send',model,protocol:anthropic?'anthropic':gemini?'gemini':'chat',stage:prompt.artifact?'verifier':'executor'});if(model==='slow-executor')await new Promise(r=>setTimeout(r,45000));const output=prompt.artifact?JSON.stringify({artifactSha256:prompt.binding.artifactSha256,criteriaVersion:prompt.criteria.version,criteriaHash:prompt.binding.criteriaHash,verdict:'passed',checks:[{criterion:prompt.criteria.description,passed:true,quote:'Rendered browser fixture result',reason:'Synthetic exact-text evidence'}]}):'Rendered browser fixture result';
 res.end(JSON.stringify(anthropic?{id:'browser-qa',type:'message',role:'assistant',model,stop_reason:'end_turn',content:[{type:'text',text:output}],usage:{input_tokens:3,output_tokens:2}}:gemini?{responseId:'browser-qa',modelVersion:model,candidates:[{finishReason:'STOP',content:{role:'model',parts:[{text:output}]}}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:2,totalTokenCount:5}}:{id:'browser-qa',object:'chat.completion',created:1,model,choices:[{index:0,finish_reason:'stop',message:{role:'assistant',content:output}}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}}));
});provider.listen(18767,'127.0.0.1');await once(provider,'listening');const store=new InMemoryStore<Mission>(),artifacts=new TextArtifactStore(resolve(root,'artifacts'));const connections=new ConnectionWorkbench(store,artifacts,{transport:(url,init)=>fetch(url,init),allowFixture:true});const server=createWorkbench(store,root,{connections});server.listen(8766,'127.0.0.1');await once(server,'listening');console.log(JSON.stringify({workbench:'http://127.0.0.1:8766',providerBase:'http://127.0.0.1:18767/',root,mode:'disposable-in-memory-synthetic-browser-qa'}));for(const signal of ['SIGTERM','SIGINT'] as const)process.on(signal,()=>{server.closeAllConnections();provider.closeAllConnections();server.close();provider.close();process.exit(0);});
