/** Session-scoped user connection setup. Credentials remain exclusively in the host resolver. */
import {DomainError,hash} from './domain.ts';
import type {Mission} from './domain.ts';
import type {Store,Snapshot} from './storage.ts';
import {ConnectionCatalog} from './provider-profiles.ts';
import type {ModelConnectionProfile} from './provider-profiles.ts';
import {chatProfileFactory} from './chat-profile-factory.ts';
import type {CredentialResolver} from './chat-profile-factory.ts';
import {nativeProfileFactory,credentialHeaders,validateModelEndpoint} from './native-model-providers.ts';
import {readBoundedJson} from './http-provider.ts';
import type {HttpProviderTransport} from './http-provider.ts';
import {SelectableTextRuntime} from './selectable-runtime.ts';
import type {ExecutionAuthorization,ExecutionChoice} from './selectable-runtime.ts';
import type {WorkRuntime} from './configured-runtime.ts';
import type {TextArtifactStore} from './text-artifacts.ts';
import {boundedPlainJson} from './bounded-json.ts';
export const MODEL_PROVIDER_TYPES=[
 {id:'openai',label:'OpenAI API',protocol:'openai-chat-completions/v1',baseUrl:'https://api.openai.com/v1/',auth:'bearer',discovery:'models'},
 {id:'openrouter',label:'OpenRouter API',protocol:'openai-chat-completions/v1',baseUrl:'https://openrouter.ai/api/v1/',auth:'bearer',discovery:'models'},
 {id:'anthropic',label:'Anthropic API',protocol:'anthropic-messages/v1',baseUrl:'https://api.anthropic.com/v1/',auth:'anthropic-api-key',discovery:'models'},
 {id:'gemini',label:'Gemini Developer API',protocol:'gemini-generate-content/v1',baseUrl:'https://generativelanguage.googleapis.com/v1beta/',auth:'google-api-key',discovery:'models'},
 {id:'compatible',label:'Custom Chat Completions API',protocol:'openai-chat-completions/v1',baseUrl:'',auth:'bearer',discovery:'models'}
] as const;
export type ProviderType=typeof MODEL_PROVIDER_TYPES[number]['id'];
export interface ConnectionInput {id:string;label:string;providerType:ProviderType;baseUrl:string;mode:'https'|'local-http-mock';secretRef?:string}
export interface HostConnectionBindings {revision:string;bindingHash:string;connections:{input:ConnectionInput;models:readonly string[]}[]}
interface ConnectionOptions {transport:HttpProviderTransport;resolveCredential?:CredentialResolver;allowFixture?:boolean;allowLiveExecution?:boolean;discoveryTimeoutMs?:number;hostBindings?:HostConnectionBindings}
export interface DiscoveredModel {id:string;label:string;outputTokenLimit:number|null}
interface ConnectionState {input:ConnectionInput;configHash:string;models:DiscoveredModel[];discovery:'not-requested'|'models-discovered'|'discovery-failed';generation:number}
function ensure(v:unknown,m:string):asserts v {if(!v)throw new DomainError(m);}
function id(v:unknown):asserts v is string {ensure(typeof v==='string'&&/^[a-zA-Z0-9:_-]{1,128}$/.test(v),'Invalid connection identity');}
function label(v:unknown):asserts v is string {ensure(typeof v==='string'&&v.length>0&&v.length<=512&&v.trim()===v&&v.isWellFormed()&&!/[\u0000-\u001f\u007f]/.test(v),'Invalid connection label');}
function exact(value:unknown,keys:string[],optional:string[]=[]):asserts value is Record<string,any> {boundedPlainJson(value);ensure(value&&typeof value==='object'&&!Array.isArray(value)&&keys.every(k=>Object.hasOwn(value,k))&&Object.keys(value).every(k=>[...keys,...optional].includes(k)),'Exact connection fields required; raw credentials are not accepted');}
const positive=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>0;
export class ConnectionWorkbench implements WorkRuntime {
 readonly #store:Store<Mission>;readonly #artifacts:TextArtifactStore;readonly #options:ConnectionOptions;#enrolling=false;
 readonly #connections=new Map<string,ConnectionState>();readonly #profiles=new Map<string,{connectionId:string;profile:ModelConnectionProfile}>();#grants:ExecutionAuthorization[]=[];#generation=0;#draining=false;readonly #active=new Map<string,SelectableTextRuntime>();
 constructor(store:Store<Mission>,artifacts:TextArtifactStore,options:ConnectionOptions){this.#store=store;this.#artifacts=artifacts;ensure(options.discoveryTimeoutMs===undefined||positive(options.discoveryTimeoutMs)&&options.discoveryTimeoutMs<=15000,'Invalid discovery timeout');this.#options={...options,...(options.hostBindings?{hostBindings:structuredClone(options.hostBindings)}:{})};this.#enrolling=true;try{for(const entry of this.#options.hostBindings?.connections??[]){this.connect(entry.input);const connection=this.#connections.get(entry.input.id)!;for(const model of entry.models)this.selectModel(entry.input.id,{model,label:model,expectedConfigHash:connection.configHash});}}finally{this.#enrolling=false;}}
 private factories(mode:'https'|'local-http-mock'){const options={mode,transport:this.#options.transport,resolveCredential:this.#options.resolveCredential};return [chatProfileFactory(options),nativeProfileFactory('anthropic-messages/v1',options),nativeProfileFactory('gemini-generate-content/v1',options)];}
 private catalog(){// One catalog per transport mode avoids protocol aliasing between fixture and live.
  const profiles=[...this.#profiles.values()].map(v=>v.profile);const modes=new Set([...this.#profiles.values()].map(v=>this.#connections.get(v.connectionId)!.input.mode));ensure(modes.size<=1,'Fixture and live profiles cannot share a session');return new ConnectionCatalog(profiles,this.factories([...modes][0]??'https'));
 }
 private router(){return new SelectableTextRuntime(this.#store,this.catalog(),this.#grants,this.#artifacts);}
 configuration(){return this.router().configuration();}
 availability(mission:Mission){return this.router().availability(mission);}
 preflight(snapshot:Snapshot<Mission>,workId:string,expectedRevision:number,choice?:ExecutionChoice){return this.router().preflight(snapshot,workId,expectedRevision,choice);}
 beginDrain(){this.#draining=true;for(const runtime of this.#active.values())runtime.beginDrain();}
 async drain(){this.beginDrain();await Promise.all([...this.#active.values()].map(runtime=>runtime.drain()));}
 async run(missionId:string,workId:string,runId:string,expectedRevision:number,choice?:ExecutionChoice){if(this.#draining)throw new DomainError('Local host is draining; no new run is admitted.');const key=missionId+'\0'+workId;if(this.#active.has(key))return {status:'already-started' as const,snapshot:(await this.#store.load(missionId))!,reason:'This Work has an active dispatch.'};const router=this.router();this.#active.set(key,router);try{return await router.run(missionId,workId,runId,expectedRevision,choice);}finally{this.#active.delete(key);}}
 owns(missionId:string,workId:string,runId:string){return this.#active.get(missionId+'\0'+workId)?.owns(missionId,workId,runId)??false;}
 interrupt(missionId:string,workId:string){this.#active.get(missionId+'\0'+workId)?.interrupt(missionId,workId);}
 private version(){return hash({connections:[...this.#connections.values()].map(c=>c.configHash),profiles:[...this.#profiles.values()].map(v=>hash(v.profile)),grants:this.#grants});}
 list(){return {host:this.#options.hostBindings?{managed:true,revision:this.#options.hostBindings.revision,bindingHash:this.#options.hostBindings.bindingHash}:null,providerTypes:MODEL_PROVIDER_TYPES.map(p=>({...p,backend:'model-provider',liveVerified:false})),agentBackends:[{id:'acp',label:'ACP agent session',supported:false},{id:'cli',label:'CLI/subscription agent',supported:false}],connections:[...this.#connections.values()].map(c=>{const p=MODEL_PROVIDER_TYPES.find(p=>p.id===c.input.providerType)!;return {id:c.input.id,label:c.input.label,providerType:p.id,protocol:p.protocol,baseUrl:c.input.baseUrl,mode:c.input.mode,auth:c.input.mode==='local-http-mock'?'none':p.auth,configHash:c.configHash,credentialConfigured:c.input.mode==='local-http-mock'||!!(c.input.secretRef&&this.#options.resolveCredential),connectionStatus:c.input.mode==='local-http-mock'?'fixture':c.input.secretRef&&this.#options.resolveCredential?'configured-unverified':'credential-required',discovery:c.discovery,models:structuredClone(c.models),liveVerified:false};}),runtime:this.configuration(),configHash:this.version(),sessionOnly:true,fixtureModeEnabled:this.#options.allowFixture===true,liveExecutionEnabled:this.#options.allowLiveExecution===true};}
 connect(value:unknown){ensure(!this.#options.hostBindings||this.#enrolling,'Host connections are declared in the selected manifest; edit it and restart to change bindings');ensure(this.#active.size===0,'Active Work pins its connections. Observe completion or cancellation before changing connection configuration.');exact(value,['id','label','providerType','baseUrl','mode'],['secretRef']);id(value.id);label(value.label);const type=MODEL_PROVIDER_TYPES.find(p=>p.id===value.providerType);ensure(type,'Unsupported provider API; ACP/CLI are separate backends');ensure(value.mode==='https'||value.mode==='local-http-mock'&&this.#options.allowFixture===true,'Transport mode is not enabled by this host');if(value.secretRef!==undefined)id(value.secretRef);ensure(value.mode!=='local-http-mock'||value.secretRef===undefined,'Fixture mode cannot carry credentials');const base=value.baseUrl;ensure(typeof base==='string'&&base.endsWith('/'),'Canonical API base URL ending in / required');try{validateModelEndpoint(base+'models',value.mode,'/models');}catch{throw new DomainError('Invalid API base URL; use a canonical URL for the selected transport');}if(type.id!=='compatible'&&value.mode==='https')ensure(base===type.baseUrl,'Choose Custom API for a custom endpoint');ensure([...this.#connections.values()].every(c=>c.input.id===value.id||c.input.mode===value.mode),'Fixture and live connections must use separate sessions');ensure(this.#connections.has(value.id)||this.#connections.size<32,'Connection limit reached');const input=structuredClone(value) as ConnectionInput;this.#connections.set(input.id,{input,configHash:hash(input),models:[],discovery:'not-requested',generation:++this.#generation});const retired=new Set([...this.#profiles].filter(([,p])=>p.connectionId===input.id).map(([key])=>key));for(const key of retired)this.#profiles.delete(key);this.#grants=this.#grants.filter(g=>![...g.executor,...g.verifier].some(p=>retired.has(p.profileId)));return this.list();}
 async discover(connectionId:string,expectedConfigHash:string){const c=this.#connections.get(connectionId);ensure(c&&c.configHash===expectedConfigHash,'Connection changed; refresh before discovery');const current=structuredClone(c);const p=MODEL_PROVIDER_TYPES.find(p=>p.id===c.input.providerType)!;const endpoint=c.input.baseUrl+'models';const controller=new AbortController();const signal=controller.signal;let rejectAbort!:()=>void;const aborted=new Promise<never>((_,reject)=>rejectAbort=()=>reject(Error('Discovery cancelled')));signal.addEventListener('abort',rejectAbort,{once:true});const timer=setTimeout(()=>controller.abort(),this.#options.discoveryTimeoutMs??15000);let failure=false,hasMore=false,models:DiscoveredModel[]=[];
  try{await Promise.race([(async()=>{const headers=await credentialHeaders(c.input.mode==='local-http-mock'?'none':p.auth,{secretRef:c.input.secretRef,profileId:c.input.id,endpoint,signal},this.#options.resolveCredential);signal.throwIfAborted();const response=await this.#options.transport(endpoint,{method:'GET',headers,redirect:'error',credentials:'omit',cache:'no-store',signal});signal.throwIfAborted();ensure(response instanceof Response&&!response.redirected&&(!response.url||response.url===endpoint)&&response.status===200&&/^application\/json(?:\s*;\s*charset=(?:utf-8|"utf-8"))?\s*$/i.test(response.headers.get('content-type')??''),'Model discovery failed');const body=await readBoundedJson(response,524288,signal) as any;hasMore=body.has_more===true||typeof body.nextPageToken==='string'&&body.nextPageToken.length>0;const entries=p.id==='gemini'?body.models:body.data;ensure(Array.isArray(entries)&&entries.length<=1000,'Bounded model list required');for(const entry of entries){ensure(entry&&typeof entry==='object'&&!Array.isArray(entry),'Invalid model metadata');if(p.id==='gemini'){ensure(typeof entry.name==='string'&&entry.name.startsWith('models/')&&Array.isArray(entry.supportedGenerationMethods)&&entry.supportedGenerationMethods.every((method:unknown)=>typeof method==='string'),'Invalid Gemini model metadata');if(!entry.supportedGenerationMethods.includes('generateContent'))continue;}const model=p.id==='gemini'?entry.name.slice(7):entry.id;label(model);ensure(/^[a-zA-Z0-9._:/-]{1,256}$/.test(model),'Invalid model identity');if(this.#options.hostBindings&&!this.#options.hostBindings.connections.find(entry=>entry.input.id===connectionId)?.models.includes(model))continue;const title=entry.display_name??entry.displayName??entry.name??model;label(title);models.push({id:model,label:title,outputTokenLimit:positive(entry.outputTokenLimit)?entry.outputTokenLimit:positive(entry.max_tokens)?entry.max_tokens:null});}ensure(new Set(models.map(m=>m.id)).size===models.length,'Duplicate model identity');})(),aborted]);
  }catch{failure=true;}finally{clearTimeout(timer);signal.removeEventListener('abort',rejectAbort);controller.abort();}
  const latest=this.#connections.get(connectionId);if(!latest||latest.generation!==current.generation||latest.configHash!==expectedConfigHash)return {status:'stale' as const,models:[],message:'Connection changed; previous model results were discarded.'};latest.models=failure?[]:models;latest.discovery=failure?'discovery-failed':'models-discovered';return {status:failure?'unavailable' as const:'listed' as const,models:structuredClone(latest.models),message:failure?'Model discovery unavailable. Connect the host credential or enter an exact model ID manually.':(hasMore?'First page of model metadata received. More models may be entered manually.':'Model metadata received; this does not verify live inference.'),hasMore,liveVerified:false};
 }
 selectModel(connectionId:string,value:unknown){ensure(this.#active.size===0,'Active Work pins its connections. Observe completion or cancellation before changing model configuration.');exact(value,['model','label','expectedConfigHash']);label(value.model);label(value.label);const c=this.#connections.get(connectionId);ensure(c&&c.configHash===value.expectedConfigHash,'Connection changed; refresh model selection');ensure(!this.#options.hostBindings||this.#options.hostBindings.connections.find(entry=>entry.input.id===connectionId)?.models.includes(value.model),'Model is not declared in the selected host manifest');const p=MODEL_PROVIDER_TYPES.find(p=>p.id===c.input.providerType)!;ensure(/^[a-zA-Z0-9._:/-]{1,256}$/.test(value.model),'Invalid exact model ID');if(p.id==='gemini')ensure(/^[a-zA-Z0-9._-]{1,128}$/.test(value.model),'Gemini requires exact model ID without models/ prefix');const modelId='profile:'+hash({connectionId,configHash:c.configHash,model:value.model}).slice(0,32);const endpoint=c.input.baseUrl+(p.id==='anthropic'?'messages':p.id==='gemini'?'models/'+value.model+':generateContent':'chat/completions');const profile:ModelConnectionProfile={id:modelId,label:value.label,backend:'model-provider',providerKind:p.id,protocol:p.protocol,model:value.model,endpoint,revision:c.configHash,enabled:true,auth:c.input.mode==='local-http-mock'?{method:'none'}:{method:p.auth,...(c.input.secretRef?{secretRef:c.input.secretRef}:{})},capabilities:['text-output'],usage:{inputTokens:'reported',outputTokens:'reported',cost:'unknown'},limits:{maxInputBytes:131072,maxOutputTokens:Math.min(c.models.find(m=>m.id===value.model)?.outputTokenLimit??4096,4096),maxResponseBytes:1048576,timeoutMs:60000}};ensure(this.#profiles.has(modelId)||this.#profiles.size<64,'Selected model limit reached');this.#profiles.set(modelId,{connectionId,profile});return {profileId:modelId,...this.list()};}
 authorize(value:unknown){ensure(this.#active.size===0,'Active Work pins its permissions. Observe completion or cancellation before changing authorization.');exact(value,['id','scope','executorProfileId','verifierProfileId','maxOutputTokensPerCall','expectedConfigHash']);id(value.id);ensure(typeof value.scope==='string'&&value.scope.trim().length>0&&value.scope.length<=16000,'Invalid Mission scope');ensure(positive(value.maxOutputTokensPerCall)&&value.expectedConfigHash===this.version(),'Configuration changed or invalid output cap');ensure(!this.#grants.some(g=>g.id===value.id),'Authorization identity already used');const catalog=this.catalog();const permissions=[];let mode:'mock-http'|'live'|undefined;for(const role of ['executor','verifier'] as const){const selected=catalog.resolve(value[role+'ProfileId'],['text-output']);ensure(selected.status==='selected','Connection unavailable; configure credentials and exact model first');const connection=this.#connections.get(this.#profiles.get(selected.profile.id)!.connectionId)!;const selectedMode=connection.input.mode==='local-http-mock'?'mock-http':'live';ensure(!mode||mode===selectedMode,'Mixed execution modes are not permitted');mode=selectedMode;ensure(selected.profile.limits.maxOutputTokens>=value.maxOutputTokensPerCall,'Profile output cap exceeded');permissions.push({profileId:selected.profile.id,configHash:selected.configHash});}ensure(mode==='mock-http'||this.#options.allowLiveExecution===true,'Live execution requires a separately authorized host integration');const grant:ExecutionAuthorization={id:value.id,scope:value.scope,mode:mode!,executor:[permissions[0]!],verifier:[permissions[1]!],maxOutputTokensPerCall:value.maxOutputTokensPerCall};ensure(this.#grants.length<64,'Authorization limit reached');this.#grants.push(grant);return this.list();}
}
