export const conversationWorkPanel=String.raw`<details id="conversation-work-panel" class="impact-panel"><summary>New Work from a saved owner message</summary><p class="hint">Select one original message, edit the requested task, then review and explicitly save a separate Work. Original discussion is provenance, not another instruction or retry permission. Editable task line breaks use LF; the original message stays exact in the comparison. Run remains a separate decision.</p><form id="conversation-work-form"><fieldset id="conversation-work-fields"><label for="conversation-work-source">Exact stored message</label><select id="conversation-work-source"><option value="">Choose original message</option></select><label for="conversation-work-title">New requested task · editable draft</label><textarea id="conversation-work-title" maxlength="16000" required></textarea><label for="conversation-work-budget">New Work budget · host units</label><input id="conversation-work-budget" type="number" min="0" step="any" value="0" required><pre id="conversation-work-original" tabindex="0" aria-label="Original message and reviewed Work inputs"></pre><p id="conversation-work-base" class="hint"></p><div class="row"><button id="conversation-work-review" type="button">Review original and new Work</button><button id="conversation-work-cancel" type="button" class="secondary">Cancel private Work draft</button><button id="conversation-work-save" type="submit" data-write>Save reviewed new Work</button></div></fieldset></form><p id="conversation-work-status" class="status" role="status" aria-live="polite">No Work saved or executed.</p></details>`;
export const conversationWorkClient=String.raw`
const conversationWorkDrafts=new Map(),conversationWorkSubmissions=new Map(),conversationWorkStatuses=new Map();
function conversationWorkDraft(){let d=conversationWorkDrafts.get(selectedId);if(!d){d={source:'',title:'',budget:'0',review:null,workId:null};conversationWorkDrafts.set(selectedId,d);}return d;}
function conversationWorkSource(d){for(const c of snapshot?.value.conversations||[])for(const m of c.messages)if(JSON.stringify([c.workId,m.id])===d?.source)return {workId:c.workId,conversationId:c.id,message:m};return null;}
function conversationWorkCurrent(d){const r=d?.review,s=conversationWorkSource(d);return !!(r&&s&&r.feed===feedId&&r.epoch===connectionEpoch&&r.revision===snapshot?.revision&&r.missionId===selectedId&&r.source===d.source&&r.title===d.title&&r.budget===d.budget&&r.original===sequenceCanonical(s));}
function conversationWorkControls(){const d=conversationWorkDrafts.get(selectedId),editable=revisionEditable();$('conversation-work-fields').disabled=!editable;$('conversation-work-save').disabled=!editable||!conversationWorkCurrent(d);$('conversation-work-review').disabled=!editable||!conversationWorkSource(d)||!d.title.trim()||!d.title.isWellFormed()||d.title.length>16000||!d.budget||!Number.isFinite(Number(d.budget))||Number(d.budget)<0;$('conversation-work-cancel').disabled=!editable;}
function renderConversationWork(){if(!snapshot||snapshot.value.id!==selectedId){conversationWorkControls();return;}for(const [key,s] of conversationWorkSubmissions){if(s.missionId!==selectedId||!confirmedOperations.has(key)||snapshot.revision<=s.body.expectedRevision)continue;const w=snapshot.value.works.find(w=>w.id===s.body.workId);if(!w||w.title!==s.body.title||w.conversationSource?.messageHash!==s.body.conversationSource.messageHash)continue;conversationWorkSubmissions.delete(key);if(conversationWorkDrafts.get(selectedId)===s.draft)conversationWorkDrafts.delete(selectedId);else if(conversationWorkDrafts.get(selectedId)?.workId===s.body.workId)conversationWorkDrafts.set(selectedId,{...conversationWorkDrafts.get(selectedId),workId:'work:'+crypto.randomUUID(),review:null});conversationWorkStatuses.set(selectedId,'Exact new Work confirmed. Original message retained. No execution started.');}
 const d=conversationWorkDraft(),target=$('conversation-work-source');target.replaceChildren();const placeholder=element('option','Choose original message');placeholder.value='';target.append(placeholder);for(const c of snapshot.value.conversations||[])for(const m of c.messages){const o=element('option',(c.workId===null?'Mission discussion':c.workId)+' · #'+m.ordinal+' · '+m.id);o.value=JSON.stringify([c.workId,m.id]);target.append(o);}if(d.source&&!Array.from(target.children).some(o=>o.value===d.source)){const o=element('option','Original selection unavailable');o.value=d.source;target.append(o);}target.value=d.source;$('conversation-work-title').value=d.title;$('conversation-work-budget').value=d.budget;const source=conversationWorkSource(d);$('conversation-work-original').textContent=source?JSON.stringify({original:source,reviewedInputs:d.review?.inputs||null},null,2):'Choose an exact stored original.';$('conversation-work-base').textContent='Current revision '+snapshot.revision+' · '+(conversationWorkCurrent(d)?'Exact draft reviewed.': 'Review required; retained drafts are never automatically rebased.');$('conversation-work-status').textContent=conversationWorkStatuses.get(selectedId)||'Private draft only. No Work saved or executed.';conversationWorkControls();}
$('conversation-work-source').addEventListener('change',()=>{if(!revisionEditable())return;const old=conversationWorkDraft(),d={...old,source:$('conversation-work-source').value,review:null};const s=conversationWorkSource(d);d.title=(s?.message.text||'').replace(/\r\n?/g,'\n');if(s&&!d.workId)d.workId='work:'+crypto.randomUUID();conversationWorkDrafts.set(selectedId,d);renderConversationWork();});
for(const id of ['conversation-work-title','conversation-work-budget'])$(id).addEventListener('input',()=>{const d=conversationWorkDraft();conversationWorkDrafts.set(selectedId,{...d,title:$('conversation-work-title').value,budget:$('conversation-work-budget').value,review:null});conversationWorkControls();});
$('conversation-work-review').addEventListener('click',async()=>{conversationWorkControls();if($('conversation-work-review').disabled)return;const missionId=selectedId,d=conversationWorkDraft(),s=conversationWorkSource(d),epoch=connectionEpoch,revision=snapshot.revision,feed=feedId,original=sequenceCanonical(s),messageHash=await sequenceHash(s.message);if(selectedId!==missionId||connectionEpoch!==epoch||snapshot?.revision!==revision||feedId!==feed||conversationWorkDrafts.get(missionId)!==d||!revisionEditable()||sequenceCanonical(conversationWorkSource(d))!==original)return;conversationWorkDrafts.set(missionId,{...d,review:{missionId,feed,epoch,revision,source:d.source,title:d.title,budget:d.budget,original,messageHash,inputs:correctionNewInput()}});renderConversationWork();});
$('conversation-work-cancel').addEventListener('click',()=>{if(!revisionEditable())return;conversationWorkDrafts.delete(selectedId);conversationWorkStatuses.set(selectedId,'Private Work draft cancelled. No write; original discussion retained.');renderConversationWork();});
$('conversation-work-form').addEventListener('submit',async event=>{event.preventDefault();if(!revisionEditable())return;const d=conversationWorkDraft();if(!conversationWorkCurrent(d))return;const missionId=selectedId,s=conversationWorkSource(d),body={commandId:crypto.randomUUID(),expectedRevision:d.review.revision,workId:d.workId,title:d.title,budget:Number(d.budget),conversationSource:{workId:s.workId,messageId:s.message.id,messageHash:d.review.messageHash}};if(!commandBodyFits(body))return;conversationWorkStatuses.set(missionId,'Saving exact new Work once; await original receipt.');await write('/missions/'+encodeURIComponent(missionId)+'/work',body,missionId,'New Work saved; no execution started.',null,null,null,null,null,null,null,null,null,null,null,null,{missionId,draft:d,body});if(selectedId===missionId)renderConversationWork();});
`;
