export const memorySearchPanel=String.raw`<details id="memory-search-panel" class="impact-panel"><summary>Find explicit memory by content fragment</summary><p class="hint">Search original content in this Mission, including inactive explicit versions. Matches are literal and case-sensitive, with no ranking. A result is an original reference, not permission to apply memory. Enter a quoted JSON string: escapes such as \r\n preserve original line endings. No trimming or normalization.</p><label for="memory-search-text">Literal content fragment (quoted JSON string; up to 512 units)</label><textarea id="memory-search-text" rows="3" placeholder='"remembered content"'></textarea><div class="row"><button id="memory-search-read" type="button">Search original content</button><button id="memory-search-more" type="button" class="secondary">Next 20 versions</button><button id="memory-search-cancel" type="button" class="secondary">Cancel content search</button></div><p id="memory-search-status" class="status" role="status" aria-live="polite">No version search.</p><div id="memory-search-results" class="impact-results" role="region" aria-label="Literal matching explicit memory versions" tabindex="0" hidden></div></details>`;
export const memorySearchClient=String.raw`
let memorySearchSequence=0,memorySearchReading=false,memorySearchPage=null,memorySearchBoundary=null;
function memorySearchText(){try{const text=JSON.parse($('memory-search-text').value);return typeof text==='string'&&text.trim()&&text.length<=512&&text.isWellFormed()?text:null;}catch{return null;}}
function memorySearchClear(message){++memorySearchSequence;memorySearchReading=false;memorySearchPage=null;$('memory-search-results').replaceChildren();$('memory-search-results').hidden=true;$('memory-search-status').textContent=message;}
function memorySearchControls(){if(reconnectRequired&&(memorySearchPage||memorySearchReading))memorySearchClear('Connection changed; explicitly search against refreshed state.');const ready=!!snapshot&&snapshot.value.id===selectedId&&!loading&&!reconnectRequired;$('memory-search-text').disabled=!ready;$('memory-search-read').disabled=!ready||memorySearchText()===null||memorySearchReading;$('memory-search-more').disabled=!ready||memorySearchReading||!memorySearchPage||memorySearchPage.nextAfter===null;$('memory-search-cancel').disabled=!ready;}
function renderMemorySearch(){const boundary=JSON.stringify([selectedId,feedId,connectionEpoch,snapshot?.revision]);if(boundary!==memorySearchBoundary){const old=memorySearchBoundary?JSON.parse(memorySearchBoundary):null;memorySearchBoundary=boundary;if(old&&(old[0]!==selectedId||old[1]!==feedId))$('memory-search-text').value='';memorySearchClear('State changed; explicitly search original versions.');}memorySearchControls();}
$('memory-search-text').addEventListener('input',()=>{memorySearchClear('Fragment changed; explicitly search original content.');memorySearchControls();});
$('memory-usage-target').addEventListener('change',()=>{memorySearchClear('Usage selection changed; version search closed.');memorySearchControls();});
$('memory-search-cancel').addEventListener('click',()=>{memorySearchClear('Version search canceled. No write or usage read.');$('memory-search-text').value='';memorySearchControls();});
async function readMemorySearch(next=false){
 memorySearchControls();if($(next?'memory-search-more':'memory-search-read').disabled)return;const text=memorySearchText(),prior=memorySearchPage,offset=next?prior.nextAfter:0,sequence=++memorySearchSequence,missionId=selectedId,feed=feedId,epoch=connectionEpoch,revision=snapshot.revision,input=$('memory-search-text').value,focus=document.activeElement,current=()=>sequence===memorySearchSequence&&selectedId===missionId&&feedId===feed&&connectionEpoch===epoch&&snapshot?.revision===revision&&$('memory-search-text').value===input&&!reconnectRequired;
 if(!next){memorySearchPage=null;$('memory-search-results').replaceChildren();$('memory-search-results').hidden=true;}memorySearchReading=true;memorySearchControls();$('memory-search-status').textContent='Searching original content; no writes.';
 try{
  if(next&&(prior.text!==text||prior.missionId!==missionId||prior.feedId!==feed||prior.revision!==revision))throw Error('Original version search boundary changed');const {response,body:r}=await request('/missions/'+encodeURIComponent(missionId)+'/memory-search?text='+encodeURIComponent(text)+'&revision='+revision+(next?'&after='+offset:''),{headers:{'X-Massion-Feed':feed}});if(!current())return;if(!response.ok)throw Error(r.error||'Exact version search failed');
  const matches=snapshot.value.memories.filter(m=>m.content.includes(text)&&m.authority==='explicit'&&m.scope===snapshot.value.scope),expected=await Promise.all(matches.slice(offset,offset+20).map(async memory=>{const {effective,...original}=memory;return {memory,versionHash:await sequenceHash(original)};})),expectedNext=offset+expected.length<matches.length?offset+expected.length:null;
  if(r.missionId!==missionId||r.text!==text||r.feedId!==feed||r.revision!==revision||r.offset!==offset||r.limit!==20||r.totalVersions!==matches.length||r.nextAfter!==expectedNext||!Number.isSafeInteger(r.cursor)||r.cursor<0||!Array.isArray(r.versions)||await sequenceHash(r.versions)!==await sequenceHash(expected))throw Error('Original version search failed exact binding');if(!current())return;
  memorySearchPage=r;const area=$('memory-search-results');area.replaceChildren();for(const entry of r.versions){const m=entry.memory,button=element('button','Choose '+JSON.stringify(m.id)+' @ '+m.version+' for usage inspection');button.type='button';button.addEventListener('click',()=>{if(!current()||memorySearchReading)return;memoryUsageSelection=JSON.stringify([m.id,m.version]);$('memory-usage-target').value=memoryUsageSelection;memoryUsageReset('Exact original version chosen from content search; explicitly read uses. No read or write sent.');memoryFindClear('Content search selected a version; ID search closed.');memoryFindControls();memorySearchClear('Original version chosen for separate usage inspection.');memorySearchControls();$('memory-usage-panel').open=true;restoreControlFocus(document.activeElement,'memory-usage-read');});area.append(element('h4',JSON.stringify(m.id)+' · version '+m.version),element('p',m.effective?'Effective for new Work':'Historical or inactive'),element('p','Original version hash: '+entry.versionHash,'hint'),element('pre',m.content),element('p','Original source: '+m.source,'hint'),button);}if(!r.versions.length)area.append(element('p','No literal matching explicit versions in this Mission.'));area.hidden=false;$('memory-search-status').textContent=r.totalVersions+' literal matching explicit versions; showing '+r.versions.length+' (positions '+(r.versions.length?offset+1:0)+'–'+(offset+r.versions.length)+'). No usage read or write.';
 }catch(error){if(current())memorySearchClear(error.message+' · Explicit initial search required.');}finally{if(current()){memorySearchReading=false;memorySearchControls();if(document.activeElement===focus)restoreControlFocus(focus,focus?.id);}else memorySearchControls();}
}
$('memory-search-read').addEventListener('click',()=>readMemorySearch());$('memory-search-more').addEventListener('click',()=>readMemorySearch(true));
`;
