export const memoryExpiryPanel=String.raw`<details id="memory-expiry-panel" class="impact-panel"><summary>Declare an explicit memory expiry</summary><p class="hint">Review one exact effective explicit version and a future UTC deadline. At or after the deadline the host clock blocks new Work while this version applies. Existing Work pins, execution and Records remain unchanged. Existing retirement can stop this version applying; nothing happens automatically. Host time is local clock evidence.</p><form id="memory-expiry-form"><fieldset id="memory-expiry-fields"><label for="memory-expiry-first">Exact explicit memory</label><select id="memory-expiry-first"></select><label for="memory-expiry-deadline">Future UTC deadline (YYYY-MM-DDTHH:mm:ss.sssZ)</label><input id="memory-expiry-deadline" placeholder="2026-10-09T00:00:00.000Z" maxlength="24"><label for="memory-expiry-reason">Owner reason for expiry</label><textarea id="memory-expiry-reason" rows="2" maxlength="2000"></textarea><div class="row"><button id="memory-expiry-review" type="button" class="secondary">Review exact version and deadline</button><button id="memory-expiry-save" type="submit" data-write>Declare reviewed expiry</button><button id="memory-expiry-cancel" type="button" class="quiet">Cancel private expiry draft</button></div></fieldset></form><p id="memory-expiry-base" class="hint"></p><pre id="memory-expiry-current" tabindex="0" aria-label="Current original memory version"></pre><pre id="memory-expiry-original" tabindex="0" aria-label="Original version retained with review"></pre><pre id="memory-expiry-preview" tabindex="0" aria-label="Exact reviewed expiry declaration" hidden></pre><p id="memory-expiry-status" role="status" aria-live="polite">No expiry declared.</p><pre id="memory-expiry-history" tabindex="0" aria-label="Immutable expiry history"></pre></details>`;
export const memoryExpiryClient=String.raw`
const memoryExpiryDrafts=new Map(),memoryExpirySubmissions=new Map(),memoryExpiryStatuses=new Map();let memoryExpiryMission='',memoryExpiryFocus=null;
function memoryExpiryValues(){return [$('memory-expiry-first').value,$('memory-expiry-deadline').value,$('memory-expiry-reason').value];}
function memoryExpiryEditable(){return snapshot?.value.id===selectedId&&!!feedId&&!reconnectRequired&&!loading&&!busy&&!unknownOperation&&!recoveryProblem&&!fixtureUnknown;}
function newMemoryExpiryDraft(){return {missionId:selectedId,feed:feedId,baseRevision:snapshot.revision,values:['','',''],originals:null,review:null};}
function memoryExpirySelected(value){return snapshot?.value.memories.find(m=>JSON.stringify([m.id,m.version])===value)||null;}
function memoryExpiryEligible(m){return m&&m.effective===true&&m.authority==='explicit'&&m.scope===snapshot?.value.scope;}
function memoryExpiryVersion(m){const {effective,...original}=m;return original;}
function memoryExpiryReviewCurrent(d){const first=memoryExpirySelected(d?.values[0]);return !!d?.review&&d.missionId===selectedId&&d.feed===feedId&&d.baseRevision===snapshot?.revision&&d.review.epoch===connectionEpoch&&JSON.stringify(d.values)===JSON.stringify(memoryExpiryValues())&&memoryExpiryEligible(first)&&JSON.stringify(d.originals)===JSON.stringify([first]);}
function memoryExpiryControls(){const fields=$('memory-expiry-fields'),ready=memoryExpiryEditable(),active=document.activeElement;if(!fields.disabled&&fields.contains(active))memoryExpiryFocus={missionId:selectedId,previous:active,targetId:active.id};fields.disabled=!ready;$('memory-expiry-save').disabled=!ready||!memoryExpiryReviewCurrent(memoryExpiryDrafts.get(selectedId));if(ready&&memoryExpiryFocus){const f=memoryExpiryFocus;memoryExpiryFocus=null;if(f.missionId===selectedId)restoreControlFocus(f.previous,f.targetId);}}
function confirmMemoryExpirySubmission(key){const s=memoryExpirySubmissions.get(key);if(!s||snapshot?.value.id!==s.missionId||selectedId!==s.missionId||snapshot.revision<=s.expectedRevision||!confirmedOperations.has(key))return;memoryExpirySubmissions.delete(key);const d=memoryExpiryDrafts.get(s.missionId);if(d===s.draft&&JSON.stringify(d.values)===JSON.stringify(s.values))memoryExpiryDrafts.delete(s.missionId);memoryExpiryStatuses.set(s.missionId,'Exact owner expiry declaration confirmed. Existing Work inputs and execution remain unchanged.');}
function renderMemoryExpiries(){
 if(snapshot?.value.id!==selectedId){memoryExpiryControls();return;}if(memoryExpiryMission!==selectedId){const old=memoryExpiryDrafts.get(memoryExpiryMission);if(old)old.values=memoryExpiryValues();memoryExpiryMission=selectedId;}
 for(const key of memoryExpirySubmissions.keys())confirmMemoryExpirySubmission(key);let d=memoryExpiryDrafts.get(selectedId);if(!d){d=newMemoryExpiryDraft();memoryExpiryDrafts.set(selectedId,d);}
 for(const [i,id] of [[0,'memory-expiry-first']]){const select=$(id);select.replaceChildren();const p=element('option','Choose exact effective explicit version');p.value='';select.append(p);for(const m of snapshot.value.memories.filter(memoryExpiryEligible)){const o=element('option',JSON.stringify(m.id)+' · v'+m.version);o.value=JSON.stringify([m.id,m.version]);select.append(o);}if(d.values[i]&&!Array.from(select.children).some(o=>o.value===d.values[i])){const o=element('option','Original selection no longer effective or available · '+d.values[i]);o.value=d.values[i];select.append(o);}select.value=d.values[i];}$('memory-expiry-deadline').value=d.values[1];$('memory-expiry-reason').value=d.values[2];if(d.review&&!memoryExpiryReviewCurrent(d))d.review=null;
 const current=[memoryExpirySelected(d.values[0])];$('memory-expiry-current').textContent='Current exact originals\n'+JSON.stringify(current,null,2);$('memory-expiry-original').textContent='Original versions retained with private review\n'+JSON.stringify(d.originals,null,2);$('memory-expiry-base').textContent='Mission '+selectedId+' · current revision '+snapshot.revision+' · draft base '+d.baseRevision+(d.feed!==feedId||d.baseRevision!==snapshot.revision?' · State/feed changed; explicit Review required.':'');$('memory-expiry-preview').hidden=!d.review;if(d.review)$('memory-expiry-preview').textContent=JSON.stringify({memory:d.review.memory,deadline:d.review.deadline,reason:d.review.reason,revision:d.baseRevision},null,2);$('memory-expiry-status').textContent=memoryExpiryStatuses.get(selectedId)||'No expiry declared.';
 const history=(snapshot.value.memoryExpiries||[]).map(e=>({...e,exactVersionCurrentlyEffective:snapshot.value.memories.some(m=>m.id===e.memory.id&&m.version===e.memory.version&&m.effective===true)}));$('memory-expiry-history').textContent='Retained deadlines; host clock is checked on explicit new Work admission\n'+JSON.stringify(history,null,2);memoryExpiryControls();
}
for(const id of ['memory-expiry-first','memory-expiry-deadline','memory-expiry-reason'])for(const event of ['input','change'])$(id).addEventListener(event,()=>{const d=memoryExpiryDrafts.get(memoryExpiryMission);if(!d)return;memoryExpiryDrafts.set(memoryExpiryMission,{...d,values:memoryExpiryValues(),review:null});memoryExpiryStatuses.set(memoryExpiryMission,'Private draft changed. Explicitly Review before declaring.');renderMemoryExpiries();});
$('memory-expiry-review').addEventListener('click',async()=>{
 if(!memoryExpiryEditable())return;const d=memoryExpiryDrafts.get(selectedId),values=memoryExpiryValues(),first=memoryExpirySelected(values[0]),missionId=selectedId,revision=snapshot.revision,feed=feedId,epoch=connectionEpoch;
 try{const deadline=Date.parse(values[1]);if(!memoryExpiryEligible(first)||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(values[1])||!Number.isSafeInteger(deadline)||new Date(deadline).toISOString()!==values[1]||deadline<=Date.now()||!values[2].trim()||!values[2].isWellFormed()||values[2].length>2000)throw new Error('Choose an effective explicit memory, future canonical UTC deadline and bounded reason.');const originals=structuredClone([first]),refs=await Promise.all(originals.map(async m=>({id:m.id,version:m.version,hash:await sequenceHash(memoryExpiryVersion(m))})));if(!memoryExpiryEditable()||selectedId!==missionId||snapshot.revision!==revision||feedId!==feed||connectionEpoch!==epoch||memoryExpiryDrafts.get(missionId)!==d||JSON.stringify(memoryExpiryValues())!==JSON.stringify(values))return;if((snapshot.value.memoryExpiries||[]).some(e=>e.memory.id===refs[0].id&&e.memory.version===refs[0].version&&e.memory.hash===refs[0].hash))throw new Error('This exact version already has an immutable deadline.');if((snapshot.value.memoryExpiries||[]).length>=100)throw new Error('Expiry history bound reached.');const draft={...newMemoryExpiryDraft(),values:[...values],originals,review:{memory:refs[0],deadline:values[1],reason:values[2],epoch}};memoryExpiryDrafts.set(missionId,draft);memoryExpiryStatuses.set(missionId,'Exact original, UTC deadline and reason reviewed. Declare records the expiry; no Work or Run starts.');renderMemoryExpiries();}catch(error){if(selectedId!==missionId||memoryExpiryDrafts.get(missionId)!==d)return;d.review=null;memoryExpiryStatuses.set(missionId,error.message+' No command was sent.');renderMemoryExpiries();}
});
$('memory-expiry-cancel').addEventListener('click',()=>{if(!memoryExpiryEditable())return;memoryExpiryDrafts.delete(selectedId);memoryExpiryStatuses.set(selectedId,'Private expiry draft cancelled. No command was sent; history retained.');renderMemoryExpiries();});
$('memory-expiry-form').addEventListener('submit',async event=>{event.preventDefault();if(!memoryExpiryEditable())return;const d=memoryExpiryDrafts.get(selectedId);if(!memoryExpiryReviewCurrent(d)){memoryExpiryStatuses.set(selectedId,'State or draft changed. Explicitly Review again; no command sent.');renderMemoryExpiries();return;}const missionId=selectedId,values=memoryExpiryValues(),body={commandId:crypto.randomUUID(),expectedRevision:d.baseRevision,expiryId:'expiry:'+crypto.randomUUID(),memory:structuredClone(d.review.memory),deadline:d.review.deadline,reason:d.review.reason};if(!commandBodyFits(body)){memoryExpiryStatuses.set(missionId,'Serialized request exceeds the UTF-8 bound. No command was sent.');renderMemoryExpiries();return;}const focus=document.activeElement;memoryExpiryStatuses.set(missionId,'Declaring this exact expiry once; awaiting durable receipt…');renderMemoryExpiries();const saved=await write('/missions/'+encodeURIComponent(missionId)+'/memory-expiry',body,missionId,'Owner memory expiry saved. Existing Work remains unchanged.',...Array(16).fill(null),{missionId,draft:d,values:[...values],expectedRevision:body.expectedRevision});if(selectedId===missionId&&snapshot?.value.id===missionId){if(!saved&&!confirmedOperations.has(operationKey({missionId,commandId:body.commandId})))memoryExpiryStatuses.set(missionId,'Declaration not confirmed here. Exact draft retained; inspect receipt without replay.');renderMemoryExpiries();if($('memory-expiry-form').contains(focus)){memoryExpiryFocus={missionId,previous:focus,targetId:focus.id};memoryExpiryControls();}}});
`;
