export const memoryConflictPanel=String.raw`<details id="memory-conflict-panel" class="impact-panel"><summary>Declare an explicit memory conflict</summary><p class="hint">Choose two exact currently effective explicit versions and review their originals. An owner declaration blocks newly created Work while both versions apply. Existing Work execution, pins and Records remain unchanged. Use the existing retirement controls to stop one version applying; no automatic resolution or Run follows.</p><form id="memory-conflict-form"><fieldset id="memory-conflict-fields"><label for="memory-conflict-first">First exact explicit memory</label><select id="memory-conflict-first"></select><label for="memory-conflict-second">Second exact explicit memory</label><select id="memory-conflict-second"></select><label for="memory-conflict-reason">Owner reason for the conflict</label><textarea id="memory-conflict-reason" rows="2" maxlength="2000"></textarea><div class="row"><button id="memory-conflict-review" type="button" class="secondary">Review exact versions</button><button id="memory-conflict-save" type="submit" data-write>Declare reviewed conflict</button><button id="memory-conflict-cancel" type="button" class="quiet">Cancel private conflict draft</button></div></fieldset></form><p id="memory-conflict-base" class="hint"></p><pre id="memory-conflict-current" tabindex="0" aria-label="Current original memory versions"></pre><pre id="memory-conflict-original" tabindex="0" aria-label="Original versions retained with review"></pre><pre id="memory-conflict-preview" tabindex="0" aria-label="Exact reviewed conflict declaration" hidden></pre><p id="memory-conflict-status" role="status" aria-live="polite">No conflict declared.</p><pre id="memory-conflict-history" tabindex="0" aria-label="Immutable conflict history and current applicability"></pre></details>`;
export const memoryConflictClient=String.raw`
const memoryConflictDrafts=new Map(),memoryConflictSubmissions=new Map(),memoryConflictStatuses=new Map();let memoryConflictMission='',memoryConflictFocus=null;
function memoryConflictValues(){return [$('memory-conflict-first').value,$('memory-conflict-second').value,$('memory-conflict-reason').value];}
function memoryConflictEditable(){return snapshot?.value.id===selectedId&&!!feedId&&!reconnectRequired&&!loading&&!busy&&!unknownOperation&&!recoveryProblem&&!fixtureUnknown;}
function newMemoryConflictDraft(){return {missionId:selectedId,feed:feedId,baseRevision:snapshot.revision,values:['','',''],originals:null,review:null};}
function memoryConflictSelected(value){return snapshot?.value.memories.find(m=>JSON.stringify([m.id,m.version])===value)||null;}
function memoryConflictEligible(m){return m&&m.effective===true&&m.authority==='explicit'&&m.scope===snapshot?.value.scope;}
function memoryConflictVersion(m){const {effective,...original}=m;return original;}
function memoryConflictPair(first,second){return JSON.stringify([JSON.stringify([first.id,first.version,first.hash]),JSON.stringify([second.id,second.version,second.hash])].sort());}
function memoryConflictReviewCurrent(d){const first=memoryConflictSelected(d?.values[0]),second=memoryConflictSelected(d?.values[1]);return !!d?.review&&d.missionId===selectedId&&d.feed===feedId&&d.baseRevision===snapshot?.revision&&d.review.epoch===connectionEpoch&&JSON.stringify(d.values)===JSON.stringify(memoryConflictValues())&&memoryConflictEligible(first)&&memoryConflictEligible(second)&&JSON.stringify(d.originals)===JSON.stringify([first,second]);}
function memoryConflictControls(){const fields=$('memory-conflict-fields'),ready=memoryConflictEditable(),active=document.activeElement;if(!fields.disabled&&fields.contains(active))memoryConflictFocus={missionId:selectedId,previous:active,targetId:active.id};fields.disabled=!ready;$('memory-conflict-save').disabled=!ready||!memoryConflictReviewCurrent(memoryConflictDrafts.get(selectedId));if(ready&&memoryConflictFocus){const f=memoryConflictFocus;memoryConflictFocus=null;if(f.missionId===selectedId)restoreControlFocus(f.previous,f.targetId);}}
function confirmMemoryConflictSubmission(key){const s=memoryConflictSubmissions.get(key);if(!s||snapshot?.value.id!==s.missionId||selectedId!==s.missionId||snapshot.revision<=s.expectedRevision||!confirmedOperations.has(key))return;memoryConflictSubmissions.delete(key);const d=memoryConflictDrafts.get(s.missionId);if(d===s.draft&&JSON.stringify(d.values)===JSON.stringify(s.values))memoryConflictDrafts.delete(s.missionId);memoryConflictStatuses.set(s.missionId,'Exact owner conflict declaration confirmed. Existing Work inputs and execution remain unchanged.');}
function renderMemoryConflicts(){
 if(snapshot?.value.id!==selectedId){memoryConflictControls();return;}if(memoryConflictMission!==selectedId){const old=memoryConflictDrafts.get(memoryConflictMission);if(old)old.values=memoryConflictValues();memoryConflictMission=selectedId;}
 for(const key of memoryConflictSubmissions.keys())confirmMemoryConflictSubmission(key);let d=memoryConflictDrafts.get(selectedId);if(!d){d=newMemoryConflictDraft();memoryConflictDrafts.set(selectedId,d);}
 for(const [i,id] of [[0,'memory-conflict-first'],[1,'memory-conflict-second']]){const select=$(id);select.replaceChildren();const p=element('option','Choose exact effective explicit version');p.value='';select.append(p);for(const m of snapshot.value.memories.filter(memoryConflictEligible)){const o=element('option',JSON.stringify(m.id)+' · v'+m.version);o.value=JSON.stringify([m.id,m.version]);select.append(o);}if(d.values[i]&&!Array.from(select.children).some(o=>o.value===d.values[i])){const o=element('option','Original selection no longer effective or available · '+d.values[i]);o.value=d.values[i];select.append(o);}select.value=d.values[i];}$('memory-conflict-reason').value=d.values[2];if(d.review&&!memoryConflictReviewCurrent(d))d.review=null;
 const current=[memoryConflictSelected(d.values[0]),memoryConflictSelected(d.values[1])];$('memory-conflict-current').textContent='Current exact originals\n'+JSON.stringify(current,null,2);$('memory-conflict-original').textContent='Original versions retained with private review\n'+JSON.stringify(d.originals,null,2);$('memory-conflict-base').textContent='Mission '+selectedId+' · current revision '+snapshot.revision+' · draft base '+d.baseRevision+(d.feed!==feedId||d.baseRevision!==snapshot.revision?' · State/feed changed; explicit Review required.':'');$('memory-conflict-preview').hidden=!d.review;if(d.review)$('memory-conflict-preview').textContent=JSON.stringify({first:d.review.first,second:d.review.second,reason:d.review.reason,revision:d.baseRevision},null,2);$('memory-conflict-status').textContent=memoryConflictStatuses.get(selectedId)||'No conflict declared.';
 const history=(snapshot.value.memoryConflicts||[]).map(c=>({...c,bothExactVersionsCurrentlyApply:[c.first,c.second].every(ref=>snapshot.value.memories.some(m=>m.id===ref.id&&m.version===ref.version&&m.effective===true))}));$('memory-conflict-history').textContent='Retained owner declarations (applicability is not semantic resolution)\n'+JSON.stringify(history,null,2);memoryConflictControls();
}
for(const id of ['memory-conflict-first','memory-conflict-second','memory-conflict-reason'])for(const event of ['input','change'])$(id).addEventListener(event,()=>{const d=memoryConflictDrafts.get(memoryConflictMission);if(!d)return;memoryConflictDrafts.set(memoryConflictMission,{...d,values:memoryConflictValues(),review:null});memoryConflictStatuses.set(memoryConflictMission,'Private draft changed. Explicitly Review before declaring.');renderMemoryConflicts();});
$('memory-conflict-review').addEventListener('click',async()=>{
 if(!memoryConflictEditable())return;const d=memoryConflictDrafts.get(selectedId),values=memoryConflictValues(),first=memoryConflictSelected(values[0]),second=memoryConflictSelected(values[1]),missionId=selectedId,revision=snapshot.revision,feed=feedId,epoch=connectionEpoch;
 try{if(!memoryConflictEligible(first)||!memoryConflictEligible(second)||first.id===second.id||!values[2].trim()||!values[2].isWellFormed()||values[2].length>2000)throw new Error('Choose two different currently effective explicit memories and a bounded nonblank reason.');const originals=structuredClone([first,second]),refs=await Promise.all(originals.map(async m=>({id:m.id,version:m.version,hash:await sequenceHash(memoryConflictVersion(m))})));if(!memoryConflictEditable()||selectedId!==missionId||snapshot.revision!==revision||feedId!==feed||connectionEpoch!==epoch||memoryConflictDrafts.get(missionId)!==d||JSON.stringify(memoryConflictValues())!==JSON.stringify(values))return;if((snapshot.value.memoryConflicts||[]).some(c=>memoryConflictPair(c.first,c.second)===memoryConflictPair(refs[0],refs[1])))throw new Error('This exact unordered version pair was already declared.');if((snapshot.value.memoryConflicts||[]).length>=100)throw new Error('Memory conflict history bound reached.');const draft={...newMemoryConflictDraft(),values:[...values],originals,review:{first:refs[0],second:refs[1],reason:values[2],epoch}};memoryConflictDrafts.set(missionId,draft);memoryConflictStatuses.set(missionId,'Exact original versions and owner reason reviewed. Declare records the conflict; no Work or Run starts.');renderMemoryConflicts();}catch(error){if(selectedId!==missionId||memoryConflictDrafts.get(missionId)!==d)return;d.review=null;memoryConflictStatuses.set(missionId,error.message+' No command was sent.');renderMemoryConflicts();}
});
$('memory-conflict-cancel').addEventListener('click',()=>{if(!memoryConflictEditable())return;memoryConflictDrafts.delete(selectedId);memoryConflictStatuses.set(selectedId,'Private conflict draft cancelled. No command was sent; history retained.');renderMemoryConflicts();});
$('memory-conflict-form').addEventListener('submit',async event=>{event.preventDefault();if(!memoryConflictEditable())return;const d=memoryConflictDrafts.get(selectedId);if(!memoryConflictReviewCurrent(d)){memoryConflictStatuses.set(selectedId,'State or draft changed. Explicitly Review again; no command sent.');renderMemoryConflicts();return;}const missionId=selectedId,values=memoryConflictValues(),body={commandId:crypto.randomUUID(),expectedRevision:d.baseRevision,conflictId:'conflict:'+crypto.randomUUID(),first:structuredClone(d.review.first),second:structuredClone(d.review.second),reason:d.review.reason};if(!commandBodyFits(body)){memoryConflictStatuses.set(missionId,'Serialized request exceeds the UTF-8 bound. No command was sent.');renderMemoryConflicts();return;}const focus=document.activeElement;memoryConflictStatuses.set(missionId,'Declaring this exact conflict once; awaiting durable receipt…');renderMemoryConflicts();const saved=await write('/missions/'+encodeURIComponent(missionId)+'/memory-conflict',body,missionId,'Owner memory conflict saved. Existing Work remains unchanged.',...Array(15).fill(null),{missionId,draft:d,values:[...values],expectedRevision:body.expectedRevision});if(selectedId===missionId&&snapshot?.value.id===missionId){if(!saved&&!confirmedOperations.has(operationKey({missionId,commandId:body.commandId})))memoryConflictStatuses.set(missionId,'Declaration not confirmed here. Exact draft retained; inspect receipt without replay.');renderMemoryConflicts();if($('memory-conflict-form').contains(focus)){memoryConflictFocus={missionId,previous:focus,targetId:focus.id};memoryConflictControls();}}});
`;
