export const memoryFindPanel=String.raw`<details id="memory-find-panel" class="impact-panel"><summary>Find explicit memory versions by original ID</summary><p class="hint">Find an exact ID in this Mission, including inactive explicit versions. A result is an original reference, not permission to apply memory. Enter a quoted JSON string: escapes such as \r\n preserve original line endings. No trimming or normalization.</p><label for="memory-find-id">Exact original ID (quoted JSON string)</label><textarea id="memory-find-id" rows="3" placeholder='"original ID"'></textarea><div class="row"><button id="memory-find-read" type="button">Find exact versions</button><button id="memory-find-more" type="button" class="secondary">Next 20 versions</button><button id="memory-find-cancel" type="button" class="secondary">Cancel version search</button></div><p id="memory-find-status" class="status" role="status" aria-live="polite">No version search.</p><div id="memory-find-results" class="impact-results" role="region" aria-label="Exact explicit memory versions" tabindex="0" hidden></div></details>`;
export const memoryFindClient=String.raw`
let memoryFindSequence=0,memoryFindReading=false,memoryFindPage=null,memoryFindBoundary=null;
function memoryFindID(){try{const id=JSON.parse($('memory-find-id').value);return typeof id==='string'&&id.trim()&&id.length<=16000&&id.isWellFormed()?id:null;}catch{return null;}}
function memoryFindClear(message){++memoryFindSequence;memoryFindReading=false;memoryFindPage=null;$('memory-find-results').replaceChildren();$('memory-find-results').hidden=true;$('memory-find-status').textContent=message;}
function memoryFindControls(){if(reconnectRequired&&(memoryFindPage||memoryFindReading))memoryFindClear('Connection changed; explicitly find against refreshed state.');const ready=!!snapshot&&snapshot.value.id===selectedId&&!loading&&!reconnectRequired;$('memory-find-id').disabled=!ready;$('memory-find-read').disabled=!ready||memoryFindID()===null||memoryFindReading;$('memory-find-more').disabled=!ready||memoryFindReading||!memoryFindPage||memoryFindPage.nextAfter===null;$('memory-find-cancel').disabled=!ready;}
function renderMemoryFind(){const boundary=JSON.stringify([selectedId,feedId,connectionEpoch,snapshot?.revision]);if(boundary!==memoryFindBoundary){const old=memoryFindBoundary?JSON.parse(memoryFindBoundary):null;memoryFindBoundary=boundary;if(old&&(old[0]!==selectedId||old[1]!==feedId))$('memory-find-id').value='';memoryFindClear('State changed; explicitly find original versions.');}memoryFindControls();}
$('memory-find-id').addEventListener('input',()=>{memoryFindClear('ID changed; explicitly find exact versions.');memoryFindControls();});
$('memory-usage-target').addEventListener('change',()=>{memoryFindClear('Usage selection changed; version search closed.');memoryFindControls();});
$('memory-find-cancel').addEventListener('click',()=>{memoryFindClear('Version search canceled. No write or usage read.');$('memory-find-id').value='';memoryFindControls();});
async function readMemoryFind(next=false){
 memoryFindControls();if($(next?'memory-find-more':'memory-find-read').disabled)return;const id=memoryFindID(),prior=memoryFindPage,offset=next?prior.nextAfter:0,sequence=++memoryFindSequence,missionId=selectedId,feed=feedId,epoch=connectionEpoch,revision=snapshot.revision,input=$('memory-find-id').value,focus=document.activeElement,current=()=>sequence===memoryFindSequence&&selectedId===missionId&&feedId===feed&&connectionEpoch===epoch&&snapshot?.revision===revision&&$('memory-find-id').value===input&&!reconnectRequired;
 if(!next){memoryFindPage=null;$('memory-find-results').replaceChildren();$('memory-find-results').hidden=true;}memoryFindReading=true;memoryFindControls();$('memory-find-status').textContent='Finding original versions; no writes.';
 try{
  if(next&&(prior.id!==id||prior.missionId!==missionId||prior.feedId!==feed||prior.revision!==revision))throw Error('Original version search boundary changed');const {response,body:r}=await request('/missions/'+encodeURIComponent(missionId)+'/memory-versions?id='+encodeURIComponent(id)+'&revision='+revision+(next?'&after='+offset:''),{headers:{'X-Massion-Feed':feed}});if(!current())return;if(!response.ok)throw Error(r.error||'Exact version search failed');
  const matches=snapshot.value.memories.filter(m=>m.id===id&&m.authority==='explicit'&&m.scope===snapshot.value.scope),expected=await Promise.all(matches.slice(offset,offset+20).map(async memory=>{const {effective,...original}=memory;return {memory,versionHash:await sequenceHash(original)};})),expectedNext=offset+expected.length<matches.length?offset+expected.length:null;
  if(r.missionId!==missionId||r.id!==id||r.feedId!==feed||r.revision!==revision||r.offset!==offset||r.limit!==20||r.totalVersions!==matches.length||r.nextAfter!==expectedNext||!Number.isSafeInteger(r.cursor)||r.cursor<0||!Array.isArray(r.versions)||await sequenceHash(r.versions)!==await sequenceHash(expected))throw Error('Original version search failed exact binding');if(!current())return;
  memoryFindPage=r;const area=$('memory-find-results');area.replaceChildren();for(const entry of r.versions){const m=entry.memory,button=element('button','Choose version '+m.version+' for usage inspection');button.type='button';button.addEventListener('click',()=>{if(!current()||memoryFindReading)return;memoryUsageSelection=JSON.stringify([m.id,m.version]);$('memory-usage-target').value=memoryUsageSelection;memoryUsageReset('Exact original version chosen from search; explicitly read uses. No read or write sent.');memoryFindClear('Original version chosen for separate usage inspection.');memoryFindControls();$('memory-usage-panel').open=true;restoreControlFocus(document.activeElement,'memory-usage-read');});area.append(element('h4',JSON.stringify(m.id)+' · version '+m.version),element('p',m.effective?'Effective for new Work':'Historical or inactive'),element('p','Original version hash: '+entry.versionHash,'hint'),element('pre',m.content),element('p','Original source: '+m.source,'hint'),button);}if(!r.versions.length)area.append(element('p','No exact explicit versions in this Mission.'));area.hidden=false;$('memory-find-status').textContent=r.totalVersions+' exact explicit versions; showing '+r.versions.length+' (positions '+(r.versions.length?offset+1:0)+'–'+(offset+r.versions.length)+'). No usage read or write.';
 }catch(error){if(current())memoryFindClear(error.message+' · Explicit initial search required.');}finally{if(current()){memoryFindReading=false;memoryFindControls();if(document.activeElement===focus)restoreControlFocus(focus,focus?.id);}else memoryFindControls();}
}
$('memory-find-read').addEventListener('click',()=>readMemoryFind());$('memory-find-more').addEventListener('click',()=>readMemoryFind(true));
`;
