import {DomainError} from './domain.ts';
import type {Mission} from './domain.ts';
import {conflictMemory} from './memory-conflicts.ts';
import type {MemoryConflictReference} from './memory-conflicts.ts';
export interface MemoryExpiry {id:string;memory:MemoryConflictReference;deadline:string;actorId:string;reason:string;declaredAt:number}
export interface TimeObservation {observedAt:number}
const exact=(v:unknown,fields:string[])=>!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===fields.length&&Object.keys(v).every(k=>fields.includes(k));
function ensure(v:unknown,message:string):asserts v {if(!v)throw new DomainError(message);}
const id=(v:unknown)=>typeof v==='string'&&/^[A-Za-z0-9:_-]{1,128}$/.test(v);
export function expiryDeadline(value:unknown):number {ensure(typeof value==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value),'Canonical UTC expiry deadline required');const n=Date.parse(value);ensure(Number.isSafeInteger(n)&&n>=0&&new Date(n).toISOString()===value,'Invalid UTC expiry deadline');return n;}
export function validateMemoryExpiries(mission:Mission):void {
 if(!Object.hasOwn(mission,'memoryExpiries')){ensure(!Object.hasOwn(mission,'memoryTimeWatermark'),'Expiry clock watermark lacks history');return;}
 const history=mission.memoryExpiries;ensure(Array.isArray(history)&&history.length>0&&history.length<=100&&Object.keys(history).length===history.length&&Object.keys(history).every((k,i)=>k===String(i))&&Buffer.byteLength(JSON.stringify(history),'utf8')<=131072,'Expiry history exceeds bounded array contract');ensure(Number.isSafeInteger(mission.memoryTimeWatermark)&&mission.memoryTimeWatermark!>=0,'Invalid expiry clock watermark');const ids=new Set<string>(),versions=new Set<string>();let last=0;
 for(const e of history){ensure(exact(e,['id','memory','deadline','actorId','reason','declaredAt'])&&id(e.id)&&!ids.has(e.id)&&id(e.actorId)&&typeof e.reason==='string'&&!!e.reason.trim()&&e.reason.isWellFormed()&&e.reason.length<=2000,'Invalid owner memory expiry');conflictMemory(mission,e.memory);const key=JSON.stringify([e.memory.id,e.memory.version,e.memory.hash]);ensure(!versions.has(key),'Exact memory version already has expiry');ensure(Number.isSafeInteger(e.declaredAt)&&e.declaredAt>=last&&e.declaredAt<=mission.memoryTimeWatermark!&&expiryDeadline(e.deadline)>e.declaredAt,'Invalid original expiry observation');last=e.declaredAt;ids.add(e.id);versions.add(key);}
}
export function requiresMemoryTime(mission:Mission,type:string):boolean {return type==='declare-memory-expiry'||type==='admit-work'&&Object.hasOwn(mission,'memoryExpiries');}
export function observeMemoryTime(mission:Mission,context:TimeObservation|undefined):number {validateMemoryExpiries(mission);ensure(exact(context,['observedAt'])&&Number.isSafeInteger(context!.observedAt)&&context!.observedAt>=0&&context!.observedAt>=(mission.memoryTimeWatermark??0),'Host expiry clock observation unavailable or moved backwards; no new Work');mission.memoryTimeWatermark=context!.observedAt;return context!.observedAt;}
export function declareMemoryExpiry(mission:Mission,input:{expiryId:string;memory:MemoryConflictReference;deadline:string;reason:string},actorId:string,context:TimeObservation|undefined):void {ensure(exact(input,['expiryId','memory','deadline','reason']),'Exact memory expiry fields required');const memory=conflictMemory(mission,input.memory);ensure(memory.effective===true,'Only currently effective explicit memory may receive expiry');const observedAt=observeMemoryTime(mission,context);ensure(expiryDeadline(input.deadline)>observedAt,'Expiry deadline must be in the future');(mission.memoryExpiries??=[]).push({id:input.expiryId,memory:structuredClone(input.memory),deadline:input.deadline,reason:input.reason,actorId,declaredAt:observedAt});validateMemoryExpiries(mission);}
export function requireUnexpiredNewWork(mission:Mission,context:TimeObservation|undefined):void {const observedAt=observeMemoryTime(mission,context),expired=mission.memoryExpiries!.filter(e=>conflictMemory(mission,e.memory).effective&&expiryDeadline(e.deadline)<=observedAt);ensure(!expired.length,'New Work admission blocked by explicit memory expiry: '+expired.map(e=>e.id+' ['+e.memory.id+'@'+e.memory.version+'] '+e.deadline).join('; ')+'. Deliberately retire the exact version before new admission; existing Work remains unchanged.');}
