export const memoryUsagePanel=String.raw`<details id="memory-usage-panel" class="impact-panel"><summary>Inspect exact memory version uses</summary><p class="hint">Read original retained Work/Record pins, including inactive versions. Current effective state describes new admission only. Uses do not prove learning quality or authorize execution. Each explicit read displays at most 20 uses with the exact total. Read next keeps the original revision and feed; changed state requires a new initial read.</p><label for="memory-usage-target">Exact original memory version</label><select id="memory-usage-target"><option value="">Choose exact version</option></select><div class="row"><button id="memory-usage-read" type="button">Read original memory uses</button><button id="memory-usage-more" type="button" class="secondary">Read next 20 uses</button><button id="memory-usage-cancel" type="button" class="secondary">Cancel private inspection</button></div><p id="memory-usage-status" class="status" role="status" aria-live="polite">No memory inspected.</p><pre id="memory-usage-result" tabindex="0" aria-label="Original memory and retained Work Record uses" hidden></pre></details>`;
export const memoryUsageClient=String.raw`
let memoryUsageSequence=0,memoryUsageReading=false,memoryUsageSelection='',memoryUsageBoundary=null,memoryUsageIdentity=null,memoryUsagePage=null;
function memoryUsageReset(message='Choose an exact version; no command or execution is issued.'){++memoryUsageSequence;memoryUsageReading=false;memoryUsagePage=null;$('memory-usage-result').textContent='';$('memory-usage-result').hidden=true;$('memory-usage-status').textContent=message;memoryUsageControls();}
function memoryUsageMemory(){return snapshot?.value.memories.find(m=>JSON.stringify([m.id,m.version])===memoryUsageSelection);}
function memoryUsageControls(){if(reconnectRequired&&(memoryUsagePage||memoryUsageReading)){++memoryUsageSequence;memoryUsagePage=null;memoryUsageReading=false;$('memory-usage-result').textContent='';$('memory-usage-result').hidden=true;$('memory-usage-status').textContent='Connection changed; explicitly read against refreshed state. No write or execution.';}const ready=!!snapshot&&snapshot.value.id===selectedId&&!loading&&!reconnectRequired;$('memory-usage-target').disabled=!ready;$('memory-usage-read').disabled=!ready||!memoryUsageMemory()||memoryUsageReading;$('memory-usage-cancel').disabled=!ready;$('memory-usage-more').disabled=!ready||memoryUsageReading||!memoryUsagePage||memoryUsagePage.nextAfter===null;}
function renderMemoryUsage(){const identity=JSON.stringify([selectedId,feedId]);if(identity!==memoryUsageIdentity){memoryUsageIdentity=identity;memoryUsageSelection='';}const boundary=JSON.stringify([selectedId,feedId,connectionEpoch,snapshot?.revision]);if(boundary!==memoryUsageBoundary){memoryUsageBoundary=boundary;memoryUsageReset('State changed; explicitly read the retained exact selection.');}const target=$('memory-usage-target');target.replaceChildren();const empty=element('option','Choose exact version');empty.value='';target.append(empty);for(const m of snapshot?.value.memories||[]){const o=element('option',m.id+' @ '+m.version+' · '+m.authority+' · '+(m.effective?'effective':'historical/inactive'));o.value=JSON.stringify([m.id,m.version]);target.append(o);}if(memoryUsageSelection&&!Array.from(target.children).some(o=>o.value===memoryUsageSelection)){const o=element('option','Original version unavailable; no replacement');o.value=memoryUsageSelection;target.append(o);}target.value=memoryUsageSelection;memoryUsageControls();}
$('memory-usage-target').addEventListener('change',()=>{memoryUsageSelection=$('memory-usage-target').value;memoryUsageReset();});
$('memory-usage-cancel').addEventListener('click',()=>{memoryUsageSelection='';$('memory-usage-target').value='';memoryUsageReset('Private inspection cancelled. No write or execution.');});
function memoryUsageUse(work){return {workId:work.id,title:work.title,execution:work.execution,acceptance:work.acceptance,criteriaVersion:work.criteria.version,...(work.record?{record:{id:work.record.id,checksum:work.record.checksum,evidenceClass:work.record.evidenceClass,memoryVersions:structuredClone(work.record.memoryVersions)}}:{})};}
async function readMemoryUsagePage(next=false){
 memoryUsageControls();if($(next?'memory-usage-more':'memory-usage-read').disabled)return;const prior=memoryUsagePage,offset=next?prior.nextAfter:0,sequence=++memoryUsageSequence,missionId=selectedId,feed=feedId,epoch=connectionEpoch,revision=snapshot.revision,selection=memoryUsageSelection,memory=structuredClone(memoryUsageMemory()),focus=document.activeElement,current=()=>sequence===memoryUsageSequence&&selectedId===missionId&&feedId===feed&&connectionEpoch===epoch&&snapshot?.revision===revision&&memoryUsageSelection===selection&&!reconnectRequired;
 if(!next){memoryUsagePage=null;$('memory-usage-result').textContent='';$('memory-usage-result').hidden=true;}memoryUsageReading=true;memoryUsageControls();$('memory-usage-status').textContent='Reading original version page; no writes.';
 try{
  const {effective,...original}=memory,versionHash=await sequenceHash(original);if(!current())return;if(next&&(prior.missionId!==missionId||prior.feedId!==feed||prior.revision!==revision||prior.versionHash!==versionHash))throw Error('Original usage page boundary changed. Explicitly read again.');
  const {response,body:r}=await request('/missions/'+encodeURIComponent(missionId)+'/memory-usage?id='+encodeURIComponent(memory.id)+'&version='+memory.version+'&hash='+versionHash+'&revision='+revision+(next?'&after='+offset:''),{headers:{'X-Massion-Feed':feed}});if(!current())return;if(!response.ok)throw Error(r.error||'Exact memory read failed');
  const {effective:currentEffective,...returned}=r.memory||{},uses=snapshot.value.works.filter(w=>w.appliedMemoryVersions.includes(memory.id+'@'+memory.version)),expected=uses.slice(offset,offset+20).map(memoryUsageUse),expectedNext=offset+expected.length<uses.length?offset+expected.length:null;
  if(r.missionId!==missionId||r.feedId!==feed||r.revision!==revision||r.versionHash!==versionHash||await sequenceHash(returned)!==versionHash||!Number.isSafeInteger(r.cursor)||r.cursor<0||r.offset!==offset||r.nextAfter!==expectedNext||r.limit!==20||r.totalUses!==uses.length||!Array.isArray(r.uses)||await sequenceHash(r.uses)!==await sequenceHash(expected))throw Error('Original memory use page failed exact binding');if(!current())return;
  memoryUsagePage=r;$('memory-usage-result').textContent=JSON.stringify(r,null,2);$('memory-usage-result').hidden=false;$('memory-usage-status').textContent='Original version · '+r.totalUses+' retained Work uses; showing '+r.uses.length+' (positions '+(r.uses.length?offset+1:0)+'–'+(offset+r.uses.length)+'). No write or execution.';
 }catch(error){if(current()){memoryUsagePage=null;$('memory-usage-result').textContent='';$('memory-usage-result').hidden=true;$('memory-usage-status').textContent=error.message+' · No newer version substituted. Explicit initial read required.';}}finally{if(current()){memoryUsageReading=false;memoryUsageControls();if(document.activeElement===focus)restoreControlFocus(focus,focus?.id);}}
}
$('memory-usage-read').addEventListener('click',()=>readMemoryUsagePage());
$('memory-usage-more').addEventListener('click',()=>readMemoryUsagePage(true));
`;
