/** Native bounded, stateless text APIs. No implicit credentials, retries, tools or subprocesses. */
import {readBoundedJson,providerRequestId} from './http-provider.ts';
import type {HttpProviderTransport} from './http-provider.ts';
import type {ModelAdapterFactory,ModelConnectionProfile} from './provider-profiles.ts';
import type {ProviderOutcome,ProviderRequest} from './providers.ts';
import type {CredentialResolver} from './chat-profile-factory.ts';
export type NativeProtocol='anthropic-messages/v1'|'gemini-generate-content/v1';
export type TransportMode='https'|'local-http-mock';
const record=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const integer=(v:unknown):v is number=>Number.isSafeInteger(v)&&Number(v)>=0;
const label=(v:unknown):v is string=>typeof v==='string'&&v.length>0&&v.length<=512&&v.trim()===v&&!/[\u0000-\u001f\u007f]/.test(v);
export function validateModelEndpoint(endpoint:string,mode:TransportMode,suffix:string){
 if(typeof endpoint!=='string'||endpoint.length>2048||/[?#\\\s]/.test(endpoint))throw Error('Invalid model endpoint');const url=new URL(endpoint);
 if(url.href!==endpoint||url.username||url.password||!url.pathname.endsWith(suffix)||(mode==='https'?url.protocol!=='https:':url.protocol!=='http:'||url.hostname!=='127.0.0.1'||!url.port))throw Error('Canonical explicit endpoint required');
}
export function nativeBody(protocol:NativeProtocol,p:ModelConnectionProfile,r:ProviderRequest,cap:number){
 const text=r.instruction+(r.inputReferences.length?'\n\nLiteral input references (identifiers only):\n'+r.inputReferences.join('\n'):'');
 return JSON.stringify(protocol==='anthropic-messages/v1'?{model:p.model,max_tokens:cap,stream:false,messages:[{role:'user',content:text}]}:{contents:[{role:'user',parts:[{text}]}],generationConfig:{candidateCount:1,maxOutputTokens:cap}});
}
export function parseNativeCompletion(protocol:NativeProtocol,body:unknown,model:string,cap:number):ProviderOutcome{
 if(!record(body)||body.error!==undefined)throw Error('invalid_native_schema');let input:number,output:number,text:string,reason:string;
 if(protocol==='anthropic-messages/v1'){
  if(body.type!=='message'||!label(body.id)||body.role!=='assistant'||body.model!==model||!record(body.usage)||!integer(body.usage.input_tokens)||!integer(body.usage.output_tokens)||!Array.isArray(body.content)||!label(body.stop_reason))throw Error('native_model_or_usage_mismatch');
  input=body.usage.input_tokens;output=body.usage.output_tokens;for(const key of ['cache_creation_input_tokens','cache_read_input_tokens'])if(body.usage[key]!==undefined){if(!integer(body.usage[key]))throw Error('invalid_usage');input+=body.usage[key];}
  text=body.content.filter((p:unknown)=>record(p)&&p.type==='text'&&typeof p.text==='string').map((p:any)=>p.text).join('');reason=body.stop_reason==='end_turn'&&body.stop_details?.type!=='refusal'&&body.content.every((p:unknown)=>record(p)&&p.type==='text'&&typeof p.text==='string')?'completed':body.stop_reason==='max_tokens'?'output_truncated':'unsupported_or_refused_output';
 }else{
  const u=body.usageMetadata,c=body.candidates;if(body.modelVersion!==model||!label(body.responseId)||!record(u)||!integer(u.promptTokenCount)||!integer(u.candidatesTokenCount)||!integer(u.totalTokenCount)||!Array.isArray(c)||c.length!==1||!record(c[0])||!record(c[0].content)||c[0].content.role!=='model'||!Array.isArray(c[0].content.parts))throw Error('native_model_or_usage_mismatch');
  if(u.thoughtsTokenCount!==undefined&&!integer(u.thoughtsTokenCount))throw Error('invalid_usage');input=u.promptTokenCount;output=u.candidatesTokenCount+(u.thoughtsTokenCount??0);if(u.totalTokenCount!==input+output)throw Error('invalid_usage');
  const parts=c[0].content.parts;text=parts.filter((p:unknown)=>record(p)&&typeof p.text==='string'&&p.thought!==true).map((p:any)=>p.text).join('');reason=c[0].finishReason==='STOP'&&!body.promptFeedback?.blockReason&&parts.every((p:unknown)=>record(p)&&typeof p.text==='string'&&p.text.isWellFormed()&&Object.keys(p).every(k=>['text','thought','thoughtSignature'].includes(k))&&(p.thought===undefined||typeof p.thought==='boolean')&&(p.thoughtSignature===undefined||typeof p.thoughtSignature==='string'))?'completed':c[0].finishReason==='MAX_TOKENS'?'output_truncated':'unsupported_or_filtered_output';
 }
 if(!text.isWellFormed()||!integer(input)||!integer(output)||output>cap)throw Error('invalid_or_unbounded_usage');return {status:reason==='completed'&&text.trim()?'completed':'failed',output:reason==='completed'&&text.trim()?text:null,usage:{inputTokens:input,outputTokens:output},reason:reason==='completed'&&!text.trim()?'empty_output':reason};
}
export async function credentialHeaders(method:string,request:{secretRef?:string;profileId:string;endpoint:string;signal:AbortSignal},resolver?:CredentialResolver){
 const headers=new Headers({'content-type':'application/json',accept:'application/json'});if(method==='none')return headers;if(!request.secretRef||!resolver)throw Error('Credential connection required');
 const secret=await resolver({...request,secretRef:request.secretRef});request.signal.throwIfAborted();if(typeof secret!=='string'||!secret||secret.length>8192||/[^\x21-\x7e]/.test(secret))throw Error('Invalid credential');
 if(method==='bearer')headers.set('authorization',`Bearer ${secret}`);else if(method==='anthropic-api-key'){headers.set('x-api-key',secret);headers.set('anthropic-version','2023-06-01');}else if(method==='google-api-key')headers.set('x-goog-api-key',secret);else throw Error('Unsupported auth');return headers;
}
export function nativeProfileFactory(protocol:NativeProtocol,options:{mode:TransportMode;transport:HttpProviderTransport;resolveCredential?:CredentialResolver}):ModelAdapterFactory{
 const method=protocol==='anthropic-messages/v1'?'anthropic-api-key':'google-api-key';const suffix=protocol==='anthropic-messages/v1'?'/messages':':generateContent';
 return {protocol,authMethods:[options.mode==='local-http-mock'?'none':method],capabilities:['text-output'],evidenceClass:options.mode==='local-http-mock'?'fixture':'real-provider',validate(p){const errors=[];
  try{validateModelEndpoint(p.endpoint,options.mode,suffix);if(protocol==='gemini-generate-content/v1'&&(!/^[a-zA-Z0-9._-]{1,128}$/.test(p.model)||!p.endpoint.endsWith('/models/'+p.model+':generateContent')))throw Error('Model path mismatch');}catch{errors.push({code:'endpoint_invalid',message:'Explicit canonical native model endpoint required.'});}
  if(options.mode==='https'&&(!p.auth.secretRef||!options.resolveCredential))errors.push({code:'credential_resolver_missing',message:'Connect the caller-owned API credential before using this profile.'});if(options.mode==='local-http-mock'&&p.auth.secretRef)errors.push({code:'auth_invalid',message:'No credentials on fixture transport.'});if(p.usage.inputTokens!=='reported'||p.usage.outputTokens!=='reported')errors.push({code:'usage_unsupported',message:'Reported token usage is required.'});return errors;
 },create(profile){const p=structuredClone(profile);validateModelEndpoint(p.endpoint,options.mode,suffix);if(!label(p.id)||!label(p.model)||!label(p.providerKind)||!label(p.revision)||p.protocol!==protocol||p.auth.method!==(options.mode==='local-http-mock'?'none':method)||!record(p.limits)||Object.keys(p.limits).length!==4||!['maxInputBytes','maxOutputTokens','maxResponseBytes','timeoutMs'].every(k=>integer(p.limits[k as keyof typeof p.limits])&&p.limits[k as keyof typeof p.limits]>0)||p.limits.timeoutMs>2147483647||p.usage.inputTokens!=='reported'||p.usage.outputTokens!=='reported'||options.mode==='local-http-mock'&&p.auth.secretRef!==undefined||options.mode==='https'&&(!p.auth.secretRef||!options.resolveCredential))throw Error('Invalid native profile');if(protocol==='gemini-generate-content/v1'&&(!/^[a-zA-Z0-9._-]{1,128}$/.test(p.model)||!p.endpoint.endsWith('/models/'+p.model+':generateContent')))throw Error('Gemini model endpoint mismatch');return {descriptor:{provider:p.providerKind,model:p.model,configVersion:p.revision,enabled:p.enabled,capabilities:['text-output'],evidenceClass:options.mode==='local-http-mock'?'fixture':'real-provider'},async invoke(request){
  const outcome=(status:ProviderOutcome['status'],reason:string):ProviderOutcome=>({status,output:null,usage:{inputTokens:null,outputTokens:null},reason});if(request.signal.aborted)return outcome('cancelled','cancelled_before_dispatch');const cap=request.maxOutputTokens??p.limits.maxOutputTokens;
  if(!p.enabled||!label(request.invocationId)||!label(request.workId)||typeof request.instruction!=='string'||!request.instruction.trim()||!request.instruction.isWellFormed()||!Array.isArray(request.inputReferences)||!request.inputReferences.every(v=>typeof v==='string'&&v.isWellFormed())||!integer(cap)||cap<1||cap>p.limits.maxOutputTokens)return outcome('failed','invalid_request_or_bound');request={...request,inputReferences:[...request.inputReferences]};const body=nativeBody(protocol,p,request,cap);if(Buffer.byteLength(body)>p.limits.maxInputBytes)return outcome('failed','input_byte_limit');
  const controller=new AbortController();let dispatched=false,reason='cancelled_after_dispatch';const cancel=()=>controller.abort();request.signal.addEventListener('abort',cancel,{once:true});const timer=setTimeout(()=>{reason='timeout_after_dispatch';controller.abort();},p.limits.timeoutMs);let reject!:()=>void;const aborted=new Promise<never>((_,r)=>reject=()=>r(Error('aborted')));controller.signal.addEventListener('abort',reject,{once:true});
  try{return await Promise.race([(async()=>{const headers=await credentialHeaders(p.auth.method,{secretRef:p.auth.secretRef,profileId:p.id,endpoint:p.endpoint,signal:controller.signal},options.resolveCredential);controller.signal.throwIfAborted();headers.set('x-client-request-id',providerRequestId(request.invocationId));dispatched=true;const response=await options.transport(p.endpoint,{method:'POST',headers,body,redirect:'error',credentials:'omit',cache:'no-store',signal:controller.signal});controller.signal.throwIfAborted();if(!(response instanceof Response)||response.redirected||response.url&&response.url!==p.endpoint||response.status!==200||!/^application\/json(?:\s*;\s*charset=(?:utf-8|"utf-8"))?\s*$/i.test(response.headers.get('content-type')??'')){void response.body?.cancel().catch(()=>{});throw Error('invalid_http_response');}const result=await readBoundedJson(response,p.limits.maxResponseBytes,controller.signal);controller.signal.throwIfAborted();return parseNativeCompletion(protocol,result,p.model,cap);})(),aborted]);}
  catch{return outcome(dispatched?'unknown':request.signal.aborted?'cancelled':'failed',dispatched?(controller.signal.aborted?reason:'native_remote_outcome_unknown'):'credential_or_cancellation_before_dispatch');}
  finally{clearTimeout(timer);request.signal.removeEventListener('abort',cancel);controller.signal.removeEventListener('abort',reject);controller.abort();}
 }};}};
}
