export const fileDocumentPanel=String.raw`<details id="file-document-panel" class="impact-panel"><summary>Import an owner-selected text file as a private source draft</summary><p class="hint">Choose one approved local UTF-8 file, at most 16 KiB. Only your browser reads it. Inspect the original and explicitly use it to replace private content/source; storing is a separate reviewed document command. CRLF/CR line endings become LF. Raw-file and initial draft hashes differ when normalized; later edits are separate. Filename/source are owner-supplied provenance, not external truth verification. No upload, path access, execution or automatic save.</p><label for="file-document-choice">Select one local UTF-8 text file</label><input id="file-document-choice" type="file"><pre id="file-document-preview" tabindex="0" aria-label="Selected file original and normalized private draft" hidden></pre><div class="row"><button id="file-document-use" type="button" disabled>Use reviewed file in private document draft</button><button id="file-document-cancel" type="button" class="secondary">Cancel private file import</button></div><p id="file-document-status" class="status" role="status" aria-live="polite">No file read, document stored or execution started.</p></details>`;
export const fileDocumentClient=String.raw`
let fileDocumentSequence=0,fileDocumentPreview=null,fileDocumentBoundary=null;
function fileDocumentCurrent(p){return !!p&&p.sequence===fileDocumentSequence&&p.missionId===selectedId&&p.feed===feedId&&p.epoch===connectionEpoch&&p.revision===snapshot?.revision&&p.values===JSON.stringify(documentValues())&&organizationEditable();}
function fileDocumentReset(message='Private file preview cleared. No document write or execution.'){++fileDocumentSequence;fileDocumentPreview=null;$('file-document-preview').hidden=true;$('file-document-preview').textContent='';$('file-document-choice').value='';$('file-document-status').textContent=message;fileDocumentControls();}
function fileDocumentControls(){const ready=organizationEditable();$('file-document-choice').disabled=!ready;$('file-document-use').disabled=!ready||!fileDocumentCurrent(fileDocumentPreview);$('file-document-cancel').disabled=!ready;}
function renderFileDocument(){const boundary=JSON.stringify([selectedId,feedId,connectionEpoch,snapshot?.revision]);if(boundary!==fileDocumentBoundary){fileDocumentBoundary=boundary;fileDocumentReset('State changed; explicitly choose a file for this Mission draft.');}fileDocumentControls();}
async function fileDocumentHash(bytes){if(!crypto.subtle)throw Error('Exact SHA-256 is unavailable');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(v=>v.toString(16).padStart(2,'0')).join('');}
$('file-document-choice').addEventListener('change',async()=>{const file=$('file-document-choice').files?.[0];fileDocumentReset();if(!organizationEditable()||!file)return;const p={sequence:fileDocumentSequence,missionId:selectedId,feed:feedId,epoch:connectionEpoch,revision:snapshot.revision,values:JSON.stringify(documentValues())};$('file-document-status').textContent='Reading selected local file privately; no request sent.';try{if(typeof file.name!=='string'||!file.name.trim()||file.name.length>200||!file.name.isWellFormed()||!Number.isSafeInteger(file.size)||file.size<1||file.size>16384)throw Error('A nonempty named UTF-8 file of at most 16 KiB is required');const raw=await file.arrayBuffer();if(!fileDocumentCurrent(p))return;if(raw.byteLength!==file.size||raw.byteLength>16384)throw Error('Selected file size changed or exceeds the bound');const original=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(raw);if(!original.trim()||original.includes('\u0000'))throw Error('Nonblank plain UTF-8 text without NUL is required');const content=original.replace(/\r\n?/g,'\n'),rawSha256=await fileDocumentHash(raw),draftSha256=await fileDocumentHash(new TextEncoder().encode(content));if(!fileDocumentCurrent(p))return;const provenance={kind:'owner-selected UTF-8 file draft',name:file.name,rawBytes:raw.byteLength,rawSha256,normalization:'CRLF/CR to LF; UTF-8 BOM preserved',initialDraftSha256:draftSha256};fileDocumentPreview={...p,name:file.name,content,source:JSON.stringify(provenance)};$('file-document-preview').textContent=JSON.stringify(provenance,null,2)+'\n\n'+content;$('file-document-preview').hidden=false;$('file-document-status').textContent='Private original preview ready. Explicit Use replaces content/source only; then review and save separately.';fileDocumentControls();}catch(error){if(fileDocumentCurrent(p)){$('file-document-status').textContent='File not imported: '+error.message+'. Existing private draft retained.';fileDocumentControls();}}});
$('file-document-cancel').addEventListener('click',()=>{if(organizationEditable())fileDocumentReset();});
$('file-document-use').addEventListener('click',()=>{const p=fileDocumentPreview;if(!fileDocumentCurrent(p))return;const draft=documentDrafts.get(selectedId),values=documentValues();if(!values[2])values[2]=p.name;values[3]=p.source;values[4]=p.content;documentIds.forEach((id,i)=>$(id).value=values[i]);documentDrafts.set(selectedId,{...draft,values:[...values],baseRevision:null});fileDocumentReset('Selected file copied to private document draft. Review ID/version/current revision before separate Store.');documentStatuses.set(selectedId,'Imported private draft requires deliberate revision review. Raw-file provenance is distinct from edited stored text.');renderDocuments();$('document-content').focus();});
for(const id of documentIds)for(const event of ['input','change'])$(id).addEventListener(event,()=>fileDocumentReset('Private document edited; explicitly choose a file again. No write.'));
$('cancel-document').addEventListener('click',()=>{if(organizationEditable())fileDocumentReset('Private document cancelled; pending file read invalidated.');});
`;
