/** Inline owner controls use the same headless request. No browser scheduler or restored plan. */
export const runSequencePanel=String.raw`<details id="sequence-panel" class="impact-panel"><summary id="sequence-summary">Review and start an exact Work sequence</summary><p id="sequence-hint" class="hint">Choose one to three existing fresh Work in order and existing permitted connections. Each next Work needs independent acceptance of its predecessor. Review checks the first selection; Start rechecks every stage. Unknown, cancellation, busy or changed state stops later admission. No automatic retry or restart continuation.</p><form id="sequence-form"><fieldset id="sequence-fields"><label for="sequence-work-1">First Work</label><select id="sequence-work-1" aria-describedby="sequence-hint sequence-base"></select><label for="sequence-work-2">Second Work (optional)</label><select id="sequence-work-2"></select><label for="sequence-work-3">Third Work (optional)</label><select id="sequence-work-3"></select><label for="sequence-executor">Executor connection / model</label><select id="sequence-executor"></select><label for="sequence-verifier">Independent verifier connection / model</label><select id="sequence-verifier"></select><label for="sequence-authorization">Existing authorized use</label><select id="sequence-authorization"></select><label for="sequence-cap">Output-token cap per call for each Work</label><input id="sequence-cap" type="number" min="1" step="1"><p id="sequence-base" class="hint"></p><div id="sequence-comparison" class="impact-results" tabindex="0" role="region" aria-label="Current and reviewed exact Work sequence"></div><div class="row"><button id="sequence-review" type="button" class="secondary">Review exact plan and first selection</button><button id="sequence-cancel" type="button" class="secondary">Cancel private plan</button><button id="sequence-start" type="submit" data-write>Start reviewed sequence</button></div></fieldset></form><p id="sequence-status" class="status" role="status" aria-live="polite">Choose exact Work and existing permitted connections. Nothing starts until Start.</p><button id="sequence-recheck" type="button" class="secondary">Read pending admission receipt</button><p class="hint">A first Work admission receipt is not whole sequence completion. Unknown replies are never replayed. Cancel private plan sends no command and cannot stop submitted execution; use the exact Work cancellation controls above. Plans stay private to this open page and are not restored after reload.</p></details>`;

export const runSequenceClient=String.raw`
const sequenceIds=['sequence-work-1','sequence-work-2','sequence-work-3','sequence-executor','sequence-verifier','sequence-authorization','sequence-cap'];
const sequenceDrafts=new Map(),sequenceStatuses=new Map(),sequenceRequests=new Map(),sequenceSubmissions=new Map();
function sequenceValues(){return sequenceIds.map(id=>$(id).value);}
function sequenceConfiguration(){return JSON.stringify(runtimeConfiguration);}
function sequenceDraft(){let draft=sequenceDrafts.get(selectedId);if(!draft){draft={values:Array(7).fill(''),review:null,version:0,reviewing:false};sequenceDrafts.set(selectedId,draft);}return draft;}
function sequenceCanonical(value){if(Array.isArray(value))return '['+value.map(sequenceCanonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+sequenceCanonical(value[key])).join(',')+'}';return JSON.stringify(value);}
async function sequenceHash(value){if(!crypto.subtle)throw Error('Exact input hashing is unavailable.');const bytes=new TextEncoder().encode(sequenceCanonical(value)),digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}
function sequenceInput(work){return {...(Object.hasOwn(work,'questions')?{questions:work.questions}:{}),...(Object.hasOwn(work,'conversationSource')?{conversationSource:work.conversationSource}:{}),...(Object.hasOwn(work,'correction')?{correction:work.correction}:{}),...(Object.hasOwn(work,'prerequisites')?{prerequisites:work.prerequisites}:{}),mission:work.missionSnapshot,title:work.title,instructions:work.instructions||[],memoryVersions:work.appliedMemoryVersions,...(Object.hasOwn(work,'sourceDocuments')?{sourceDocuments:work.sourceDocuments}:{}),...(work.organizationSnapshot?{organization:work.organizationSnapshot}:{})};}
function sequenceEditable(){return revisionEditable()&&!sequenceRequests.has(selectedId);}
function sequenceMatches(draft){const r=draft?.review;return !!r&&snapshot?.value.id===selectedId&&r.missionId===selectedId&&r.revision===snapshot.revision&&r.feed===feedId&&r.configuration===sequenceConfiguration()&&JSON.stringify(draft.values)===JSON.stringify(r.values)&&r.originals.every(original=>{const w=snapshot.value.works.find(w=>w.id===original.id);return budgetFresh(w)&&sequenceCanonical(w)===original.full;});}
function sequenceControls(){const draft=sequenceDrafts.get(selectedId),editable=sequenceEditable();$('sequence-fields').disabled=!editable;$('sequence-review').disabled=!editable||!!draft?.reviewing;$('sequence-cancel').disabled=!editable;$('sequence-start').disabled=!editable||!sequenceMatches(draft)||!!draft?.reviewing;$('sequence-recheck').disabled=!!busy||!!loading||!unknownOperation;}
function sequenceOptions(id,items,value,prompt){const select=$(id);select.replaceChildren();const empty=element('option',prompt);empty.value='';select.append(empty);for(const item of items){const option=element('option',item.label);option.value=item.id;option.disabled=!!item.disabled;select.append(option);}if(value&&!items.some(item=>item.id===value)){const old=element('option',value+' · previous selection unavailable; no replacement');old.value=value;select.append(old);}select.value=value;}
function renderSequence(){if(!snapshot||snapshot.value.id!==selectedId){sequenceControls();return;}const draft=sequenceDraft(),values=draft.values,works=snapshot.value.works.filter(budgetFresh).map(w=>({id:w.id,label:w.title+' · '+w.id}));for(let index=0;index<3;index++)sequenceOptions(sequenceIds[index],works,values[index],index?'No later Work':'Choose exact first Work');const profiles=(runtimeConfiguration?.connections||[]).filter(p=>p.backend==='model-provider').map(p=>({id:p.id,label:p.label+' · '+p.model,disabled:p.diagnostics.length>0}));sequenceOptions('sequence-executor',profiles,values[3],'Choose executor');sequenceOptions('sequence-verifier',profiles,values[4],'Choose independent verifier');sequenceOptions('sequence-authorization',(runtimeConfiguration?.authorizations||[]).filter(a=>a.scope===snapshot.value.scope).map(a=>({id:a.id,label:a.id+' · '+a.mode+' · max '+a.maxOutputTokensPerCall})),values[5],'Choose existing authorized use');$('sequence-cap').value=values[6];$('sequence-base').textContent='Mission '+selectedId+' · Current revision '+snapshot.revision+(draft.review?' · Reviewed revision '+draft.review.revision+(sequenceMatches(draft)?' · Exact review still current.':' · State, selections or permissions changed. Deliberate review required.'):' · Not reviewed.');const area=$('sequence-comparison');area.replaceChildren();for(const [index,id] of values.slice(0,3).entries()){if(!id)continue;const w=snapshot.value.works.find(w=>w.id===id);area.append(element('p','Position '+(index+1)+' · '+id+(budgetFresh(w)?' · fresh':' · unavailable for a new run')),element('pre',w?JSON.stringify({title:w.title,criteria:w.criteria,budget:w.budget,input:sequenceInput(w),prerequisites:(w.prerequisites||[]).map(pin=>({...pin,record:snapshot.value.works.find(target=>target.id===pin.workId)?.record||null})),execution:w.execution,acceptance:w.acceptance},null,2):'Original Work is absent; no replacement is selected.'));}if(draft.review){area.append(element('p','Original reviewed request · revision '+draft.review.revision),element('pre',JSON.stringify({works:draft.review.works,originalInputs:draft.review.originals.map(original=>{const w=JSON.parse(original.full);return {workId:w.id,input:sequenceInput(w),criteria:w.criteria,budget:w.budget,prerequisites:w.prerequisites||[]};}),selection:draft.review.selection},null,2)));}$('sequence-status').textContent=sequenceStatuses.get(selectedId)||'Choose exact Work and existing permitted connections. Nothing starts until Start.';sequenceControls();}
for(const id of sequenceIds)for(const event of ['input','change'])$(id).addEventListener(event,()=>{if(!snapshot||snapshot.value.id!==selectedId)return;const draft=sequenceDraft();draft.values=sequenceValues();draft.review=null;draft.reviewing=false;++draft.version;sequenceStatuses.set(selectedId,'Private selection changed. Review its exact current Work and permitted connections; no command sent.');renderSequence();});
$('sequence-cancel').addEventListener('click',()=>{if(!sequenceEditable())return;sequenceDrafts.delete(selectedId);sequenceStatuses.set(selectedId,'Private plan cancelled. No command was sent; existing Work and submitted execution stay unchanged.');renderSequence();});
$('sequence-review').addEventListener('click',async()=>{
 if(!sequenceEditable())return;const missionId=selectedId,draft=sequenceDraft(),values=[...draft.values],version=++draft.version,origin=snapshot,feed=feedId,epoch=connectionEpoch,configuration=sequenceConfiguration(),focus=document.activeElement;draft.review=null;draft.reviewing=true;sequenceStatuses.set(missionId,'Reading first selection and exact original Work without execution…');renderSequence();
 const current=()=>snapshot?.value.id===missionId&&selectedId===missionId&&snapshot.revision===origin.revision&&feedId===feed&&connectionEpoch===epoch&&sequenceConfiguration()===configuration&&sequenceDrafts.get(missionId)===draft&&draft.version===version&&JSON.stringify(draft.values)===JSON.stringify(values);
 try{
  const ids=values.slice(0,3);if(!ids[0]||!ids[1]&&ids[2]||new Set(ids.filter(Boolean)).size!==ids.filter(Boolean).length)throw Error('Choose one to three distinct Work in contiguous prerequisite order.');if(values.slice(3).some(value=>!value)||!Number.isSafeInteger(Number(values[6]))||Number(values[6])<1)throw Error('Choose existing executor, verifier, authorized use and a positive whole output cap.');
  const selected=ids.filter(Boolean),works=[],originals=[];for(const id of selected){const w=origin.value.works.find(w=>w.id===id);if(!budgetFresh(w)||!w.missionSnapshot)throw Error('Original selected Work is not fresh. No other Work is substituted.');works.push({workId:id,inputHash:await sequenceHash(sequenceInput(w)),criteriaHash:await sequenceHash(w.criteria)});originals.push({id,full:sequenceCanonical(w)});}
  for(const [index,entry] of works.entries()){const w=origin.value.works.find(w=>w.id===entry.workId);for(const pin of w.prerequisites||[]){const target=origin.value.works.find(w=>w.id===pin.workId),position=selected.indexOf(pin.workId);if(!target||await sequenceHash(sequenceInput(target))!==pin.inputHash||await sequenceHash(target.criteria)!==pin.criteriaHash||position>=index||position<0&&(target.acceptance!=='accepted'||!target.record))throw Error('Original prerequisite must be an earlier selected Work or an exact already accepted Record.');}}
  const selection={executorProfileId:values[3],verifierProfileId:values[4],authorizationId:values[5],outputTokenCap:Number(values[6])};if(!current())return;const {response,body}=await request('/missions/'+encodeURIComponent(missionId)+'/preflight',{method:'POST',headers:{'Content-Type':'application/json',...(feed?{'X-Massion-Feed':feed}:{})},body:JSON.stringify({commandId:crypto.randomUUID(),workId:works[0].workId,expectedRevision:origin.revision,selection})});if(!current())return;
  if(!response.ok||body.ready!==true||body.missionId!==missionId||body.workId!==works[0].workId||body.revision!==origin.revision||body.expectedRevision!==origin.revision||body.feedId!==feed||!Array.isArray(body.diagnostics)||body.diagnostics.length)throw Error((body.diagnostics||[]).map(d=>d.message).join(' ')||body.error||'First selection was not confirmed at this exact revision.');
  draft.review={missionId,revision:origin.revision,feed,configuration,values,works,originals,selection};sequenceStatuses.set(missionId,'Exact plan reviewed. First selection checked without execution. Later stages still require current gates and independently accepted predecessor Records. Press Start to request this order.');
 }catch(error){if(current())sequenceStatuses.set(missionId,'Review not confirmed: '+error.message+' No sequence was started.');}finally{if(sequenceDrafts.get(missionId)===draft&&draft.version===version){draft.reviewing=false;if(selectedId===missionId){renderSequence();restoreControlFocus(focus,'sequence-review');}}}
});
function sequenceAdmissionObserved(operation){const item=sequenceSubmissions.get(operationKey(operation));if(!item)return;item.firstObserved=true;if(!item.terminalKnown){sequenceStatuses.set(item.missionId,'First Work admission confirmed. Whole sequence completion is not confirmed; inspect original Work. No sequence or remaining stage will be retried.');if(selectedId===item.missionId)renderSequence();}if(!sequenceRequests.has(item.missionId))sequenceSubmissions.delete(operationKey(operation));}
function validSequenceReply(result,item){if(!result||!['completed','stopped'].includes(result.status)||!validSnapshot(result.snapshot,item.missionId)||!Array.isArray(result.results)||!Array.isArray(result.completedWorkIds)||result.completedWorkIds.length>item.body.works.length||result.results.length!==(result.status==='completed'?item.body.works.length:result.completedWorkIds.length+1))return false;for(const [index,id] of result.completedWorkIds.entries()){const expected=item.body.works[index],w=result.snapshot.value.works.find(w=>w.id===id);if(id!==expected.workId||result.results[index]?.status!=='settled'||w?.runtimeRun?.id!==item.runIds[index]||w.runtimeRun.inputHash!==expected.inputHash||w.runtimeRun.criteriaHash!==expected.criteriaHash||w.acceptance!=='accepted'||!w.record)return false;}if(result.status==='completed'&&result.completedWorkIds.length!==item.body.works.length)return false;return result.results.every((row,index)=>{const position=result.status==='stopped'&&result.completedWorkIds.length===0?item.body.works.findIndex(entry=>entry.workId===row?.workId):index;return row&&position>=0&&row.workId===item.body.works[position]?.workId&&row.runId===item.runIds[position]&&['settled','blocked','cancelled','already-started','conflict'].includes(row.status)&&!(result.status==='stopped'&&index===result.completedWorkIds.length&&row.status==='settled');});}
$('sequence-form').addEventListener('submit',async event=>{
 event.preventDefault();const draft=sequenceDrafts.get(selectedId);if(!sequenceEditable()||!sequenceMatches(draft))return;const missionId=selectedId,review=draft.review,focus=document.activeElement,item={missionId,draft,review,values:[...draft.values],body:{commandId:crypto.randomUUID(),expectedRevision:review.revision,works:structuredClone(review.works),selection:{...review.selection}},runIds:[],terminalKnown:false,firstObserved:false};sequenceRequests.set(missionId,item);sequenceStatuses.set(missionId,'Preparing this exact reviewed request once…');renderSequence();let operation,transmitted=false;
 try{
  for(let index=0;index<item.body.works.length;index++)item.runIds.push('sequence:'+await sequenceHash({commandId:item.body.commandId,index}));if(!sequenceMatches(draft)||selectedId!==missionId)throw Error('Exact review changed before transmission; no request sent.');operation={commandId:item.runIds[0],missionId,reconcileCursor:cursor};busy=true;controls();if(!await persistPending(operation))return;if(reconnectRequired||feedId!==review.feed||!sequenceMatches(draft)){await clearPending(operation);throw Error('Host state changed before transmission; no sequence sent.');}sequenceSubmissions.set(operationKey(operation),item);transmitted=true;const promise=request('/missions/'+encodeURIComponent(missionId)+'/run-sequence',{method:'POST',headers:{'Content-Type':'application/json','X-Massion-Feed':review.feed},body:JSON.stringify(item.body)},item.body.works.length*300000+15000);busy=false;controls();
  const {response,body:result}=await promise;if(feedId!==review.feed)throw Error('Reply belongs to an old database; current admission readback required.');
  if(response.status>=400&&response.status<500&&!validSequenceReply(result,item)||response.status===503&&result.outcome==='rejected'){item.terminalKnown=true;await clearPending(operation);sequenceStatuses.set(missionId,'Sequence rejected: '+(result.error||'inspect the current state')+'. Original private plan retained; no retry.');if(selectedId===missionId)await loadMission(missionId,false);return;}
  if(!validSequenceReply(result,item))throw Error(result.error||'Reply did not confirm this exact sequence prefix.');const current=await verifyAcknowledgementFeed(review.feed,result.feedId,missionId);item.terminalKnown=true;confirmOperation(operation);await clearPending(operation);
  const same=sequenceDrafts.get(missionId)===draft&&draft.review===review&&JSON.stringify(draft.values)===JSON.stringify(item.values);if(result.status==='completed'&&same)sequenceDrafts.delete(missionId);sequenceStatuses.set(missionId,(result.status==='completed'?'Sequence completed: ':'Sequence stopped. Confirmed completed Work: ')+(result.completedWorkIds.join(', ')||'none')+'. '+(result.reason||'Inspect independently accepted Records.')+(same?'':' Later private edits retained.'));
  if(selectedId===missionId&&(!snapshot||snapshot.revision<=current.revision)){++readSequence;installSnapshot(current);}
 }catch(error){sequenceStatuses.set(missionId,(transmitted?'Whole sequence completion is unconfirmed: ':'Sequence was not transmitted: ')+error.message+' Original private plan retained. Read original Work and admission receipts; no sequence or remaining stage will be replayed.');if(transmitted&&operation&&!confirmedOperations.has(operationKey(operation))&&(!unknownOperation||operationKey(unknownOperation)===operationKey(operation)))unknownOperation=operation;if(selectedId===missionId)await loadMission(missionId,false);await pollEvents();}
 finally{busy=false;sequenceRequests.delete(missionId);if(operation&&(item.terminalKnown||confirmedOperations.has(operationKey(operation))))sequenceSubmissions.delete(operationKey(operation));if(selectedId===missionId){renderSequence();restoreControlFocus(focus,$('sequence-start').disabled?'sequence-work-1':'sequence-start');}controls();}
});
$('sequence-recheck').addEventListener('click',()=>{void pollEvents();});
`;
