export const clarificationPanel=String.raw`<details id="clarification-panel" class="impact-panel"><summary>Questions before first Run</summary><p class="hint">Record a question on a fresh Work, or answer one exact open question. Open questions block Run. Saving an answer never starts execution. Each literal text is limited to 4096 UTF-8 bytes.</p><form id="clarification-form"><fieldset id="clarification-fields"><label for="clarification-work">Fresh Work</label><select id="clarification-work"></select><label for="clarification-question">Question decision</label><select id="clarification-question"></select><label for="clarification-text">Original question or answer · private draft</label><textarea id="clarification-text" maxlength="4096" required></textarea><pre id="clarification-original" tabindex="0"></pre><div class="row"><button id="clarification-review" type="button">Review exact question decision</button><button id="clarification-cancel" type="button" class="secondary">Cancel private question draft</button><button id="clarification-save" type="submit" data-write>Save reviewed question decision</button></div></fieldset></form><p id="clarification-status" class="status" role="status" aria-live="polite">No question saved or execution started.</p></details>`;
export const clarificationClient=String.raw`
const clarificationDrafts=new Map(),clarificationSubmissions=new Map(),clarificationStatuses=new Map();
function clarificationDraft(){let d=clarificationDrafts.get(selectedId);if(!d){d={workId:'',questionId:'',text:'',newId:null,review:null};clarificationDrafts.set(selectedId,d);}return d;}
function clarificationWork(d){return snapshot?.value.works.find(w=>w.id===d?.workId);}
function clarificationFresh(w){return !!(w&&w.acceptance==='pending'&&['queued','blocked','waiting'].includes(w.execution)&&!w.runtimeRun&&!w.runtimeRecovery&&!w.effects.length&&!w.assignments.length&&!w.artifact&&!w.verdict&&!w.record&&w.attempts.length===1&&w.attempts[0].status==='queued'&&w.tasks.length===1&&w.tasks[0].status==='queued'&&!w.tasks[0].result);}
function clarificationOriginal(d){const w=clarificationWork(d);return w?sequenceCanonical({work:w,question:d.questionId?w.questions?.find(q=>q.id===d.questionId)||null:null}):null;}
function clarificationValid(d){const w=clarificationWork(d);return clarificationFresh(w)&&d.text.trim()&&d.text.isWellFormed()&&new TextEncoder().encode(d.text).length<=4096&&(d.questionId?w.questions?.some(q=>q.id===d.questionId&&q.answer===null):(w.questions||[]).length<3);}
function clarificationCurrent(d){const v=d?.review;return !!(v&&clarificationValid(d)&&v.missionId===selectedId&&v.revision===snapshot?.revision&&v.feed===feedId&&v.epoch===connectionEpoch&&v.original===clarificationOriginal(d)&&v.text===d.text&&v.workId===d.workId&&v.questionId===d.questionId);}
function clarificationControls(){const d=clarificationDrafts.get(selectedId),editable=revisionEditable();$('clarification-fields').disabled=!editable;$('clarification-review').disabled=!editable||!d||!clarificationValid(d);$('clarification-save').disabled=!editable||!clarificationCurrent(d);$('clarification-cancel').disabled=!editable;}
function renderClarification(){if(!snapshot||snapshot.value.id!==selectedId){clarificationControls();return;}for(const [key,s] of clarificationSubmissions){if(s.missionId!==selectedId||!confirmedOperations.has(key)||snapshot.revision<=s.body.expectedRevision)continue;const q=snapshot.value.works.find(w=>w.id===s.body.workId)?.questions?.find(q=>q.id===s.body.questionId);if(!q||(s.answer?q.answer?.text:q.text)!==s.body.text)continue;clarificationSubmissions.delete(key);if(clarificationDrafts.get(selectedId)===s.draft)clarificationDrafts.delete(selectedId);else if(!s.answer&&clarificationDrafts.get(selectedId)?.newId===s.body.questionId)clarificationDrafts.set(selectedId,{...clarificationDrafts.get(selectedId),newId:null,review:null});clarificationStatuses.set(selectedId,'Exact question decision confirmed. No execution started.');}
 const d=clarificationDraft(),target=$('clarification-work');target.replaceChildren();const initial=element('option','Choose fresh Work');initial.value='';target.append(initial);for(const w of snapshot.value.works.filter(clarificationFresh)){const o=element('option',w.id+' · '+w.title);o.value=w.id;target.append(o);}if(d.workId&&!Array.from(target.children).some(o=>o.value===d.workId)){const o=element('option','Stored Work no longer fresh');o.value=d.workId;target.append(o);}target.value=d.workId;const choices=$('clarification-question');choices.replaceChildren();const fresh=element('option','Record a new question');fresh.value='';choices.append(fresh);for(const q of clarificationWork(d)?.questions||[]){const o=element('option',q.id+' · '+(q.answer?'Answered, immutable':'Open question'));o.value=q.id;choices.append(o);}choices.value=d.questionId;$('clarification-text').value=d.text;$('clarification-original').textContent=JSON.stringify({revision:snapshot.revision,workId:d.workId,originalQuestion:clarificationWork(d)?.questions?.find(q=>q.id===d.questionId)||null,decision:d.questionId?'Answer exact open question':'Record new question',text:d.text,reviewed:clarificationCurrent(d)},null,2);$('clarification-status').textContent=clarificationStatuses.get(selectedId)||'Private draft only. Review current revision before Save.';clarificationControls();}
for(const key of ['clarification-work','clarification-question'])$(key).addEventListener('change',()=>{if(!revisionEditable())return;const d=clarificationDraft();clarificationDrafts.set(selectedId,{...d,workId:$('clarification-work').value,questionId:key==='clarification-work'?'':$('clarification-question').value,newId:null,review:null});renderClarification();});
$('clarification-text').addEventListener('input',()=>{const d=clarificationDraft();clarificationDrafts.set(selectedId,{...d,text:$('clarification-text').value,review:null});clarificationControls();});
$('clarification-review').addEventListener('click',()=>{const d=clarificationDraft();if(!revisionEditable()||!clarificationValid(d))return;clarificationDrafts.set(selectedId,{...d,newId:d.questionId?null:d.newId||'question:'+crypto.randomUUID(),review:{missionId:selectedId,revision:snapshot.revision,feed:feedId,epoch:connectionEpoch,workId:d.workId,questionId:d.questionId,text:d.text,original:clarificationOriginal(d)}});renderClarification();});
$('clarification-cancel').addEventListener('click',()=>{if(!revisionEditable())return;clarificationDrafts.delete(selectedId);clarificationStatuses.set(selectedId,'Private question draft cancelled. No write or execution.');renderClarification();});
$('clarification-form').addEventListener('submit',async event=>{event.preventDefault();const d=clarificationDraft();if(!revisionEditable()||!clarificationCurrent(d))return;const missionId=selectedId,answer=!!d.questionId,body={commandId:crypto.randomUUID(),expectedRevision:d.review.revision,workId:d.workId,questionId:d.questionId||d.newId,text:d.text};if(!commandBodyFits(body))return;clarificationStatuses.set(missionId,'Saving once; await exact original receipt.');await write('/missions/'+encodeURIComponent(missionId)+(answer?'/work-answer':'/work-question'),body,missionId,'Owner question decision saved; no execution started.',null,null,null,null,null,null,null,null,null,null,null,null,null,{missionId,draft:d,body,answer});if(selectedId===missionId)renderClarification();});
`;
